xiph/rav1e

- Cargo.toml
- build.rs
The crate was renamed: https://github.com/alexcrichton/cc-rs
> Upgrade gcc 0.3 -> cc 1.0

- Cargo.toml
- src/main.rs
There are many ways to specify options using clap, see
https://github.com/kbknapp/clap-rs#quick-example, I chose the simplest
one.
> Fix #4: Proper CLI argument parsing using clap

- Cargo.toml
- README.md
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/lib.rs
Currently only contains one command "process_repl" that encodes one frame.
To run the REPL:
```
cargo run --bin rav1repl
```
To run the main encoder (unfortunately there is no way to make "cargo run" do this by default):
```
cargo run --bin rav1e
```
> Add a simple REPL

- src/ec.rs
The only calls to od_icdf() use constants so this function is
unnecessary and can be deleted.
> Replace od_icdf() usage with actual constants.

- Cargo.toml
Only include the `src`, `aom_build` and `Crago.toml` as build deps. This fixes #28
> Don't rebuild unnecessarily.

- src/lib.rs
This patch fixes a bug introduced in 9eecb5ca where only the IVF header
is written.
> Fix IVF file writer bug.

- src/lib.rs
Use more idiomatic Rust when parsing the command line parameters.
> Clean up EncoderConfig.from_cli().

- Cargo.lock
- Cargo.toml
- src/lib.rs
The FrameType enum uses a custom derive to automatically provide an
iter_variants() function you can use to get a simple iterator.
> Add a FrameType to the FrameInvariants.

- src/partition.rs
The names go_left() and go_up() return the above and left slices
respectivley which is confusing and why the previous patch did not
predict properly.
This will be addressed in a separate patch.
> Fix incorrect prediction introduced in 0df1e6ed.

- src/partition.rs
- src/plane.rs
The functions go_up() and go_left() now correctly return the above and
left slices.
> Rationalize go_up() and go_left() functions.

- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/lib.rs
The "Show Existing Frames" feature uses this to copy into the reconstruction stream.
This demonstrates the plumbing required to resolve #67, and only covers the current behavior.
For future-proofing, an actual frame context buffer is needed.
> Buffer last reconstructed frame

- src/lib.rs
Some demuxers will cry foul if the framerate is 0/60.
> Fix the frame rate in ivf

- src/predict.rs
rust-1.24
from
test native_trait  ... bench:     988,673 ns/iter (+/- 185,503)
to
test native_trait  ... bench:     806,088 ns/iter (+/- 150,647)
rust-1.25 (nightly)
from
test native_trait  ... bench:     653,069 ns/iter (+/- 104,601)
to
test native_trait  ... bench:     421,896 ns/iter (+/- 78,777)
> Slice before building the iterators in pred_dc

- Cargo.toml
So that upgraded rustc 1.25.0 version does not slow down
the release/test/bench binary by setting the default value of
codegen-units = 16.
> Set codegen-units = 1

- src/context.rs
The "mi_*" tables seem left mistakenly, when the better named *b_*
were replacing them.
> Delete duplicate tables

- src/context.rs
- src/lib.rs
- src/partition.rs
- Add update_partition_context() function.
- Add partition_context_lookup[] and subsize_lookup[] tables.
- Add mi_size_wide[] and mi_size_high[] tables.
- Fix outdated lookup tables, for ex: all 2x2, 4x2, 2x4 are dropped.
- Use BLOCK_SIZES_ALL whenever possible for the size of lookup table.
- As a separate commit for submodule libaom,
manually update the corresponding lookup tables, esp. all the tables with the size
BLOCK_SIZES_ALL.
> Another prep work to enable partitionining

- src/context.rs
To avoid the multiple copies of array whenever it is referenced,
also more importantly, the generated asm code seems slower
if const is used w/o '&', i.e. referencing.
> Use static instead of const for array

- src/lib.rs
The quantizer tables that rav1e currently use are those from libaom,
which are all in Q3 precision (except, qindex=0, lossless mode, which is Q2).
Thus, if we derive lambda which applies to pixel domain in Q0,
we should use quantizers in Q0.
> Use Q0 quantizers to derive lambda for Q0 pixel domain

- benches/bench.rs
Fixes build error for `cargo bench` since:
c6504a9 "Add quantizer parameter."
> Specify quantizer in write_b_bench

- benches/bench.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/context.rs
- src/lib.rs
- src/partition.rs
- src/rdo.rs
This is part 1 of ongoing work of enabling partition encoding.
Every SuperBlock is partitioned down to 8x8 partitions,
where pre-existing RDO mode decision decides intra modes
(among three, DC_PRED, HORZ_PRED. VERT_PRED) for the 8x8 partition.
If input image size is not multiple of 8 pixels,
the coded image is padded to be multiple of 8 pixels in both width and height.
TEST: subset1 images.
cargo build --bin rav1e --release
rm test.ivf test_rec.y4m test_dec.y4m
./target/release/rav1e /home/yushin/sequences/subset1-y4m/125_-_Québec_-_Pont_de_Québec_de_nuit_-_Septembre_2009.y4m -o test.ivf  -r test_rec.y4m --quantizer 50
./aom_test/aomdec test.ivf -o test_dec.y4m -v
mpv --keep-open test_dec.y4m &
mpv --keep-open test_rec.y4m &
KNOWN ISSUES:
1. If SBs on right and bottom frame borders are …
> Enable partition : part 1, split down to 8x8 blocks

- benches/bench.rs
- src/context.rs
- src/lib.rs
For #131.
Add set_skip() function which sets skip flags of all MI blocks in
a partition block size.
> Fix skip mode

- src/context.rs
- src/lib.rs
This patch is for issue: #127.
So that it sets mode for all the MI blocks in block size, not just one MI block.
> Fix set_mode() function

- build.rs
It has the very same behaviour as the code it replaces,
but it is much shorter.
> Use File::create instead of OpenOptions

- benches/bench.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/context.rs
- src/lib.rs
This patch is for issue: #140.
Speed level decides the minimum partition block size, where recursive quadri-sect splitting stops at.
0(slowest) : BLOCK_4X4
1 : BLOCK_8X8
2 : BLOCK_16X16
3 : BLOCK_32X32
4~10(fastest) : BLOCK_64X64
Encoder option : "--speed=[0..10]" or "-s [0..10]".
Exception: SuperBlock(SB)s on right or bottom frame borders always split down to BLOCK_4X4.
In the future, min partition block size may be controlled by separate encoder option.
>  Basic speed level based on minimum partition block size

- benches/bench.rs
- build.sh
- src/context.rs
- src/lib.rs
- src/partition.rs
- src/predict.rs
- src/transform.rs
The largest transform that fits into the partition is used (up to 8x8).
> Add support for 8x8 transforms.

- src/context.rs
For issue #165, #128.
TD-Linux: This is where I meant to apply <<xdec and <<ydec for chroma coeff context writing.
I.e. only on even places. Well, but once we start to use compact storage for chroma coeff context, then this part would go away as well.
Write the chroma coeff context only on necessary places.
> Improve coeff_context() for chroma

- src/lib.rs
For issue #165, #128.
The pixel position when calling encode_tx_block() for chroma is
the start of current partition + size of tx blocks processed so far.
> Rewrite the plane offset for chroma

- README.md
I decided to try out rav1e this weekend. There were dependencies that I needed to install but weren't explained in the documentation. It's a good idea to note that we need these libraries and how to install them.
> Document dependencies required to build rav1e.

- src/bin/rav1e.rs
For #160.
Fix that the incomplete inter mode has been enabled in the previous commit.
> Encode Key frame only

- src/lib.rs
New write_frame_size function writes out the correct number of bits for
the frame width and height.
> Variable Frame Size Bit Lengths

- build.sh
This is an edge case, e.g., when trying to run ./build.sh after an incomplete build.
> build.sh: don't error out if distclean target is not available

- build.sh
That should make sure that stray defaults won't get in the way (assuming it is a problem at it is for the cmake crate).
> test: Always wipe the test-build dir for aomdec

- src/context.rs
- src/lib.rs
For #131 , "Support Skip Mode".
Once a partition is skipped,
this function sets left and right coefficients contexts,
which includes dc_sign and coeff_levels, as zeros.
> Add reset_skip_context() function

- src/context.rs
test write_b_bench(TX_4X4, 20) ... bench:     349,474 ns/iter (+/- 8,282)
test write_b_bench(TX_4X4, 55) ... bench:     355,071 ns/iter (+/- 6,491)
test write_b_bench(TX_8X8, 20) ... bench:     658,938 ns/iter (+/- 59,722)
test write_b_bench(TX_8X8, 55) ... bench:     653,857 ns/iter (+/- 10,898)
test write_b_bench(TX_4X4, 20) ... bench:     350,559 ns/iter (+/- 6,332)
test write_b_bench(TX_4X4, 55) ... bench:     350,818 ns/iter (+/- 6,957)
test write_b_bench(TX_8X8, 20) ... bench:     662,450 ns/iter (+/- 11,495)
test write_b_bench(TX_8X8, 55) ... bench:     664,664 ns/iter (+/- 31,544)
Benchmarks are in the noise.
> Replace clip table with function.

- src/ec.rs
Given the max probability of 32768,
probability of bit write is 32768/2 = 16384.
> Use constant for probability of bit_write()

- Cargo.toml
- src/lib.rs
- src/plane.rs
Note this cannot yet encode high bitdepth; it reads it and then shifts
to 8 before encode.  Updated with [corrected and tested] version of lu_zero's pattern.
> Read 10-bit y4m input. #107

- src/context.rs
Bug fix for #216.
With level map coding, the coefficient contexts from above and left
can be more than one element which is all the adjacent contexts to the
current tx block size.
(Prior to level map, only one left and above contexts are used to choose a cdf)
Fix is to apply the same indexing method as used in set_coeff_context().
The test to confirm the bug and fix is to enforce all first SB row
and firt SB column to use 4x4 txs, so that it can be contexts for next rows and columnms
which I enforce to use 16x16 tx blockss or 32x32 tx blocks.
> Fix the bug in coeff context indexing for chroma planes

- src/context.rs
- src/lib.rs
While looking at #189, I found that inter blocks in inter frames are
still writing an intra mode.  This doesn't get tripped yet as we're
only writing intra frames, but it will soon enough.
> In inter frame, only write intra mode if block is intra

- benches/bench.rs
- src/predict.rs
This tests the Paeth predictor as part of the `pred_max()` function.
Some indentation and naming consistency fixes in `predict.rs` and `bench.rs` were added as well. These can be moved to a different PR if preferred.
> Add missing Paeth predictor test

- build.rs
The aom/build folder watched before may not change for all changes.
Closes #233
> build.rs: watch for changes the full aom/ folder

- src/lib.rs
64x64 transforms only need 32x32 coefficients at most.
This speeds up the encoder some due to not zeroing the memory.
> Only allocate coeff buffers up to 32x32.

- benches/bench.rs
- src/context.rs
- src/predict.rs
Smooth predictors require knowledge of bit depth to clamp predictions, so the native function includes the `bd` parameter.
> Add smooth predictors and tests

- src/lib.rs
This reverts commit 6f61d4c0382fc45cdd034ce66950735095bb2c7f.
For 64x64 TX, forward_transform() still needs 64x64 coefficients buffer
as input and inverse_transform_add() needs 64x64 coefficients buffer as
output. This is because forward_transform() and inverse_transform_add()
do packing and unpacking to/from upper left 32x32 coefficients area
inside themselves.
So, after calling 64x64 fwd tx, the output has first 1/4 area filled in
64x64 buffer. The level map encoder can encode maximum 32x32
coefficients thus it only encodes first 32z32 coefficnets in the buffer
for the 64x64 tx block.
Instead, what we can reduce is the buffer inside level map encoder,
from 64x64 down to 32x32, as I commited in libaom codebase,
https://aomedia.googlesource.com/aom/+/4f347987bb14b6bdc10a121659e5608731e71e0 …
> Revert "Only allocate coeff buffers up to 32x32."

- src/context.rs
The maximum number of coefficients that level map encoder can
encode is 32x32, so reducing the existing buffer size from 64x64
downto 32x32.
> Reduce the buffer size of level map encoder

- build.rs
We do not care if we fail to delete a file because it is already
missing.
> Drop a warning for fs::remove() return value

- src/lib.rs
- src/quantize.rs
A rounding offset of 21/64 is added to reduce
reconstruction error
> Add rouding to quantization process

- build.sh
- src/lib.rs
Enabled at s=0, `min_partition_size` adjusted at higher speed levels
```
ravmaster@2018-06-14T23:27:19.500Z -> bup@2018-06-14T23:26:50.801Z
-1.5433 | 23.1016 |     N/A |  -3.4251 | -2.7440 | -4.4090 |     8.7047
```
4.48s -> 10.40s on nyan.y4m
> Add exhaustive ("bottom-up") RDO partition search

- src/partition.rs
- src/predict.rs
At s=0, with exhaustive partitioning:
```
bup@2018-06-14T23:26:50.801Z -> smooth@2018-06-15T19:42:21.397Z
PSNR |  PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000
-0.1549 | -11.2290 |     N/A |   2.0102 | 1.0432 |  2.2848 |    -6.1379
```
> Support encoding of smooth prediction modes

- benches/bench.rs
- src/partition.rs
- src/predict.rs
This also extracts the unsafe top-left pixel access from the native predictor function.
> Support encoding of Paeth prediction mode

- src/partition.rs
Increase size for intra reference sample buffers to include
above-left, above-right and below-left samples. Make size a
function of the maximum supported transform size.
> Set proper size for intra reference sample buffers

- src/lib.rs
`set_mode()` is executed in `encode_block()` already, so there is no need to call it beforehand.
> Remove redundant binary coder mode setting operations

- build.sh
- src/context.rs
- src/lib.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
* Force a `cargo clean` when the submodule is out of date, as it can be necessary to link correctly  
* Remove assertion to support additional (non-DCT) transform types (as part of #267)  
* Rename some variables, simplify some operations
* Move `RAV1E_PARTITION_TYPES` to `partition.rs` (from `predict.rs`)
* Move RDO decision functions to `rdo.rs`
* Extract rate-distortion cost computation to a new function
> Clean up and refactor RDO-related areas

- src/predict.rs
Oops.
```
nopaeth@2018-06-21T09:29:47.514Z -> paeth@2018-06-21T09:28:52.893Z
-0.0962 | -0.4074 | -0.3002 |   0.0372 | -0.1525 | -0.0627 |    -0.0307
```
> Add Paeth to the list of supported prediction modes

- src/lib.rs
- src/partition.rs
- src/rdo.rs
Uses a limited subset of available transform types (DCT, ADST and combinations), always tested exhaustively.
Also extracts transform block writes to their own function `write_tx_blocks()`.
Part of #267.
> Add intra mode transform type RDO

- src/lib.rs
- src/partition.rs
- src/quantize.rs
- src/rdo.rs
```
txtype@2018-06-21T09:57:19.682Z -> idtx_max16x16@2018-06-23T00:13:43.743Z
-0.7795 |  1.3157 |  1.0336 |   0.7239 | -0.1461 |  0.6128 |    -0.0174
```
Encoding time (Q80): 32.739 -> 37.841
> Enable identity transform for sizes 16x16 and below

- src/context.rs
- src/lib.rs
- src/partition.rs
- src/rdo.rs
Further work for #267.
* Skip unsupported/invalid transform types during RDO
* ADST and DCT/ADST combinations no longer coded at sizes of 32x32
* Remove the identity transform size check workaround, as it is not valid
* Enable full intra transform type set (`H_DCT` and `V_DCT`) at speed levels 0 (exhaustive partitioning) and 1 (top-down partitioning)
At speed = 0:
```
idtx_max16x16@2018-06-23T00:13:43.743Z -> tx_h_v@2018-06-25T16:06:25.030Z@2018-06-25T16:07:04.497Z
-0.5303 |  1.1060 |  1.0042 |   0.3591 | 0.3729 |  1.3064 |     0.4017
```
Encoding time (Q80): 37.841 -> 41.557
> Properly handle transform type sets

- src/lib.rs
- src/rdo.rs
Resolves #278.
This is exhaustively tested during mode RDO and applies to speed levels 0 (exhaustive partitioning) and 1 (top-down partitioning).
```
idtx_max16x16@2018-06-23T00:13:43.743Z -> skip_nohv@2018-06-25T19:17:44.838Z
-1.2821 |     N/A | 14.4267 |  -1.3549 | -1.7057 | -1.4930 |     2.3784
```
Encoding time (Q80): 37.841 -> 66.445
Relative to #279:
```
tx_h_v@2018-06-25T16:06:25.030Z@2018-06-25T16:07:04.497Z -> skip@2018-06-25T18:54:47.920Z
-1.4006 | 16.0167 | 15.1763 |  -1.4152 | -1.7293 | -1.4402 |     2.1841
```
> Add block skip RDO decision at low speed levels

- src/lib.rs
- src/rdo.rs
Resolves #271.
Adds exhaustive chroma prediction mode search for chroma blocks, for speed levels 0 and 1.
```
skip@2018-06-25T18:54:47.920Z -> chroma_pred@2018-06-28T12:58:27.121Z
0.3054 | -4.4343 | -4.1336 |   0.2530 | 0.2041 |  0.0571 |    -1.5576
```
Encoding time (Q80): 72.303 -> 286.638
> Add exhaustive chroma prediction mode RDO at low speed levels

- src/lib.rs
- src/predict.rs
- src/rdo.rs
Transform types and prediction modes are currently all tested at all speed levels, which slows down every speed level considerably. With this change, speed levels 0-3 will test all prediction modes and transform types exhaustively, while higher levels will default to a smaller set of prediction modes and DCT transforms.
> Restrict scope of RDO above low speed levels

- benches/bench.rs
- src/context.rs
- src/lib.rs
- src/partition.rs
- src/rdo.rs
This PR refactors the usage of TxSize and BlockSize, removes several lookup tables and exposes most of the previous functionality as member methods on `TxSize` and `BlockSize`.
> Remove lookup tables

- build.sh
Fixes ./build.sh since README.md now includes more references to cmake.
> build: make fgrep invocation more specfic

- src/context.rs
- src/ec.rs
Avoid passing the superfluous `nsymbs` value around, this is now always computed from the length of the cdf slice, i.e. `cdf.len() - 1`.
> Clean up CDFs.

- .gitignore
- .travis.yml
- Cargo.toml
- build.rs
- src/lib.rs
- src/partition.rs
- src/plane.rs
- src/transform.rs
Here the initial implementation of two encode-decode test.
It cover all the speeds and some quantization.
In the process of using the test, I found the hard way a couple of issues that got fixed in the first commits.
Fixes #3
> Encode decode tests

- benches/bench.rs
- src/context.rs
- src/lib.rs
- src/rdo.rs
This change is to allow multiple and throwaway writers to be used in
predictive and out-of-order coding.  A Writer must be passed in (and
checkpointed) separately/explicitly.
> Remove 'Writer' from 'ContextWriter' structure

- src/transform.rs
This is required because the old ones are only available as
sse2 intrinsics.
This disables 4x4 and 8x8 transform assembly.
> Use new fwd transforms for 4x4 and 8x8.

- src/cdef.rs
Add guard to not process blocks within a SB that are entirely off the
edge of the frame. The filter function was already guarded against
this possibility, but the find_dir function was not.
Closes #399.
> Fix for issue #399 (multiply overflow in cdef_find_dir)

- src/cdef.rs
Which check whether input pixel values  are withing a valid range,
for ex, 0 <= (pixel_value >> bitdepth) <= 255.
This patch can be used to fix #399 .
This assert fails with  rav1e built in debug mode! :)
> Add assert in cdef code

- Cargo.toml
Cargo would try to compile each file at the root of benches/ as
stand alone benchmark.
Disable the behaviour.
> Future proof the benchmarks

- src/plane.rs
- src/util.rs
Plane data uses `u16` so the stride just needs to be a multiple of 8 to be 16 byte aligned.
> Alignment Cleanup

- Cargo.toml
- README.md
- build.rs
This allows `libaom` to compile and link to `rav1e` on Windows, tested with MSVC. Note that this will not compile until https://github.com/alexcrichton/cmake-rs/pull/49 is pulled and `cmake-rs` receives a version update.
Closes #412.
> Support build on Windows

- src/lib.rs
- src/partition.rs
Inter mode prediction can be done for a whole partition,
instead of each tx-block.
TODO: Fix the plane_offset() function of BlockOffset struct for chroma
planes, so that bo.plane_offset() can be directly and conveniently called
instead of using a block of long codes in several places.
> [WIP] Do the inter prediction for a whole partition

- benches/bench.rs
- src/context.rs
- src/lib.rs
- src/rdo.rs
It has been wrong when SB is partitioned, thus we were using a block of codes doing that.
> Fix plane_offset() of BlockOffset struct for chroma planes

- benches/bench.rs
- src/context.rs
- src/ec.rs
- src/lib.rs
Reimplement od_ec_enc and Writer, add record/playback
Flatten od_ec_enc and Writer, as one was just a thin wrapper for the other
Reimplement range encoding writer as a Writer trait and encoding backend
Reimplement recording as a second backend to same Writer trait
> Cdef recorder

- src/rdo.rs
Currently, cdef_dist_wxh() is called for 4x4 as well, which is a bug.
> Assert to check  cdef_dist is called for multiple of 8x8 pixels

- Cargo.toml
- build.rs
This aims to enable compilation on non-MSVC Windows targets.
This change is untested, so in order to pull it I would like confirmation that it works on at least one non-MSVC Windows target. If compilation fails, please provide the location of the `aom.pc` file in the build directory.
> Restore pkg-config dependency for non-MSVC Windows targets

- src/ec.rs
- src/lib.rs
- src/rdo.rs
Add a new Writer type 'WriterCounter' that stores nothing, it merely tracks bits for cost analysis
Convert RDO to use local throwaway WriterCounters instead of checkpointing/rolling back a master Writer
> Cdef counter

- src/lib.rs
- src/partition.rs
If tune=Psychovisual is used, min partition size is enforced to 8x8.
Temporary fix for #432.
> Temporary fix to cdef_dist_8x8 (#432)

- src/context.rs
- src/ec.rs
- src/lib.rs
- src/rdo.rs
Last encoding structural work to allow CDEF RDO decisions to happen at end-of-partition;
Implements split partition encode with 'everything up to the CDEF strength' and 'everything after the CDEF strength' coded in parallel separate Writers, such that the CDEF strength can be determined at the end of partition encode.
Also corrects a serious algebra error int he WriterRecorder, now that it's in full use. Local range state was not being used properly during replay.
> Cdef splitencode2

- .gitmodules
- Cargo.toml
- README.md
- benches/bench.rs
- build.sh
- src/bin/rav1e.rs
- src/cdef.rs
- src/context.rs
- src/lib.rs
- src/partition.rs
- src/predict.rs
- src/quantize.rs
- src/rdo.rs
- src/transform.rs
- src/util.rs
* Handle high bit depth across the encoder
* Allow 10- and 12-bit 4:2:0 y4m input
* Add encode-decode test for high bit depth
* Add operations on high bit depth sequences in the build script (commented out by default)
* Update README.md
* Move `context::clamp()` to `util.rs` and make it generic
Closes #325.
> Enable and test high bit depth input

- src/lib.rs
We can't guarantee we meet a level, so choose level 31 for now
which has no constraints.
> Write level 31 instead of 0.

- src/cdef.rs
- src/rdo.rs
Split analysis and filtering of CDEF superblocks so that RDO can do a
single find_dir before a number of filter tests at diffrerent
strengths.
> Eliminate redundant CDEF find_dir calls

- README.md
Clang is needed in order to run integration tests. Fixes #122.
> Add info about Clang dependency

- Cargo.toml
- src/bin/common.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/lib.rs
- src/util.rs
That's a preliminary to the actual user API patch.
This way we:
- can optionally build rav1e w/out the cli
- have 2 dependencies optional as well (`y4m` is sort of tiny, but `clap` is relatively big)
> Move cli-specific code where it belongs

- Cargo.toml
- src/lib.rs
I originally wanted to update this outdated dependency, but turns out it was unused.
> Remove unused EnumIterator derive

- src/lib.rs
This ensures that frame sizes that are not divisible by 16 are working as expected.
Also re-enable CDEF at low bit depth, as it was erroneously always disabled.
> Add more frame dimensions to the decode test

- appveyor.yml
For #457. Currently just runs `cargo test`.
To set up CI checks and for non-MSVC or 32-bit builds, please perform the necessary adjustments in a future PR.
> Add Appveyor configuration for MSVC 64-bit

- src/rdo.rs
AWCY Results for subset1 at --speed=1
master_s1@2018-08-14T20:42:35.057Z -> fix_topdown_rdo_mode_update_s1@2018-08-15T20:06:31.213Z
-0.1532 | -0.2611.    |     N/A        |  -0.1801 | -0.1267 | -0.1137 |    -0.2634
> [WIP]Fix for top-down RDO search not updating mode

- src/context.rs
Make most calls use the non-mutable version
> Rename mutable and non-mutable versions of at() function

- src/context.rs
- src/rdo.rs
Chroma distortion was sometimes being computed on inexistant 2x2 blocks
> Fix chroma distortion computation

- src/context.rs
Because the coefficient block coder encode maximum 32x32 (== 1024) coefficients in a
block.
> Change max scan order size from 4096 to 1024.

- benches/bench.rs
- benches/comparative/mod.rs
- benches/comparative/predict.rs
- benches/predict.rs
- src/context.rs
- src/encoder.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
> Implement Chroma-from-Luma

- src/encoder.rs
- src/rdo.rs
The current restrictions of square partitions and 4:2:0 yield only one sub-8x8 case to be handled.
> Enable CfL on sub-8x8 partitions

- src/encoder.rs
- src/me.rs
Currently this feature yields an average loss of about 1 percent BD rate, so keep it disabled by default
> Add 1/8th pel motion refinement step

- src/bin/rav1e.rs
- src/context.rs
- src/encoder.rs
- src/me.rs
- src/partition.rs
Reference frame structure captures YUV data and probabilities
of a previously decoded frame.
Symbol counts are reset and not carried from one frame to the next.
Error resilient mode is disabled to support this feature.
> Reuse probabilities from previous frame

- src/ec.rs
Provides an overall encoder run time reduction of about 1 percent
> Speed up probability update function

- src/encoder.rs
- src/rdo.rs
master-48326cdc05f9f042ae05e6d7066f1b89152daaba -> tx_type_rdo_use_luma_only@2018-08-22T00:10:46.630Z
-0.1634 | -0.2861 | -0.2602 |  -0.1993 | -0.2388 | -0.2718 |    -0.2315
> tx_type_rdo_decision() uses luma only

- src/encoder.rs
- src/rdo.rs
Also does pulling tx_type_rdo() out of chroma RDO, as requested in #521.
There should not be any change in coding performance but only speed improvements.
AWCY results for the default speed -s 3 will come at: 
https://beta.arewecompressedyet.com/?job=master-ea40e92a90aac92766cf9f89a6194d388c1917c9&job=pull_txtype_rdo%402018-08-28T20%3A21%3A59.599Z
For -s 1,
https://beta.arewecompressedyet.com/?job=master-ea40e92_s1%402018-08-28T18%3A16%3A46.433Z&job=pull_txtype_rdo_s1%402018-08-28T20%3A21%3A51.138Z
> Pull rdo_tx_type_decision() out of encode_block_b()

- src/rdo.rs
Fix a small bias in RDO that favors UV_PRED_CFL.
[AWCY results](https://beta.arewecompressedyet.com/?job=master-14de53db77678da6fef5370c38c0583bde83dc31&job=rav1e-cfl-rdo-rollback%402018-08-31T07%3A01%3A38.825Z) at default speed:
| -0.0955 |  1.5592 |  1.0264 |  -0.1145 | -0.0963 | -0.1592 |     0.4496 |
Encoding time is about 1.5% lower.
[AWCY results](https://beta.arewecompressedyet.com/?job=master-14de53_s1%402018-08-30T23%3A18%3A37.272Z&job=rav1e-s1-cfl-rdo-rollback%402018-08-31T10%3A27%3A30.053Z) for speed 1:
|    ---: |    ---: |    ---: |     ---: |    ---: …
> CfL RDO: rollback ContextWriter after luma reconstruction

- src/encoder.rs
Add assert statement to check that nearest MV is indeed the same
as the MV passed as argument to encode_block_b()
> Fix RDO bug that was causing speed levels 1 and 2 to not work

- benches/bench.rs
- src/cdef.rs
This reduces the time for cdef_filter_frame by ~33%.
[AWCY results](https://beta.arewecompressedyet.com/?job=master-fd6d02d1d1b9f37d458105e3c70efede611da67c&job=rav1e-cdef-faster-unsafe%402018-09-03T15%3A04%3A33.425Z) at the default speed show a 6%~8% reduction in total encoding time.
> Trust the pointer arithmetic in cdef_filter_block

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/encoder.rs
- src/lib.rs
- src/test_encode_decode.rs
See issue https://github.com/xiph/rav1e/issues/410
API:
Usage:
Refactor:
> [WIP] User api

- src/me.rs
Restrict motion vectors to lie within the bounds defined by the AV1 spec.
Fixes #558
> Avoid searching out of bounds motion vectors in ME

- src/encoder.rs
- src/plane.rs
This just adds the infrastructure to support future parallelization.
Not wired into RDO yet as existing code mutates FrameState where it probably should not.
> Add FrameState::window() to create scratch buffers

- src/encoder.rs
Resolve build error:
```
error[E0308]: mismatched types
--> src/encoder.rs:260:20
|
260 |            input: self.input.window(sbo),
|                    ^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::sync::Arc`, found struct `encoder::Frame`
|
= note: expected type `std::sync::Arc<encoder::Frame>`
found type `encoder::Frame`
```
> Fix conflict with user API change in FrameState::window

- src/context.rs
- src/me.rs
This time minimally invasive renamings! Just added a prefix 'mv'.
In ME search range setup, rename x_min, x_max, y_min and y_max variables
as mvx_min, mvx_max, ... since they are limits of mv allowed to code thus needed 
to search.
Closing #573 since this PR replaces it.
> Rename min max variables in ME search range setup

- src/deblock.rs
Improve cache behavior by running vertical and horizontal deblocking in one pass.  Horizontal lags one SB behind vertical.  No functional change.
> run vertical and horizontal deblocking (almost) concurrently

- src/encoder.rs
- src/rdo.rs
There is no change in coding encoding behavior as shown in [AWCY run](https://beta.arewecompressedyet.com/?job=master-2c6a3f51e8f5964aae403246c8389fa57b164121&job=luma_only_mc_if_tx_type_rdo%402018-09-17T16%3A19%3A21.474Z)
> Luma only motion compensate if tx_type_rdo()

- src/context.rs
- src/partition.rs
BLOCK_SIZES is 22, and BLOCK_128X32 and BLOCK_32X128 do not exist in the AV1 spec.  This PR removes them.  Tests pass and the nyancat video seems to work. Issue #592
> Remove BLOCK_128X32 and BLOCK_32X128 #592

- src/encoder.rs
[AWCY results for 5 frames at speed 0](https://beta.arewecompressedyet.com/?job=master-s0_5f%402018-09-18T20%3A00%3A40.807Z&job=predicted_me_center_bottom_up_rdo-s0_5f%402018-09-18T20%3A01%3A32.697Z)
| -1.8632 | -1.7386 | -1.7199 |  -1.8155 | -1.8189 | -1.7893 |    -1.8325 |
> Predicted ME search center for bottom-up partition rdo

- src/deblock.rs
- src/encoder.rs
No reason for the top level deblocking to be chunking thinks by SB in
the final filter.  There are fewer checks and corner-cases needed to
simply make full-frame passes.
> Move deblocking fitler to by-MI rather than by by-SB

- README.md
The affected command line is also used in `build.sh`.
> Fix a libaom compilation flag in README.md

- src/transform.rs
Reverts xiph/rav1e#613
No metrics for "Use 2 multiply rotation by PI/4." patch.
> Revert "Embed the rust idct functions."

- src/deblock.rs
The belief that a deblocking pass at level zero is a no-op is incorrect;
disable the deblocking of an edge when its filter level is zero
> Fix deblocking when only one of first two deblocking levels is zero

- src/deblock.rs
Presented for the overenginnering award of the week:
First cut of full RDO using SSE.  Active for speed <=3, mainly because the final process is fast enough it's barely a blip in encoding time.  Performs the equivalent of an exhaustive separable parameter search in the equivalent ~ approximately twice the time needed to run the full deblocking filter itself by doing a single pass over the current frame to prime four 65-point radix sorts.
psychovisual distortion (cdef-dist) implementation comes next.
> Deblock rdo2

- src/partition.rs
12-bit is a special case that rounds differently.
See 7.11.3.2. Rounding variable derivation process in the spec.
Fixes #622
> Fix inter for 12-bit input.

- Cargo.toml
- src/ec.rs
- src/encoder.rs
This PR bump bitstream-io to 0.8. For packaging purpose, we want to always depends on the latest crates available.
Reference used: https://docs.rs/bitstream-io/0.8.0/bitstream_io/write/struct.BitWriter.html
Tested in Fedora Rawhide (https://copr.fedorainfracloud.org/coprs/eclipseo/rav1e/build/807224/)
> Bump bitstream-io to 0.8

- src/me.rs
The operation is used for generating test planes.
> Use modulo instead of remainder in SAD test

- Cargo.toml
I noticed it while running some analysis with [critcmp](https://github.com/BurntSushi/critcmp).
Alex suggested to manually disable the impossible inline-benchmarks in https://github.com/rust-lang/cargo/issues/6156.
> Make simpler to pass options to criterion

- build.rs
The rust compiler DCE works in a different way so conditionals on `cfg!`
should not be used if the code in the branches may not compile.
While at it move the `use` statements where they are needed to avoid
warnings.
Fix #657
> Unbreak non-x86_64

- benches/predict.rs
- src/partition.rs
- src/predict.rs
Prerequisite to predict u8/u16 generic in a simpler way and also address part of #654
> Make the default Intra impl not use libaom

- src/partition.rs
- src/predict.rs
Make the prediction generic over u8 and u16.
> Pred generic

- .travis.yml
- build.rs
Hi!
I was just reading the .travis.yml and didn't understand why you installed nasm with apt and build it in the before_script section. Hence, I tried to remove the addons part and travis seems to have no particular issue to build and test the package.
So I make this PR to remove 3 useless lines (I guess) of your project, but i'm still wandering why you can't install nasm with apt only.
> Refractoring travis

- src/api.rs
- src/context.rs
- src/encoder.rs
- src/entropymode.rs
- src/me.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
Compound mode is used in conjunction with frame reordering. It is limited to the case where one forward and one backward reference are used.
> Add support for compound mode

- benches/predict.rs
- build.rs
- src/predict.rs
- src/x86/ipred.asm
See #675 for full list of predictors to map.
As a first step, map `pred_dc_128`.
> Integrate intra-prediction assembly from dav1d

- benches/bench.rs
- rustfmt.toml
- src/context.rs
- src/encoder.rs
- src/lib.rs
- src/lrf.rs
No functional change, but some added infrastructure and a Writer flow change in shared code menas I probably want to get this in sooner rather than later to avoid surprises.
Aside from adding RestorationUnits and a RestorationContext, coding the loop restoration parameters requires yet one more temporary Writer in the tile encode loop, as for each LRU the filter params have to be decided last, but written first.
> Loop restoration filter beginnings

- src/api.rs
- src/bin/common.rs
* adds --compound as boolean to enable reordering
* adds --keyframe_interval which I think could be useful to specify other value than 30, say, for when encoding 60fps videos.
> Adds --low_latency and --keyint command line options

- benches/comparative/predict.rs
- benches/predict.rs
Remove the `MAX_ITER` loops that pre-date moving to criterion-rs, so that time units match singular calls. Annotate the number of output bytes to measure prediction throughput.
> Output correct units for prediction benchmarks

- src/api.rs
- src/bin/common.rs
Frame reordering should be applied when low_latency is false
> Fix semantics of low_latency

- benches/bench.rs
- src/encoder.rs
- src/quantize.rs
- src/rdo.rs
Enabled when speed >= 1.
[For 5 frames AWCY](https://beta.arewecompressedyet.com/?job=master-e06321d_s3_5f%402018-10-23T18%3A53%3A09.943Z&job=test8_tx_dist_5f%402018-10-25T23%3A13%3A04.088Z), 
|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 0.1717 |  0.2794 |  0.1181 |   0.1141 | 0.1624 |  0.1534 |     0.6118 |
Currently, it causes regression of 0.17% for PSNR bd rate, with 44 (unit is probably sec?) --> 36 speed improvement, ~20% down. It also hurts CIEDE 2000 by 0.6%.
For now, the code is hard-coded to always use tx-domain distortion.
[Full AWCY results](https://beta.arewecompressedyet.com/?job=master-e06321d177cc14b1aa09952a4bb26f7f61512f5e&job=test8_tx_dist%402018-10-25T23%3A26%3A00.24 …
> Transform domain distortion for RDO-based mode decision

- src/api.rs
- src/context.rs
- src/encoder.rs
- src/me.rs
- src/partition.rs
- src/plane.rs
- src/rdo.rs
Motion estimation is initially done on 64x64 blocks which are downsampled to 16x16. A refinement step is then done on 32x32 blocks which are downsampled to 16x16.
Hierarchical motion estimation provides better run times when using large search ranges
> Hierarchical motion estimation

- benches/predict.rs
- src/predict.rs
Add 8-bit benchmarks for all existing intra predictors.
Call the remaining dc, h, and v predictors if AVX2 is available.
> Integrate dav1d ipred.asm (dc, h, v)

- src/predict.rs
- src/rdo.rs
Reduces encoder runtime by about 5% at default speed setting
> Avoid testing same MV multiple times in RDO loop

- Cargo.toml
- README.md
- benches/bench.rs
- build.rs
- src/api.rs
- src/bin/common.rs
- src/predict.rs
Currently we use it only for the tests. Once `dav1d` API is stable enough I would use it for the decode tests.
from 
```
real	2m44.705s
user	10m28.276s
sys	0m47.549s
```
to
```
real	0m59.245s
user	2m39.561s
sys	0m7.051s
```
> Make building libaom optional

- src/predict.rs
- src/x86/ipred.asm
Apply more asm patches from dav1d.
Call the `paeth`, `smooth`, `smooth_h` and `smooth_v` predictors if AVX2 is available.
> Integrate dav1d ipred.asm (paeth, smooth, smooth_h, smooth_v)

- src/context.rs
- src/encoder.rs
- src/partition.rs
- src/util.rs
It is more idiomatic in Rust to omit the `return` keyword when possible.
This is a purely stylistic lint and has no effect on performance.
> Cleanup unneeded return statements identified by clippy

- src/encoder.rs
`write` may not process the entire buffer, so if using it, it is
recommended to handle the return value (number of bytes written), or
strange runtime errors may occur. Since we are clearing the buffers
immediately after, it seems the desired behavior is to write the entire
buffer, for which `write_all` will guarantee correct behavior.
> Use `write_all` instead of `write` to handle buffers

- src/api.rs
- src/encoder.rs
Without increasing depth, yields the following when using frame reordering:
| -1.7571 | -2.3703 | -2.5057 |  -1.7010 | -1.7046 | -1.6254 |    -1.9372 |
> Modify frame management to allow for deeper frame hierarchies

- src/predict.rs
`add` takes a `usize` parameter, so this method can be used to avoid an
unnecessary cast to `isize`.
> Use `add` for pointer arithmetic to avoid casting

- src/context.rs
- src/encoder.rs
- src/partition.rs
- src/predict.rs
- src/quantize.rs
- src/rdo.rs
- src/transform/forward.rs
- src/transform/inverse.rs
- src/transform/mod.rs
Inverse 64-point transform is added.
Forward 64-point transform computes all 4096 coefficients such
that distortion from zeroing high-frequency coefficients can
be easily computed
> Add support for coding 64x64 blocks

- README.md
rav1e is no longer dependent on libaom unless running the comparative bench suite.
> Remove outdated info from readme

- benches/bench.rs
It seems to make no difference in benchmark reliability for me.
> Use reduced warm up time for get_sad.

- src/partition.rs
- src/predict.rs
Straightforward addition of 15 more 2:1 and 4:! rectangular
sized intra predictions, following current trait approach.
> Enable 2:1 and 4:1 rectangular intra prediction function calls"

- benches/bench.rs
- src/api.rs
- src/bin/common.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
- src/test_encode_decode.rs
This opens the path to finer control by the user over the encoding
options, and centralizes the speed preset logic in one location.
Closes #290
> Refactor speed level to act as an initialization preset

- src/bin/common.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
Fixes #720
```
─ rav1e --low_latency false -o /dev/null -v ~/bbb_480p.y4m
854x480 @ 24/1 fps
Frame 0 - Key frame - 183 bytes - encoded 1 frames, inf fps, 34.31 Kb/s
Frame 1 - Inter frame - 364 bytes - encoded 2 frames, 0.40 fps, 51.28 Kb/s
Frame 2 - Inter frame - 5 bytes - encoded 3 frames, 0.60 fps, 34.50 Kb/s
Frame 3 - Inter frame - 63 bytes - encoded 4 frames, 0.80 fps, 28.83 Kb/s
Frame 4 - Inter frame - 5 bytes - encoded 5 frames, 1.00 fps, 23.25 Kb/s
Frame 5 - Inter frame - 632 bytes - encoded 6 frames, 0.60 fps, 39.12 Kb/s
Frame 6 - Inter frame - 5 bytes - encoded 7 frames, 0.70 fps, 33.67 Kb/s
Frame 7 - Inter frame - 181 bytes - encoded 8 frames, 0.80 fps, 33.70 Kb/s
Frame 8 - Inter frame - 5 bytes - encoded 9 frames, 0.90 fps, 30.06 Kb/s
Frame 9 - Inter frame - 781 bytes - encoded …
```
> Fix low_latency mode which was broken in #718

- src/bin/common.rs
For some reason `Duration::as_secs()` only provides the whole part, so this adds millisecond-scale accuracy.
Fixes #662.
> Improve frame rate accuracy in CLI output

- src/context.rs
Some of my fix was wrong: which checks if whether tx_size == 32x32 or 32x? or 32x?,  where ? < 32.
> Fix the part of fixes in ecb01d413d9

- src/transform/forward.rs
32x16, 16x32, 32x8, 8x32 to have idtx in addition to dct_dct.
> Fix for 32x16, 32x8, etc. rect tx functions to have idtx tx_type as well

- src/me.rs
Bit depth was previously assumed to be 8.
> Pass bit depth to inter prection in motion estimation

- src/quantize.rs
> get_log_tx_scale: remove mutable variable

- src/bin/rav1repl.rs
Some recent commits changed some return types, but usage was not updated in `rav1repl`.
> Fix rav1repl compilation

- src/api.rs
- src/bin/common.rs
gop size 30 to 60
| -9.2210 | -5.3204 | -5.1895 |  -9.3851 | -9.5071 | -9.4011 |    -7.9515 |
master@2018-11-23T19:28:56.273Z -> master_gop_size_60@2018-11-26T18:00:26.878Z
> Change the default key frame interval from 30 to 60

- src/api.rs
- src/bin/common.rs
- src/encoder.rs
- src/lib.rs
- src/scenechange/mod.rs
- src/test_encode_decode.rs
Detects the level of difference between the current frame and the
previous frame, and if the difference is above a preset threshold,
encodes the current frame as a keyframe.
Introduces a new CLI option, --max-keyint (-i), to set the maximum
interval between two keyframes. Reuses the existing --keyint (-I) option
as the minimum interval between two keyframes. Adjusts the default
settings to be 15 frames minimum and 150 frames maximum. In theory, 300
frames may even be a safe default, but a conservative default was
selected given that decoder performance is still insufficient for higher
definition videos, and particularly long keyframe intervals negatively
impact seek time.
Compression improvements were up to 25% on test sources.
Before:
```
Frame 1499 - Inter frame - 756 bytes - encoded …
```
> Adaptive keyframe selection

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/lib.rs
- src/metrics.rs
- src/plane.rs
In verbose mode, will output planar PSNR for each frame. Will always
output planar and average PSNR for the whole video in the summary at the
end.
Closes #672 
Example:
```
╰─ target/release/rav1e ~/bbb_480p.y4m -o /dev/null -v --limit 40 -s 10
848x480 @ 60/1 fps
Frame 0 - Key frame - 131 bytes - PSNR: Y: 100.0000  U: 100.0000  V: 100.0000 - encoded 1/40 frames, 4.07 fps, 61.41 Kb/s, est. size: 0.00 MB
Frame 1 - Inter frame - 91 bytes - PSNR: Y: 100.0000  U: 100.0000  V: 100.0000 - encoded 2/40 frames, 2.87 fps, 52.03 Kb/s, est. size: 0.00 MB
Frame 2 - Inter frame - 85 bytes - PSNR: Y: 100.0000  U: 100.0000  V: 100.0000 - encoded 3/40 frames, 2.53 fps, 47.97 Kb/s, est. size: 0.00 MB
Frame 3 - Inter frame - 84 bytes - PSNR: Y: 100.0000  U: 100.0000  V: 100.0000 - encoded 4/40 frames, 2.51 …
```
> Output PSNR for each frame and average for video

- src/transform/inverse.rs
Number of columns sholud be used.
> Fix that number of rows is used for vertical 1d tx in inverse tx

- src/transform/inverse.rs
- src/transform/mod.rs
The forward rect tx has sqrt 2 term but inv rect tx has been missing 1/sqrt2 term.
> Fix missing inv sqrt2 factor for rect inv tx

- src/encoder.rs
- src/predict.rs
That is, with Block::W stride rather than fixed 32 stride.
> Fill subsampled luma AC buffer in dav1d layout

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/encoder.rs
- src/test_encode_decode.rs
No desync based on a run of the build script (using the default sequence, i.e. `CSP_VERTICAL`).
> Set the chroma sample position based on Y4M color space

- benches/bench.rs
- src/encoder.rs
- src/partition.rs
- src/rdo.rs
This eliminates a case of code duplication and adds support for all chroma sampling formats.
> Map U/V transform size in partition.rs

- benches/bench.rs
- benches/comparative/predict.rs
- benches/me.rs
- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/ec.rs
- src/encoder.rs
- src/lib.rs
- src/lrf.rs
- src/me.rs
- src/metrics.rs
- src/partition.rs
- src/plane.rs
- src/predict.rs
- src/quantize.rs
- src/rdo.rs
- src/scenechange/mod.rs
- src/test_encode_decode.rs
- src/transform/forward.rs
- src/transform/inverse.rs
- src/transform/mod.rs
- src/util.rs
More of it.
* Organize use statements
* Add missing license headers
* Trim trailing whitespace and redundant/outdated comments
* Fix some inconsistent indentation
> Miscellaneous clean-up

- src/api.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/test_encode_decode.rs
They match ISO/IEC 23091-4/ITU-T H.273.
Partially address #728.
> Add the missing Color config semantics enums

- src/api.rs
It is unused there, because parameters are passed to `EncoderConfig` instead.
> Remove color description from FrameInfo

- src/api.rs
Will be consumed by `crav1e` as well.
> Make the color properties repr C

- benches/bench.rs
- src/api.rs
- src/bin/common.rs
- src/encoder.rs
More work for #72.
This set allows to output the reconstruction for 4:4:4 chroma without crashing (4:2:2 is untested). The output `IVF` file for the default sequence is still undecodable. There are still likely many things to fix for higher sampling support, but this should help with debugging.
> Fix undersized frame buffers with non-4:2:0 chroma

- src/context.rs
- src/encoder.rs
- src/partition.rs
- src/rdo.rs
> [WIP] Add horz/vert (2:1 only) partitions to top-down partition rdo

- benches/bench.rs
- src/api.rs
- src/cdef.rs
- src/deblock.rs
- src/encoder.rs
- src/lrf.rs
- src/me.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
This simplifies several function signatures.
I think that a reference to a `Sequence` would be better, but currently the header writing functions require a mutable `Sequence` and `FrameInvariants`, so there are some complications with mutable borrows. It is relatively simple to transition to a reference from there.
Will probably require changes to [crav1e](https://github.com/lu-zero/crav1e/).
> Move Sequence into FrameInvariants

- src/context.rs
- src/encoder.rs
- src/lrf.rs
`lrf_type` and `unit_size` are per-plane values, there is no need to duplicate them as arrays in `RestorationState`.
(we could also rename `plane` to `planes`)
> Remove duplicate fields

- src/encoder.rs
- src/lrf.rs
- src/plane.rs
In order to prepare for the possibility to encode tiles in parallel, I implemented an iterator providing non-overlapping tiles (`TileMut<'_>`), which are a "view" on the underlying frame (see https://github.com/xiph/rav1e/pull/821).
But _frames_ are only part of the data to be split.
To encode a tile, we will also need one `TileState` (similar to `FrameState`) per tile, each providing access to the tile (`TileMut<'_>`).
In addition, currently, the `RestorationState` is used both at "tile level" (accessing only data for a specific tile, independently of other tiles) and at "frame level" (crossing tile borders). To allow tile parallelization, the same way we created `TileMut<'_>` view from a `Frame`, we can create a `TileRestorationStateMut<'_>` (or whatever the name) view from a …
> Store RestorationState into FrameState

- src/plane.rs
Previous implementation prevented uses like
let newslice = oldslice.go_left().go_up();
> Fix over restrictive borrow rules for plane slice

- src/encoder.rs
- src/lrf.rs
As I explained in #836, I want to create `TileState<'_>` views from a `FrameState`, so that we can encode tiles in parallel (several threads could work on different `TileState<'_>` simultaneously).
`FrameState` now contains (since #836) a `RestorationState`, so `TileState<'_>` will contain a `TileRestorationState<'_>`, a tiled-view of the restoration state.
However, `RestorationState` contains `RestorationPlane`s, which each in turn contain a `PlaneConfig` named `clipped_cfg`. As a preliminary step, I would like to **remove this field entirely**, to simplify the future `TileRestorationState<'_>`.
AFAIU, this _clipped_ `PlaneConfig` was used for two reasons.
`Frame`s are created with [padded width and height](https://github.com/xiph/rav1e/blob/969549044933efcdc4e98d900f63fc4fa69b3f40/src/en …
> Simplify RestorationState (prepare for tiling)

- src/encoder.rs
Only works for --speed 0.
(the earlier, the better) of four split partitions is larger than the reference one
(or current best) by avoiding further recursively splitting down.
> Early termination for bottomup partition search (i.e. speed 0 only)

- Cargo.toml
[nasm-rs 0.1.4](https://crates.io/crates/nasm-rs/0.1.4) is available. As it contains https://github.com/medek/nasm-rs/pull/21 and https://github.com/medek/nasm-rs/pull/22 there's no need to pull the dependency over Git anymore.
> Switch nasm-rs to crates.io release

- src/rdo.rs
There is a slight speed gain with no change in bdrate.
[AWCY result](https://beta.arewecompressedyet.com/?job=master_de68ab_5f%402019-01-15T22%3A37%3A23.075Z&job=test0_topdown_refactor_chkpt_5f%402019-01-16T18%3A46%3A01.349Z)
> Deduplicate checkpoint() calls in rdo_partition_decision()

- build.rs
While debugging some strange issue with @xiphmont I noticed we spend time building something we not use.
> Do not build aom examples and tools

- src/api.rs
- src/bin/common.rs
- src/test_encode_decode_aom.rs
Allows rav1e to read frames into the frame queue ahead of the current
one, to allow for future features to be added that depend on a lookahead
pass. Currently the lookahead distance is hardcoded to 10. In the
future, this would probably be configurable as a CLI option. Increasing
the lookahead distance primarily comes with a memory cost. This lookahead
implementation aims to minimize the memory cost by removing previous frames
from the queue after they are processed.
Among other items, this is necessary to implement #794.
> Implement lookahead queue

- src/encoder.rs
Don't use Option type and not use the work variables as much as possbible, esp. vector for holding modes from children, then use the main RDOOutput struct to keep the best modes.
> Improve bottomup partition code 0

- .travis.yml
- src/context.rs
- src/ec.rs
- src/lib.rs
- src/plane.rs
- src/predict.rs
- src/quantize.rs
- src/rdo.rs
This PR adds Clippy (a linter for code quality verification) to the CI pipeline.
Currently, in order to prevent build failures and minimize the amount of noise in the build output, all errors and warnings are disabled. The idea is to start enabling different lints and lint categories slowly, one by one, fixing all found warnings and errors, so that such changes would be minimal and wouldn't affect anyone else.
Some files with `cfg_attr` attributes for Clippy had to be modified, because otherwise Clippy would treat them as warnings, since they're deprecated. Clippy is configured to treat warnings as errors, so this would cause build failures. I didn't find a way to ignore such issues, so I decided to simply fix them, because changes that they cause are quite small.
> Add Clippy to CI

- src/encoder.rs
- src/rdo.rs
This also makes it possiblt to remove all .clone() calls to
the return value of rdo_mode_decision().
> The rdo_mode_decision() only  returns RDOPartitionOutput struct

- .travis.yml
Some small patches to the Travis CI
- Update `cmake` to `3.13.3`
- Update `nasm` to `2.14.02`
- Only install `cargo-kcov` on job that uses it
- Merge `Doc` and `Clippy` jobs since both are very quick
- Test `build` in `--release` configuration
Reduces total run time from about 1 hr 6 min to about 57 min.
>  Travis CI: Cleanup & update dependencies

- src/bin/common.rs
Replaces #888.
Some small changes to the CLI output
- Adds a estimated time
- Adds a 3rd decimal to fps
Previous CLI output: 
```encoded 60/120 frames, 0.25 fps, 1075.22 Kb/s, est. size: 0.26 MB```
New CLI output: 
```encoded 60/120 frames, 0.248 fps, 1075.22 Kb/s, est. size: 0.26 MB, est. time: 242 s```
> Add estimated time and 3rd decimal to fps in CLI output

- src/context.rs
- src/encoder.rs
Fix the bug that update_partition_context() has been called for rectangular partition.
This bug has probably been introduced due to the design differences between rav1e and libaom.
The rav1e recursively calls the partitioning function until the final leaf block (and encode the block in the same function), while libaom calls dedicated encode block function once partitioning is finished.
> Fix update_partition_context() to be not called for rect partition

- .travis.yml
- src/cdef.rs
- src/context.rs
- src/encoder.rs
- src/rdo.rs
This PR enables lints from the [clippy::style](https://rust-lang.github.io/rust-clippy/master/index.html) category, and fixes the [clippy::redundant_field_names](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names) warnings.
Other lints from the style category, that are causing warnings, were disabled, in order to keep the amount of noise and changes as minimal as possible.
> Fix warnings caused by redundant field names

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/decoder/mod.rs
- src/decoder/y4m.rs
- src/encoder.rs
- src/lib.rs
- src/scenechange/mod.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
This allows implementing other decoders in the future, and isolates the
decoding logic into one section of the codebase, making it easier to
refactor the encode/decode tests to handle lookahead and frame
reordering the same way as rav1e.
> Refactor decoder to be codec agnostic

- src/encoder.rs
- src/rdo.rs
First, tune cdef_dist_wxh_8x8 scaling:
- Ensure ssim_boost >= 1 where svar < 4096 and dvar < 8192.
- Fix the value of ssim_boost at (0, 4096) to 5/4.
Fall back to SSE for blocks where w < 8 or h < 8.
AWCY results at [speed 1 relative to --tune=Psnr](https://beta.arewecompressedyet.com/?job=rav1e-s1%402019-02-01T15%3A39%3A55.533Z&job=rav1e-s1-psy-9%402019-02-04T11%3A22%3A43.572Z):
|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |    ---: |    ---: |       ---: |
| 1.1413 | -6.4113 | -6.5019 |  -2.2832 | -6.5178 | -6.9733 |    -3.4859 |
AWCY results at [speed 2 relative to prior constants](https://beta.arewecompressedyet.com/?job=rav1e-s2-psy%402019-02-01T01%3A14%3A38.035Z&job=rav1e-s2-psy-9%402019-02-04T07%3A03%3A17.426Z): …
> Allow sub-8x8 partitions with --tune=Psychovisual

- .travis.yml
- src/cdef.rs
- src/context.rs
- src/me.rs
- src/transform/forward.rs
This PR enables Clippy's [let_and_return](https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return) and [needless_return](https://rust-lang.github.io/rust-clippy/master/index.html#needless_return) lints, and fixes related warnings.
P.S. I also noticed something strange, which is not related to this PR, but I think it's worth mentioning. Some blocks of code are marked with `#[cfg(debug)]` attributes ([for example](https://github.com/xiph/rav1e/blob/31bf6a6c91d323402ba81aa3a75862ca2a3c49cc/src/context.rs#L1810)). The intent is clear - to have additional functionality in debug builds, which must not present in the release ones. The problem is that there's no such configuration in Rust. So, currently, all code that is marked with such attribute is completely ignored. The …
> Fix warnings caused by non-idiomatic returns

- src/cdef.rs
> cdef: use left-most direction in case of ties

- src/api.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
Fixes #890. Also fixes the tests to test frame reordering and lookahead correctly.
> Fix infinite loop for very short clips with frame reordering

- src/api.rs
- src/bin/common.rs
Note in the help text which is the default.
Fix #905.
> Disable low_latency by default

- src/bin/common.rs
Right now if someone specifies `--keyint 10` for instance the interface will complain that it is lower than the minimum interval. For CLI usage it seems more practical to just set the minimum keyframe interval to match rather than force the user to add an additional option.
If `--min-keyint` is also specified, it will not be overridden.
> Override min-keyint in CLI if keyint is smaller

- benches/bench.rs
- src/api.rs
- src/bin/common.rs
- src/bin/decoder/mod.rs
- src/bin/decoder/y4m.rs
- src/bin/rav1e.rs
- src/encoder.rs
- src/partition.rs
- src/predict.rs
- src/scenechange/mod.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
as mentioned in #910 this should simplify the api a bit and other portions of the codebase
relevant commit message:
>    VideoDetails is mainly used while decoding y4m, but it is carried
>    around in the configuration, initializing various internal structures.
>
>   Having all encoding-related fields in a single structure simplifies
>  setting up and configuring the encoder, as well as offering
> an easier-to-use and more expandable API.
> Simple config

- src/partition.rs
I misread the specification in #784, this fixes reconstruction output for 4:4:4 encoding.
> Fix chroma transform sizes with 4:4:4 sampling

- README.md
Switch AppVeyor badge link to https://ci.appveyor.com/project/tdaede/rav1e/history
Migrates #935
> Update AppVeyor link in README.md

- Cargo.toml
Without it, a vendored version of the crate won't build.
> Include `build.rs` in the set of files

- README.md
- src/api.rs
- src/encoder.rs
- src/partition.rs
- src/rdo.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
This reverts an erroneous commit that caused intra frames in 4:4:4 to no longer be decodable, and fixes some additional issues. 4:4:4 and 4:2:2 encoding now work down to `-s 0` with keyframes only (enforced on the API end) and restoration disabled. CfL prediction is also disabled based on a comment from @barrbrain.
> Support degraded 4:2:2/4:4:4 encoding

- src/api.rs
This way, the default speed (3) always uses pixel domain distortion
which is easier to understand while we figure out what our quantizers
should look like, how to set lambda, what distortion metrics to use,
etc.
Note that this only affects --tune Psnr since --tune Psychovisual always
uses (weighted) pixel domain distortion.
> Enable tx domain distortion at speed >= 4 instead of >= 1

- src/encoder.rs
- src/rdo.rs
Fully use tx-domain distortion with topdown partition search
The 'needs_rec' parameter for one of the two rdo_mode_decision() calls by
topdown parition search has been passed with wrong value.
It should be false, since re-encoding step follows once rdo_mode_decision()
decided the mode.
In fact, we don't need 'needs_rec' parameter in rdo_mode_decision(), so remove it.
This patch will cause loss of coding efficiency (0.1250% at speed 1)
with a small speedup.
However, if there is more than one intra prediction blocks in a
partition, i.e. tx_size < partition size, rdo_mode_decision() will need
generate reconstrtucted pixels for intra prediction modes. Sine tx
partition is not provided by rav1e yet, this condition can be
implemented in the future.
> Fully use tx-domain distortion (when chosen) with topdown partition search

- benches/me.rs
- src/me.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
More warnings showed up following the previous pass. This should clear the remaining warnings in the benchmarks and the main codebase.
> Remove leftover unnecessary "mut"s

- src/api.rs
- src/encoder.rs
- src/lib.rs
- src/me.rs
- src/quantize.rs
- src/rate.rs
- src/rdo.rs
This is an adaptation of [tterribe/rate_control3c](https://git.xiph.org/?p=users/tterribe/rav1e.git;a=shortlog;h=refs/heads/rate_control3c):
* Compute and store lambda in the FrameInvariants
* Add a skeleton rate control API
* Use the same quantizer for DC and AC coefficients
With credit to @smarter for the inital rebaseline effort.
In addition, some adjustment of quantizer choice:
* Pick a quantizer between similar DC and AC entries
> Add a skeleton rate control API

- src/rdo.rs
Use sum-of-squared error as the distortion metric for picking CDEF parameters with --tune=Psnr.
AWCY results [relative to metric from libaom](https://beta.arewecompressedyet.com/?job=rav1e-s2%402019-02-01T01%3A14%3A08.420Z&job=rav1e-s2-cdef-sse%402019-02-04T16%3A59%3A28.508Z):
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| -0.1880 |  0.0690 |  0.2093 |   0.0097 | 0.4081 |  0.3468 |    -0.2152 |
> Use SSE for CDEF RDO with --tune=Psnr

- src/encoder.rs
https://github.com/xiph/rav1e/issues/877
In addition to PARTITION_SPLIT, fully enable early-exit for HORZ
and VERT partition types. This gives further reduction of encoding time
at speed 0, now x3 and x2 for Qindex 252 and 220, resp.
It turns out that the broken directional intra prediction has been
the curprit of bdrate change when enabling full early-exit with bottomup
partition search.
> Enable full early-exit for bottomup partition search

- Cargo.toml
- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/encoder.rs
- src/lib.rs
More data will likely be added to this stats file in the future.
Adds in `--pass 1` or `--pass 2` CLI options to prepare for two-pass encoding.
Currently the only difference between these, or omitting the option (which assumes
one-pass encoding) is that using `--pass 1` outputs the stats file. This will be added to
and optimized later.
Closes #898
> Output JSON stats file with frame types

- src/predict.rs
- src/quantize.rs
- src/transform/inverse.rs
- src/util.rs
In order to use either `u8` or `u16` for plane components, a `Pixel` trait regroups several "capabilities" that a generic pixel type must support, through trait inheritance.
That way, a generic function can just use the Pixel type, without listing them all:
```rust
fn f<T: Pixel>(...) { ... }
```
However, trait inheritance cannot express constraints about `T` for other types (like `i32: AsPrimitive<T>`). As a consequence, callers had to specify these additional constraints manually:
```rust
where
T: Pixel,
i32: AsPrimitive<T>,
u32: AsPrimitive<T>,
```
This is redundant, because if `T` is a `Pixel`, then `i32` and `u32` necessarily implement `AsPrimitive<T>` (since Pixel is only implemented for `u8` and `u16`).
To express these relationships, create a new trait, `CastFromPrimitive<T>`, …
> Improve generic usage of Pixel trait 

- src/api.rs
- src/bin/common.rs
Defaults block size to 16x16
Allows specifying multiple settings at once (space separated)
Uses low_latency setting specified on CLI during speed-test
> Fixes for speed-test option

- src/api.rs
- src/bin/common.rs
- src/encoder.rs
- src/me.rs
- src/rate.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
This is an adaptation of [tterribe/rate_control8](https://git.xiph.org/?p=users/tterribe/rav1e.git;a=shortlog;h=refs/heads/rate_control8):
> This is just the minimal patch required to get something working. There are still plenty of TODOs left to do: two-pass support, VFR support, golden frame support, the ability to drop frames, trial encodes for the first frames, quantization matrices, separate quantizer choices for Cb and Cr, proper lossless handling, support for AV1's levels, and some general refactoring to improve maintainability.
> Add basic 1-pass rate control

- src/api.rs
- src/plane.rs
With frame reordering enabled, every other frame would be compared to a
blank frame, generating a very low PSNR calculation. Also fixes an issue
where the PlaneIter ends one pixel too early, which currently is only
used by PSNR calculation.
> Fix miscalculation of PSNR with frame reordering

- src/bin/common.rs
It is implemented as an advanced command line option.
Run `rav1e advanced --help` for the list of supported shells.
> Add Shell auto-completion support

- benches/bench.rs
- benches/me.rs
- src/api.rs
- src/bin/common.rs
- src/bin/decoder/mod.rs
- src/bin/decoder/y4m.rs
- src/bin/muxer.rs
- src/bin/rav1e.rs
- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/header.rs
- src/lib.rs
- src/lrf.rs
- src/mc.rs
- src/me.rs
- src/metrics.rs
- src/partition.rs
- src/plane.rs
- src/predict.rs
- src/rate.rs
- src/rdo.rs
- src/scenechange/mod.rs
- src/segmentation.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
- src/transform/mod.rs
- src/util.rs
In order to support both `u8` and `u16` for plane components, make the `Plane` structure generic over the component type. As a consequence, many other structures and functions also become generic.
Some functions are not `u8`-compatible yet, although they have been make generic over the component type to make the compilation work. They assert that the size of the generic parameter is 16 bits wide.
For this reason, the root context structure is unconditionally created as `Context<u16>` for now.
> Make plane generic over pixel component type

- src/rdo.rs
When `svar*dvar` is small or even zero and `bit_depth > 8`, the overflow results in taking the square-root of a negative number which yields `NaN`. This is cast to `u64` as `1 << 63`, causing overflow on unsaturated add later in `cdef_dist_wxh`.
> Resolve an overflow on left-shift cdef_dist_wxh_8x8

- src/cdef.rs
- src/context.rs
- src/ec.rs
- src/encoder.rs
- src/lrf.rs
- src/plane.rs
- src/rdo.rs
he impact of LRF is currently quite muted, as we're locked to the smallest possible loop restoration unit size right now (LRU == SB) and the coding overhead is very high.
> Add limited (first cut) but true CDEF <-> LRF aware loop filter RDO to rav1e

- src/deblock.rs
This PR is an alternative to #1023.
It avoids the confusion caused by both "pitch" and `stride` parameters, and paves the way to replace `slice` and `stride` by `Plane(Mut)Slice`.
The change can seem unnecessary, because currently horizontal and vertical versions access the plane buffer "directly". When we replace slice+stride by `Plane(Mut)Slice`, the access will be different for each directions.
> Split horizontal/vertical deblocking functions

- src/rate.rs
Avoids a panic for extremely low complexity frames. Fixes #1020.
> Clamp quantizer indices pending lossless support

- src/api.rs
- src/bin/rav1e.rs
Fixes #1036 where encoder would hang at end of video if `--limit` not
used
Fixes issue where encoder would read too many frames, causing high
memory usage
> Fix issues with reading lookahead

- src/cdef.rs
- src/deblock.rs
- src/encoder.rs
- src/lrf.rs
- src/mc.rs
- src/me.rs
- src/partition.rs
- src/plane.rs
- src/rdo.rs
- src/transform/inverse.rs
- src/util.rs
Currently, many functions access rectangular regions of planes (spanning multiple rows) via a primitive slice to the whole plane along with the stride information.
This strategy is not compatible with tiling, since this borrows the memory belonging to other tiles.
This is basically what I explained in https://github.com/xiph/rav1e/issues/631#issuecomment-456088577.
Therefore, only expose separate rows in `PlaneSlice`.
Concretely, here are the changes from the caller point of view:
```rust
// get a specific row
// before
let row = plane_slice.as_slice()[y * stride..(y + 1) * stride];
// or if we don't care about the end
let row = plane_slice.as_slice()[y * stride..];
// after
let row = &plane_slice[y];
```
```rust
// get a component value
// before
let value = plane_slice.as_slice()[y * …
```
> Expose separate rows from PlaneSlice

- .travis.yml
- src/api.rs
This PR enables the Clippy's [get_unwrap](https://rust-lang.github.io/rust-clippy/master/index.html#get_unwrap) lint, and fixes all warnings caused by it.
> Use the Index trait ([]) instead of .get().unwrap()

- .travis.yml
- src/api.rs
- src/bin/common.rs
- src/test_encode_decode_aom.rs
Makes use of all 10 speed levels, and updates the CLI help text to
reflect which settings are enabled at specific speed levels.
This also changes the default speed level to 5.
Based on benchmarks which are viewable (at least for the time being) [here](https://condor3280.startdedicated.com/files/rav1espeed/). Closes #1015
> Rebalance speed levels based on benchmarks

- .travis.yml
- src/me.rs
- src/rdo.rs
This PR enables the Clippy's [ptr_arg](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg) lint, and fixes all warnings caused by it.
> Enable the Clippy's ptr_arg lint

- benches/predict.rs
- src/cdef.rs
- src/deblock.rs
- src/encoder.rs
- src/lrf.rs
- src/mc.rs
- src/partition.rs
- src/plane.rs
- src/predict.rs
- src/transform/inverse.rs
- src/transform/mod.rs
This PR is to `PlaneMutSlice` what #1035 was to `PlaneSlice`.
~It is written over #1040 (so ignore the first commit).~
> Expose separate rows from PlaneMutSlice

- src/util.rs
The compiler wasn't doing this for encode_tx_block, among others.
Seems to speed up intra functions a bit? It's in the noise though.
> Inline cast_from always.

- src/context.rs
- src/header.rs
- src/lrf.rs
- src/rdo.rs
In `RestorationState`, the field is an array of 3 planes, so use the plural form (as in `Frame::planes`).
---
(I was annoyed by sometimes writing `plane` and sometimes `planes` for the same meaning, and that way the naming in my tiling structures may be consistent)
> Rename "plane" to "planes"

- src/cdef.rs
- src/deblock.rs
- src/mc.rs
- src/partition.rs
- src/predict.rs
- src/transform/inverse.rs
- src/transform/mod.rs
In #1035 and #1043, I added many unnecessary explicit lifetimes. Let's fix that (and some others).
---
Most of the replacements are equivalent, and some of them relax unnecessary constraints. For example:
```rust
&'a mut Type<'a>
```
is rewritten:
```
&mut Type<'_>
```
In that case, the lifetime of the reference need not be the same as the one bound to the type.
<https://doc.rust-lang.org/nightly/edition-guide/rust-2018/ownership-and-lifetimes/the-anonymous-lifetime.html>
<https://doc.rust-lang.org/book/ch19-02-advanced-lifetimes.html#the-anonymous-lifetime>
> Remove unnecessary explicit lifetimes

- Cargo.toml
- src/lib.rs
- src/test_encode_decode.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
Closes #956
Some dav1d tests are known to fail due to rounding errors.
This is an existing issue and is not resolved in this commit.
> Refactor encode-decode tests to reduce duplication

- src/bin/common.rs
- src/bin/rav1e.rs
In x265 and other encoders, there are options to skip n number of frames while in rav1e, as_of_now we don't have support to skip n frames.
With this users can skip n frames easily.
For example:
```
cargo run --release --bin rav1e  /Volumes/buildBox/rav1e/dummyData/ducks_take_off_420_720p50.y4m --skip 450 --limit 454 -o test.ivf -v
Finished release [optimized] target(s) in 0.77s
Running `target/release/rav1e /Volumes/buildBox/rav1e/dummyData/ducks_take_off_420_720p50.y4m --skip 450 --limit 454 -o test.ivf -v`
1280x720 @ 50/1 fps
newLimit 4
Frame 0 - Key frame - 181632 bytes - encoded 1/4 frames, 0.083 fps, 70950.00 Kb/s, est. size: 0.69 MB, est. time: 36 s
Frame 1 - Inter frame - 82332 bytes - encoded 2/4 frames, 0.065 fps, 51555.47 Kb/s, est. size: 0.50 MB, est. time: 31 s
Frame 2 - Inter …
```
> Add option to skip n frames of a video

- src/bin/rav1e.rs
The default value of 0 is skipping the first frame.
> Fix an off-by-one with --skip parameter

- src/context.rs
There is no need to compute the superblock offset and the block offset &inside the superblock separately.
> Simplify plane_offset()

- build.rs
- src/bin/rav1e.rs
- src/cdef.rs
- src/encoder.rs
- src/me.rs
- src/plane.rs
- src/rdo.rs
- src/test_encode_decode.rs
- src/test_encode_decode_aom.rs
- src/test_encode_decode_dav1d.rs
- src/transform/mod.rs
- src/x86/sad_sse2.asm
Fix all of the paths that do not currently support u8 and at least match the performance of u16.
> Use u8 pixels for sequences of bitdepth 8

- src/plane.rs
The feature is already provided by the `Index` and `IndexMut` traits (i.e. operator[]).
Concretely, we always use:
plane_slice[index]
instead of:
plane_slice.row(index)
> Remove row() method from Plane(Mut)Slice

- src/me.rs
The initial fall-back logic was a bit too pessimistic since 4x4 and 8x8 don't have strict alignment requirements. This removes the fall-back to the Rust-native function on sub-16x16 alignment.
From an [AWCY run](https://beta.arewecompressedyet.com/?job=master-85c8e57e982cc81cd02877e94604605c8de6939b&job=sad-alignment%402019-03-08T09%3A27%3A01.118Z) we see a tiny improvement up to 0.4%.
> Allow unaligned sad_sse2 calls below 16x16

- src/encoder.rs
- src/partition.rs
- src/plane.rs
- src/rdo.rs
This is an alternative to #1071.
This PR introduces a new structure to hold a slice with its edges, so that a subslice never exceeds its parent slice, and uses it to get rid of `go_up()` and `go_left()` from `PlaneMutSlice`.
I think the resulting code is less confusing than #1071.
> Avoid out-of-slice accesses from PlaneMutSlice (alternative)

- src/util.rs
Since commit 0a35174f959269c147a497e7ac4ee8843f393107, the function `convert_slice_2d()` is not used anymore.
> Remove unused convert_slice_2d()

- .travis.yml
- src/cdef.rs
- src/encoder.rs
- src/lrf.rs
- src/transform/forward.rs
This PR enables the Clippy's [erasing_op](https://rust-lang.github.io/rust-clippy/master/index.html#erasing_op), [identity_op](https://rust-lang.github.io/rust-clippy/master/index.html#identity_op), and [neg_multiply](https://rust-lang.github.io/rust-clippy/master/index.html#neg_multiply) lints, and fixes all warnings and errors caused by them.
I disabled some lints for some functions, because they have code like [this](https://github.com/xiph/rav1e/blob/714765bded83d76d93e804f44cff06f4c067eaa7/src/transform/forward.rs#L1575), [this](https://github.com/xiph/rav1e/blob/714765bded83d76d93e804f44cff06f4c067eaa7/src/cdef.rs#L141), and [this](https://github.com/xiph/rav1e/blob/714765bded83d76d93e804f44cff06f4c067eaa7/src/encoder.rs#L607). I don't fully understand the meaning of these numbers, …
> Remove meaningless operations

- src/api.rs
- src/bin/common.rs
- src/cdef.rs
- src/encoder.rs
- src/rdo.rs
This facilitates testing the the impact on complexity and efficiency of enabling CDEF. This also restores the logic for when CDEF is disabled, which was temporarily removed while enabling `u8` encdoing paths. AWCY results at [default settings](https://beta.arewecompressedyet.com/?job=master-97fc520bf6c65cd8a2fb8e0a3333d3e658faccf3&job=cdef-speed-setting-else%402019-03-11T12%3A46%3A40.215Z) show no change in output.
> Add a speed setting for CDEF

- src/plane.rs
This is required for enabling AVX2 assembly on Windows. It even passes on AppVeyor now.
> Align PlaneData to 32 bytes on Windows

- src/me.rs
The functions `sad_ssse3()` and `sad_sse2()` only support `u16` and `u8` respectively, so they are not generic.
Make the caller pass the expected type.
> Remove fake-genericity from sad functions

- src/api.rs
This function is not needed in rust and it is mostly a convenience for
other languages. Instead move this chunk in the appropriate bindings.
> api: Drop parse() function from Config

- benches/me.rs
- src/me.rs
In tests, the function `get_sad()` was called with block width and block height parameters swapped.
As a consequence, associate the precomputed SAD values to the transposed block size.
> Fix get_sad() tests

- src/encoder.rs
- src/partition.rs
- src/rdo.rs
To compute the number of pixels available in the top-right and bottom-left edges, `get_intra_edges()` received `frame_w_in_b` (`MiCols`) and `frame_h_in_b` (`MiRows`) as parameters, initialized as follow:
MiCols = 2 * ( ( FrameWidth + 7 ) >> 3 )
MiRows = 2 * ( ( FrameHeight + 7 ) >> 3 )
<https://aomediacodec.github.io/av1-spec/#compute-image-size-function>
The sizes computed by `get_intra_edges()` were basically the frame dimensions rounded up to the next multiple of 8, decimated:
(MI_SIZE >> plane_cfg.xdec) * frame_w_in_b
(MI_SIZE >> plane_cfg.ydec) * frame_h_in_b
But in `Frame::new()`, the luma plane dimensions are also initialized with the frame dimensions rounded up to the next multiple of 8. Therefore, it is equivalent to directly use the plane dimensions.
> Retrieve dimensions from plane_cfg

- src/context.rs
- src/transform/forward.rs
Benchmarks `write_b_bench(TX_4X4, _)` improved by ~20%; `write_b_bench(TX_8X8, _)` by ~8%.
> Avoid superfluous memset in transforms and coeff coding

- src/me.rs
- src/rdo.rs
> Move motion_estimation to a trait

- src/mc.rs
Fixes the underlying issue of #1115.
> Cast before left shift in native prep_8tap

- .travis.yml
- src/rdo.rs
- src/transform/forward.rs
This PR enables the Clippy's [manual_memcpy](https://rust-lang.github.io/rust-clippy/master/index.html#manual_memcpy) lint, and fixes all warnings caused by it.
> Enable the Clippy's manual_memcpy lint

- src/cdef.rs
- src/lrf.rs
- src/me.rs
- src/util.rs
The intent of most of these functions is akin to C macros. Inlining them honors that intent.
> Inline often called and almost-trivial functions

- .travis.yml
- src/context.rs
- src/encoder.rs
This PR enables the Clippy's [if_same_then_else](https://rust-lang.github.io/rust-clippy/master/index.html#if_same_then_else) lint, and fixes all errors caused by it.
> Enable the Clippy's if_same_then_else lint

- src/encoder.rs
- src/me.rs
- src/rdo.rs
The motion vectors were stored in a `Vec<Vec<MotionVector>>`.
The innermost `Vec` contains a flatten matrix (`fi.w_in_b` x `fi.h_in_b`) of `MotionVector`s, and there are `REF_FRAMES` instances of them (the outermost `Vec`).
Introduce a typed structure to replace the innermost `Vec`:
- this improves readability;
- this allows to expose it as a 2D array, thanks to `Index` and `IndexMut` traits;
- this will allow to split it into (non-overlapping) tiled views, containing only the motion vectors for a bounded region of the plane (see <https://github.com/xiph/rav1e/pull/1126>).
> Add struct FrameMotionVectors

- .travis.yml
- src/encoder.rs
- src/me.rs
- src/rdo.rs
This PR enables the Clippy's [len_zero](https://rust-lang.github.io/rust-clippy/master/index.html#len_zero) lint, and fixes all warnings caused by it.
> Enable the Clippy's len_zero lint

- benches/bench.rs
- benches/me.rs
- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/lrf.rs
- src/me.rs
- src/partition.rs
- src/plane.rs
- src/rdo.rs
`BlockOffset` has a size of 128 bits (the same as a slice), and is trivially copyable, so make it derive `Copy`.
Once it derives `Copy`, [clippy suggests to never pass it by reference](https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref).
So pass it by value everywhere to simplify usage.
In particular, this avoids lifetimes bounds where not necessary:
```diff
@@ -1044,8 +1044,8 @@ pub fn rdo_tx_type_decision<T: Pixel>(
best_type
}
-pub fn get_sub_partitions<'a>(four_partitions: &[&'a BlockOffset; 4],
-                              partition: PartitionType) -> Vec<&'a BlockOffset> {
+pub fn get_sub_partitions(four_partitions: &[BlockOffset; 4],
+                          partition: PartitionType) -> Vec<BlockOffset> {
let mut partitions = vec![ …
```
> Make BlockOffset derive Copy

- src/context.rs
- src/me.rs
In motion estimation, several functions received both the offset expressed in blocks and in pixels for the luma plane. This information is redundant: a block offset is trivially convertible to a luma plane offset.
With tiling, we need to manage both absolute offsets (relative to the frame) and offsets relative to the current tile. This will be more simple without duplication.
> Do not pass both BlockOffset and PlaneOffset

- src/me.rs
This is redundant. For consistency, keep `blk_w` and `blk_h`.
> Do not pass both (blk_w, blk_h) and BlockSize

- src/me.rs
Some functions accepting an `Arc` don't want to share ownership: they just require a reference.
> Remove some unnecessary Arc

- Cargo.toml
This shows a pretty nice improvement of ~15% on encode block
benchmarks.
> Enable LTO on release and bench builds.

- src/cdef.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
BlockContext was borrowed but only read.
> Avoid unneeded mutable borrows on BlockContext

- src/context.rs
`BlockContext::checkpoint()` returned a whole copy of `BlockContext`, while only a subset of its fields were actually part of the checkpoint. The other fields, unused, were filled by default values.
Instead, use a structure dedicated to `BlockContext` checkpoints, containing only the relevant fields.
> Add checkpoint structure for BlockContext

- benches/bench.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/entropymode.rs
- src/header.rs
- src/partition.rs
- src/rdo.rs
Currently there is no RDO and split one leve partition of transforms for intra block.
Also, for intra frame only because enabling tx_mode_select (in frame header) in any inter frame requires necessary signaling of var-tx for inter mode blocks, which we don't have yet.
Deblocking is disabled since it causes mismatch between encoder and decoder's reconstructed images. Communicated with Monty and he figured out why and stared to modify deblocking filter code.
> Transorm block partition for intra

- src/encoder.rs
- src/rdo.rs
Enabled for speed <= 2, i.e. when fi.config.speed_settings.rdo_tx_decision == true
&& INTRA frame only.
TODO: Currently, partition depths are 0 or 1. Plan to fix for max depth 2 in a separate patch.
> RDO of transform size for intra block

- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/header.rs
- src/me.rs
- src/partition.rs
- src/rdo.rs
Moves all functions that previously used usize to this type.
Instead of direct conversions to a slot number, use a to_index fn.
This also changes the size of the global mv state and context
ref counting arrays as they don't need LAST_FRAME.
> Create RefFrame enum.

- src/context.rs
The methods `above_of()`, `left_of()` and `above_left_of()` returned the matching block by value, or a default block if the offset resulted in a block outside boundaries.
The Block structure is quite big (`std::mem::size_of::<Block>() == 120`). For reading a field, it is probably not optimal to return a whole `Block` copy or a new default block (although the compiler might optimize such accesses).
Moreover, the boundaries checks were often redundant, because already done by the callers.
Instead, let the callers check boundaries and return a reference to the matching block.
> Return blocks by reference, not by value

- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
Some `BlockContext` methods are specific to `FrameBlocks`, so move them.
With tiling, the lifetime of `FrameBlocks` will exceed that of `BlockContext` (which will exist only during tile encoding).
This paves the way to move `FrameBlocks` out of `BlockContext`.
> Move methods from BlockContext to FrameBlocks

- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
For convenience, implement `Index` and `IndexMut` traits with `BlockOffset` index for `FrameBlocks`. That way, we can index a block directly from a `BlockOffset`:
```rust
let bo = BlockOffset { x, y };
// before
bc.blocks.at_mut(bo).neighbors_ref_counts = ref_counts;
// after
bc.blocks[bo].neighbors_ref_counts = ref_counts;
```
---
This is a superficial change, but I propose it now because I will do (did on my local branch) it for the tiled version on my local branch.
> Replace at() and at_mut() by operator[]

- src/encoder.rs
TD-Linux on IRC:
> superframe anti emulation was dropped from the spec mid development
> Remove "superframe anti emulation" byte

- benches/bench.rs
- src/cdef.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
`FrameBlocks` is part of the `BlockContext` structure. Many functions which used only the `FrameBlocks` (but not the other `BlockContext` fields) received a reference to the whole `BlockContext` as parameter.
`FrameBlocks` will survive tiles-encoding: it will be accessed through a tiled version for each tile, then frame-wise after all tiles are encoded.
However, `BlockContext` will only be used tile-wise: there will be one instance per tile, destroyed once the tile is encoded. Therefore, frame-wise functions may not receive the whole `BlockContext` anymore
(all tile-specific `BlockContext` instances won't exist anymore).
> Pass FrameBlocks instead of BlockContext

- src/context.rs
The code was inspired by libaom, which calls `scan_blk_mbmi()` unconditionally:
<https://aomedia.googlesource.com/aom/+/9a7e8768d39793963725da754e61d8115e2404d0/av1/common/mvref_common.c#490>
<https://aomedia.googlesource.com/aom/+/9a7e8768d39793963725da754e61d8115e2404d0/av1/common/mvref_common.c#549>
However, the boundaries are checked in the implementation of `scan_blk_mbmi()`:
<https://aomedia.googlesource.com/aom/+/9a7e8768d39793963725da754e61d8115e2404d0/av1/common/mvref_common.c#251>
Check that the given offset will not make the resulting block offsets negative (and wrap).
Also refactor `get_comp_mode_ctx()` and `get_comp_ref_type_ctx()` to never create negative block offsets.
Fixes <https://github.com/xiph/rav1e/issues/1103>.
> Avoid negative (and unsigned) block offsets

- .travis.yml
- src/cdef.rs
- src/deblock.rs
- src/ec.rs
- src/encoder.rs
- src/lrf.rs
- src/rate.rs
- src/rdo.rs
This PR enables the Clippy's [precedence](https://rust-lang.github.io/rust-clippy/master/index.html#precedence) lint, and fixes all warnings caused by it.
> Enable the Clippy's precedence lint

- benches/bench.rs
- src/context.rs
- src/encoder.rs
There will be one instance of `BlockContext` and `ContextWriter`  per-tile.
However, they owned respectively `FrameBlocks` and `CDFContext`, which will survive tile-encoding to be used frame-wise, so they will have a longer lifetime.
Therefore, make `BlockContext` and `ContextWriter` reference `FrameBlocks` and `CDFContext` (instead of taking ownership).
> Use FrameBlocks and CDFContext by reference

- src/api.rs
- Drop the spurious `#[test]` attribute (caused double runs)
- Use speed level 10
> Speedup the flush tests

- src/me.rs
The first commit is just a refactor for consistency/simplicity.
The function `get_subset_predictors()` was called with block offset relative to the half-resolution frame, but used to index `FrameMotionVectors` relative to the full-resolution frame. The second commit passes the expected (IIUC) block offset.
For info, here are the [AWCY results](https://beta.arewecompressedyet.com/?job=rom1v_ref%402019-04-02T16%3A29%3A43.335Z&job=rom1v_test%402019-04-02T16%3A12%3A16.865Z).
Some values increase a little, some others decrease a little.
---
Related: what do you think about https://github.com/xiph/rav1e/issues/1171?
> Fix block offset half-resolution mismatch

- build.rs
- src/me.rs
- src/x86/sad_avx.asm
Here are the obtained bench results with a unaligned accesses:
```
Benchmarking get_sad/BLOCK_4X4: Collecting 100 samples in estimated 5.0000 s (28                                                                                get_sad/BLOCK_4X4       time:   [12.919 ns 12.926 ns 12.935 ns]
change: [-7.8931% -7.7870% -7.6862%] (p = 0.00 < 0.05)
Found 6 outliers among 100 measurements (6.00%)
2 (2.00%) high mild
4 (4.00%) high severe
Benchmarking get_sad/BLOCK_4X8: Collecting 100 samples in estimated 5.0000 s (21                                                                                get_sad/BLOCK_4X8       time:   [19.543 ns 19.551 ns 19.561 ns]
change: [-6.0339% -5.9476% -5.8651%] (p = 0.00 < 0.05)
Found 7 outliers among 100 …
```
> AVX-2 accelerated SAD functions to speedup motion estimation

- benches/me.rs
This allows to call the right ASM SAD implementation.
> SAD bench: use the right Pixel format (u8 or u16) in function of the bit depth

- benches/bench.rs
- src/ec.rs
Trash benchmarks on my threadripper:
```
$ cargo bench update_cdf_4
Finished release [optimized] target(s) in 0.08s
Running target/release/deps/bench-0f4a29071020d296
update_cdf_4_native     time:   [8.6011 us 8.6224 us 8.6451 us]                                 
change: [-1.5134% -1.1721% -0.8184%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
update_cdf_4_sse2       time:   [3.0597 us 3.0648 us 3.0700 us]                               
change: [-1.2574% -0.8472% -0.4612%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
```
Will do real benchmarks on cannon lake in a bit.
> Add update_cdf_4 sse2 implementation.

- src/api.rs
- src/bin/rav1e.rs
This should hopefully fix #1081 and make the API a bit simpler.
> Further flush fixes

- src/encoder.rs
- src/partition.rs
- src/plane.rs
- src/rdo.rs
`EdgedPlaneSlice` was added by #1082 so that a slice never needed to exceed its parent.
However, it added complexity, and happens to be insufficient to adapt `get_intra_edges()` for tiling (we can't retrieve the tile dimensions).
This "reverts" #1082 and solves the problem differently: pass the whole `Plane` (in the future, plane region associated with the tile) and its offset.
It's simpler, and it still does not require a slice to exceed its parent.
> Remove EdgedPlaneSlice

- src/me.rs
- src/x86/sad_avx.asm
Here are the `cargo bench get_sad` run on my  Core i7-8550U CPU @ 1.80GHz laptop.
The most significant performance improvement is confirmed on non-squared blocks but square blocks seems also to benefit.
```
get_sad/(BLOCK_4X4, 8)  time:   [10.148 ns 10.204 ns 10.257 ns]                                    
change: [-22.251% -21.840% -21.407%] (p = 0.00 < 0.05)
Found 19 outliers among 100 measurements (19.00%)
1 (1.00%) high mild
18 (18.00%) high severe
get_sad/(BLOCK_4X8, 8)  time:   [12.625 ns 12.698 ns 12.778 ns]                                    
change: [-50.362% -49.793% -49.211%] (p = 0.00 < 0.05)
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
get_sad/(BLOCK_8X4, 8)  time:   [10.208 ns 10.256 ns 10.308 ns] …
```
> Full ASM AVX2 accelerated version of the SAD functions

- src/encoder.rs
The vector of frame motion vectors may be moved instead of cloned.
> Remove unnecessary clone()

- src/encoder.rs
This simplifies `encode_tile_group()` and (hopefully) improves the readability of the code which retrieve the initial CDFContext.
(these are currently the 2 first commits of my #1126, which can be merged independently).
> Extract and refactor initial CDFContext

- src/encoder.rs
- src/partition.rs
- src/rdo.rs
Rate-distortion optimization for chroma-from-luma was skipped for subsamplings other than 4:2:0 due to `luma_ac()`, `is_sub8x8()` and `sub8x8_offset()` not accounting for them. Complete the implementation for all allowed subsamplings.
> Implement chroma-from-luma for 4:2:2 and 4:4:4

- src/encoder.rs
- src/rdo.rs
Commit 8412ff0b70022180c63dffab38140770c410e75a avoided some crashes on tiny images, but it was incomplete: since it did not execute subsampled motion estimation with 32x32 blocks when the image was smaller, it left the array of `Option<MotionVector>` full of `None`, while `rdo_mode_decision()` unwrapped the values.
If the option is `None`, use a default `MotionVector` instead to fix the problem.
> Do not crash on very tiny images

- src/ec.rs
> Only use update_cdf_4_sse2 on x86_64.

- ivf/Cargo.toml
Avoid a cargo warning.
The license file itself is redundant, but some downstream apparently need it.
> Drop a redundant entry

- src/encoder.rs
- src/rate.rs
Plumb the quantizer indices through from rate-control and mimic the plane-level quantizer interpolation from Daala.
[AWCY results at default speed](https://beta.arewecompressedyet.com/?job=master-bda810b66b57c0c128d5bc8f689b0db802f80c77&job=uv-delta-q%402019-04-12T15%3A37%3A57.659Z):
|   PSNR |  PSNR Cb |  PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |     ---: |     ---: |     ---: |   ---: |    ---: |       ---: |
| 7.2036 | -31.2794 | -49.6207 |   7.7265 | 6.8570 |  7.2429 |    -8.7732 |
<details>
|                                                       Video |    PSNR | PSNR HVS |    SSIM | CIEDE 2000 |  PSNR Cb |  PSNR Cr |   APSNR | APSNR Cb | APSNR Cr | MS SSIM |    VMAF |
|                                                        ---: |    ---: |     ---: |    ---: | …
> Separate quantizers for chroma planes

- benches/me.rs
- src/me.rs
The [comment](https://github.com/xiph/rav1e/pull/1111#issuecomment-472889389) points out that the order of parameters in the get_sad() function is not as per the usual norm of WxH
This pull tries to solve that.
> get_sad() Parameter rearrangement

- src/rdo.rs
Commit 3d8c463c5bbbb2f69c1c8b388bc3efad0de66cc5 reversed the width and height parameters of `get_sad()`. Reverse the arguments for one missing call.
> Fix get_sad() arguments order

- src/api.rs
- src/encoder.rs
This fine-grained parallelization caused performance drop with parallel tile encoding.
Here is an example with 8 tiles, not parallelizing gives a speed up of ~1.24x.
**Before:**
```
$ time target/release/rav1e \
--tile-cols-log2 2 \
--tile-rows-log2 1 \
Netflix_Crosswalk_1920x1080_60fps_8bit_420_60f.y4m \
-o video.ivf
1920x1080 @ 60/1 fps
encoded 60 frames, 0.403 fps, 3950.45 Kb/s
Key Frames:      1    avg size:   46692 B
Inter:          59    avg size:    7779 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
real    2m28,724s
user    11m17,732s
sys     0m4,482s
```
**After:**
```
$ time target/release/rav1e \
--tile-cols-log2 2 \
--tile-rows-log2 1 \
Netflix_Crosswalk_1920x1080_60fps_8bit_420_60f.y4m \
-o video.ivf
1920x1080 @ 60/1 fps
encoded 60 …
```
> Don't parallelize coarse motion estimation

- src/encoder.rs
In commit 1d39058af520661010798241de6029477371e395, I didn't notice that the offsets were different for each `save_block_motion()` call.
As a result, objective quality results [decreased](https://beta.arewecompressedyet.com/?job=master-cd3ef475ba6a2a7d9832e78dbc296f64e6e7a859&job=master-3c2aebf88ab6f1218f87f37527861afb2547ef6b):
```
0.3851 |  0.3281 |  0.3225 |   0.3801 | 0.3967 |  0.3853 |     0.3381
```
I launched a AWCY job, there is no objective quality difference now: 
```
0.0000 |  0.0000 |  0.0000 |   0.0000 | 0.0000 |  0.0000 |     0.0000
```
https://beta.arewecompressedyet.com/?job=master-cd3ef475ba6a2a7d9832e78dbc296f64e6e7a859&job=fix_subme%4020 …
> Fix refactor of subsampled motion estimation

- Cargo.toml
- src/context.rs
- src/ec.rs
Activate it with feature=desync_finder rather than debug.
Print to stdout rather than stderr because the latter deadlocks.
> Bring back desync_finder from the dead.

- src/api.rs
The additional Pixel bound is spurious and wrong.
> Fix the send_frame bound

- src/api.rs
- src/bin/rav1e.rs
- src/test_encode_decode.rs
It is not really needed and if we want to continue encoding after a flush we should use a different mean.
> Remove set_limit from the public API

- src/tiling/plane_region.rs
The lifetime in Index and IndexMut trait implementation can be anonymous.
All tiling structures implementing `Index` and `IndexMut` use an anonymous lifetime, except plane regions. Fix this inconsistency.
> Use anonymous lifetimes where relevant

- src/encoder.rs
Replace `par_iter()` by `into_par_iter()` so that the tile contexts may be consumed.
> Consume tile contexts to avoid a clone()

- src/bin/common.rs
This PR fixes the issue #1224. It changes the low_latency option that takes a boolean value to a flag, which can be used without arguments. If the flag is present, the low latency mode is enabled; otherwise, it's disabled.
> Change the low_latency option to a flag

- src/partition.rs
we will have following build error on cargo 1.13.0
this patch will fix it
$cargo build --release
Compiling rav1e v0.1.0 (/home/thomas/codec/rav1e)
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
--> src/partition.rs:54:5
|
25 | / pub enum RefType {
26 | |   INTRA_FRAME = 0,
27 | |   LAST_FRAME = 1,
28 | |   LAST2_FRAME = 2,
...  |
34 | |   NONE_FRAME = 8,
35 | | }
| |_- not an extern crate passed with `--extern`
...
54 |   use RefType::*;
|       ^^^^^^^
|
note: this import refers to the enum defined here
--> src/partition.rs:25:1
|
25 | / pub enum RefType {
26 | |   INTRA_FRAME = 0,
27 | |   LAST_FRAME = 1,
28 | |   LAST2_FRAME = 2,
...  |
34 | |   NONE_FRAME = 8,
35 | | }
| |_^
error: aborting due to previous error …
> fix build error for cargo 1.13.0

- .travis.yml
This may save some time when travis is busy.
> Only document rav1e on travis, not its deps

- README.md
- rustfmt.toml
It had been removed to support external aom.
> Remove reference to comparative_bench

- src/api.rs
- src/encoder.rs
speed 5, (encoding time increase 14%~1%) [AWCY](https://beta.arewecompressedyet.com/?job=master-ef7a66a2ff710352d8fd0048c67048158c2e28ff&job=rect_part_leaf_s5%402019-04-30T20%3A05%3A35.283Z)
| -1.4529 | -1.9177 | -1.8769 |  -1.4698 | -1.3873 | -1.3750 |    -1.6576 |
speed 1, 5 frames, (encoding time increase 44%~11%) [AWCY](https://beta.arewecompressedyet.com/?job=test_rect_part_inside_16x16_or_smaller_s1_5f%402019-04-29T23%3A55%3A48.318Z&job=master-ef7a66a2_s1_5f%402019-04-29T23%3A20%3A33.601Z)
|    ---: |    ---: |    ---: |     ---: |    ---: |    ---: | …
> Allow rectangular partition at leaf nodes of topdown partition search

- src/rate.rs
PSNR and CIEDE2000 rate distortion curves were collected for [subset3](https://media.xiph.org/video/derf/), sampled at `--quality [5, 21, ..., 245]` for chroma quantization gradients in the range `10...25`(Q6), using a training binary built from https://github.com/barrbrain/rav1e/commit/uv-delta-q-train and flags `--tune Psnr -s 4`.
BD-rates were derived with an anchor of 24 in Q6, the CIEDE2000-optimal point for the lower half of the quality range. CIEDE 2000 was initially targeted exclusively but this ends up significantly harming luma-only BD-rates (+5%) for minor gains (-1%). Y-PSNR is the most structurally similar to CIEDE 2000 among the luma-only metrics. We trade the marginal gains in CIEDE 2000 for greater losses in Y-PSNR by targeting the sum of their BD-rates. A gradient was …
> Optimize chroma quantizer offsets for subset3

- Cargo.toml
- src/rdo.rs
These are fixed size and stack allocated rather than malloc()'ed,
hopefully improving speed and reducing memory fragmentation.
Vecs that are passed across functions have not been converted.
> Convert some Vecs in RDO to ArrayVecs.

- src/encoder.rs
- src/header.rs
So that "use_filter_intra = false" is not coded for every intra mode block.
> Turn off enable_filter_intra in sequence header

- src/me.rs
Let's drop few more tiny allocations.
> Don't alloc in get_subset_predictors

- src/bin/common.rs
cargo run -- nyan.y4m -I 0 --output test.ivf
Finished dev [optimized + debuginfo] target(s) in 0.43s
Running `target/debug/rav1e nyan.y4m -I 0 --output test.ivf`
thread 'main' panicked at 'Keyframe interval must be greater than 0', src/bin/common.rs:357:7
> Enforce a lower bound of 1. Fixes #1211.

- benches/bench.rs
- src/encoder.rs
- src/rdo.rs
Because it has been quite confusing, when its sole effect is
to decide whether doing pixel reconstruction or not.
> Rename 'rdo_use_only' function parameters as 'use_recon_pixel'

- src/encoder.rs
- src/rdo.rs
The fix applies when tx rdo is turned on.
> Fix rec pixels not computed when tx is smaller than block

- src/bin/common.rs
The help text said it was, but we were not actually multiplying by
1000.
Thanks to Derek Buitenhuis for the report.
> Make bitrate on the command line be kbps

- src/api.rs
- src/bin/rav1e.rs
This avoids some confusion @dwbuiten reported some time ago. (yet another cherry-pick from the segment-threading set)
(crav1e will be updated accordingly)
> Do not use NeedMoreData to signal that a frame had been encoded

- src/header.rs
The number of ones to write the number of tile _rows_ in the bitstream
was incorrectly computed from the minimum tile _columns_.
The bug remained undetected because unless the video is larger than
MAX_TILE_WIDTH or bigger than MAX_TILE_AREA:
min_tile_rows_log2 = min_tile_cols_log2 = 0
> Fix tile rows count in bitstream

- appveyor.yml
Updates to the Visual Studio 2019 AppVeyor image, which contains Visual Studio 16.1.
We don't use msbuild so it shouldn't matter that much.
> CI: Update AppVeyor to Visual Studio 2019

- src/api.rs
Probably wasn't noticed because the rav1e CLI usually sets it from the Y4M.
> api: Make the default time base sane

- src/rate.rs
This is a bug fix and aligns to rate-control in [Theora](https://git.xiph.org/?p=theora.git;a=blob;f=lib/rate.c;h=bf2b1396a17ea3c7d7ac87e8b78771f7874a4a8a;hb=HEAD#l808) and [Daala.](https://git.xiph.org/?p=daala.git;a=blob;f=src/rate.c;h=339dd56569c6b5b3b6879e860b601b7af79a651d;hb=refs/heads/master#l1123)
> rate: Reset log_scale after first frame of each type

- src/rate.rs
It wasn't supposed to be enabled, and we don't handle it correctly.
> rate: Do not enable frame drops by default

- build.rs
The build target in `build.rs` is available as environment variable at
runtime, not compile time.
While at it refactor the code to support the ARM assembly.
> Support cross compiling

- src/api.rs
- src/bin/common.rs
- src/rate.rs
There's no reason to explicitly bind this to the max keyframe interval. It's useful to, for example, set it larger than 1.5x the keyframe interval for short intervals (1-3s) to prevent bitrate starvation after larger than expected (complex) keyframes.
* Right now the default is 1.5x the max keyframe interval. Would it be useful to set it based on some threshold of big/small keyints, or would that be too confusing?
* Is there a better option name I could use?
* This should address most of #1262 by way of letting users set this value when using small GOPs. The weird edge artifacts at high quantziers remain.
* Since it will now be user settable, we need to definitely address `log_scale` overflow ([link](https://github.com/xiph/rav1e/blob/52f0bd7fc460e3f3a137d5b48ddfc075bbc78649/src/rate.rs#L3 …
> api: Expose the reservoir frame delay as a settable option

- .travis.yml
- src/transform/inverse.rs
This PR enables the [type_complexity](https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity) lint, and fixes all warnings caused by it.
> Enable the Clippy's "type_complexity" lint

- src/bin/rav1e.rs
`Muxer` is a trait, and passing dynamic traits without the `dyn` keyword is now deprecated.
> Use `dyn` for a dynamic trait

- .travis.yml
- benches/bench.rs
- benches/me.rs
- benches/predict.rs
- benches/transform.rs
- examples/simple_encoding.rs
- src/api.rs
- src/bin/common.rs
- src/bin/decoder/mod.rs
- src/bin/decoder/y4m.rs
- src/bin/muxer/y4m.rs
- src/bin/rav1e.rs
- src/cdef.rs
- src/deblock.rs
- src/entropymode.rs
- src/header.rs
- src/lib.rs
- src/lrf.rs
- src/mc.rs
- src/predict.rs
- src/rate.rs
- src/rdo.rs
- src/rdo_tables.rs
- src/test_encode_decode.rs
- src/tiling/plane_region.rs
- src/util.rs
Use `cargo doc --open` to see the difference.
Would probably make sense to group all the configuration structs in some way e.g. all the color definition structs in a `color` module.
> Public API / Doc cleanup

- src/api.rs
- src/bin/common.rs
- src/rate.rs
This is useful for 1-pass ABR to stop it from going totally nuts on some clips that have, for example, hard black cuts.
@tterribe needs to confirm im not doing something stupid here.
> API: Expose minimum quantizer option

- src/api.rs
- src/bin/common.rs
- src/encoder.rs
Use a simple algorithm that greedily splits, longer direction first.
> Add --tiles option to automatically assign tiles.

- src/bin/common.rs
- src/bin/rav1e.rs
Attempt to fix #1341. I don't think the `y4m` crate is parsing range in the header, so simply use the default value of limited.
> Set Y4M pixel range to limited from CLI

- src/encoder.rs
> Disable CDEF for 4:2:2 input

- src/deblock.rs
- src/encoder.rs
This patch fixes rav1e to the agreed deblocking crop behavior in the
spec.  It should correct several desyncs that were showing up in the
following (CDEF and LRF) filters that pull pixels out of the
non-displayed buffer area.
> Fix for deblocking desync on non-mult-of-8 crop frame sizes

- src/rdo.rs
when directional intra modes are enabled, running "target\release\rav1e.exe nyan.y4m -o enc_file.ivf --limit 1 -s 3 -r rec_file.y4m" will cause crash due to hard coded ArrayVec::<_;7>.
This commit fixed this potential crash issue.
> fix one potential crash issue when directional intra modes enabled

- src/partition.rs
The goal of this change is to improve readability and conciseness. LUTs are unreadable without comments to remind the reader of what item each value is associated with (for example each block size). Pattern matching is self-documenting. There is also some redundancy with LUTs, such as multiple types of horizontal and vertical partitioning schemes using the same block size to subsize maps (compare the size of the LUT used by the `subsize()` function vs. the pattern matching alternative).
> Replace LUTs with pattern matching in partition.rs

- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/partition.rs
- src/rdo.rs
Requesting @ycho for review as the last person who touched this code, but if someone else wants to review please go ahead.
I found the format of the `Subsampled_Size` table (which is equivalent to `ss_size_lookup`) to be difficult to read, and there is unnecessary data for subsampling in the vertical but not horizontal direction (which does not correspond to any supported color space). It is replaced here with pattern matching. It is a bit longer than the LUT but more readable in my opinion.
There were also some errors in the `ss_size_lookup` tables, mostly block sizes that should be invalid that were not marked as such in 4:2:2. I used the specification as reference for this conversion.
> Clean up subsampled block size and chroma transform size functions

- .travis.yml
It works OK for decimals but splits hex unnecessarily. If it
gets an option for controlling how sensitive it is, we can turn
it back on.
> Disable unreadable literal lint.

- src/encoder.rs
- src/partition.rs
One branch was allowing vertical partitions to be added to the list.
Also panic with a more friendly error message instead of trying to access an array out of bounds when trying to code such an invalid partition.
> Fix vertical partitions being coded for 4:2:2 content

- src/encoder.rs
- src/predict.rs
Disable transform partition for intra mode block
Until the two functons has_tr() and has_bl() is fixed to use partition type info
or add new two separate versions, disable intra tx partition.
Our existing has_tr() and has_bl() have been shared by both mvref and intra prediction uses,
and it works if partition size == tx block size.
However, it can fail if multiple tx blocks exist in a partition, due to missing logic
to decide the availability of top right and bottom left pixels based on partition type.
Then, enable the disabled directional intra prediction
since it works if no tx partition is done.
> Disable intra tx partition

- src/api.rs
- src/encoder.rs
- src/test_encode_decode/mod.rs
Some work towards #970.
This also explicitly disables blocks of size under 8x8 for non-4:2:0 inter frames via ugly condition sets in the `encoder.rs` partitioning functions.
> Fix and enable non-4:2:0 inter frames (excluding sub-8x8 blocks)

- Cargo.toml
- cbindgen.toml
- src/capi.rs
- src/lib.rs
Follow [the short instructions](https://github.com/lu-zero/cargo-c/wiki#install) to test it.
> Import crav1e lib.rs in rav1e and make it buildable using cargo-c

- src/context.rs
Now that partition context is stored at 8x8 granularity, a different
constant needs to be used for above_coeff_context size.
Fixes #1386
> Correct size of above_coeff_context.

- src/bin/common.rs
underscored options left as aliases for backward compatibility
this should fix https://github.com/xiph/rav1e/issues/1376 (assuming dashes is decided to be the spacing style)
> replaced underscores with dashes in cli options

- src/header.rs
This avoids a desync when e.g., CDEF bits == 2
> header: write CDEF strengths in order

- src/capi.rs
This was already in crav1e but forgotten when it was merged in master!
> Expose min_quantizer in the C API

- src/cdef.rs
- src/encoder.rs
- src/rate.rs
| -0.3890 | -0.7035 | -1.2771 |  -0.1636 | -0.0987 | -0.0441 |    -0.1748 |
~4-6% faster encoding time for low QP.
https://beta.arewecompressedyet.com/?job=master-7f7209e95861e4d15211cb465f1d49dbef86029e&job=rav1e-cdef-from-q-squash%402019-07-03T04%3A00%3A41.134Z
> cdef: pick strength based on quantizer

- rustfmt.toml
This was renamed here: https://github.com/rust-lang/rustfmt/commit/e6b60a40d50c8905d8ef8696943c686947f905d7
> rustfmt: Use fn_args_layout instead of fn_args_density

- src/frame/plane.rs
- src/lrf.rs
This reverts commit 16ea18ea6eaf3f0e8549a6804ebb45ea37f659fb.
AWCY shows this commit changing stats. It should not.
> Revert "Use integral images in the self guided filter (#1396)"

- src/capi.rs
It apparently worked without them... somehow.
Spotted by @jamrial.
> capi: Add some missing "C"

- src/encoder.rs
master-98f4d66d1fc5456a4b3178c8694fb2d03d44504a -> level_2_primary_ref@2019-07-09T01:46:21.426Z
|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|-|-|-|-|-|-|-|
| -2.4867 | -2.4091 | -2.4374 |  -2.4710 | -2.5525 | -2.5742 |    -2.6157 |
https://beta.arewecompressedyet.com/?job=level_2_primary_ref%402019-07-09T01%3A46%3A21.426Z&job=master-98f4d66d1fc5456a4b3178c8694fb2d03d44504a
> Use same-level primary references for levels up to 2.

- src/api.rs
- src/scenechange/mod.rs
https://beta.arewecompressedyet.com/?job=master-47cea49ada2684410e250602b07176977d8f0cbc&job=lookahead-scd-2
This introduces a lookahead computation function and moves scene change detection there. The effect is that it's now done in the correct frame order, and therefore the tests from the previous PR are now fixed.
I also changed `SceneChangeDetector` to not update the last frame on `send_frame` as I'm always updating it manually.
I think this logic still has a potential of breaking if the lookahead size is less than the subgop size, but I haven't tried that, and also it's currently at 10 and the plan is to increase it further.
> Move scene change detection to lookahead

- .editorconfig
This isn't "standard" but is supported by a range of editors. For me in nvim it makes comment reflow automatically work at the correct 79 characters instead of the default 100 which is very convenient.
> Add max_line_length into .editorconfig

- Cargo.toml
Some users on IRC were seeing build failures solved by
a cargo update.
> Increase min scan_fmt version.

- src/lrf.rs
Doesn't fix any bugs. Might give a tiny speedup.
Results: https://beta.arewecompressedyet.com/?job=master-5079a62a69ec62578452ead6b9d5e5022b37996e&job=test_new_bounds_lrf2%402019-07-17T19%3A46%3A51.020Z
> Constrain input y and stripe size to fit in frame

- .travis.yml
As far as I can tell, we are not using CI benchmark results and they may be unreliable. With this change, they will still be built and return compilation errors, but they will not run on Travis.
> Do not run benchmarks on Travis CI

- src/lrf.rs
```
-0.1518 | -0.1329 | -0.1283 |  -0.1500 | -0.2130 | -0.1771 |    -0.1877
```
https://beta.arewecompressedyet.com/?job=master-dc15476cb8a3d552488e9138dc0585d775a13749&job=lrf_banish_the_triangle%402019-07-18T19%3A45%3A33.819Z
> Fix order of x and y in sgr solve

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
This was added before Rav1e even had rate control, and was never used, since Tim's pass API is buffer based.
Sending this now since it needs to be cleaned up before Crate Day™.
So this builds and runs fine, but now the build has a bunch of weird and (entirely unrelated?) dead code warnings like:
```
warning: method is never used: `y`
--> src/tiling/tile_motion_vectors.rs:79:7
|
79  |       pub fn y(&self) -> usize {
|       ^^^^^^^^^^^^^^^^^^^^^^^^
...
113 | tile_motion_vectors_common!(TileMotionVectorsMut, mut);
| ------------------------------------------------------- in this macro invocation
```
Also from `rdo.rs`, `lrf.rs`, and a few others. I don't get it... can someone help?
> api: Remove the old and never-used stats/pass API

- src/encoder.rs
- src/tiling/tiler.rs
Renamed based on my comment in #1451.
The rationale is that `new()` is normally reserved for "general constructors" that set fields based on the values provided. It is expected that the parameters passed to such constructors are mapped to struct fields "as-is".
I believe that the `TilingInfo` is closer to a "conversion constructor", hence the `from_` prefix. I hope that it will make it clearer that the arguments are not mapped to the struct fields directly.
My main reference is https://rust-lang-nursery.github.io/api-guidelines/naming.html.
If anyone disagrees, or wants to suggest a different name, please feel free.
> Rename TilingInfo constructor

- src/encoder.rs
`EncoderConfig` has a `Default` implementation to support tests, so this simply propagates its implementation to allow initializing a test `Sequence` or `FrameInvariants` in one line.
Since tests seem to use non-default resolutions, I have not changed them.
> Implement Default for Sequence and FrameInvariants

- src/cdef.rs
The tests were using a `Sequence` initialized with a default `EncoderConfig`, and the parameters did not correspond with the configuration passed to `FrameInvariants`.
> Create CDEF test Sequence with correct EncoderConfig

- src/encoder.rs
Work towards #1464.
The same cannot be done with corresponding `FrameInvariants` functions, because trait bounds other than `Sized` are not supported with `const fn` currently (`FrameInvariants` has a `Pixel` bound).
> Make Sequence::sb_size[_log2]() const fn

- src/mc.rs
Cast before adding.
Fixes #1311.
> Fix overflow in mc::native::mc_avg()

- src/api.rs
- src/encoder.rs
- src/tiling/tiler.rs
This reverts commit 95c773470fdb6bd0e6126e85ae834bdec72494bf and adds a rate restriction to the `TilingInfo` constructor.
Fixes #1451.
> Deduplicate tiling configuration validation and adjustment

- src/encoder.rs
- src/util.rs
Thanks to @tterribe for pointing out the usually unnecessary conversion.
> Change ilog() return type to usize

- benches/bench.rs
- benches/transform.rs
- src/transform/forward.rs
- src/transform/inverse.rs
Work towards #634.
Transform benchmark functions are simplified and benchmarks are added for the 4x4 and 8x8 variants of DCT, identity and ADST transforms, both forward and inverse.
> Add transform benchmarks

- Cargo.toml
- src/api.rs
- src/encoder.rs
- src/rdo.rs
- tools/draw-importances.py
- tools/draw-mvs.py
This PR adds original-frame motion vector computation in lookahead, and block importance computation in lookahead, which is heavily based on x264's MBTree, as described in [this paper](https://pdfs.semanticscholar.org/032f/1ab7d9db385780a02eb2d579af8303b266d2.pdf). Additionally, the distortion is biased in the RD-cost computation according to the computed block importance. [Three-way AWCY](https://beta.arewecompressedyet.com/?job=master-5de2d05cbdc78af88402ee3d7b74261cb11c90ad&job=lookahead-mv-3-16-2019-07-23_131331-dbb9d2f&job=lookahead-mv-3-16-INVERTED-2019-07-23_131446-8df6d94) (original; this PR; this PR with inverted bias to show that it works).
The block importance computation is far from final. For instance, right now it only uses half-res MVs and a single intra prediction mode. …
> Initial temporal RDO implementation

- src/encoder.rs
I re-tested it and it works with `nyan.y4m` converted to 4:4:4. If decoding tests succeed in CI I assume it is working. There are still desyncs when enabling it with 4:2:2, including out-of-bounds memory access in the self-guided filter and further desyncs causing decoding errors.
> Enable loop restoration filter for 4:4:4 input

- src/lrf.rs
This leads to about -73% to BD rate when CDEF is not used (at `-s 10`).
This should be reverted when #1399 is fixed.
> Disable self-guided filter when CDEF is disabled

- rustfmt.toml
> Remove trailing_comma setting from rustfmt.toml

- src/bin/common.rs
- src/bin/muxer/ivf.rs
- src/bin/muxer/mod.rs
When --o flag contains a path not writable to user, the result is:
```
Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.
The application panicked (crashed).
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
in src/libcore/result.rs, line 999
thread: main
```
With patch the result is:
`error: Cannot open input file: Permission denied (os error 13)`
> Handle write permissions for output.

- src/api.rs
The bitstream signals the information using a boolean.
> Remove Unspecified from the PixelRange

- src/bin/common.rs
> Fix default CLI value for pixel range

- src/rate.rs
- src/util.rs
It is superseded by `util.rs::ILog::ilog()`.
> Remove rate::ilog64()

- src/api.rs
[AWCY](https://beta.arewecompressedyet.com/?job=master-5ea7a15c0a7a60c37be637851f2b594a9a6b79e4&job=fix-block-imp-mv-search-2) where I set `--range full`, not sure if it affects anything.
> Fix block importance propagation MV top left block

- src/api/mod.rs
It can be used to simplify the c-api.
> Add another IntoFrame variant

- src/api/mod.rs
- src/rdo.rs
So I have a better baseline for segmentation.
[AWCY](https://beta.arewecompressedyet.com/?job=master-c0990b3336e6e37691f65c6f17f62448322d6e4d&job=tune-rdo-coeffs-f3-a0.8-l40)
[AWCY between master, optimal coeffs with 10 lookahead, optimal coeffs with 40 lookahead (this PR)](https://beta.arewecompressedyet.com/?job=master-c0990b3336e6e37691f65c6f17f62448322d6e4d&job=tune-rdo-coeffs-f3-a0.8-l10&job=tune-rdo-coeffs-f3-a0.8-l40)
As per [a big number of AWCY runs](https://beta.arewecompressedyet.com/?job=master-c0990b3336e6e37691f65c6f17f62448322d6e4d&job=tune-rdo-coeffs-f2-a0.5-l10&job=tune-rdo-coeffs-f2-a0.6-l10&job=tune-rdo-coeffs-f2-a0.4-l10&job=tune-rdo-coeffs-f3-a0.6-l10&job=tune-rdo-coeffs-f3-a0.5-l10&job=tune-rdo-coeffs-f3-a0.4-l10&job=tune-rdo-coeffs-f2-a0.5-l40&job=tune-rdo-coeffs-f2- …
> Tune temporal RDO coefficients

- src/api/mod.rs
Instead of starting from 0 and looping to the current frame,
start at the first frame we want to clear out. This will slightly
improve performance, particularly on long videos.
> Optimize garbage collect loop

- src/api/mod.rs
- src/encoder.rs
- src/rdo.rs
- src/segmentation.rs
- src/test_encode_decode/mod.rs
[AWCY](https://beta.arewecompressedyet.com/?job=master-speed2-914fe8df0df9cdb87bd0f56fa8a57c8a3eab9489%402019-08-01T17%3A03%3A57.470Z&job=temporal-rdo-quantizer-27)
[AWCY but on --speed 5](https://beta.arewecompressedyet.com/?job=master-914fe8df0df9cdb87bd0f56fa8a57c8a3eab9489&job=temporal-rdo-quantizer-26)
With @tdaede we decided I should put this in `--speed 2` as it about doubles the encoding time.
This adds three quantizer index deltas: 0, -15 and 15, and adds searching them to the RDO. This way it's affected by any RDO biasing, be it block importance or activity. This showed better results than me trying to naively set the segment delta according to mean importance.
> Adjust quantizers via segmentation and RDO

- .travis.yml
- src/api/mod.rs
The lookahead would read all frames in the video into memory
before processing any of them. This would lead to huge amounts of
memory usage on longer videos.
Fixes #1523.
> Fix excessive memory usage issue in lookahead

- src/capi.rs
- src/frame/mod.rs
Tested and seems to work (on Linux).
In particular, someone needs to double check my `Box` usage in the commit `
Switch RaFrame to a struct with an internal enum`. I am not confident I did that right.
CC: @nox (since he isn't listed
> Expose the Frame Override API in the C API

- benches/bench.rs
- src/api/mod.rs
- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/me.rs
- src/partition.rs
- src/rdo.rs
- src/recon_intra.rs
- src/tiling/plane_region.rs
- src/tiling/tile.rs
- src/tiling/tile_blocks.rs
- src/tiling/tile_restoration_state.rs
- src/tiling/tile_state.rs
- src/tiling/tiler.rs
Helps ensure type safety. `Plane` offsets are relative to the plane, and `Tile` offsets are relative to the tile, with methods on `TileState` providing conversions.
This is an idea I had ever since I bumped into this while implementing mean block importance computation in `compute_rd_cost()`. While I would like to say that error would've been entirely prevented had this been in-place, it wouldn't, because in that code I extracted raw `.x` and `.y` anyway. However, I clearly needed the frame block offset and I could've figured it out by looking at the type names.
[AWCY just in case (all zeros)](https://beta.arewecompressedyet.com/?job=block-offset-refactor&job=master-52074d09a3563fe7c2ea0730c13ec919052b847c)
> Add newtypes for {Plane,Tile}{Super,}BlockOffset

- src/api/mod.rs
Fixes #1513. @gnafuthegreat please check that this does indeed fix your issue.
We should probably add some two-pass test to the CI.
Also I'm not sure if this is even supposed to get to `guess_frame_subtypes()` when called before the very first `receive_packet()` and `send_frame()`. I'm not familiar with the logic there.
> Check for missing gop values in guess_frame_subtypes

- src/capi.rs
This was missed in 2db1f9c81f033fcd1eb421236b52036ee74b03f2.
Maybe we should have some sort of test or checklist for API changes, since this seems to get missed often.
> capi: Expose RDO lookahead frames

- src/api/color.rs
- src/bin/decoder/y4m.rs
- src/bin/muxer/y4m.rs
- src/frame/mod.rs
- src/frame/plane.rs
```
None of the existing input/output code was accounting for odd luma
sizes when subsampling chroma correctly.
This replaces the previous sampling_period() API, which encouraged
divisions and was used incorrectly everywhere it was invoked, with
a get_chroma_dimensions() API.
Since this is what everyone was doing after calling
sampling_period() anyway, we can now implement the logic once,
correctly, in a central place.
There is still an API for getting the chroma decimation shifts,
since these are used internally in by our Planes and tiling logic.
But we now use an API that actually returns the shifts
(gauranteeing that the decimation can be expressed in terms of
shifts, instead of blindly converting by subtracting 1 from the
period), and correctly identifies that there is no sensible …
```
> Fix chroma subsampling with odd luma sizes.

- tools/submit_awcy.py
Decode the output of subprocess, otherwise it's a bytes and you can't concatenate that with a string below.
> Fix submit_awcy.py with empty -prefix

- src/ec.rs
Test for `update_cdf_4_sse2` fails since the method under test cannot be found.
> Fix build for tests non-x86_64

- src/api/mod.rs
This required moving the RDO lookahead frames from a constant into `EncoderConfig` (it is not yet configurable from the CLI). This also cleans up some behaviors in lookahead, so it is now reading no more than the needed number of frames at any time and behaves correctly via the API as well as the CLI.
> Add test for amount of lookahead consumed

- src/test_encode_decode/aom.rs
- src/test_encode_decode/dav1d.rs
- src/util.rs
Both `cargo test` and `cargo build` were run without errors.
> Fixes #1292

- .travis.yml
- Cargo.toml
- build.rs
The addition of a minimum Rust version also means we should
test against both the minimum version and the latest stable
version in .travis.yml. This MR adds the CI tests against the
latest stable, and mentions that the minimum version in .travis.yml
should match the minimum version in build.rs.
> Give an intuitive error message if the Rust version is too old

- src/api/mod.rs
- src/encoder.rs
- src/me.rs
- tools/draw-mvs.py
Bonus: cool Unicode box drawing character diagrams.
I don't like how there's `motion_estimation` and `estimate_motion`, but `estimate_motion` had a big precedent: `estimate_motion_ss2` and `estimate_motion_ss4`.
[AWCY](https://beta.arewecompressedyet.com/?job=master-e0d9e789f49207b95e12b35309fbf27737e9886c&job=lookahead-full-res-mvs-7-2019-08-09_124236-e6fdc6f), two individual AWCYs in the commit messages.
This is [very slightly worse](https://beta.arewecompressedyet.com/?job=lookahead-full-res-mvs-5-2019-08-08_180621-0c26826&job=lookahead-full-res-mvs-7-2019-08-09_124236-e6fdc6f) than a previous version I had with candidates that made slightly less sense. I mean, I could just throw all MVs I have there as candidates, but is this the correct approach to take?
> Add full-resolution 16×16 MV search to lookahead

- src/lib.rs
- src/lrf.rs
The LRF SIMD module is effectively empty on non-x86 targets.
> Resolve unused code warnings on non-x86

- src/bin/common.rs
Initially, just wrap ParseIntError for quantizer.
> Wrap CLI error: ParseIntError for quantizer

- src/cdef.rs
https://beta.arewecompressedyet.com/?job=vmaf-c8ca08c77c19514d251b497900d9a24e203caa0b%402019-08-20T22%3A46%3A27.079Z&job=cdef_fix_cast%402019-08-20T22%3A47%3A09.280Z
```
-0.0005 |  0.0108 | -0.0075 |  -0.0009 | -0.0005 | -0.0010 |    -0.0014
```
> Fix early cast in CDEF

- .travis.yml
> Travis: split aom and dav1d decode tests

- src/encoder.rs
- src/rdo.rs
[AWCY](https://beta.arewecompressedyet.com/?job=master-db0da3c97efb269cb23571f2c1f68afdf1ad9813&job=per-block-distortion-4-2019-08-21_141456-89544e8)
Previously the distortion was computed for a given block, then biased with the mean importance of this block. Now the distortion is biased granularly as it is computed which allows the biasing to be more accurate (as importance is computed on a small block size basis).
> Bias distortion per-block rather than with mean

- src/cdef.rs
- src/frame/plane.rs
- src/rdo.rs
Due to shared code, CDEF currently has a bug in RDO; skipped blocks are not copied to output, causing LRF to optimize partially on garbage blocks.
> CDEF RDO skip fix

- src/api/mod.rs
- src/encoder.rs
- src/rdo.rs
- tools/draw-importances.py
[AWCY](https://beta.arewecompressedyet.com/?job=per-block-distortion-5-2019-08-21_174156-9c0e06e&job=per-block-distortion-8x8-4-2019-08-22_140122-0be6916)
Better quality, faster encode. Going further up to 16×16 [seems to make the quality worse](https://beta.arewecompressedyet.com/?job=per-block-distortion-8x8-4-2019-08-22_140122-0be6916&job=per-block-distortion-16x16-2-2019-08-21_155825-e7e7fe3).
> Switch block importance computation to 8×8 blocks

- Cargo.toml
- src/api/color.rs
- src/api/mod.rs
- src/bin/common.rs
- src/capi.rs
- src/frame/mod.rs
- src/frame/plane.rs
- src/lib.rs
- src/util.rs
Closes #1076, closes #1078, closes #1484, closes #1349, closes #1219.
Adds `#![deny(missing_docs)]` to capi and `src/api/mod.rs`.
> Document the rest of the owl

- src/rdo.rs
- src/segmentation.rs
[AWCY](https://beta.arewecompressedyet.com/?job=tune-rdo-coeffs-2-q15-f3-a0.8-2019-08-26_225010-d31741f&job=tune-rdo-coeffs-2-q21-f3-a0.65-2019-08-27_130909-d31741f)
[AWCY on `--speed 2`](https://beta.arewecompressedyet.com/?job=tune-rdo-coeffs-2-q15-f3-a0.8-speed2-2019-08-28_101943-d31741f&job=tune-rdo-coeffs-2-q21-f3-a0.65-speed2-2019-08-28_102019-d31741f)
> Tune temporal RDO constants

- src/api/mod.rs
- src/bin/common.rs
- src/capi.rs
Opening this for discussion.
The goal of this PR is to provide a simple interface to set an infinite keyframe interval (i.e. keyframes inserted only on scene changes), as opposed to having users pass the maximum value of an unsigned 64-bit value themselves.
The alternative solution would be to add a new option that overrides the keyframe interval values provided, but in order to support this through the C API a new encoder config parameter would be needed, so overall it seems unnecessarily complex to me.
In order to avoid duplicating logic between the C API and the CLI, a function is added to the encoder config. It takes both minimum and maximum keyframe interval values in case we want to map more special cases in the future (e.g. auto interval when the minimum interval input value is 0).
> Map an input maximum keyframe interval of 0 to "infinity" (u64::MAX)

- src/lib.rs
> Remove "experimental" from crate-level docs

- Cargo.toml
- src/api/mod.rs
- src/bin/common.rs
- src/bin/error.rs
- src/bin/rav1e.rs
- src/bin/stats.rs
- src/context.rs
- src/encoder.rs
- src/lib.rs
Split from #1620
The log level can be toggled using the RUST_LOG
environment variable, e.g. set to `RUST_LOG=debug`
for local debugging. This also enables us to add
e.g. debug! statements throughout the crate that
we wouldn't want users to see in production, but
would generally be useful to a rav1e developer.
> Use the log crate instead of eprintln! statements

- Cargo.toml
- src/api/color.rs
- src/api/mod.rs
- src/bin/rav1e.rs
- src/bin/stats.rs
- src/cpu_features.rs
- src/encoder.rs
- src/lib.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
- src/stats.rs
- src/tiling/tile_state.rs
- src/transform/mod.rs
Closes #1595
Example of verbose output:
```
[INFO  rav1e] Using y4m decoder: 1280x720p @ 60/1 fps, 4:2:0, 8-bit
[INFO  rav1e] CPU Feature Level: AVX2
[INFO  rav1e] Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual tiles=0 tile_rows=0 tile_cols=0 rdo_lookahead_frames=40 min_block_size=4x4 multiref=true fast_deblock=false reduced_tx_set=false tx_domain_distortion=true tx_domain_rate=false encode_bottomup=true rdo_tx_decision=true prediction_modes=Complex-All include_near_mvs=true no_scene_detection=false diamond_me=true cdef=true quantizer_rdo=true use_satd_subpel=true
[INFO  rav1e] Input Frame 0 - Key frame - 59872 bytes - encoded 1 frames, 0.003 fps, 28738.56 Kb/s
[INFO  rav1e] Input Frame 1 - Inter frame - 27367 …
```
> Enhanced CLI stats

- crates/nasm_rs/src/lib.rs
This was creating local build issues when running clippy
against rav1e, because our clippy command sets clippy
warnings to deny.
> Fix clippy issues in nasm-rs

- src/x86/satd.asm
I probably should have held out on the previous patch but eh.
I suspect this will fix the bug.
> Correct number of registers used in satd8x8

- src/api/mod.rs
- src/bin/common.rs
The speed settings had reduced TX set enabled, but it was not
documented as such.
> Fix documentation for speed levels 9 and 10

- src/context.rs
- src/encoder.rs
- src/lrf.rs
- src/rdo.rs
- src/test_encode_decode/mod.rs
- src/tiling/tile_restoration_state.rs
- src/tiling/tiler.rs
This patch set attempts to both improve cooperation between LRF and
tiling setup, but also eliminate several illegal configurations.
The patch strategy is to consistently eliminate evaluation of
'stretch' superblocks in RDO of LRUs for the loop restoration filter.
This primarily affects the case where a tile consists of
primarily/exclusively SBs that belong to an LRU stretched from some
other tile.
> Fix for #1601, #1611 and #1629 and possibly #1608

- src/rate.rs
The comment says the default size should be max-capped at 240, however the condition was wrong so it was min-capped at 240. I changed it to cap between 12 and 240 regardless of whether it's user-specified or default, seems to make more sense to me. I'll need someone knowledgeable to review this though.
> Fix reservoir constraints

- .gitlab-ci.yml
This is more optimized than the travis script, because Gitlab:
- Allows us to use a custom docker image which already has all our dependencies
- Runs the build in stages, allowing us to reuse the results from one stage in a future stage or fail fast
> Update Gitlab CI script with stages similar to Travis

- src/quantize.rs
I had originally merged them since they were only 1/256 different, but it seems it actually does make a difference.
AWCY Link: https://beta.arewecompressedyet.com/?job=master-cc170c2a17675aae6fdcfd12ecc97eaeba90b974&job=deadzoning1%402019-09-02T14%3A31%3A02.785Z
Based on that AWCY link, do you guys think it's worth bringing them back / merging this PR?
> quantize: Bring back the very slightly smaller inter biasing

- src/quantize.rs
Total encode time reduction of ~3%. No metrics change.
> Simplify deadzoning of trailing coefficients

- Cargo.toml
- README.md
- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/construct_context.rs
- fuzz/fuzz_targets/encode.rs
- fuzz/fuzz_targets/encode_decode.rs
- src/fuzzing.rs
- src/lib.rs
- src/test_encode_decode/aom.rs
- src/test_encode_decode/dav1d.rs
- src/test_encode_decode/mod.rs
Find assertion fails in your own rav1e clone in one simple command.
Closes #115, although new issues could be opened for adding, for example, proptest, or the randomizing RDO decisions thing.
The design I chose here (putting actual fuzzable functions inside the `rav1e` crate) should make it easy to hook up other fuzzers such as AFL and honggfuzz (more fuzzers more better), although it doesn't make it easy to hook up proptest or quickcheck because those frameworks want you to generate each individual parameter through them, rather than feeding in a chunk of random bytes (this is so that they can meaningfully shrink and expand the inputs, which is the whole point).
Additionally included is the ability to inspect crashing state straight through the fuzz target executables via the …
> Add fuzzing support

- src/bin/common.rs
- src/rate.rs
The previous fix (#1637) was incorrect and removes part of the entire point of exposing it as an API (I should know... I added it). Capping to 240 makes no sense for user input... it make about as much sense as capping VBV buffer and maxrate in H.264. Maybe I want a 30 second frame reservoir. Maybe my frame rate isn't 24. This is also important for 2-pass, because with a capped reservori delay, 2nd pass could only hae the option of "240 frames or less" or "the whole file", which is not sufficient.
This PR reverts that change and makes the code match what the comment actually says (and what was actually asked for by @tdaede in #1324), as well as enforces a minimum of 12 for the default too.
#1637 was merged without any of the people who actually wrote this part of the code looking at it, …
> Un-break reservoir constraints

- src/rdo.rs
FIx 1:  At speed 0 and 1, this fix gives gains of PSNR BD-Rate, -0.1537% and  -0.1763%, resp.
Fix 2: Enc time is slightly reduced.
[AWCY, speed 0, 1 frame](https://beta.arewecompressedyet.com/?job=ref_master_s0_psnr_1f%402019-09-06T22%3A51%3A05.284Z&job=fix2_tx_size_s0_psnr_1f%402019-09-06T23%3A16%3A16.803Z)
[AWCY, speed 1, 1 frame](https://beta.arewecompressedyet.com/?job=ref_master_s1_psnr_1f%402019-09-06T22%3A52%3A00.413Z&job=fix2_tx_size_s1_psnr_1f%402019-09-06T23%3A16%3A30.126Z)
> Fix tx size rdo

- src/transform/forward.rs
- src/transform/inverse.rs
Provides about 2.5% overall speedup at -s1.
When manually accessing slice indices in series,
the compiler cannot determine the highest index you
are going to access, so it adds a bounds check around
every access. Many transform functions were suffering
from this. For example, our dct16 function would have
32 extra branches from this, 16 for the input array
and 16 for the output array. By adding explicit bounds
checks at the start of the function, or by using an iterator,
the compiler knows that it can elide the other bounds
checks, and you end up with 2 bounds checks per function.
This also allows the compiler to auto-vectorize the code
in these functions where it would have previously been
unable to do so.
For example, this terrible compiler concoction:
```asm
pub fn …
```
> Add explicit bounds checks in txfm functions

- .travis.yml
- .travis/install-aom.sh
- .travis/install-dav1d.sh
- .travis/install-kcov.sh
- .travis/install-nasm.sh
- .travis/install-sccache.sh
The Minimum Rustc Version jobs were hanging due to taking too long to extract the cache. It appears that the overall cache size was over 14GB. This PR reduces the amount of files cached in order to attempt to relieve this issue, down to 1.2GB. Travis will now only cache the built binaries for dependencies we build ourselves, and only cache the sccache directory, instead of the target directory. These changes show significant speedups for the longer-running jobs (10% on average, but 50% on the Minimum Rustc job).
> Cleanup travis and reduce the amount cached

- benches/bench.rs
- src/api/mod.rs
- src/bin/error.rs
- src/cdef.rs
- src/encoder.rs
- src/lib.rs
- src/rate.rs
- src/tiling/tiler.rs
Please comment on the design.
- I have to store the maximal values to print them, unfortunately; I reported an issue into `err-derive` about this: https://gitlab.com/torkleyy/err-derive/issues/5
- Do we want to expose this in the C API somehow?
- Do we want to clearly expose all the min/max values as public constants or something?
- The hidden variant is added so that it's possible for us to add more variants without it being a breaking change (as more checks are added for example).
- Error is implemented for `EncoderStatus` so that it's possible to convert it to `Box<dyn Error>` (see doctests).
I don't _particularly_ like the magic number checks instead of checked operations, but on the other hand it results in clear range guarantees (rather than "we changed the order of operations in …
> Extract Config validation into a function

- src/api/mod.rs
- src/api/test.rs
Leaving this as a draft because I want to collect more potential fixes from further fuzzing... Although currently both of my fuzzing runs are blocked on #1611.
Fixes #1631.
> Fix some more things found by fuzzing

- src/api/mod.rs
The inner `send_frame()` would call it even in that case.
> Do not call twice compute_lookahead_data on the flushing action

- src/capi.rs
The condition was inverted compared to its Rust API equivalent.
Should fix #1658.
> Fix tile log2 validation in the C API

- README.md
All sampling formats are supported (though not fully for non-4:2:0 as mentioned above).
> Remove input chroma sampling restriction in readme

- src/encoder.rs
Related to #1612
Reverting c4886a38f0a8bba7c0377375eb8a4e564518cd0e
This causes coding loss by 1.29% at speed1, 1 fame, --tune psnr,
with reduced encoding time by 10%~40%.
> Disable non-square partition for topdown partition search

- src/bin/stats.rs
Split the estimated time into hours, minutes, seconds to make this statistic more useful for long videos.
> Make estimated time human readable

- src/lrf.rs
The choices made by the heuristic are still subject to adjustment to
meet tiling demads as before.  However, we no longer default only to
'largest possible LRU'.
AWCY results incoming.
> Add smarter LRU sizing heuristic based on stretch and quantizer

- src/api/config.rs
[AWCY results showing the change from master at speed 1](https://beta.arewecompressedyet.com/?job=master-2b20894d_s1%402019-08-21T16%3A10%3A31.334Z&job=test_s1_min_blk_4x4%402019-08-21T16%3A17%3A33.625Z)
> Change min block size for speed 1 from 8x8 to 4x4

- Cargo.toml
We only use it when building the binary.
> Upgrade better-panic to 0.2 and make it optional

- benches/dist.rs
- src/api/internal.rs
- src/asm/dist.rs
- src/asm/mod.rs
- src/cpu_features.rs
- src/dist.rs
- src/lib.rs
- src/me.rs
- src/rdo.rs
Switches to indexing these functions using BlockSizes.
Removes 10 bit only sad functions and unused satd functions.
I didn't see any speedup or slowdown.
> Call sad/satd using new way

- src/rdo.rs
Results on subset1:
master-2019-09-23_160214-b4d418a -> intra_prune_satd-2019-09-23_160204-1a821a8
-0.1007 | -0.0694 |     N/A |  -0.0845 | -0.1145 | -0.1157 |    -0.0402
https://beta.arewecompressedyet.com/?job=intra_prune_satd-2019-09-23_160204-1a821a8&job=master-2019-09-23_160214-b4d418a
> Prune intra modes with SATD instead of SAD.

- src/cdef.rs
- src/lrf.rs
- src/rdo.rs
- src/tiling/tile_restoration_state.rs
Restoration (or more specifically the LRU partition tracking code) did not implement support for the rectangular superblocks used by 4:2:2 inputs.  This implements the missing support and fixes #1692.
AWCY test metrics incoming.
> Implement missing LRF 4:2:2 support

- Cargo.toml
It's only used by the desync finder
> Make backtrace dependency optional

- Cargo.toml
It would otherwise break cargo-c.
> Workaround rust 1.38 pipelined compilation

- src/api/config.rs
Because it casues x2 ~ x3 increase in encoding time but only gives less
than 0.5% gain.
> Change speed level when quant rdo is enabled from 3 downto 1

- src/api/config.rs
- src/api/internal.rs
- src/bin/common.rs
The tile settings are chosen based on video dimensions and
may not match the user input settings. This change moves the
tile settings log out of the encoder settings, and has it
show the real number of tiles chosen.
720p heuristically chosen:
```
Running `target/debug/rav1e /Users/jholmer/Downloads/ducks_take_off_420_720p50.y4m -s 10 -l 10 --keyint 3 --min-keyint 3 -o /dev/null`
INFO  rav1e > Using y4m decoder: 1280x720p @ 50/1 fps, 4:2:0, 8-bit
INFO  rav1e > Encoding settings: keyint_min=3 keyint_max=3 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=64x64 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple …
```
> Log correct tile settings

- src/asm/dist.rs
- src/cpu_features.rs
- Log the correct CPU feature if "nasm" feature is disabled
- Enable choosing SSE2 and SSSE3 optimization levels
- Fix a crash that would occur from attempting to call SSSE3
assembly when SSE2 optimization level is selected
> Fix various conditions around ASM selection

- .travis.yml
Add a basic cargo build and cargo test configuration for the Arm (aarch64) platform.
@shssoichiro or @barrbrain Could you take a look at the sccache configuration to enable aom and dav1d decode tests?
> Travis CI: Add Arm build

- src/cpu_features.rs
SSE2 crashes on non-mod-64 videos.
Disable it until a proper fix is found.
Closes #1752
> Temporarily disable SSE2 optimizations

- src/asm/x86/dist.rs
- src/cpu_features.rs
The broken SSE2 functions don't get overridden
until AVX2, so #1755 failed to fix the issue
for SSSE3 CPUs. This is also a more targeted approach.
Verified testing against speed 0 locally with SSSE3 feature set enabled.
> Disable only the broken SSE2 function

- Cargo.toml
This version removes the build dependency on skeptic tests.
> Bump again err-derive

- src/encoder.rs
- src/rate.rs
- src/rdo.rs
@barrbrain can you rerun your tuning on top of this patch
> Scale chroma distortion.

- src/encoder.rs
- src/quantize.rs
Previous compression optimizations made the quantization process
dependent on the order that the coefficients are processed without
changing to using scan order. This patch corrects this.
Improves quality at the expense of encode speed.
```
-0.4854 | -0.2923 | -0.4541 |  -0.6873 | -0.3795 | -0.5577 |    -0.4489
```
> Quantize in scan order

- src/api/config.rs
Closes #1707 via @ycho's suggested solution.
[Here](https://beta.arewecompressedyet.com/?job=master-s4%402019-10-17T18%3A18%3A25.883Z&job=master-s5%402019-10-17T18%3A19%3A08.579Z&job=s5-txset%402019-10-17T16%3A41%3A04.262Z&job=master-s6%402019-10-17T18%3A20%3A01.049Z) is a comparison between speed level 4, 5 as of now, 5 with this PR, and 6. It is clear that 5 and 6 are far too similar right now. This PR enables transform type and size RDO with a reduced transform set for speed level 5, which differentiates level 5 from 6 while remaining a reasonable speed/quality tradeoff compared to level 4.
> Rebalance transform set speed presets

- src/transform/inverse.rs
We can do w/out the `reverse()`.
> Refactor iadst/flipadst

- src/asm/x86/cdef.rs
Missed this in the previous PR
> Future-proof cdef test for other instruction sets

- src/transform/mod.rs
This clamp isn't needed and is broken (clamping a i32 to i32 ranges).
This code was only being reached at the start of the forward transform,
where we are shifting our pixels up. We are never shifting out of i32s.
> Remove broken clamp from the forward transforms.

- .travis.yml
- .travis/install-aom.sh
- .travis/install-dav1d.sh
- .travis/install-kcov.sh
- .travis/install-nasm.sh
- .travis/install-sccache.sh
Some of our deps should be optional until caching is available on arm64 Travis builds.
Fixes #1771.
> Restore before_install for Travis on arm64

- .travis.yml
- .travis/install-sccache.sh
As seen on [Travis job 600798255](https://travis-ci.org/xiph/rav1e/jobs/600798255#L986)
```
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
$ Installing caching utilities
attempting to download cache archive
fetching PR.1784/cache-linux-bionic-95fb48e796aab48d30b2fe4364d7a581547ec2aa7892c330f8706fbe1d260fee--cargo-stable.tgz
fetching PR.1784/cache--cargo-stable.tgz
fetching master/cache-linux-bionic-95fb48e796aab48d30b2fe4364d7a581547ec2aa7892c330f8706fbe1d260fee--cargo-stable.tgz
fetching master/cache--cargo-stable.tgz
could not download cache
/home/travis/.casher/bin/casher: line 259: ruby: command not found
```
> Hot fix for Travis cache failure on arm64

- Cargo.toml
- build.rs
- src/arm/32/mc.S
- src/arm/32/util.S
- src/arm/64/looprestoration.S
- src/arm/64/mc.S
- src/arm/64/util.S
- src/arm/asm.S
- src/asm/aarch64/mc.rs
- src/asm/aarch64/mod.rs
- src/cpu_features/aarch64.rs
- src/cpu_features/mod.rs
- src/mc.rs
Hi,
This patch set adds mc.S from dav1d 0.1.0 to rav1e.
- Adds cc-rs dependency 
- Incorporate the changes to asm module for aarch64's mc  neon functions.
- Use asm_neon flag for invoking neon specific functions. 
- Add CPU config for AArch64.
- Do benchmark with [rd_collect](https://git.xiph.org/?p=daala.git;a=blob;f=tools/rd_collect.sh;h=dd7c50f9126acc79f4cd2be0b0f82fc63afbbd3c;hb=e126af0c8bc67df532efc1c008386ca50917cdfe)
- Integrate LR to complete 0.1 importing from dav1d.
```
running 145 tests
test api::test::flush_low_latency_no_scene_change ... test api::test::flush_low_latency_no_scene_change has been running for over 60 seconds
test api::test::flush_low_latency_scene_change_detection ... test api::test::flush_low_latency_scene_change_detection has been running for over 60 seconds …
```
> Merge dav1d 0.1.0 AArch64 assembly 

- src/tiling/tiler.rs
When calculating the minimum number of tiles needed
to code a valid bitstream, the rate restriction did
not return valid results. This uses the Rust log2()
function instead of an integer logarithm, and rounds
the result up rather than to the nearest integer.
> Fix tile rate restriction calculation in tiler

- src/context.rs
- src/encoder.rs
- src/predict.rs
- src/rdo.rs
Part of larger cleanup effort, but I'm opening this first in case there are comments on this change. I have thought for a while that the current names are a bit vague, and the parameters are reused without transformation in the encoder module, so they are not necessarily specific to RDO.
> Rename RDO(Partition)Output to Partition(Group)Parameters and reuse them where appropriate

- src/encoder.rs
- src/lrf.rs
Found this while fuzzing and took the easy way out. An alternative or complementary solution would be to assert that the frame size is valid and display a proper error message if it is not (I could not find the minimum frame size requirements in the spec, but I seem to recall they exist).
> Fix an LRF crash when encoding tiny frames

- src/api/config.rs
- src/api/test.rs
- src/capi.rs
- src/test_encode_decode/mod.rs
The AV1 format specification, section A.3 specifies that
the frame width and height must be at minimum 16 px for
a valid AV1 stream. Since we are not upscaling or padding
input video below that size, ~panic with a friendly error message~ return an error in the API.
> Ensure that frame sizes passed to the API are valid

- src/asm/x86/predict.rs
- src/asm/x86/transform/inverse.rs
- src/x86/cdef_ssse3.asm
- src/x86/ipred_ssse3.asm
- src/x86/itx_ssse3.asm
- src/x86/looprestoration_ssse3.asm
- src/x86/msac.asm
Advances #1750.
This also includes changes from 0.2.1, 0.2.2 and 0.3.0 releases. Bundling them together to pick up the remaining inverse transform functions for SSSE3 and associated bug fixes.
Difference between upstream commit list and this PR:
```diff
+Integrate functions from itx_ssse3
+Integrate ipred_paeth_ssse3 from ipred_ssse3.asm
-x86: cdef_dir: optimize best cost finding for SSE
-x86: cdef_filter: use 8-bit arithmetic for SSE
-x86: cdef_filter: use a better constant for SSE4
-x86: cdef_filter: fix macro case (lower to upper)
-x86: Add minor CDEF AVX2 optimizations
-x86: optimize AVX2 cdef_dir
-Use some 8 bit arithmetic in AVX2 CDEF filter
-Utilize a better CDEF constant for avx2
```
Our CDEF assembly is divergent from dav1d.
There are 31 new SSSE3 functions since dav1d 0.2.0: …
> Merge dav1d 0.3.1 x86 assembly

- .travis.yml
Reverts xiph/rav1e#1807
Merge once Travis CI ARM machines start booting again.
> Revert "Disable Travis ARM builds due to them not completing."

- src/asm/x86/dist.rs
- src/asm/x86/mc.rs
- src/cpu_features/aarch64.rs
- src/cpu_features/x86.rs
This involves adding a new CpuFeatureLevel for SSE4.1.
Because of being unable to use a decimal in an enum variant name,
this required manually implementing FromStr and Display
instead of using the arg enum proc macro.
> Integrate SATD ASM for SSSE3 and SSE4.1

- src/cpu_features/aarch64.rs
This matches recent changes to the `x86_64` implementation.
> Simplify aarch64 CpuFeatureLevel with FromStr

- src/asm/x86/dist.rs
- src/me.rs
By aligning blocks that overlap the right edge to block width, the result is effectively cloned from the adjacent block. Note that only the bottom/right edge blocks can be unaligned anyhow; this is only in motion estimation, not motion compensation.
Fixes #1715. No change in [AWCY results at default speed](
https://beta.arewecompressedyet.com/?job=master-588d7219bc7d1f360f24f64b9cf6485ce41928f7&job=sad16x16_sse2%402019-11-01T15%3A39%3A27.558Z).
> Enable rav1e_sad16x16_sse2 by enforcing alignment

- src/capi.rs
> Mention the need to free the strings returned by rav1e_status_to_str()

- src/encoder.rs
- src/stats.rs
AOMAnalyzer shows the percentage of pixels in a frame
that comprise each block size or transform type.
This commit updates rav1e to do the same.
> Align end-of-encode stats to what AOMAnalyzer would show

- src/api/internal.rs
- src/encoder.rs
- src/rdo.rs
- src/segmentation.rs
With the data carried over, we can remove a prior workaround and fix the outstanding desyncs.
Fixes #1815.
> Carry over segmentation data between frames

- ivf/src/lib.rs
- src/bin/decoder/mod.rs
- src/bin/decoder/y4m.rs
- src/bin/error.rs
- src/bin/muxer/ivf.rs
- src/capi.rs
- src/rdo_tables.rs
These files lack a Copyright message:
build.rs
examples/simple_encoding.rs
ivf/src/lib.rs
crates/avformat-sys/build.rs
src/bin/error.rs
crates/avformat-sys/src/lib.rs
crates/nasm_rs/src/lib.rs
src/bin/decoder/mod.rs
src/bin/decoder/y4m.rs
src/bin/muxer/ivf.rs
Unsure if these should be updated as well...
> Added Copyright message.

- src/capi.rs
Make it future proof in case a frame queue limit is introduced.
> Fix the doxy for EnoughData encoder status

- src/transform/inverse.rs
- src/transform/mod.rs
This Option is no longer needed
since we now support all transform types.
> Remove Option from get_1d_tx_types

- src/api/config.rs
- src/bin/common.rs
As discussed a few times, because of how encoding tools interact,
we will get more accurate speed test results if we default to
having all encoding tools enabled, and disable one at a time
to see if that tool was actually useful or if another tool
compensates for it.
> Make speed test start with all features enabled

- src/encoder.rs
master-4ab62c6273e0ec64656e85df9602a2046d0ed460 -> cdef-damping-by-quantizer@2019-11-10T07:03:15.921Z
-0.5995 |  0.1251 |  0.3360 |  -0.3509 | -0.3706 | -0.3460 |    -0.4835
https://beta.arewecompressedyet.com/?job=master-4ab62c6273e0ec64656e85df9602a2046d0ed460&job=cdef-damping-by-quantizer%402019-11-10T07%3A03%3A15.921Z
> encoder: adjust CDEF damping based on quantizer

- Cargo.toml
Cuts away a good bit of time if you are rebuilding on debug or running cargo check.
> Make building asm parallel

- src/transform/mod.rs
This results in approximately a 25% speedup of the
forward_transform native code and a 1.5% overall speedup
at default speed settings.
> Enable auto-vectorization of av1_round_shift_array

- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/lib.rs
- src/lrf.rs
- src/scan_order.rs
- src/segmentation.rs
It had been also updated to be an hard error in rust 1.40.
> Remove the unused allow safe_extern_statics

- src/transform/forward.rs
Provides a very minor performance improvement.
In order to auto-vectorize, more bounds checks
will need to be elided, which are more difficult to remove
without unsafe code.
> Move bounds check out of loop in fwd_txfm2d_daala

- build.rs
- src/arm/32/cdef.S
- src/arm/32/looprestoration.S
- src/arm/32/mc.S
- src/arm/32/util.S
- src/arm/64/cdef.S
- src/arm/64/ipred.S
- src/arm/64/itx.S
- src/arm/64/looprestoration.S
- src/arm/64/mc.S
- src/arm/64/msac.S
- src/arm/tables.S
- src/asm/aarch64/mod.rs
- src/asm/aarch64/predict.rs
- src/predict.rs
Hi,
This is the final patchset for the dav1d merge into rav1e, this set includes changes from 0.5.0 and 0.5.1.
New functions added are:
<Details>
</Details>
Other improvements from this patchset
- Minor Improvements to Inverse transformations
- Addition of sm_weight table in native arm assembly
- And more...
This Closes #1754
> Merge dav1d 0.5.1 AArch64 Assembly

- benches/bench.rs
- src/api/internal.rs
- src/api/mod.rs
- src/api/test.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
- src/test_encode_decode/mod.rs
- src/tiling/tile_state.rs
Results in 5-8% encoding time improvement with 1 tile. [AWCY](https://beta.arewecompressedyet.com/?job=master-edbc586999d6a1e49e1e35d84a0c8a2c9dcf7990&job=reuse-lookahead-mvs%402019-11-24T06%3A32%3A54.455Z)
Closes #1677
> Reuse lookahead frame state and motion vectors

- src/api/internal.rs
Usual `Bosphorus_1920x1080_120fps_420_8bit_YUV`
master:
```
INFO  rav1e::api::internal > Using 8 tiles (4x2)
INFO  rav1e::stats         > encoded 600 frames, 1.122 fps, 1955.96 Kb/s
```
this pr:
```
INFO  rav1e::api::internal > Using 8 tiles (4x2)
INFO  rav1e::stats         > encoded 600 frames, 1.135 fps, 1955.96 Kb/s
```
About another 1% faster...
> Refactor compute block importances

- .travis.yml
- .travis/install-aom.sh
- .travis/install-dav1d.sh
- .travis/install-nasm.sh
The only build-dep with significant transitive dependencies is kcov.
No changes to update or clean the cache for these yet.
> Replace travis build deps with debian packages

- .github/workflows/rav1e.yml
- README.md
As requested by @lu-zero, I've ported most of the CI tasks to the `Github Actions` system with the exception of the `arm` tests that will remain on `Travis` and `AppVeyor`.
The "Build and Coveralls" test is now done using `grcov` instead of `kcov` and can be run only on the nightly because of the [-Z profile feature](https://github.com/rust-lang/rust/issues/42524).
The entire CI process takes approximately 25 minutes.
> Add Github Actions

- .github/workflows/rav1e.yml
Original patch from @Luni-4 moved back to local sccache store, populated by an actions/cache rule. There was a small, blocking issue with the syntax for setting a path relative to `HOME`. As well as resolving that, @barrbrain optimised the cache size and partitioning rules with consideration for the statistics in earlier runs.
> Add sccache locally (with fixes)

- src/api/internal.rs
- src/encoder.rs
- src/tiling/tile_state.rs
Reduces overall memory usage by 33%
on a 1080p test clip
(from 1.5GB to 1.0GB).
master:
this PR:
> Wrap frame and lookahead MVs in Arc

- .github/workflows/rav1e.yml
This ensures that the cache key is bound to the specific crate versions that will be built.
> Derive sccache cache key from Cargo.lock

- src/me.rs
- src/rdo.rs
Drop about a 36% of the overall (re)allocations over a 200 frames encoding (usual Bosphorus 1080p 8 tiles).
On Linux it makes the encoding slightly faster as well.
> Remove tiny allocs

- Cargo.toml
- src/api/config.rs
- src/api/mod.rs
- src/api/test.rs
- src/bin/common.rs
- src/encoder.rs
- src/lib.rs
- src/rdo.rs
- src/tiling/tile_state.rs
- tools/rdo.sh
Per Guillaume:
"It's not usable currently,
and my patch should eventually completely replace it."
> Remove RDOTracker and train-rdo feature

- .github/workflows/rav1e.yml
This avoids churning the build cache daily.
> Pin nightly toolchain for grcov

- src/encoder.rs
- src/rdo.rs
From the memory profile, this reduces allocations per second by about two thirds.
No significant change in speed. (Timings vary by ~0.3%)
> Remove allocations from partition search

- src/context.rs
- src/encoder.rs
The preskip should be initially false, then only become true if seg
feature >= SEG_LVL_REF_FRAME is enabled.
> Fix wrong init for preskip

- src/encoder.rs
- src/header.rs
- src/rdo.rs
- src/segmentation.rs
By default, segmentation is turned off.
Note that there is an existing similar flag 'segmentation.enabled' under
SegmentationState struct under TileState, and the new one from this commit is
the master switch and later will be controllable by CLI.
By not using any segment, this temporarilly fixes the ongoing desync issues #1858 caused by quantizer rdo and heuristic quantizer choice at speed 0,1,2.
> Add an enable/disable switch for using segmentation

- src/rdo.rs
The caller is in charge of assembling the candidates and should do so based on the same condition checked there.
> Make sure we do not test invalid candidates to begin with

- .github/actions-rs/grcov.yml
Remove some noise in results reported on Coveralls. Effectively limit results to the rav1e crate sources.
> Add configuration for grcov action

- Cargo.toml
- src/api/color.rs
- src/api/config.rs
- src/api/mod.rs
- src/api/test.rs
- src/bin/common.rs
- src/bin/kv.rs
- src/bin/rav1e.rs
- src/encoder.rs
- src/lib.rs
- src/partition.rs
It is useful to debug so maybe we could use it in another hidden subcommand, right now I put it in the `advanced` one.
``` sh
rav1e-advanced
Advanced features
USAGE:
rav1e advanced [OPTIONS]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-l, --load_config <LOAD_CONFIG>    Save the encoder configuration from a toml file
-s, --save_config <SAVE_CONFIG>    Save the current configuration in a toml file
-c, --completion <SHELL>           Output to stdout the completion definition for the shell [possible values: zsh,
bash, fish, powershell, elvish]
```
It should make easier to reproduce specific scenarios and avoid repeating manually what is set or not set in the speed levels.
```
-s, --speed <SPEED>
Speed level (0 is best quality, 10 is …
```
> Provide a mean to dump and restore the encoder config

- src/api/internal.rs
- src/api/lookahead.rs
- src/api/mod.rs
This code can be reusable in different parts
of the lookahead, for example from scenechange detection.
> Refactor out intra/inter cost lookahead code

- benches/transform.rs
- src/asm/aarch64/transform/inverse.rs
- src/asm/x86/transform/inverse.rs
- src/transform/mod.rs
Once both forward and inverse have native modules, naming conflicts will
pop up.
> Don't pub use forward and inverse impl in transform module

- src/encoder.rs
- src/tiling/tile_restoration_state.rs
Tiling had broken an edge-of-frame check in superblock queue flush triggering.  It was checking tile-local superblock offset against the edge of the frame instead of checking *global* superblock offset against the edge of frame.  This should fix the desync bug with no other functional change.
Fixes #1903
> Fix for issue #1903 (Krøyer_PS.y4m desync)
