xiph/rav1e

- src/lib.rs
- src/predict.rs
> Implement a pure-rust pred_dc

- src/lib.rs
> Fix command line

- src/predict.rs
Since it is only available for testing.
> Move pred_dc_4x4 to testing namespace

- build.rs
- src/ec.rs
> Test the entropy encoder

- src/lib.rs
- src/predict.rs
Native rust h_pred implementation
> Native rust h_pred implementation

- src/lib.rs
> Reset left coefficent contexts for all planes.

- rustfmt.toml
Not used because of https://github.com/rust-lang-nursery/rustfmt/issues/2418
> Add (but do not use) rustfmt configuration

- README.md
smooth_hv must be implemented to progress further.
> Update libaom to November 9.

- build.sh
Some parts will be merged in build.rs at some point
> By popular demand the bash build script

- src/bin/rav1e.rs
- src/lib.rs
Every odd frame is a show_existing_frame.
> Show Existing Frames

- src/partition.rs
left and above edges code was swapped.
> Unbreak prediction

- benches/bench.rs
And make the benchmark cover more cases.
> Consider all the modes in the write_b benchmark

- benches/bench.rs
- src/partition.rs
- src/predict.rs
> Refactor the intra pred functions in a separate trait

- src/bin/rav1e.rs
> Flush output file on every packet write.

- .travis.yml
- Cargo.toml
- build.rs
- data/aom.h
> Preparation for encode-decode tests

- .travis.yml
> Update travis conf to run the benchmarks

- src/lib.rs
- src/plane.rs
This uses iterators and zip to avoid bounds checks.
> Add Plane::copy_from_raw_u8().

- src/lib.rs
> Change default speed level as 0

- src/lib.rs
> Fix the bug of incorrect chroma context access with 4x4 partitions

- src/partition.rs
> Bubble up the Intra trait

- benches/bench.rs
- src/partition.rs
And use a dynbench to avoid additional boilerplate.
> Benchmark more qindex

- src/lib.rs
> Use iterators to dump y4m reconstructed output.

- src/bin/rav1e.rs
- src/context.rs
- src/lib.rs
For #160.
- Add inter/intra mode symbol for blocks in inter frame.
- Add intra prediction mode coding for inter frame.
> Add intra inter mode coding

- src/ec.rs
This patch will be part of prep work for LV_MAP_MULTI, #106.
If we ever want to merge this patch, replace CONFIG_LV_MAP_MULTI as 1 in
aom_dsp/entcode.h, so that the precision of entropy coder is enforced to change.
> [NOW READY TO MERGE] Change precision in advance for the coming Level Map.

- src/ec.rs
> fh <= fl if lv_map_multi is turned on

- src/ec.rs
For #106.
This patch requires corresponding change in libaom,
https://github.com/tdaede/aom/pull/7.
> update_cdf() for LV_MAP_MULTI=1

- src/lib.rs
Some small refactoring assuming that's the direction we want to take.
> Refactor uncompressed header

- src/bin/rav1e.rs
- src/lib.rs
For #174, "[Inter Mode] Add necessary inter mode info in frame header for inter frame".
> Enable inter mode 2

- benches/bench.rs
- src/predict.rs
This change depends on a submodule update in order to run tests. The predictor is not included in the coding process yet.
> Add Paeth predictor and tests

- build.rs
This may fix the first problem in issue #178, deleting the cache we
are forcing a libaom rebuild if the `CMakeLists.txt` is updated.
To be tested, because I'm not testing the build output but only the build times :)
> build.rs: remove CMakeCache.txt just after the build

- src/lib.rs
FIx bug #253.
ref_f3add@2018-06-15T23:53:02.448Z -> chroma_dist_fix@2018-06-15T23:53:34.992Z
0.5788 | -5.8690 | -5.7240   |  -0.6027    | 0.2688 | -0.3279 |    -2.0912
> Fix that chroma distortion is not computed during RDO (#253)

- src/lib.rs
Forces a partition split when necessary.
Resolves #226, resolves #227, and resolves #258.
```
paeth@2018-06-16T00:12:39.612Z -> edge_part@2018-06-18T19:44:10.880Z
PSNR |  PSNR Cb |  PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000
-2.4924 | -14.0054 | -13.5264 |  -2.9324 | -1.8998 | -2.4383 |    -8.2508
```
> Enable partitioning RDO on frame edges

- src/context.rs
This task is one of the blockers to enable inter mode.
> Enable tx_type writing for inter mode

- benches/bench.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/context.rs
- src/ec.rs
- src/lib.rs
- src/partition.rs
- src/predict.rs
- src/quantize.rs
- src/rdo.rs
- src/transform.rs
Update the year and add a header to files where it was missing.
> Update copyright notice headers

- build.rs
> Rebuild if the aom_build contents changed

- README.md
This makes a *huge* difference in runtime performance, so you probably want to use it.
Then again, maybe not! No worries if you don't want this PR  :)
> Use release mode in example instructions

- src/quantize.rs
The offsets computation got lost.
> Fix a rebase glitch in quantize

- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/lib.rs
First of several PRs that will clean up how config options are threaded through.
> Split up EncoderConfig into mutable / immutable structs.

- src/lib.rs
Correction to end-of-frame bounds checking on skip flags (can't get
skip flag for blocks of the endge of the frame)
> CDEF bounds error fix

- src/bin/rav1e.rs
- src/lib.rs
A reference frame buffer with 8 slots is defined. The buffer is
updated after encoding each frame according to the value of
refresh_frame_flags. The value of refresh_frame_flags is also
set and properly encoded.
> Define reference frame buffer array

- src/rdo.rs
The commit be197cf580d5e45d867d09d75d6bb7b2da2c77c9 has caused
the corrupted decoded video frames with speed=0 or 1, since its landing on
June 26.
This bug has been there around a month and believed to be the culprit of
breakage of ext_partition_types PR by TD-Linux as well.
Better fix will come, which is also coincidentally stated earlier in
https://github.com/xiph/rav1e/issues/373.
> Quick fix the corruption with speed=0 or 1 (#374)

- src/lib.rs
> Validate command line arguments

- src/cdef.rs
- src/context.rs
- src/ec.rs
- src/lib.rs
- src/rdo.rs
rework of cdef-rdosetup to remove the addition of Sequence reference to the FrameInvariants.
> Cdef montywork

- src/context.rs
- src/partition.rs
- src/predict.rs
This affects all intra prediction modes in rav1e except DC_PRED.
> Enable INTRA_EDGE prediction

- src/context.rs
- src/lib.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
> Revert "Use zero MV for all blocks in inter frames"

- README.md
With nitpicky sentence structure changes.
> Document Perl dependency

- benches/bench.rs
- src/lib.rs
- src/quantize.rs
Use smaller rounding offset in inter blocks to produce more
zero coefficients
> Make quantization offset depend on mode type

- build.sh
Add a check for reconstructed vs decoded image difference on each build in build.sh
> Check for reconstruction/decode deync in build.sh

- Cargo.toml
- src/ec.rs
- src/lib.rs
- src/util.rs
There is at least one place that would use it but on 32bit in a pending patch from @ycho
> Add an Ilog impl for primitive integers

- src/bin/common.rs
- src/context.rs
- src/ec.rs
- src/lib.rs
- src/rdo.rs
- src/util.rs
- add rust_2018_preview lang feature
- cargo fix --edition
- cargo fix --edition-idioms
> switch to 2018 edition

- src/cdef.rs
- src/context.rs
- src/lib.rs
- src/rdo.rs
> Test skip on and off in RDO loop

- src/quantize.rs
Use right shift opertator for faster code
> Don't use division in inverse quantizer

- src/predict.rs
- src/rdo.rs
Reuse exisiting intra mode lists to determine which intra modes
to search in an inter frame
> Search more intra modes in inter frames

- src/transform.rs
Before merging I want to
- Find out if this will disable any simd code and add note that in the commit message
- Add at least some comments
> Implement idct 4x4 in rust.

- src/rdo.rs
Limit the intra modes searched for chroma to the colocated luma
mode plus the DC mode if different from the first mode
> Reduce the number of intra modes searched for chroma

- src/encoder.rs
- src/rdo.rs
Because luma_mode == chroma_mode.
> If inter mode, chroma_mode is not required

- src/context.rs
- src/encoder.rs
- src/lib.rs
- src/me.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
Add basic support for prediction and coding of nonzero vectors without doing actual motion estimation
> Add basic support for nonzero motion vectors

- src/me.rs
Removal suppresses compiler warnings
> Remove superfluous lines of code

- src/encoder.rs
- src/me.rs
- src/partition.rs
Implement motion compensation interpolation filters since chroma
may now require half-sample interpolation
> Reduce motion estimation search step from 2 to 1

- src/me.rs
Search 1/2 pel square, then 1/4 pel square
> Add subpel motion search

- src/context.rs
- src/encoder.rs
- src/rdo.rs
Replace the fixed parameters for chroma-from luma with a search among the 8 alpha pairs combining -1, 0 and 1. Only search if the current best chroma mode is intra.
> Search CfL parameters of unit magnitude

- src/quantize.rs
Use single loop for all coefficients.
Reduces overall encoder run time by about 2 percent
> Speed up dequantize function

- src/encoder.rs
Reduces overall run time by about 2 percent
> Speed up diff() function

- src/predict.rs
Not quite as fast as the C intrinsics implementation in libaom yet.
Already a lot faster than the current native rust implementation.
> SSSE3 implementation of CfL predictor

- src/context.rs
Duplicate code comes from:
c0b01f05f744dac545f0e394401d9e9847a3ddf5
> Fix rebase leftover

- src/encoder.rs
- src/rdo.rs
[AWCY results](https://beta.arewecompressedyet.com/?job=master-352a95563ec3ec1f6401590b7e384ad47524dbc6&job=rav1e-cfl-pred-full-2%402018-08-29T09%3A51%3A13.330Z) at default speed level:
|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 0.0110 | -7.0461 | -4.9412 |   0.0287 | 0.0321 |  0.0721 |    -2.2357 |
> Full CfL search by prediction error

- src/context.rs
- src/encoder.rs
- src/predict.rs
- src/rdo.rs
Move MV stack construction out of encoding function such that the
value of the nearest MV can be determined before encoding
> Add search for NEARESTMV mode

- rustfmt.toml
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/lib.rs
No RDO as yet, but the deblocking filter and parameter infrastructure are
fully implemented, functional and tested.
Filter is currently turned on at a low-strength default; RDO is next.
> First cut code for loop deblocking filter

- src/deblock.rs
Fix a type mismatch in deblocking
> Build fix for deblocking; collided with frame padding

- README.md
> Update instructions for using rustfmt and clippy

- benches/comparative/mod.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/ec.rs
- src/encoder.rs
- src/me.rs
- src/partition.rs
- src/plane.rs
- src/predict.rs
- src/quantize.rs
- src/rdo.rs
- src/test_encode_decode.rs
- src/transform.rs
- src/util.rs
Using nightly rustfmt.
Hopefully shouldn't conflict with anything.
> Do low impact rust format

- src/me.rs
> Format function changed in recent commit 7e2f72d

- src/deblock.rs
Roll in typo fixes and comment corrections from Yushin's review.
No functional change.
> Trivial typos and comment corrections to deblocking filter

- src/api.rs
- src/deblock.rs
- src/encoder.rs
Some more basic deblocking configuration machinery, and code changes to enable real RDO.
beta run in progress now.
> Deblock from q

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
And use it in rav1e to output the same stats it did before.
> Add Display for Context

- src/api.rs
- src/bin/common.rs
The context status is updated on receive.
> Fix the stats output

- benches/bench.rs
- benches/comparative/predict.rs
- benches/predict.rs
- rustfmt.toml
This I think I can do without holding a townhall.
> Add benchmarks to rust format

- src/encoder.rs
- src/me.rs
- src/rdo.rs
Implemented for top-down partition search only.
If result is promising, I will need experiment adjusting ME search range when predicted search center is used.
> ME use predicted search center for topdown partition search

- src/rdo.rs
[AWCY results](https://beta.arewecompressedyet.com/?job=master-0326f7b306cd4cd4fb121a2dd42fa9dc94d39d6e&job=cfl-after-all2%402018-09-14T10%3A54%3A31.433Z) at default speed:
| -0.4946 |  0.3913 |  0.3843 |  -0.5444 | -0.5728 | -0.6244 |    -0.2061 |
About 1.2% reduction in encoding time.
> Try CfL last, only if best luma mode is intra

- src/rdo.rs
Some propedeutics to the rayon experiments.
> Rdo iterators

- src/me.rs
- src/predict.rs
- src/rdo.rs
Mainly refactor away the luma loop and apply it on separate `intra-modes` and `inter-mode`.
It should be a little faster since some branches aren't in the way anymore.
I folded in @fbossen early exit patch as well.
> Rdo iterators step 2

- src/test_encode_decode.rs
Fixes the extra silly indentation of this file.
> Format src/test_encode_decode.rs

- src/context.rs
- src/rdo.rs
Don't test these modes at speed settings higher than 2
> Test NEAR1 and NEAR2 modes based on speed testing

- src/api.rs
- src/encoder.rs
For now a single bit is used for encoding order_hint
> Add encoding of order_hint

- src/deblock.rs
Fix a subtraction that accidentally preceeded its guard statement.
> Fix an unsigned underflow in deblocking code

- src/deblock.rs
More staging work for fast RDO
> Deblock opt4

- src/deblock.rs
An exhaustive check indicates that over the given parameter range, one of the clamp operations in the narrow deblocking filters is unneeded.
> eliminate unneded clamp in narrow deblocking filters

- benches/me.rs
- src/me.rs
- src/plane.rs
(I tested by comparing the `rav1e` output)
> Use an iterator in get_sad

- src/api.rs
This is needed to make downstream developers life easier (it is also hopefully simpler than what `aom` offers).
> Add a function to produce a container-compatible sequence header

- src/api.rs
- src/bin/common.rs
- src/context.rs
- src/encoder.rs
- src/rdo.rs
- src/test_encode_decode.rs
Group frames in sets of 4. Encode the far one first and then the other three using a forward and a backward reference.
> Frame reordering

- src/bin/common.rs
Unbreak encoding without producing the reconstructed video.
> Check for the y4m encoder presence

- src/encoder.rs
- src/rdo.rs
> Don't do duplicate tx_type rdo with bottom-up partition rdo

- src/encoder.rs
> Add comments on duplicated_rdo_tx_type() for top-down partition rdo

- src/ec.rs
Fixes issue #653.
Something to get me started with helping out on this project. Since the decoding is not used anywhere else I simply included it directly in the test module.
> Port the entropy decoder in libaom to rust

- src/api.rs
OBUs of reordered frames are combined with OBUs of a non-reordered
frame into a single packet. May address #674
> Combine OBUs of reordered frames

- src/partition.rs
- src/predict.rs
This enables libaom and dav1d intra prediction code that reference left-edge pixels to be used together.
> Create intra prediction edge buffer in dav1d order

- src/predict.rs
Also, add simple reference tests for u8 prediction.
> Use macro for libaom bindings in intra pred tests

- build.rs
> Add nasm files to the rerun-if-changed list

- src/api.rs
- src/bin/rav1e.rs
- src/bin/rav1repl.rs
- src/test_encode_decode.rs
One of the feedbacks from today's API review.
> Rename ratio to Rational

- clippy.toml
- src/context.rs
- src/encoder.rs
- src/me.rs
- src/partition.rs
- src/rdo.rs
> Pass more Copy types by value, optimized for 64-bit

- src/transform/mod.rs
Addressing issue #635.
I was thinking the easiest is to add round trip tests. But I'm not sure if it's good enough? It's a start at least. Should I also hardcode some cases and expected results?
I was also not sure about generating different random numbers on every test run. So far it's working, but perhaps there's a policy.
I commented out the types and sizes that are not supported now. If there are no plans to add support I can just remove those lines.
Tolerance of +-1 is accepted now, tolerance of 0 didn't work for bigger block sizes.
This is my first time writing tests for software, despite having tested software for a living over ten years now... :)
> Draft: add tests for transforms

- src/context.rs
Up to 3% improvement observed on write_b benchmarks
```
write_b_bench(TX_4X4, 20)                                                                             
time:   [1.1021 ms 1.1056 ms 1.1093 ms]
change: [-3.4999% -2.8032% -2.1049%] (p = 0.00 < 0.05)
Found 6 outliers among 100 measurements (6.00%)
2 (2.00%) high mild
4 (4.00%) high severe
write_b_bench(TX_4X4, 55)                                                                             
time:   [1.0964 ms 1.0990 ms 1.1021 ms]
change: [-3.4298% -2.8635% -2.2903%] (p = 0.00 < 0.05)
Found 8 outliers among 100 measurements (8.00%)
1 (1.00%) high mild
7 (7.00%) high severe
write_b_bench(TX_8X8, 20)                                                                            
time: …
```
> Minor optimizations in write_coeffs_lv_map

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
> Encode correct number of frames when reordering is enabled

- Cargo.toml
- src/lib.rs
- src/partition.rs
- src/predict.rs
The current stable eventually made possible to paste identifiers together, here a example on how to leverage it.
Ideally also the match we use in PredictionMode could be simplified, but right now I have a keyboard problem and typing is a bit slow, so I send this example before going further :)
> Less boilerplate

- benches/me.rs
- build.rs
- src/encoder.rs
- src/me.rs
- src/rdo.rs
- src/x86/me.asm
Rust is beating me on larger blocks, though.
> Add SSSE3 sad asm

- build.sh
For a release build use build.sh --release
> build.sh defaults to debug

- src/bin/common.rs
> Fix division by zero in CLI output when no inter frame is coded

- Cargo.toml
- build.rs
- src/me.rs
- src/predict.rs
Make nasm optional and make sure we can build with all the options disabled.
> Build improvements

- build.sh
> Improve build script compatibility

- src/context.rs
- src/encoder.rs
Also fix uv_tx_type decision for intra mode block.
> Fix get_tx_set() for rectangular tx_sizes > 32x32

- src/transform/inverse.rs
Missed the fix for inv functions/
> Counterpart fix for inv with 70477dc9

- src/context.rs
- src/encoder.rs
- src/lib.rs
- src/rdo.rs
- src/segmentation.rs
Only works for now on keyframes and as long as the delta does not have to make the quantization cdfs change index.
> Implement segmentation

- src/encoder.rs
Minor maintenance.
* Remove redundant comments
* Replace `assert!(false)` calls with `unimplemented()` where needed
> Clean up encoder.rs

- src/predict.rs
- src/x86/ipred.asm
Apply more asm patches from dav1d.
Call the `cfl`, `cfl_128`, `cfl_left` and `cfl_top` predictors if AVX2 is available.
This fixes #675.
> Integrate dav1d ipred.asm (cfl, cfl_128, cfl_left, cfl_top)

- src/bin/common.rs
- src/context.rs
- src/partition.rs
Some formatting changes in `bin/common.rs` and `partition.rs`.
> Miscellaneous clean-up

- src/encoder.rs
> Remove Sequence::enable_filter_intra

- src/quantize.rs
This adds a `Coefficient` trait to `quantize.rs` implemented for `i16` and `i32` (similar to `Pixel`), and changes the `quantize()` function coefficient arguments to allow arrays of that trait.
> Use variable-depth quantization coefficients

- src/api.rs
- src/bin/common.rs
- src/encoder.rs
* Set color description parameters in the header
* Handle color description CLI arguments
Closes #728.
> Support color description

- src/encoder.rs
- src/partition.rs
- src/rdo.rs
2:1 rectangular partitinos only.
> Enable rectangular partitions with bottomup rdo partition search

- src/transform/forward.rs
Will be used to make initial simd code.
> Make forward txfm use generic types for coeffs

- src/context.rs
- src/encoder.rs
- src/lrf.rs
Work in progress, currently here for the automated testing.
> Add and Enable Loop Restoration Filters

- src/plane.rs
The type of fields xorigin and yorigin was changed from usize to isize
only for Plane::window(), which has now been removed.
Plane origins may not be negative, so revert their type to usize.
This partially reverts 1bd94a2d4b782446ae4be8645c46136cc988af1f.
> Revert xorigin and yorigin to usize

- src/lrf.rs
The "matrix" of restoration units was stored in a vector of vectors.
To avoids an additional indirection for each row, store them in a
contiguous array instead. Besides the (theoretical) performance benerit
for every access, this will simplify the implementation of tiled-views
which have to expose non-overlapping parts of the "matrix" via unsafe
code.
Also, since its size is constant (although not known at compile-time),
replace the vector by a boxed slice.
> Store restoration units contiguously

- .travis.yml
This is an attempt to parallelize Travis to speed up the CI by splitting up the different tests
> Parallelise .travis.yml to speed up CI

- src/mc.rs
> For hbd use scalar code for subpel

- src/encoder.rs
I *think* nobody is working with this code right now.
> Format uncompressed header writing code

- Cargo.toml
> Bump dav1d-rs and bindgen versions

- README.md
- appveyor.yml
- build.rs
Automated aarch64 builds for Windows.
> Automated aarch64 builds in AppVeyor

- src/encoder.rs
- src/rdo.rs
Its value is set as true by default.
> Add a enable_early_exit flag under fi

- appveyor.yml
Updates the secure authentication token with Thomas Daede's, which allows AppVeyor to push artifacts to GitHub Releases
> Update AppVeyor secure token

- src/encoder.rs
- src/partition.rs
- src/rdo.rs
Fixes a crash in that function for non-4:2:0 chroma.
> Fix get_intra_edges() chroma handling

- src/encoder.rs
Found a few errors while looking at 4:4:4 encoding/decoding issues.
> Fix OBU header logic errors

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
A couple of minor things related to the big set later.
> Color preparations

- src/api.rs
Follow the same pattern used in FrameInvariants::new_inter_frame()
> Simplify get_frame_properties/set_frame_properties

- Cargo.toml
- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/encoder.rs
* add color range support
* add hdr metadata support
> Color and hdr

- src/cdef.rs
- src/encoder.rs
- src/rdo.rs
Instead of a random mix of 2 spaces and 4 spaces.
> Consistently use 2-spaces indent

- src/api.rs
- src/bin/common.rs
Some preliminaries before trying to make receive_frame thinner by moving the FrameInvariants generation on the `send_frame` side.
> Refactor api

- src/bin/common.rs
- src/encoder.rs
Also correct help message, now that it works for 4x4.
> Set tuning to psychovisual by default.

- .travis.yml
> Add Rust backtrace to Travis

- src/api.rs
- src/encoder.rs
> Write temporal delimiters only at the beginning of a packet.

- src/encoder.rs
Also get rid of tuples to please @smarter.
> Define chroma plane padding in both dimensions

- benches/bench.rs
- benches/me.rs
- build.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/context.rs
- src/encoder.rs
- src/lib.rs
- src/mc.rs
- src/me.rs
- src/plane.rs
- src/transform/forward.rs
- src/util.rs
Automated by running `cargo fix --edition-idioms`
> Use Rust 2018 edition idioms

- Cargo.toml
- ivf/Cargo.toml
- ivf/src/lib.rs
- src/bin/muxer.rs
- src/test_encode_decode_dav1d.rs
> Prepare an ivf dumper for tests

- .travis.yml
- appveyor.yml
Working around an outage of https://www.nasm.us/
> Download nasm archives from mirrors

- src/me.rs
The speed does not seem to change and probably the workload is still small enough that rayon won't be useful by using it directly.
> Move full_search to an iterator

- src/encoder.rs
Adjust ObuMetaType.size() to return the payload size only.
Fix #977.
> encoder: Add missing trailing bits byte at the end of metadata obu

- src/encoder.rs
> Uleb128 writer

- Cargo.toml
- src/encoder.rs
-  12.5% speedup on `-s 3`
-  25% speedup on `-s 5`
> Use rayon to mt the motion estimation

- src/encoder.rs
- src/rdo.rs
Also, change some assert!() to debug_assert!() in bottomup partition.
> Fix misc. errtas and outdated comments.

- src/bin/common.rs
In order to support group headings in the help message, we needed to
upgrade to Clap v3, which is currently in beta and only available via
git.
Closes #938
Output:
```
─ cargo run --release -- -h
rav1e 0.1.0
AV1 video encoder
USAGE:
rav1e <INPUT> --output <OUTPUT>
ARGS:
<INPUT>    Uncompressed YUV4MPEG2 video input
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
INPUT/OUTPUT:
-o, --output <OUTPUT>       Compressed AV1 in IVF video output
--stats <STATS_FILE>    Custom location for first-pass stats file [default: rav1e_stats.json]
<INPUT>                 Uncompressed YUV4MPEG2 video input
ENCODING SETTINGS:
-p, --pass <PASS>                           Specify first-pass or second-pass to run as a two-pass encode; If not
provided, will run a …
```
> Reorder CLI options and group related options together

- src/rate.rs
Mimic current boosting, at the median value of 15 quantizer steps.
Keep current quantizer values for FRAME_SUBTYPE_P.
AWCY results at [default speed and tune=Psnr](https://beta.arewecompressedyet.com/?job=psnr-4db518c3511d18ab0aca224a0ea295fa18d3f486%402019-02-12T12%3A10%3A45.965Z&job=psnr-a-la-a-daala-rnsp%402019-02-12T14%3A14%3A07.525Z):
| -0.8152 | -1.7714 | -1.8240 |  -0.7137 | -1.1781 | -1.1106 |    -1.3330 |
> Quantizer modulation a la Daala

- src/api.rs
- src/bin/common.rs
This setting is hidden from the CLI help message, since it is intended
to be for benchmarking purposes only.
> Add --speed-test option for testing speed settings in isolation

- src/api.rs
- src/encoder.rs
- src/me.rs
- src/partition.rs
- src/rdo.rs
Uses the predictors of the EPZS algorithm.
Tourapis, Alexis Michael. "Enhanced predictive zonal search for single and
multiple frame motion estimation." Visual Communications and Image
Processing 2002. Vol. 4671. International Society for Optics and Photonics,
2002.
> Fullpel only diamond search motion estimation

- src/rdo.rs
It searches both luma and chroma modes.
> Rename luma_rdo to luma_chroma_mode_rdo.

- .travis.yml
- src/context.rs
- src/deblock.rs
- src/transform/mod.rs
https://rust-lang.github.io/rust-clippy/master/index.html#absurd_extreme_comparisons
> Enable extreme comparisons lint

- .travis.yml
- src/encoder.rs
https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
> Enable unused_io_amount clippy lint

- src/cdef.rs
Once all slice+stride have been replaced by `Plane(Mut)Slice`, we will not be able to provide multirows primitive slices anymore.
Therefore, expose raw pointers for the (unsafe) function `cdef_filter_block()`.
---
This is an alternative to #1039, which caused performances regression (cf https://github.com/xiph/rav1e/commit/fa65c3ab3fa6c14c6a7a007190434d0592067017).
> Use raw pointers for cdef_filter_block() params

- src/predict.rs
(I managed to fail at `git commit --amend`)
> Add back the predict tests

- Cargo.toml
Fixes a chroma error with odd frame sizes.
> Update Y4M dependency version

- src/partition.rs
- src/predict.rs
> Fix the broken directional intra prediction modes and re-enable them

- src/me.rs
Currently high precision motion vectors are enabled by default.
> Sub-pixel diamond search motion estimation

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/test_encode_decode.rs
> Thread aware API

- src/mc.rs
- src/transform/inverse.rs
These temporary buffers were required for marshalling to 8-bit assembly from 8-in-16 frames.
From an [AWCY run](https://beta.arewecompressedyet.com/?job=master-9baf1d6cc4c4eae7da3701ad0ba6c41ccc018321&job=rm-8-bit-buffers%402019-03-08T15%3A40%3A13.780Z) we see a moderate speed-up of 2~3%
> Remove obsolete 8-bit buffers for bitdepth of 8

- .travis.yml
- Cargo.toml
- Make the dev profile a little more optimized
- Make the other profiles have the debug information
> Update the compilation profiles

- src/test_encode_decode.rs
Apparently cbindgen has problems parsing them in the former rendition.
> Rewrite the high_bit_depth and chroma_sampling tests

- src/encoder.rs
- src/lib.rs
- src/plane.rs
- src/predict.rs
- src/test_encode_decode.rs
- src/transform/mod.rs
To fix #1101 I'll need to rework `Plane::data` a bit.
> Plane custom aligned storage

- Cargo.toml
- appveyor.yml
- build.rs
This doesn't actually call the assembly functdions yet.
> Re-enable building assembly files on Windows.

- .travis.yml
- appveyor.yml
For local builds this can halve build times with a hot cache. In CI there will be some overhead managing the cache.
> Use sccache in CI scripts

- src/mc.rs
> Disable prep_8tap assembly.

- src/encoder.rs
- src/me.rs
- src/partition.rs
- src/rdo.rs
It currently does not use previous frames computed motion.
> Diamond search for half resolution motion estimation

- src/me.rs
The temporary plane need not be provided by the caller of `sub_pixel_me()` and `telescopic_subpel_search()`.
Expose it only when it allows to avoid reallocations between several function calls.
Also, the callers of `diamond_me_search()` need not provide the optional plane; they just need a flag to enable subpixel motion estimation.
> Make temporary plane more internal in motion estimation

- src/me.rs
Benchmark results taken after adapting bench_get_sad to u8.
```
get_sad/BLOCK_4X4       time:   [24.171 ns 24.173 ns 24.174 ns]                               
change: [-6.3737% -6.3006% -6.2260%] (p = 0.00 < 0.05)
Found 6 outliers among 100 measurements (6.00%)
1 (1.00%) low severe
4 (4.00%) high mild
1 (1.00%) high severe
get_sad/BLOCK_4X8       time:   [33.877 ns 33.878 ns 33.880 ns]                              
change: [-9.7904% -9.7802% -9.7698%] (p = 0.00 < 0.05)
Found 8 outliers among 100 measurements (8.00%)
1 (1.00%) low severe
5 (5.00%) high mild
2 (2.00%) high severe
get_sad/BLOCK_8X4       time:   [30.759 ns 30.760 ns 30.761 ns]                               
change: [-12.743% -12.732% -12.722%] (p = 0.00 < 0.05)
Performance …
```
> Tidy sad_sse2 and add fast-path for aligned 16x16

- src/context.rs
In `BlockContext`, the blocks were stored as `Vec<Vec<Block>>`. Use a dedicated structure instead.
This will allow to provide a tiled view (`TileBlocks`).
> Add FrameBlocks structure

- src/context.rs
- src/encoder.rs
They are redundant with those of FrameBlocks.
> Remove cols and rows from BlockContext

- benches/me.rs
They have different paths and ASM functions.
> Bench the sad function for 8 bit and 10 bit

- src/api.rs
- src/encoder.rs
- src/scenechange/mod.rs
Some patches that could land as they are while I keep working on addressing the scenechange+reorder interaction.
> Preliminaries api rework

- src/api.rs
- src/bin/rav1e.rs
- src/rate.rs
- src/test_encode_decode.rs
Here some more refactors, some tests and a fix for a corner case condition.
Still in the way of fixing #1081 once for all.
> More API rework pending flushing logic fix

- src/encoder.rs
Isolate tile-specific code from frame-wise code.
>  Extract tile encoding to encode_tile()

- src/api.rs
(For the joy of @rom1v I did not make additional ones)
> Make the tests cover another corner case

- src/api.rs
- src/bin/rav1e.rs
They shouldn't be needed anymore.
> Remove get_frame_count and needs_more_frames

- README.md
> Remove mentions of no longer used libaom submodule

- src/encoder.rs
Subsampled motion estimation may not work for a block size smaller than the input frame (e.g. block 64x64 on a 40x40 input).
This is currently rarely a problem in practice, but with tiling, the tiles on right and bottom borders may be small and crash the encoder.
> Do not crash on tiny images

- src/predict.rs
- src/rdo.rs
Fix for #1195 and current issue 3 of tiling, https://github.com/xiph/rav1e/pull/1126.
> Enable tx partition depth 2

- ivf/Cargo.toml
> Prepare ivf for publishing

- ivf/Cargo.toml
- ivf/LICENSE
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
CC: @lu-zero
> Add LICENSE file for ivf crate

- src/bin/decoder/y4m.rs
- src/deblock.rs
- src/encoder.rs
- src/rdo.rs
The latest Rust version added some clippy checks.
> Fix new clippy warnings

- .travis.yml
- src/api.rs
- src/context.rs
- src/encoder.rs
- src/header.rs
- src/rdo.rs
This PR enables the Clippy's [collapsible_if](https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if) lint, and fixes all warnings caused by it.
> Enable the Clippy's "collapsible_if" lint

- src/api.rs
Add documentation for speed settings configurations for both impl and ppublic
fields
Ref #1077
> Document SpeedSettings

- src/api.rs
Add documentation of the encoderConfig for both impl and  public fields
Ref #1078
> Document EncoderConfig

- src/api.rs
A couple of the refactor patches from the `segment-thread`.
> Small refactors

- src/rate.rs
These were derived by running encodes of many clips at each quantizer, an logging their resolution, coded size, and log-space target quantizer. The relationship appeears to be linear, unlike Theora, so the bucketing by ibpp was removed in favour of a single value per frame type.
These values seem to give pretty good ballpark results; enough to base trial frame encodes on them.
This also includes proper values for both B frame depths, and thus removes the reuse of P frame scale/exp for B frames.
The data set used for these particular values are all of the video clips on https://media.xiph.org/video/derf/ as well as subset3 (for extra I frame data). Adding more clips from Vimeo's own corpus did not seem to affect the values much at all, anyway.
Thank you to @tterribe and @barrbrain for …
> rate: Replace imported Theora scale/exp values with properly trained ones

- src/api.rs
- src/rate.rs
An optimal content-independent scale estimator is up to an order of magnitude off, depending on content complexity. Account for that by running a trial encode for the first frame of each type and replacing the estimated scale with the observed value. Note that the scale filter has a latency of one frame of the same type, so we need to update the initial scale value as well.
> Add trial encodes for first frame of each type

- .travis.yml
Things like Clippy keep on breaking.
> Use an explicit rust version on Travis.

- Cargo.toml
- src/api.rs
To ease validate the input from the C functions.
> Add FromPrimitive to C-exposed enums

- src/rate.rs
With the default max keyint of 10s, and common length fades found in content, 256 frames is not sufficient to allow rate control to adapt properly; it is barely even past the GOP boundary.
This will introduce possible overflow problems with `log_scale` when 2-pass mode is intoduced.
This fixes horrendous artifacting on some clips, particularily with fades,
Sample file can be found [here](http://chromashift.org/fades_make_me_sad.y4m.xz). It is in xz-compressed y4m form, for @tdaede's convenience.
It can be reproduced easily with: `rav1e --output out.ivf --bitrate 500 fades_make_me_sad.y4m`.
@tterribe says `inter_delay_target` should also be clamped to something like 2x the value of `reservoir_frame_delay`, but I cannot remember the reason (other than it's related to 2-ass), and thus have …
> Remove the max limit of reservoir_frame_delay 

- src/bin/rav1e.rs
This fixes the problem @rom1v and @shreevari had.
> Do not lock stderr

- src/lrf.rs
Move to unsigend arithmetic in LRF box accumulations, and simply guard
the one subtraction that can underflow (that was the reason we were
using signed ints to begin with).  Fixes an overflow in 12-bit encodes.
> Fix for mult overflow in LRF (#1300)

- Cargo.toml
- src/bin/rav1e.rs
So the cli can exit cleanly on sigterm.
> Add signal support

- src/api.rs
- src/rate.rs
This eliminates some code duplication and aligns with [Theora rate control](https://git.xiph.org/?p=theora.git;a=blob;f=lib/rate.c;h=bf2b1396a17ea3c7d7ac87e8b78771f7874a4a8a;hb=HEAD#l732) design.
> rate: Merge record_trial_encode into update_state

- Cargo.toml
> Always build nasm-rs

- Cargo.toml
- nasm_rs/.gitignore
- nasm_rs/Cargo.toml
- nasm_rs/LICENSE-APACHE
- nasm_rs/LICENSE-MIT
- nasm_rs/README.markdown
- nasm_rs/src/lib.rs
Prepares for publishing to crates.io
> Move nasm-rs to a subcrate

- src/tiling/plane_region.rs
The remaning field was not updated
> Unbreak the row iterators

- Cargo.toml
- src/bin/rav1e.rs
I might need @EwoutH to test it on windows as well.
> Enable signal-hook in the supported platforms

- examples/simple_encoding.rs
- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/encoder.rs
- src/header.rs
- src/rate.rs
- src/test_encode_decode.rs
These have been reviewed by me on IRC before sending. Mainly sending to get it to run through CI.
This PR contains a public API break.
> Rate Control Fixes from Tim

- Cargo.toml
- avformat-sys/Cargo.toml
- avformat-sys/LICENSE
- avformat-sys/build.rs
- avformat-sys/data/av.h
- avformat-sys/src/lib.rs
- src/bin/muxer/avformat.rs
- src/bin/muxer/mod.rs
- src/bin/muxer/mp4.rs
@kodabb and @tdaede 
This will fix  https://github.com/xiph/rav1e/issues/998.
I am not familiar with rust. Any suggestion is welcome.
Please ignore de2611a and 32b57af, I already sent them out at https://github.com/xiph/rav1e/pull/1259
thanks
> add mp4 muxer.

- src/context.rs
We were only using every other value of these arrays.
> Shrink size of partition contexts by half.

- src/encoder.rs
Note: right now this is using the fixed temporal ratio of 1.1 as in the specification for rate estimation. In practice we have to make sure that a single tile cannot have a rate higher than 4K60 with a `TemporalParallelDen / TemporalParallelNum` ratio of 1.1.
This sets a minimum number of tiles regardless of what is requested by the user. So if we need at least 2 tiles to encode a given clip and the user requests 1, 2 tiles will be coded (otherwise the stream will not be compliant). If the requested number of tiles is higher, there is no change in behavior.
Tested by `println!()`ing `min_tiles`. There are other issues when trying to encode very large frames.
> Enforce minimum tiling requirements when encoding large frames

- src/deblock.rs
Clarification suggested by Yushin; I agree I was being over-paranoid
in rows/cols setup, and the paranoia is just going to confuse someone
eventually.
> Address codeview's suggestion in PR #1364; not a bugfix

- src/encoder.rs
- src/rdo.rs
> \<derf\> Be the change you want to see in the source.
> Rename block encode functions for clarity

- src/lrf.rs
Correct subtle bug: LRF filters pixel source (cdef or deblock) is
chosen according to y coordinate after clamping to crop-frame, not
before.  Bug only appears at bottom-of-frame.
> Fix for #1286: desync in LRF--- not desunc anymore

- src/api.rs
- src/bin/common.rs
- src/bin/rav1e.rs
- src/rate.rs
I did a preliminary review while this was on pastebin.
More comments welcome.
crav1e will need to be updated.
> 2-pass Rate Control from Tim

- src/bin/muxer/avformat.rs
- src/bin/muxer/ivf.rs
- src/bin/muxer/mod.rs
- src/bin/rav1e.rs
container format will use this information to build seek index.
This will make the mp4 seekable
> set key frame flag for container format.

- src/capi.rs
Currently, it uses heap allocations to pass the returned slice to C-land. This isn't much a perf hit, give the infrequent use (once per frame), and is a lot simpler than having callers provide alloc callbacks.
> capi: Add two pass API

- src/rdo.rs
luma_chroma_mode_rdo was a huge closure.
It is moved to a function of it's own.
> Move luma_chroma_mode_rdo to a stand-alone function

- src/frame/plane.rs
- src/lrf.rs
> Use integral images in the self guided filter

- src/capi.rs
The hard part is done, mapping the capi::Packet can be made it work with a From impl
> capi: Support u8 pixel format

- src/api.rs
These are tests for `output_frameno` to `input_frameno` correspondence and values of `end_of_subgop`.
The first set of two tests is for low-latency mode (no reordering, nothing interesting).
The second set of 5 tests is for chopping off 0 to 4 frames from the end of the video (5 being our subgop size). These seem to work correctly.
The third set of 5 tests is for splitting a subgop of 5 with a scene change at the 0 to 4th frame. They are marked as `#[ignore]` because this logic doesn't seem to be working correctly, as I outlined in the comment:
```rust
// Ignored because (TODO):
// 1. The scene change detector is fed frames in the wrong order (in the
//    output order rather than in the input order).
// 2. The output_framenos are incorrect for some reason.
```
These tests' ground truth …
> Add output_frameno & end_of_subgop tests

- .gitlab-ci.yml
This adds `gitlab-ci.yml` needed for Gitlab CI
> CI: Add gitlab-ci.yml

- src/api.rs
Also add missing comments to the `output_frameno` tests since I now understand what's going on there.
The scene change tests are once again commented out because I don't believe that part of the code is currently working correctly.
> Add frame_invariants.pyramid_level tests

- src/api.rs
Currently it won't be populated in the first call in twopass_out(), before receive_packet() is called.
> Make guess_frame_subtypes() work without frame_invariants

- src/api.rs
- src/capi.rs
`capi.rs` is an import from a project with the default rust coding style, `api.rs` piled up discrepancies over time.
> Rustfmt api and capi

- src/api.rs
- src/encoder.rs
- src/rate.rs
[AWCY](https://beta.arewecompressedyet.com/?job=master-2e127a6af412347ee3903ad391c2fabc60c4c9fe&job=lookahead-mv-2_5_check_that_nothing_changed%402019-07-12T23%3A12%3A55.064Z)
> Move FrameInvariants computation into lookahead

- src/encoder.rs
> Fix inverted condition for min_tile_cols.

- src/lrf.rs
Might fix an rdo problem with odd frame sizes. No tests were run on
this.
> Constrain input stripe height of lrf to fit in frame

- src/encoder.rs
- src/lrf.rs
- src/me.rs
- src/tiling/mod.rs
As uncovered by @dwbuiten patch.
> Warnings cleanup

- src/lrf.rs
Precursor to some form of vectorization.
> Flip the axes sgr is looped on

- benches/dist.rs
- src/frame/mod.rs
- src/frame/plane.rs
- src/lib.rs
Before documenting we should decide what to let the user use.
> Api release preparation

- src/encoder.rs
- src/header.rs
- src/predict.rs
This has no bitstream writing or AWCY change.
> Fix filter mode header writing code.

- src/tiling/tiler.rs
- src/util.rs
> Convert two functions to const fn

- crates/nasm_rs/src/lib.rs
- src/frame/plane.rs
Fixes #1299, and a warning when NASM is disabled.
> Fix NASM-related build issues

- src/api.rs
Ignore any other input once you start flushing.
Needs to be tested on real files.
> WIP: Make flushing idempotent

- src/rdo.rs
This makes skip win ties over no-skip.
https://beta.arewecompressedyet.com/?job=master-e82003643aa440c02d3c6669cd49b529567ef277&job=chroma_reverse_order%402019-07-22T01%3A47%3A48.466Z
master-e82003643aa440c02d3c6669cd49b529567ef277 -> chroma_reverse_order@2019-07-22T01:47:48.466Z
-0.1993 | -0.1852 | -0.3532 |  -0.1811 | -0.1777 | -0.1736 |    -0.1683
> Reverse skip/no-skip search for chroma mode.

- src/rdo.rs
Tested on this clip: https://gitlab.freedesktop.org/wayland/weston/issues/265
Before:
$ time target/release/rav1e ~/Downloads/pipewire-gtksink.y4m -o /dev/null --tiles 4
1920x1200 @ 30/1 fps
encoded 346 frames, 0.792 fps, 155.85 Kb/s
Key Frames:      4    avg size:   41038 B
Inter:         342    avg size:     176 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
After:
$ time target/release/rav1e ~/Downloads/pipewire-gtksink.y4m -o /dev/null --tiles 4
1920x1200 @ 30/1 fps
encoded 346 frames, 1.647 fps, 153.50 Kb/s
Key Frames:      4    avg size:   41006 B
Inter:         342    avg size:     167 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
> Zero distortion skip

- Cargo.toml
- src/bin/common.rs
- src/bin/error.rs
- src/bin/rav1e.rs
Make panic traces nicer and setup the infrastructure to report errors in a nicer way.
> Cli error reporting

- src/api.rs
In preparation of moving all of it in a separate thread.
> Move the lookahead in send frame

- src/api.rs
- src/frame/mod.rs
- src/lib.rs
(It sits on top of the API cleanup)
> Frame params

- src/api.rs
- src/api/color.rs
- src/lib.rs
And document the struct and enums while at it.
> Split the api.rs file in multiple files

- src/api/mod.rs
- src/scenechange/mod.rs
Also fixes the current flow of lookahead so it will always look `LOOKAHEAD_FRAMES` ahead, instead of only at the start of the video.
[AWCY](https://beta.arewecompressedyet.com/?job=master-94b5fa2e61b4e63e79cf456a0db05c55c95b0cc0&job=scenechange%402019-07-22T15%3A10%3A15.475Z) shows significant improvement on one clip, no change on other clips, which seems to match the intent of this change.
Closes #1441
> Use lookahead to avoid setting short flashes as keyframes

- benches/bench.rs
- src/api/mod.rs
- src/context.rs
- src/encoder.rs
- src/frame/mod.rs
- src/lib.rs
- src/lrf.rs
- src/partition.rs
- src/rdo.rs
- src/recon_intra.rs
- src/tiling/tile_blocks.rs
Complete/Fix: #1200, #1391, #1437.
> Intra pred topright bottomleft avail checker

- src/tiling/tiler.rs
> Don't factor the tile rate limit into min_tile_rows_log2.

- Cargo.toml
- doc/PROFILING.md
> Add the debug symbols on release and document how to profile

- src/scenechange/mod.rs
The signature of `is_key_frame` can be clarified,
because it doesn't need access to the whole frame subset.
> Cleanup SceneChangeDetector

- src/cdef.rs
I misunderstood the padding mechanics of planes with the first patch. This doesn't fix any bugs.
> With cdef, fully use built-in padding from planes

- .gitlab-ci.yml
- .travis.yml
- Cargo.toml
- clippy.toml
- src/lib.rs
- src/lrf.rs
- src/lrf_simd.rs
https://beta.arewecompressedyet.com/?job=master-52074d09a3563fe7c2ea0730c13ec919052b847c&job=sgr_simd_0%402019-08-02T00%3A11%3A25.533Z
~10% speedup.
> Implement quick and dirty simd intrinsics for sgr

- tools/submit_awcy.py
> Improve submit_awcy.py

- src/frame/plane.rs
> Add back as_ptr for PlaneSlice

- src/bin/common.rs
> Actually use the min keyframe interval from CLI

- src/api/mod.rs
Required to implement #1532 in a more performant and future-proof way. 40 lookahead frames would make the test take longer than it needs to due to needing more frames overall.
This does not yet make the number of RDO lookahead frames configurable from the CLI, or change it in any speed presets.
> Move rdo lookahead into config

- src/api/color.rs
- src/api/mod.rs
* Document color config enum members
* Set some comments in `api/mod.rs` to doc comments
`mod.rs` is huge and I am not too familiar with it, so will take more time to get it documented...
> Add some doc comments to the API

- src/encoder.rs
- src/me.rs
[AWCY](https://beta.arewecompressedyet.com/?job=master-599e3dd02a63dcadab3c14482704a4074e6fe92a&job=fix-me-probably-2019-08-08_132638-02d2b27)
> Small ME refactors/improvements

- src/bin/common.rs
- src/bin/error.rs
I leave to the willing people to wrap the rest.
> Map ParseIntError to CliError

- src/api/color.rs
- src/capi.rs
- src/encoder.rs
- src/util.rs
Some minor things found when browsing through the code.
> Corrected some common misspellings.

- src/test_encode_decode/dav1d.rs
(based off #1555, only the latest commit is new)
> Fix dav1d test

- .travis.yml
- .travis/install-aom.sh
- .travis/install-dav1d.sh
- .travis/install-kcov.sh
- .travis/install-nasm.sh
- .travis/install-sccache.sh
- src/test_encode_decode/mod.rs
Run custom jobs on latest stable Rust;
Improve caching;
Fix clippy lints in order to pass on latest stable
Closes #1554
> Travis cleanup

- .travis.yml
Also, follow the same argument order as other commands in `.travis.yml`.
> Travis: build tests target for ignored tests

- src/rdo.rs
- src/segmentation.rs
Introducing quantizer adjustment without speed loss.
[AWCY](https://beta.arewecompressedyet.com/?job=master-c8ca08c77c19514d251b497900d9a24e203caa0b&job=heuristic-sidx-2019-08-19_123457-9a6e4a7)
[AWCY vs. the RDO quantizers on --speed 2](https://beta.arewecompressedyet.com/?job=speed2-2019-08-19_131220-9a6e4a7&job=heuristic-sidx-speed2-2019-08-19_131918-69c0056): as expected, the RDO finds a solution that's slightly better.
> Add heuristic quantizer adjustment

- src/api/mod.rs
- src/asm/mc.rs
- src/asm/mod.rs
- src/cpu_features.rs
- src/lib.rs
- src/mc.rs
- src/predict.rs
- src/tiling/plane_region.rs
- src/util.rs
Just want to know what people think so far.
Despite what the title says, I haven't put in the tables with indexes correlating to feature level.
> Static lookup of pointers for mc functions

- src/lrf.rs
Though adapted from libaom, the existing LRF sgrproj_solve math is
incorrect in several places.  This patch corrects the errors and is
verified against libaom to give correct results.  Note that this code
is float and libaom is integer; this affects the exact solution.
> Fixes to sgr projection solving math

- build.rs
- src/asm/cdef.rs
- src/asm/mod.rs
- src/cdef.rs
- src/frame/plane.rs
- src/x86/cdef.asm
Cuts off about 1% of the runtime
> Add AVX2 CDEF Filter Assembly

- src/rdo.rs
[AWCY result at default speed](https://beta.arewecompressedyet.com/?job=master-5ab6b1c67071d5859b1643b81eb52caf28409f0b&job=cfl-early-termination%402019-08-23T11%3A32%3A08.294Z) with up to 1.4% reduction in encoding time:
| -0.0406 | -0.1360 | -0.0170 |  -0.0317 | -0.0844 | -0.0652 |    -0.0339 |
> Faster Chroma-from-Luma RDO

- .travis.yml
- src/asm/mod.rs
- src/cdef.rs
> Unbreak building with --no-default-features

- src/context.rs
This removes a number of unneeded muts and `self`s.
> Cleanup `ContextWriter` and `BlockContext` selfs.

- src/x86/satd.asm
Not really sure if this will fix the bug we have on windows.
> Fix incorrect reg count for satd assembly

- src/api/mod.rs
- src/cdef.rs
- src/cpu_features.rs
- src/encoder.rs
- src/predict.rs
(as discussed with Tim on IRC)
> Cpu feature level rework

- src/api/test.rs
- src/rate.rs
[AWCY just in case (all zeros)](https://beta.arewecompressedyet.com/?job=master-d512dc8f5778a9119050d8778e59befa97852784&job=fix-more-things-2019-09-03_145726-c6e6dd2)
> Fix integer overflow in select_qi

- src/quantize.rs
See comments for details on how the constants were derived, and the algorithm in general.
The intent is that this is used as the fast path once we add trellis quantization.
This particulrily helps high motion clips like Red Kayak and Ducks Take Off:
|                          Video |    PSNR | PSNR HVS |    SSIM | CIEDE 2000 | MS SSIM |    VMAF |
|                           ---: |    ---: |     ---: |    ---: |       ---: |    ---: |    ---: |
| ducks_take_off_1080p50_60f.y4m | -3.5880 |  -4.6035 | -3.3884 |    -1.3255 | -4.1065 | -9.5272 |
|         red_kayak_360p_60f.y4m |  0.1735 |  -2.2590 | -0.4001 |    -1.7106 | -1.9463 | -9.1934 |
AWCY Averages (varies a lot more by clip):
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |   VMAF |
|    ---: |    ---: | …
> Wonderful Thor Hack

- benches/predict.rs
- src/context.rs
- src/encoder.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
- src/transform/forward.rs
- src/transform/inverse.rs
- src/util.rs
Does not change the functionality, just makes it less strange.
> Aligned array constructors

- src/api/config.rs
- src/api/internal.rs
- src/api/mod.rs
- src/context.rs
- src/deblock.rs
- src/dist.rs
- src/encoder.rs
- src/mc.rs
- src/me.rs
- src/partition.rs
- src/rate.rs
- src/tiling/plane_region.rs
- src/tiling/tile.rs
- src/tiling/tile_blocks.rs
- src/tiling/tile_motion_vectors.rs
- src/tiling/tile_restoration_state.rs
- src/util.rs
> Use const fn in more places

- src/me.rs
- src/tiling/plane_region.rs
Use window iterators to select square regions.
Should give a couple % speedup. Here is a test from some time ago. https://beta.arewecompressedyet.com/?job=redo-f8008ce9e43c885629456e63798b72f80db84560%402019-09-01T01%3A56%3A10.119Z&job=full_search_lite_test3%402019-09-03T17%3A01%3A50.988Z
> Lower looping overhead in full_search

- src/rdo.rs
Gives a ~1% speedup.
https://beta.arewecompressedyet.com/?job=master-b4d418af0dc169e01b445fa06deb8b4665fa4c74&job=sse_4x4%402019-09-23T19%3A57%3A31.020Z
> Compute sse in sizes up to importance block size

- src/api/config.rs
- src/bin/common.rs
> Correct comment 0

- src/encoder.rs
- src/rdo.rs
Split from #1260
Resolves #1319
> Enforce skip == true, if all tx blocks are zeros

- src/rate.rs
> Fix new clippy errors in Rust 1.38

- src/api/config.rs
- src/bin/common.rs
Sync user-facing help text and code comments with current speed settings
> Correct help text and comments

- .travis.yml
- src/encoder.rs
- src/rdo.rs
- src/segmentation.rs
> Prevent segmentation from entering lossless mode.

- src/asm/x86/cdef.rs
- src/asm/x86/dist.rs
- src/asm/x86/mc.rs
> Remove vestigial x86_64 modules for asm

- .gitlab-ci.yml
- .travis.yml
- crates/nasm_rs/src/lib.rs
- crates/vergen/src/output/mod.rs
- src/bin/rav1e.rs
- src/lib.rs
> Define allowed clippy lints in code

- Cargo.toml
It adds some features we can use, but no changes but the bump right now.
> Bump err-derive

- src/asm/x86/transform/inverse.rs
These tests run the ASM code against the native code
and verify that the results are equal.
> Add tests for inverse transform ASM

- src/api/config.rs
- src/bin/common.rs
These updates were missed as part of #1774
> Update speed settings documentation

- src/activity.rs
- src/api/internal.rs
- src/encoder.rs
- src/lib.rs
I had to change the source branch.
Continued from #1263.
>  Add an activity mask

- src/context.rs
Results in approximately 1% overall encoding time reduction
at default settings, mostly by eliding bounds checks,
allowing the compiler to auto-vectorize loops.
The speedup, although small, is consistently reproducible
and verifiable through reduced instruction counts and profiler
reporting 10% reduced time spent in write_coeffs_lv_map,
which is responsible for ~10% of the total encoding time,
adding up to 1% total reduction.
> Optimizations to loops within write_coeffs_lv_map

- src/cdef.rs
- src/rdo.rs
Fix a few bugs in LRF that weren't causing trouble (yet), and one that was (limit cycle infinite loop).
AWCY incoming.
> Eliminate loop RDO infinite limit cycle loop

- src/rdo.rs
Create easier-to-understand code by moving these into separate functions
> Split out inter and intra mode decision

- src/transform/forward.rs
Use functions instead of closures. I have had problems with mixing simd
and closures before so I want to make sure nothing breaks in the future.
Move a macro so it doesn't end inside a future macro.
Replace our usage of add, sub, and default with our own version. This is
so we can apply unsafe to all of the trait functions. This means we
have to remove + and - operations.
> Prep forward transform code for simd

- src/encoder.rs
https://beta.arewecompressedyet.com/?job=master-5bee8ea5f32820a7b25849340dd0116a103074e1&job=master-5bee8ea5_tune_psnr%402019-10-31T21%3A44%3A50.469Z&job=fix_tune_psnr%402019-11-02T14%3A08%3A34.004Z
Closes #1816
> Fix tune psnr

- src/capi.rs
> Make rav1e_status_to_str return a static string

- src/capi.rs
> Add version APIs to capi.rs.

- .travis.yml
- Cargo.toml
- src/asm/x86/cdef.rs
- src/cdef.rs
- src/cpu_features/aarch64.rs
- src/lib.rs
- src/util.rs
> Address the new lints introduced with the current clippy

- src/api/internal.rs
Overall around 5% speedup on qcif with 8 tiles.
> Push the block_importances check before the update loop

- Cargo.toml
- doc/PROFILING.md
- src/api/internal.rs
- src/bin/rav1e.rs
- src/encoder.rs
- src/lib.rs
- src/scenechange/mod.rs
it is pending a 0.5 release of rust-hawktracer, the code is complete.
> hawktrace support

- Cargo.toml
Currently our documentation is not published correctly, this fixes it.
> Fix docs.rs generation

- src/asm/x86/ec.rs
A WIP rewrite of the SSE2 version of `update_cdf`, issue https://github.com/xiph/rav1e/issues/1720.
Current resulting assembly is pretty similar to the one written by hand in `dav1d`. I would like to see if I can do slightly better, and I would like to write a small documentation of what is happening.
> Rewrite of SSE2 `update_cdf`

- src/header.rs
- src/mc.rs
Add missing SWITCHABLE to FilterMode enum type.
> Add is_filter_switchable false case to frame obu header

- src/lrf.rs
About 8% faster encoding for qcif in 4 tiles.
Testing it on 1080p and 4k would be nice.
> Refactor apply_filter out of sgrproj_stripe_filter

- src/api/internal.rs
In preparation of using a parallel iterator over it.
> Refactor compute_block_importances

- src/x86/satd.asm
This file is an original contribution to rav1e by @KyleSiefring.
> Add Copyright notice for SATD assembly

- src/api/internal.rs
This clone, which was introduced in #1871,
was responsible for 40% of allocations
within rav1e. Although counterintuitive,
removing the frame data from the map
and reinserting it at the end of the iteration
is better because it avoids this clone.
Gives about a 4% speedup over master
with 1 tile on 720p test clip.
> Avoid a very expensive clone in compute_block_importances

- .github/workflows/rav1e.yml
If the index is stale package requests may 404.
> Call apt-get update in GitHub Actions

- .github/workflows/rav1e.yml
* Use debian packages for libdav1d, libaom and nasm
* Remove unused transitive build-deps
> Replace GitHub Actions build deps with debian packages

- .github/workflows/rav1e.yml
Initially, just for build-unix steps.
> Add sccache to GitHub Actions

- .github/workflows/rav1e.yml
- Clean up the code a bit
- Split the Windows job in two different jobs
> Simplify Github Actions

- src/transform/forward.rs
- src/transform/inverse.rs
- src/transform/mod.rs
This should prevent confusion and it is a good step forward making that code a bit tidier.
> Refactor transform to not use globs

- src/bin/rav1e.rs
> Avoid constant arithmetic overflow on 32-bit

- src/activity.rs
- src/rdo.rs
The LRF search and `ActivityMask` were allocating planar data as `Vec<Vec<_>>`.
Allocate as `Vec<_>` and use computed indices instead, e.g.:
`foo[x * w + y]` or `foo.chunks_exact(w)`.
> Reduce number of allocations for planar data

- src/rdo.rs
It should be just arguably easier to follow.
0.8% faster on the 1080p 8 tiles Bosphorus encoding testcase.
> Refactor rdo_partition_decision

- Cargo.toml
Include LICENSE, PATENTS, README.md and cbindgen.toml in the crate.
Also, reformat long lines in the Cargo.toml file.
> Add necessary files to the rav1e crate

- src/api/internal.rs
The initial patch results in non-zero lambda; need to ensure that the inputs to select_qi are accurate to achieve a reasonable estimate of lambda. **Edit:** The inputs are consistent.
AWCY results at [default speed on object-1-fast](https://beta.arewecompressedyet.com/?job=master-2ec50e357aa60e7c69f5fec63d4c3761c6536e53&job=look-ahead-lambda%402019-12-08T16%3A42%3A10.233Z):
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|    ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| -0.1166 |  0.1954 |  0.3946 |  -0.0908 | 0.0119 | -0.0061 |    -0.0495 |
> Estimate lambda in look-ahead motion-estimation

- src/api/internal.rs
- src/scenechange/mod.rs
About a 1% faster for the speed 10 use-case.
> Scenechange simplification

- benches/transform.rs
- src/asm/aarch64/transform/inverse.rs
- src/asm/x86/transform/forward.rs
- src/asm/x86/transform/inverse.rs
- src/asm/x86/transform/mod.rs
- src/encoder.rs
- src/lib.rs
- src/transform/forward.rs
- src/transform/forward_shared.rs
- src/transform/mod.rs
Putting this up here for other people to see. I haven't gotten the chance to read the entire diff in full. May need to split a few things into individual pull requests/commits.
> Add avx2 for forward txfms

- src/rdo.rs
> Change functions to const fn

- src/lrf.rs
Results can always fit in i64 regardless of what bit depth is used. It
doesn't seem like much vectorization is happening but it is faster. Some
quick tests show that switching to a smaller type seems to enable
auto-vectorization.
> Optimize sgrproj_solve to avoid f64 arithmetic

- src/api/internal.rs
- src/api/lookahead.rs
> Move out the lookahead allocation

- src/context.rs
And remove one unused function.
> Remove public from coefficient writing helpers

- src/context.rs
Improves performance slightly.
> Refactor coefficient writing

- .github/workflows/rav1e.yml
> Fix Windows build

- src/bin/common.rs
- src/bin/rav1e.rs
Potentially we could add windows support using winapi-rs later.
> Add a mini benchmark report to the cli

- src/api/internal.rs
Pass all the frames in the buffer to the scenedetector only when in flushing state.
> Unbreak the scenechange detection

- build.rs
- crates/vergen/src/lib.rs
- crates/vergen/src/output/envvar.rs
- src/encoder.rs
- src/lib.rs
> Happier clippy

- .github/workflows/rav1e.yml
> CI: Add cargo-c tests

- benches/bench.rs
- benches/rdo.rs
- src/rdo.rs
Also creates unit benchmark for function.
Improves speed of function by ~1%
>  Reduce float math in cdef_dist_wxh_8x8

- src/asm/x86/dist.rs
This commit utilizes the existing high-bit-depth assembly
for get_sad for all block sizes,
allowing other block sizes to call into the existing
4x4 and 16x16 get_sad assembly.
This results in a 75-95% speedup of get_sad on 10-bit encoding
for SSSE3-enabled CPUs. Overall encode speed improves
by ~2.5% at speed 6.
> Utilize HBD get_sad assembly for all block sizes

- src/rdo.rs
Cdef dist should autovectorize with default compiler flags now.
Since I don't see a performance benifit from it anymore, remove the forced
inlining.
> Make it easier for cdef dist to auto-vectorize

- src/asm/aarch64/transform/inverse.rs
- src/asm/shared/mod.rs
- src/asm/shared/transform/inverse.rs
- src/asm/shared/transform/mod.rs
- src/asm/x86/transform/inverse.rs
Refactor so that the majority of the work happens outside of the
macros. Also, share code between the arm and x86 versions.
> Refactor inverse transform tests for asm

- benches/bench.rs
- src/api/lookahead.rs
- src/encoder.rs
- src/predict.rs
- src/rdo.rs
Support angle delta as #1721.
H_PRED and V_PRED will be supported in the future because modification of pred_h and pred_v is required.
> Add fine directional intra prediction

- src/api/config.rs
- src/lrf.rs
- src/rdo.rs
Search half as many sgr parameters for speed 10.
> For speed 10, reduce self guided search space

- src/quantize.rs
Quantize already needs code to handle signed coefficients, so it makes
sense to divide absolute value of coefficients and apply the sign
locally.
~.3% performance improvement on vidyo1_720p_60fps_60f.y4m at the
default speed and quality. More performance improvement on more complex
clips and higher quantizers.
> Refactor sign handling from divu and to quantize

- src/asm/x86/mod.rs
- src/asm/x86/quantize.rs
- src/encoder.rs
- src/quantize.rs
> Add avx2 for dequantization

- cbindgen.toml
> Add a cpp_compat key for cbindgen

- src/rdo.rs
Angle delta for directional intra prediction is only available for block
size >= 8x8 in AV1.
> Fix desync on sub8x8 partitions caused by fine dir intrapred

- .github/workflows/rav1e.yml
Pending new packages from Debian unstable.
> CI: Remove libaom test for now

- src/transform/forward.rs
Moves the native forward transform code out of the Dim trait
implementation and into a seperate function that does not get
duplicated. No performance difference detected in the changed code.
Compile time and binary size.
Before
2m16.066s
29.5 MiB
After
2m12.034s
28.9 MiB
> Move native fwd tx impl into non-duplicated fn

- .github/workflows/rav1e.yml
Courtesy of Ubuntu PPA: [jonathonf/ffmpeg-4](https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4)
> CI: Restore libaom packages and tests

- src/asm/shared/transform/inverse.rs
I thought I had to reverse what dav1d did. I didn't have to reverse it.
> Use correct dimension to get x and y coeff in test

- src/asm/x86/transform/forward.rs
Moves the avx2 forward transform code out of the Dim trait
implementation and into a seperate frunction that does not get
duplicated. We have already done this with the native code, so the next
step will be removing the Dim trait from the fwd transforms entirely.
In theory, there should be some performance penalty for doing this.
While there were no large differences in performance evident from
a quick look peek into perf, some minor changes were made to mitigate
any potential problems. Branches were hoisted outside of for loops and
changed into match statements.
Compile time and binary size:
Before
2m11.366s
28.9 MiB
After
2m8.374s
27.7 MiB
> Move avx2 fwd tx impl into non-duplicated fn

- src/lrf.rs
- src/rdo.rs
Mutable regions should be preferred over mutable slices.
> Switch mutable slice with mutable region in sgr

- src/deblock.rs
Quick solution to get parallelism from deblocking. One would expect
that this would only halve the footprint of deblocking on a parallel
workload, since the luma plane is twice the size of the two chroma
planes on 420 video.
> Parallelize applying deblocking on the plane level

- src/deblock.rs
PlaneSlices take ownership of an entire Plane while PlaneRegions can be
split. In the future, we would like to segment planes while deblocking
for parallelization. This reduces the changes needed to do that.
> Replace PlaneSlices with PlaneRegions in deblocker

- src/api/test.rs
- src/encoder.rs
> Add switch frame interval condition.

- benches/rdo.rs
- src/api/internal.rs
- src/encoder.rs
- src/rdo.rs
About a 4% faster across all the speed levels.
> Cache the distortion scale computation

- src/encoder.rs
The compiler was not autovectorizing this section of code. Switches the
code to doing two seperate iteration on the input coefficients from using
repeat and chain. The first iteration processes the stored reconstructed
coefficients and the second processes the reconstructed coefficients that
can be assumed to be zero. This isn't used by default, but Thomas is
working on a project that uses it.
> Ease auto vectorization of tx distortion computation

- src/context.rs
@xiphmont do you have a testcase for this function?
> Refactor write_block_deblock_deltas

- benches/plane.rs
- src/encoder.rs
- src/frame/plane.rs
> Don't initialize planes used for downsampling.

- benches/transform.rs
- src/asm/x86/transform/forward.rs
- src/transform/mod.rs
Checks if the output of the avx2 and native code match.
> Add tests for the avx2 forward transforms

- src/asm/x86/transform/forward.rs
- src/transform/forward.rs
For large transforms we reorder coefficients from our forward transform
so that the codable coefficients are first. Before this patch, we would
do this by buffering the output forward transform then writing it out
in the correct order.
I'm a little suprised by the lack of impact in the microbenchmark
results. I expected the copy to be inefficient enough to provide a
performance boost when removed. It seems that a copy in the L1 cache
just doesn't have a noticable impact.
In the real world, performance does seem to improve on awcy by about
half a percent.
https://beta.arewecompressedyet.com/?job=master-redo-70dc401df%402020-01-19T14%3A02%3A47.242Z&job=embed_fwd_reorder%402020-01-19T14%3A25%3A07.898Z
> Eliminate buffer and copy for sifting codable coefficients

- src/rdo.rs
> Avoid creating checkpoint in rdo_tx_size_type on early exit

- src/context.rs
This enables us to know the length of the values
in coeffs_storage at all times,
and allows the compiler to auto-vectorize the
calculation of cul_level.
Overall speed difference is <1%;
the two loops at the end of this function
are responsible for most of the time consumption here.
This commit will hopefully unblock further
optimizations on those loops.
The aligned crate is being vendored here
because the upstream crate does not
have a type for 32-byte alignment,
which we need.
> Use ArrayVec instead of array of MaybeUninit in write_coeffs_lv_map

- src/api/config.rs
[AWCY result at speed 9 coming](https://beta.arewecompressedyet.com/?job=master-7293535_s9%402020-01-23T03%3A15%3A45.805Z&job=test_enable_inter-tx-split_at_s9_s9%402020-01-23T03%3A14%3A53.863Z)
> Enable inter tx-split at speed 9

- src/encoder.rs
- src/header.rs
- src/test_encode_decode/mod.rs
`force_screen_content_tools` was not set correctly. It must be 2 only when the reduced still picture header is enabled, which it cannot yet be, since we do not write palette mode info.
Also adds a test for it.
> Fix desyncs and bitstream corruption in still picture mode

- src/asm/x86/predict.rs
- src/partition.rs
This allows Z2 prediction dav1d assembly to
be enabled along with the intra edge filter.
Context for why this data is needed:
https://bugs.chromium.org/p/aomedia/issues/detail?id=2239
Tested only on nyan.y4m locally. AWCY run started [here](https://beta.arewecompressedyet.com/?job=master-131b2916ff290147e843d6e0ae704c8d6acf5ed1&job=ief-fix-131b2916ff290147e843d6e0ae704c8d6acf5ed1%402020-01-28T20%3A11%3A43.730Z). I expect a small performance improvement, but it might be within the margin of error, since Z1 and Z3 assembly is already enabled.
Fixes #2107.
> Provide dx and dy arguments to the Z2 prediction dav1d assembly

- build.sh
Use /bin/sh
Check if cargo exists before running it and use :+ for IS_RELEASE
Remove bashism
Add curl alternative if wget doesn't exist
Remove unnecessary  subshell on echos
Test if aomdec and mpv exist before testing them
Convert comments at the bottom to block comments
Right now testing to make sure it isn't broken
> build.sh: Clean up and add some checks

- src/api/config.rs
- src/api/context.rs
- src/api/lookahead.rs
- src/bin/rav1e.rs
- src/deblock.rs
- src/encoder.rs
- src/frame/plane.rs
- src/lib.rs
> wasm32-wasi support

- src/quantize.rs
The cast from i16 to i32 was identified as a hotspot,
so we avoid doing that cast within a loop to find eob_minus_two.
We also use unwrap_or_else to avoid performing that calculation
unless the "or else" condition is reached.
Overall 1.5% encoding speed improvement.
> Optimize quantize function

- benches/bench.rs
- benches/mc.rs
- src/asm/x86/mc.rs
- src/frame/plane.rs
- src/lib.rs
- Add put_8tap and prep_8tap x86_64 asm tests
- Add benchmarks for put_8tap and prep_8tap
> Add tests and benchmarks for put_8tap and prep_8tap

- src/asm/x86/dist/hbd.rs
The aligned store and load intrinsics are simple
pointer casts under the hood, which are guaranteed to be fast.
The unaligned store and load perform copies,
which may or may not be elided based on LLVM's whims.
No measurable performance impact, but it avoids
potential regressions based on CPU layout or LLVM changes.
> Use aligned stores and loads for HBD get_satd intrinsics

- cbindgen.toml
> Add v_frame to the cbindgen-parse crates

- v_frame/Cargo.toml
Make sure the Cargo.toml metadata is correct
> Prepare the v_frame release

- Cargo.toml
- src/api/config.rs
- src/api/util.rs
- src/bin/error.rs
- src/bin/kv.rs
- src/bin/rav1e.rs
it is a little quicker to build and doesn't use internals of quote.
See  #2192
> Use thiserror instead of err-derive

- src/bin/rav1e.rs
`process_frame` never returns more than one frame at a time,
so we can remove the `Vec` from the return type.
The loop is added inside `process_frame` in order to maintain
the expectation that `None` indicates the end of encode.
> Refactor process_frame in CLI

- src/cpu_features/x86.rs
Now copy dav1d in checking for pre-Icelake and Icelake avx512.
> avx512 support

- .github/workflows/rav1e.yml
See https://github.com/rust-lang/rust/pull/67429 and related issues.
> Workaround windows-gnu being broken on the current stable

- src/asm/x86/mc.rs
> Initialize to 0 the destination buffers

- .github/workflows/rav1e.yml
- src/fuzzing.rs
> Resolve build errors for fuzzer

- build.rs
The build is triggered only if the assembly files or the configuration
changes.
> Do not try to rebuild the assembly files if not needed

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
Performance improved, authentication persisted, local branch created.
See [What's New](https://github.com/marketplace/actions/checkout?version=v2.0.0#whats-new) on GitHub Marketplace.
> CI: Upgrade actions/checkout to v2

- .github/workflows/deploy.yml
- Fix `cargo-c` build
- Create prerelease with `rav1e.exe`
- Improve some parts of the deployment process
> Fix rav1e deployment

- .github/workflows/rav1e.yml
> Add macOS tests

- Cargo.toml
We might want to bump arbitrary as well.
> Version bumps

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
- appveyor.yml
people.xiph.org is down, so use a link that's not down to unblock CI
> Use upstream nasm download for Windows

- src/rdo.rs
Reduces encoding time by 5.5% to 12.2% at default speed preset in [AWCY](https://beta.arewecompressedyet.com/?job=master%402020-05-08T02%3A52%3A30.506Z&job=prune_inter_num_09_2%402020-05-09T09%3A22%3A24.343Z).
| -0.3557 | -0.4733 | -0.4837 |  -0.3510 | -0.3247 | -0.3380 |    -0.3872 |
Closes #1500.
> Prune inter mode list by SATD

- .github/workflows/deploy.yml
- Remove a useless job
- Clean up the script a bit
> Simplify deploy script

- src/api/context.rs
The current rate control code would error out once i32::MAX frames are totaled.
> Document the internal processing limit and error out when it is hit

- src/api/test.rs
Currently the latency is 3 frames.
> Add minimum frame delay test.

- src/api/internal.rs
- src/bin/decoder/y4m.rs
- src/bin/muxer/y4m.rs
- src/cdef.rs
- src/context.rs
- src/deblock.rs
- src/encoder.rs
- src/frame/mod.rs
- src/header.rs
- src/lrf.rs
- src/rate.rs
- src/rdo.rs
- src/test_encode_decode/aom.rs
- src/test_encode_decode/dav1d.rs
- src/test_encode_decode/mod.rs
- src/tiling/plane_region.rs
- src/tiling/tile.rs
- src/tiling/tile_restoration_state.rs
- v_frame/src/plane.rs
Making a PR so I can spend 10 days fixing what clippy doesn't like.
Need to check that LRF and deblock still work and aren't broken for 420.
Fixes #2190
> Add monochrome support

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
`curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.`
> CI: Workaround network issue for Windows nasm binary

- src/rdo.rs
I want awcy working again so I can test.
> Reduce the number of checkpoints used in tx rdo

- src/api/context.rs
- src/api/internal.rs
- src/api/test.rs
- src/api/util.rs
- src/capi.rs
- src/frame/mod.rs
@dwbuiten please test the C-API.
> Add a mean to forward opaque data from Frames to Packets

- src/bin/rav1e.rs
Some refactor to make the code a little cleaner and not write incomplete files if the pass data files aren't accessible.
> Cli cleanups

- src/asm/aarch64/transform/inverse.rs
- src/asm/x86/dist.rs
- src/asm/x86/transform/inverse.rs
> Backport to 0.3 branch

- .github/workflows/rav1e.yml
https://github.com/actions/cache/releases/tag/v2.0.0
> Update cache action

- Cargo.toml
- src/bin/decoder/y4m.rs
- src/bin/muxer/y4m.rs
- src/bin/rav1e.rs
> Update the y4m dependency

- Cargo.toml
This avoids having multiple copies of y4m built.
> Update av-metrics to 0.5

- src/api/config/mod.rs
- src/api/config/rate.rs
- src/api/context.rs
- src/bin/error.rs
- src/bin/rav1e.rs
- src/lib.rs
- src/rate.rs
> New Rate Control API

- src/bin/muxer/ivf.rs
On unix named pipes and character devices such /dev/null should not
be checked for existence.
Fixes: #2353
> Check for path existence only when it is a normal file

- src/encoder.rs
- src/rdo.rs
> Stop precomputing and passing around pmvs index

- .github/workflows/rav1e.yml
> Suppress a new clippy check

- src/lrf.rs
The problem had nothing to do with multipass.  It's related to issue 
#2212.
Specifically, the LRF code correctly fixes up the UV LRU size for
4:2:2, but does not reconcile Y.  Because only 4:2:0 can have
different LRU sizes for Y and UV, it leads to a desync.  The fix is to
treat the corrected 4:2:2 UV LRU size value as a maximum, and when Y
and UV differ, set Y and UV to min(Y, UV).
> Fix for issue 2311: Corrupt bitstream: multi-pass encoding

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
> Update cargo-c version

- .github/workflows/js_api.yml
- Cargo.toml
- rav1e_js/.gitignore
- rav1e_js/Cargo.toml
- rav1e_js/README.md
- rav1e_js/src/lib.rs
- rav1e_js/src/utils.rs
- rav1e_js/tests/node.rs
- rav1e_js/tests/web.rs
- rav1e_js/www/.gitignore
- rav1e_js/www/bootstrap.js
- rav1e_js/www/index.html
- rav1e_js/www/index.ts
- rav1e_js/www/package.json
- rav1e_js/www/tsconfig.json
- rav1e_js/www/webpack.config.js
> minimal jsapi with wasm_bindgen

- README.md
As appveyor integration has been removed
> README: drop appveyor badge

- src/api/config/encoder.rs
- src/api/util.rs
- src/asm/aarch64/dist.rs
- src/asm/aarch64/mc.rs
- src/asm/shared/transform/mod.rs
- src/asm/x86/dist/mod.rs
- src/asm/x86/mc.rs
- src/asm/x86/transform/forward.rs
- src/cdef.rs
- src/context/block_unit.rs
- src/context/mod.rs
- src/context/partition_unit.rs
- src/context/superblock_unit.rs
- src/context/transform_unit.rs
- src/deblock.rs
- src/ec.rs
- src/mc.rs
- src/partition.rs
- src/predict.rs
- src/rdo.rs
- src/transform/mod.rs
- v_frame/src/pixel.rs
Improves non-lto performance by 15-20%
> Inline various code to improve non-lto performance

- .github/workflows/deploy.yml
The wasm32-unknown-unknown target is not ready for consumption anyway.
> Unbreak the CI deploy

- .github/workflows/js_api.yml
* parallelize build and testing
* caching (actions/cache, sccache)
Fixes #2416
I am not 100% sure if sccache works correctly. Can someone familiar with sccache please have a quick look? (maybe @vibhoothiiaanand ?)
> CI: Improve jsapi CI

- src/api/context.rs
- src/bin/rav1e.rs
- src/rate.rs
The tests with a limited number of frames did not show the problem.
> Unbreak whole file rate control

- src/encoder.rs
To help understanding the function
> Add asserts in topdown partition search

- src/encoder.rs
- src/predict.rs
- src/rdo.rs
> Enable NEAR_NEAR2MV compound mode.

- benches/plane.rs
Closes #2263.
Padding is added for downsampling of odd sized input.
> Fix assert failure in bench of downsample_odd

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
> CI: Update nasm

- .github/workflows/rav1e.yml
> Run tests in Github Actions with ASM disabled

- build.rs
> Use CARGO_CFG_TARGET_OS where needed

- src/test_encode_decode/mod.rs
I am HAPPY to release this PR that will save precious time of every rav1e developer! :)
> Reduce input size of the test 'odd_size_frame_with_full_rdo'

- src/me.rs
Subpel motion vectors were being created when seeding the full search.
Later, when doing subpel search, the mvs retained the fractional
component from the initial estimate.
Also prune zero mvs from coarse motion vectors. This is a side effect
of refactoring the code.
AWCY run: https://beta.arewecompressedyet.com/?job=rerun-master-96a439c1f360b510651eb7aedf39c24458e02003%402020-07-21T17%3A06%3A11.036Z&job=quantize_fullpel_fix2%402020-07-21T16%3A48%3A53.265Z
> Ensure all mv predictors are converted to fullpel

- src/api/config/mod.rs
- src/api/config/rate.rs
- src/capi.rs
It needs some testing and opinions.
> Rate Control new C-API

- tools/draw-importances.py
- tools/draw-mvs.py
- tools/pyproject.toml
- tools/submit_awcy.py
Run `black` and `isort` on the `Python` scripts. Add a toml file to set the parameters used by the format tools.
> Format tools

- src/api/context.rs
- src/bin/decoder/mod.rs
- src/bin/decoder/y4m.rs
- src/bin/rav1e.rs
- src/capi.rs
- src/frame/mod.rs
- src/fuzzing.rs
- src/lib.rs
This would help avoid the problem you had with over emitting.
> Refine the RC API

- src/me.rs
- Fix to not use ts.input.plane[] directly and instead use
ts.input_tile[].
- Candidate position for EPZS motion estimation must be clipped to frame
size if a block straddle on frame boundary.
> Revise EPZS for open-partition

- src/me.rs
Since we perform multiple passes during motion estimation, it makes
sense to sample the bottom and right edges for predictors.
| -0.3470 | -0.4163 | -0.4998 |  -0.3425 | -0.3951 | -0.3994 |    -0.4004 |
https://beta.arewecompressedyet.com/?job=master-b17d5009f7e539aba2e1abde9cbb5203f1aca3f3&job=me_port_improved_predictors2%402020-08-06T17%3A44%3A58.052Z
> Optimize predictors for multipass motion estimation

- src/context/block_unit.rs
- src/context/mod.rs
- src/mc.rs
- src/me.rs
- src/rdo.rs
> Avoid choosing unrepresentable motion vectors

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
- README.md
Note that homebrew has moved on to 2.14.05 already.
> CI: Update nasm to 2.15.04

- .github/workflows/rav1e.yml
- .travis.yml
Test all crates adding the `--workspace` option to `cargo test`
Depends on #2522 
> CI: Test all crates

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
- .travis/install-aom.sh
- .travis/install-dav1d.sh
- Cargo.lock
- Cargo.toml
- build.rs
- src/api/config.rs
- src/arm/asm.S
- src/arm/tables.S
- src/capi.rs
- src/context.rs
- src/encoder.rs
- src/mc.rs
- src/me.rs
- src/rdo.rs
- src/test_encode_decode/aom.rs
- src/tiling/tile_blocks.rs
> v0.3.4 candidate

- v_frame/src/plane.rs
Plane::p accesses pixels in a fashion that the compiler
cannot assume to be linear. This is harmful to both
compiler optimization and cache linearity.
Although we cannot completely eliminate this problem
since two rows must be accessed at a time for downsampling,
we can alleviate it by accessing the data slice directly.
Improves performance of av-scenechange by 15%.
Did not benchmark rav1e but presumably helps by 1-2% there also,
since this code is shared between both applications.
> Avoid use of Plane::p in Plane::downsample

- src/api/config/encoder.rs
- src/api/config/mod.rs
- src/encoder.rs
> Detect more invalid configurations

- src/api/internal.rs
- src/lrf.rs
- v_frame/src/plane.rs
> Remove Plane::p() and PlaneSlice::p()

- src/api/internal.rs
- src/scenechange/mod.rs
First set of tiny changes of many. The final plan is to have a function that outputs the subgop as whole and possibly make so we do not need do not need `garbage_collect` anymore.
> Simplify internals

- benches/bench.rs
- src/api/config/mod.rs
- src/api/internal.rs
- src/api/lookahead.rs
- src/encoder.rs
- src/header.rs
- src/rdo.rs
- src/scenechange/mod.rs
- src/tiling/tiler.rs
About 1% faster on `-s 6 --tiles 16` on the honeycomb.
> Leaner frame invariants

- build.rs
> Support apple-silicon

- v_frame/LICENSE
> Add LICENSE file to v_frame

- .github/workflows/js_api.yml
- .github/workflows/rav1e.yml
This PR skips a CI check when a commit message contains the `[skip ci]` tag.
> CI: Add a way to skip CI

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
Replaces the proprietary script with the [ilammy/setup-nasm@v1](https://github.com/ilammy/setup-nasm) GitHub Action.
> CI: Use ilammy/setup-nasm@v1 to install nasm

- .github/workflows/deploy.yml
- .github/workflows/rav1e.yml
- Cargo.lock
- Cargo.toml
- build.rs
- src/encoder.rs
- src/lrf.rs
- src/rdo.rs
Please test it @nilleb and @fxcoudert 
Fixes #2626
> Update 0.3 for apple silicon

- src/api/config/mod.rs
- src/bin/stats.rs
- src/cdef.rs
- src/context/block_unit.rs
- src/context/frame_header.rs
- src/context/partition_unit.rs
- src/dist.rs
- src/ec.rs
- src/encoder.rs
- src/header.rs
- src/mc.rs
- src/predict.rs
- src/rate.rs
This PR fixes `clippy` lints introduced by `Rust 1.49`
> Fix clippy lints

- Cargo.toml
- fuzz/Cargo.toml
- ivf/Cargo.toml
- ivf/src/lib.rs
- src/ec.rs
- src/encoder.rs
- src/header.rs
> Bump deps for 0.4.0

- .github/workflows/rav1e.yml
Run the CI also on pushes and pull request to the 0.x maintenance branches (0.3, 0.4 etc.)
For this PR to have effect, it needs also to be merged to the 0.3 and 0.4 branches. Are separate PRs preferred, or can this commit be cherry picked?
> CI: Run on pushes and PRs to 0.x maintenance branches

- src/context/block_unit.rs
- src/context/cdf_context.rs
We should make sure that all the fields are instrumented
> Add few missing cdfs to the map

- src/rdo.rs
- v_frame/src/pixel.rs
This PR fixes `clippy` warnings introduced by `Rust 1.50`
> Fix clippy warnings

- build.rs
> Use cc to archive nasm objects

- src/api/channel/by_gop.rs
- src/api/channel/mod.rs
- src/api/config/mod.rs
- src/bin/common.rs
- src/bin/rav1e-ch.rs
It uses the internals as they are so there is some overhead due unneeded
computation we will remove later.
- Only single pass rate-control for now.
> Minimal of by_gop parallel encoding

- .github/workflows/rav1e.yml
> Run cargo check for unstable features

- src/api/test.rs
This PR corrects names of some scene change test to better reflect expected behavior
> Correct scene change tests

- src/bin/rav1e-ch.rs
- src/bin/rav1e.rs
> Move the cpu feature info line

- README.md
I'm not sure what to use for webchat, it seems that Libera.Chat
doesn't run a webchat yet.
> Move #daala to Libera.Chat.

- src/scenechange/mod.rs
Removes a pair of unnecessary allocations
> Minor scenechange code cleanup

- src/capi.rs
@tdaede you need this I think.
> Capi extensions

- .github/workflows/rav1e.yml
- examples/simple_encoding.rs
> Demonstrate filling a frame from raw pixels in the simple_encoding example

- src/bin/rav1e.rs
> Fix cli confusing error message

- src/lib.rs
This fixes the wasm32 build without atomics.
> Extend the rayon API mock to include scope()

- src/rdo.rs
It turns out that avoiding a call to `Iterator::take` allows LLVM to autovectorize `spatiotemporal_scale`.
For a comparison of the code generated (simplified for example): https://godbolt.org/z/56Kec186G
> Better autovectorization of `spatiotemporal_scale`

- build.rs
nasm-rs already has a version check.
> Use nasm-rs for nasm version check

- .github/workflows/rav1e.yml
This drops the dependency on libaom0.
> CI: Update to libaom to 3.2.0-2

- src/asm/x86/mc.rs
> Do not call put/prep avx2 functions for ssse3

- src/api/config/speedsettings.rs
It appears as though these doc comments were mixed up somehow.
> Fix doc comments in speedsettings.rs

- v_frame/src/plane.rs
Removing the bounds check from each iteration of the loop allows LLVM to autovectorize `downscale_in_place`, resulting in about 15% better performance of `downscale_in_place` on yuv420p 1080p when compiling with AVX2 enabled.
Also adds an assertion that `box_pixels != 0` at the beginning of the function as it avoids later division-by-zero checks which happen per loop iteration.
Here you can see the difference in assembly generated with this change on godbolt: https://godbolt.org/z/4M4xnoTPn
Performance of `downscale_in_place` in current master:
Performance of `downscale_in_place` with this change:
This was tested on a zen 1 Threadripper 1950x.
> Improve autovectorization of `downscale_in_place`

- src/rdo.rs
This changeset will cause rav1e, after evaluating the first TX mode for a size (which should always be DCT_DCT), to compare that cost estimate to any previous best cost estimate. If the cost estimate for DCT_DCT at this size is greater than the previous best estimate, the remaining transform modes are skipped for this size and rav1e continues to the next size immediately.
At speeds <=5 (i.e. when RDO TX search is enabled), this results in an encoding time improvement of as much as 15% depending on the source. This testing was done using hyperfine across several speeds and sources--improvements ranged from 3-15%, in a normal distribution, with no speed regressions.
BD-Rate regression average was, with MSSSIM, around .1% for bottom-up encoding and around .25% for top-down. With VMAF, the …
> Skip transform mode search based on transform size cost estimate

- benches/dist.rs
- src/api/internal.rs
- src/api/lookahead.rs
- src/asm/aarch64/dist.rs
- src/asm/x86/dist/mod.rs
- src/dist.rs
- src/me.rs
- src/rdo.rs
Pass width and height to these functions instead of block size.
> Allow passing cropped blocks sad and satd

- src/rdo.rs
Do this by allowing the cdef_dist kernel to run on any block smaller
than 8x8.
> Use cdef_dist on smaller block and edges

- src/api/context.rs
- tests/doctests.rs
To double check what is going on with #2851.
> Put doctests code in a separate test

- v_frame/src/plane.rs
No `unsafe` code is actually needed to remove the bounds checks in this case, however the extra bounds check from PR #2824 helps ensure that the behavior is still exactly the same in all cases (since calling `zip` will basically truncate the entire iterator to the shortest one, rather than ensuring that there are always a certain number of elements beforehand).
Generated assembly difference: https://godbolt.org/z/eTG7Txh9P
> Improve codegen of `Plane::downsampled`

- src/api/internal.rs
When tested at speed 3, this `collect` call was responsible for 50% of
all allocations performed by rav1e. The `collect` was necessary for the
row multithreading here to satisfy the borrow checker. However, even
after the removal of row multithreading in the `update_block_importances`
function, this change produces the following improvements:
At speed 3:
- 1.5% wall time improvement
- 22% CPU time improvement
- 2% peak memory reduction
At speed 10:
- 5% wall time improvement
- 40% CPU time improvement
> Avoid temporary allocation of block importance costs

- src/activity.rs
> Use 64-bits for calculating 8x8 variance

- v_frame/src/plane.rs
The optimizer cannot currently recognize that on little-endian architectures, the loop is equivalent to just a memcpy. However, when using `u16::from_le_bytes`, it recognizes the pattern correctly and emits a memcpy on little-endian architectures (and would generate efficient code to swap the bytes on big-endian architectures, at least that is what it does on x86 when using `u16::from_be_bytes` which requires an endianness swap since x86 itself is a little-endian architecture).
De-referencing a fixed-size slice of 2 elements seems to be crucial for the optimizer to emit the most efficient code, i.e. the code generated is not better than the current implementation when using `u16::from_le_bytes([bytes[0], bytes[1]])`. Passing fixed-size slices can be achieved safely by using …
> Improve codegen of copy_from_raw_u8

- v_frame/src/plane.rs
Same idea as PR #2930 but applied to `copy_to_raw_u8` which is used in the C api wrapper.
> Use `to_le_bytes` in `copy_to_raw_u8`

- .github/workflows/rav1e.yml
- .gitignore
This PR shouldn't consider the `target` directory anymore for coverage
> Do not consider some directories for coverage

- src/context/block_unit.rs
This should make profiling and optimization easier, as well as improve
the code readability.
> Split `write_coeffs_lv_map` into smaller functions

- .github/workflows/rav1e.yml
This PR ignores asm for code coverage analysis
> Ignore some directories for code coverage analysis

- src/x86/sad_plane.asm
Should fix any linker failures that have been happening recently due to relocations in `sad_plane`.
> x86: Fix relocations in `sad_plane`

- benches/bench.rs
- src/api/internal.rs
- src/api/lookahead.rs
- src/encoder.rs
- src/me.rs
- src/rdo.rs
- src/scenechange/mod.rs
- src/tiling/tile_state.rs
- src/tiling/tiler.rs
This is some initial rework to remove the spurious Arc:make_mut()
> Tile rework

- README.md
- Remove `travis` badge
- Simplify badges
> Improve badges in README

- src/encoder.rs
Removes some unnecessary copies and usages of ArrayVec.
> Clean up encode_partition_topdown()

- .github/workflows/rav1e.yml
At present, this installs the following versions:
```
libaom3 3.4.0-1
libaom-dev 3.4.0-1
libdav1d6 1.0.0-2
libdav1d-dev 1.0.0-2
nasm 2.15.05-1
```
> CI: Pull in dev packages from Ubuntu Kinetic

- Cargo.toml
- console version = "0.15" 
- dav1d-sys version = "0.5.0"
- system-deps version = "6"
> Bump console + dav1d-sys + system-deps

- src/capi.rs
This is a copy-based API, assuming that the T.35 metadata will
be small. In fact, it does one extra copy internally that could
probably be eliminated with some work.
It allows for multiple T.35 metadata messages to be added to a
frame, but no method to inspect or remove them (for references
or reconstructed frames, for example).
> Add T.35 metadata C API.

- doc/QUALITY_&_SPEED_FEATURES.md
This is a simple update job on the quality and speedfeatures in regards to libaom(aomenc).
Simple enough.
> Updating QUALITY_&_SPEED_FEATURES document in regards to libaom

- src/util/kmeans.rs
* Remove `#[allow(unused)]` now that segmentation uses k-means.
* Rename `centroids` to `means` - shorter and more general.
* Rename `N` to `K` - so that there are `K` means. Wow!
* Use references in update-means iteration - reduces `kmeans` code size by 5.5%.
* Split k-independent inner loop into its own function.
- Reduces code size of the k-means implementation by 28%.
- Hot instructions are concentrated in a shared block which is only 5.1% of total k-means code bytes.
The overall code size reduction for `kmeans` is 32%.
> Clean up k-means implementation

- src/api/config/encoder.rs
- src/api/test.rs
- src/bin/common.rs
- src/fuzzing.rs
It no longer has any effect, after reworking segmentation.
> Remove `aq_strength` configuration

- src/bin/common.rs
- src/context/block_unit.rs
- src/context/mod.rs
- src/deblock.rs
- src/ec.rs
- src/encoder.rs
- src/header.rs
- src/lrf.rs
- src/me.rs
- src/quantize.rs
- src/rate.rs
- src/transform/forward.rs
One instance of https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
Many instances of https://rust-lang.github.io/rust-clippy/master/index.html#bool_to_int_with_if
> Fix new clippy lints

- Cargo.toml
- src/asm/x86/transform/forward.rs
Should slightly reduce compile times and dependency fetching.
meant to push this to my own fork... had a disk failure, git files got corrupted, recloned and pushed to 'origin' which used to be set to my own fork... sorry about that 😅 (for clarification, I mean, I still meant to open this PR, I just pushed my local changes to the wrong remote repository)
> Remove arrayref dependency

- .github/workflows/deploy.yml
* Finish fixing up deploy script (artifact names)
* Fix up archive names in deploy script
* Deploy Windows-msvc-generic rav1e.exe
> CI: Fix up deploy workflow

- Cargo.toml
> Bump built to 0.5.2

- src/activity.rs
- src/api/internal.rs
- src/asm/shared/transform/inverse.rs
- src/asm/x86/dist/sse.rs
- src/asm/x86/lrf.rs
- src/asm/x86/predict.rs
- src/bin/rav1e.rs
- src/bin/stats.rs
- src/cdef.rs
- src/context/block_unit.rs
- src/context/mod.rs
- src/context/partition_unit.rs
- src/context/transform_unit.rs
- src/deblock.rs
- src/encoder.rs
- src/entropymode.rs
- src/frame/plane.rs
- src/header.rs
- src/lrf.rs
- src/mc.rs
- src/me.rs
- src/predict.rs
- src/quantize.rs
- src/rate.rs
- src/rdo.rs
- src/scenechange/fast.rs
- src/tiling/tile.rs
- src/tiling/tile_blocks.rs
- src/tiling/tiler.rs
- https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
- https://rust-lang.github.io/rust-clippy/master/index.html#manual_clamp
- https://rust-lang.github.io/rust-clippy/master/#suboptimal_flops
> Fix new clippy lints for Rust 1.66

- src/dist.rs
This commit results in an overall performance improvement of about 1% at speed 2 10-bit:
```
Time (mean ± σ):     43.455 s ±  0.134 s    [User: 43.464 s, System: 0.179 s]
Range (min … max):   43.305 s … 43.705 s    10 runs
Time (mean ± σ):     42.926 s ±  0.098 s    [User: 42.945 s, System: 0.166 s]
Range (min … max):   42.783 s … 43.097 s    10 runs
```
> Improve vectorization in get_sad

- src/api/internal.rs
- src/me.rs
> Save some bounds checks on me_stats

- src/tiling/plane_region.rs
This commit results in an overall performance improvement of <1% at speed 2 10-bit.
> Hint that creating a region from an empty plane is unlikely

- src/ec.rs
Not sure about performance impact, just trying to make the flow clear.
> ec: Simplify `lr_compute` function

- src/context/cdf_context.rs
Fixes https://github.com/xiph/rav1e/issues/3162
> Fix undefined behavior in CDFContextLogOps

- src/api/config/mod.rs
This depends on MAX_TILING_RATE and current dimensions. Fixes #3216
> config: constrain max fps

- Cargo.lock
This fixes a bug that was resulting in slightly reduced encoding quality.
> Bump v_frame to 0.3.6

- src/encoder.rs
It is used only when doing CFL.
Addresses #3257.
> Do not pass ac when it is not needed

- src/capi.rs
Act as helper to set boolean values.
Fixes: https://github.com/xiph/rav1e/issues/2155
> Add rav1e_config_parse_bool

- src/capi.rs
This should allow using the option through ffmpeg, for example.
> Expose no_scene_detection in capi

- benches/bench.rs
- benches/mc.rs
This was identified as a hot function, so a benchmark will help us to optimize it.
> Add benchmarks for motion_compensate function

- Cargo.lock
- Cargo.toml
Update built to 0.7.7 for https://github.com/lukaslueg/built/issues/80
to make reproducible builds easier.
> Update built to 0.7.7
