src/asm/x86/transform/forward.rs

This allocation occurred millions of times on a 60 frame 1080p test.

Remove an allocation from fwd_txfm2d_daala_avx2

---

.github/workflows/rav1e.yml
.travis/install-dav1d.sh

We are exchanging the time to fetch package lists on every CI task for effort to periodically update selected package metadata.

CI: Update libdav1d to 0.5.2

---

src/arm/32/ipred.S
src/arm/32/loopfilter.S
src/arm/32/util.S
src/arm/64/loopfilter.S
src/x86/film_grain.asm

This does not appear to affect any assembly that rav1e uses, but does bring us up to date to make future diffs easier to import.

Merge dav1d 0.5.2 assembly (x86 and ARM)

---

src/context.rs

Remanent from when we hooked up to libaom to implement stuff.

Remove unused extern from context code

---

.github/workflows/deploy.yml

`cargo` and `cargo-c` binaries are built on `Windows` and  then deployed on `Github` automatically through `Linux`. To create a new release, it is sufficient to add to the `CHANGELOG.md` file the necessary infos and push a new tag.

Automatically deploy rav1e

---

src/scenechange/mod.rs

If we start with the furthest frame,
we can imply that all closer frames
are also scene flashes
and avoid testing them.
<1% overall speedup.
(Tested on 1080p 60-frames, 8-tiles, speed 6.)

Early exit exclude scene flashes loop

---

src/frame/plane.rs
src/lrf.rs
src/tiling/plane_region.rs
src/tiling/tiler.rs

See https://doc.rust-lang.org/std/iter/trait.FusedIterator.html
"Calling next on a fused iterator that has returned None once is
guaranteed to return None again. This trait should be implemented by
all iterators that behave this way because it allows optimizing
Iterator::fuse."

Implement FusedIterator for all applicable iterators

---

src/deblock.rs

At some point a code cleanup of the deblocking filter seriously broke the deblocking SSE calculation in optimization. The horizontal edge calculation was actually looking at random vertical edges through the frame.  Some potential for panic even if testing up to this point hadn't tripped it.
Better yet, fixing it actually improves metrics.
deblock-fix-baseline@2019-12-19T16:41:23.981Z -> deblock-fix-result@2019-12-19T16:41:55.514Z
-0.1511 | -0.1740 | -0.2082 |  -0.0815 | -0.1449 | -0.1509 |    -0.1157

Fix for serious bug in deblocking RDO sse calculation

---

src/asm/aarch64/transform/inverse.rs
src/asm/x86/transform/inverse.rs
src/predict.rs
src/transform/forward.rs
src/transform/forward_shared.rs
src/transform/inverse.rs
src/util.rs

Reduces binary size from 42.5 MB to 37.8 MB.
Removes 40% of the LLVM-IR currently being created.
Reduces --release compile times by 15 seconds (Ryzen 5 3600).

Refactor BlockWxH out of predict intra

---

src/deblock.rs

chroma cropping was being handled slightly differently in RDO and actual filtering.  Actual filtering was correct (not a desync, just a very minor RDO effect).
AWCY reports zeroes-- that's due to our specific AWCY testset.

Small fix to deblocking RDO

---

.github/workflows/rav1e.yml

Follow up to #1965. The nasm-rs crate requires `link.exe` on the path.

CI: Use vswhere to query compiler path

---

.github/workflows/deploy.yml

- Now a pre-release can be created using the `p{date}` tag
- Add the `Cargo.lock` file both for `Windows` and `non-Windows` users
- Create a `.zip` file for `Windows` containing both the `.exe` file and the `cargo-c` output
[Here](https://github.com/Luni-4/rav1e/releases) you can find the results produced by this action. The only parts not automatized are the ones where you find the `Inserted manually` writing. The tags used as examples are fictitious.

Update the deploy action

---

src/rdo.rs

Although rustc still fails to autovectorize this function,
eliding the extra bounds check branches
gains 2.5% encode speed at speed 6
due to how hot this function is.

Elide bounds checks in cdef_dist_wxh_8x8 inner loop

---

Cargo.toml
src/bin/rav1e.rs

It reduces significantly the build time and allows better output customization.
```
>  Using y4m decoder: 176x144p @ 30/1 fps, 4:2:0, 8-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=64x64 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple include_near_mvs=false no_scene_detection=false diamond_me=true cdef=true use_satd_subpel=false non_square_partition=false enable_timing_info=false
>  CPU Feature Level: AVX2
>  Using 6 tiles (2x3)
?  debug message
!  warning message 
!! error message
>  encoded 600 frames, 80.182 fps, 55.64 Kb/s
>  ----------
>  Key …
```

Use fern and console instead of pretty_env_logger

---

src/rdo.rs

This makes cdef_dist_wxh nearly twice as fast.
1% speedup on qcif -s 0 single tile.

Inline cdef_dist_8x8

---

src/transform/mod.rs

This code has been commented for a very long time,
and also is not very important to address
because the Rust compiler is able to
auto-vectorize av1_round_shift_array successfully.

Cleanup long-term commented code in round_shift

---

src/predict.rs

Some of angles is fixed as Dr_Intra_Derivative table in the spec:
https://aomediacodec.github.io/av1-spec/#conversion-tables

Fix dr_intra_derivative value

---

src/asm/aarch64/transform/inverse.rs
src/asm/x86/transform/inverse.rs

The inverse transform assembly implementation uses the input
coefficients as scratch to avoid stack allocations. Properly designate
the coefficent input pointers as mutable on the inverse transforms
assembly function definitions for the inverse transforms.

Designate input coeff pointers as mutable on inverse transforms

---

.github/workflows/rav1e.yml

This forces the compiler cache to be updated when a new stable version of cargo is released.

CI: Include cargo version in sccache cache key

---

src/quantize.rs

Fix a off by one error in the eob calculation. We were treating eob
as if it didn't include the dc value except for one place. When we
found no ac values below our deadzone, we would try to quantize one ac
value.
Rework quantize so that eob is related both dc and ac values. We can
now return the precalculated eob.
Add a debug_assert for the eob.

Fix eob decision/computation in quantizer

---

src/encoder.rs
src/quantize.rs

Effectively replaces a hot branchy loop with memset.
Reduces encoding time by 1.8% to 5% at default speed preset.

quantize: initially zero coefficients

---

.github/workflows/deploy.yml

In the latest releases, `rav1e.exe` is always placed outside the `Windows` zip file, so let's make this process automatized

Do not zip rav1e.exe

---

src/rdo.rs

Fix bug found in #2021.
best.angle_delta.uv was happened to be non-zero which should be zero for PredictionMode::UV_CFL_PRED.

Fix bug in angle delta with UV_CFL_PRED

---

src/context.rs
src/encoder.rs
src/util/uninit.rs

Currently we are using MaybeUninit::uninit().assume_init() is an
undefined way. This patch uses MaybeUninit::uninit().assume_init() to
create arrays of MaybeUninit<T> which is defined behavior. Slices of
these arrays have their elements set and the slices of initialized
elements are transmuted to a slice of T.
One instance of full array initialization is replaced and one instance
of undefined behaviour is replaced.

Start to safely partially initialize slices

---

benches/predict.rs
src/asm/aarch64/predict.rs
src/asm/x86/predict.rs
src/partition.rs
src/predict.rs

Support angle delta for H_PRED and V_PRED, which was not supported in #2009.
The full set of directions is supported as #1721.

Add angle delta for H_PRED and V_PRED

---

benches/predict.rs
src/asm/aarch64/predict.rs
src/asm/x86/predict.rs
src/bin/stats.rs
src/context.rs
src/partition.rs
src/predict.rs

- Align enum values to spec
- Reorder code to match enum order
- Tidy up fine angular prediction tests

Align PredictionMode code to the AV1 Spec

---

src/bin/stats.rs
src/encoder.rs
src/predict.rs
src/stats.rs

Reduces time taken for stats merging with 16 tiles from 575us
to 224us on my machine.

Use flat arrays in stats collection.

---

src/asm/aarch64/transform/inverse.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/transform/inverse.rs
src/encoder.rs
src/transform/inverse.rs
src/transform/mod.rs

The inverse transforms from dav1d have eob optimizations. It is as
simple as providing those functions with the needed parameters.
Very small performance improvement. Measures in the scale of tenths of a
percent.

Use eob in inverse transforms

---

Cargo.toml

There is an outstanding bug in Rust/LLVM
where certain panics are optimized away
in debug mode when optimization level
is set to 2.
Until this is fixed,
this commit changes the optimization level
to avoid confusion around the Illegal Instruction
segfaults that are produced due to the compiler bug.

Change debug optimization level to 1

---

benches/bench.rs
src/api/lookahead.rs
src/encoder.rs
src/predict.rs
src/rdo.rs

Only one of angle_delta or alpha is used for predict_intra().
This ensures that (alpha == 0) || (angle_delta == 0) which avoids invalid calculation of angle.

Unify angle_delta and alpha to enum

---

src/api/config.rs
src/api/internal.rs
src/api/lookahead.rs
src/api/test.rs
src/scenechange/mod.rs

Closes #1528
Provides .1-.2% BD Rate improvement on scenecut-720p set.
Because the threshold scales based on distance
since the last keyframe,
it is expected that the improvement will be more on real content
(i.e. clips with more than 240 frames).
Overall is about 1% slower (with 1 tile) compared to master.
[AWCY](https://beta.arewecompressedyet.com/?job=scenecut-master%402019-12-09T01%3A05%3A19.889Z&job=scenecut-cost-3%402019-12-09T12%3A36%3A04.496Z)

Use intra and inter costs to determine frame type

---

src/context.rs

Minor optimization, avoids 3 instructions
in the case of skipping the iteration here.
Negligible speed impact.

Move continue condition before `abs` call

---

src/context.rs

This avoids a bounds check in each iteration of the loops,
turning the compiled ASM into two memset calls.
The write_b benchmark times improve by 20%.

Optimize set_coeff_context to do memsets

---

src/ec.rs

Improves write_b benchmarks by another 15-20%.

Avoid loop to get length in write_golomb

---

src/context.rs

Use the built-in cmp::min instead.
No impact on generated assembly.

Remove clip_max3 function

---

src/context.rs
src/encoder.rs
src/partition.rs
src/rdo.rs

Drop derivation of Ord, there is not a total order. Remove greater_than() and gte() from BlockSize; replace with the equivalent operators. Alternative to #2061.

 Implement PartialOrd for BlockSize

---

src/encoder.rs

A microoptimization if there ever was one. Saves 0.112ms on 480p.

Don't create pre_cdef_frame if lrf is disabled.

---

src/context.rs

FrameBlocks::new() is still pretty slow, at 0.223ms for 480p.

Derive Copy for Block.

---

src/asm/x86/cdef.rs
src/cdef.rs
src/rdo.rs
src/x86/cdef.asm

Uses an altered version of dav1d's cdef direction assembly. dav1d uses
8-bit input for low bit depth, while our input is converted to 16 bits
ahead of time. It might be preferable to be using the 8-bit version in
the future, but using 16-bits helps us avoid too many additional code
changes.

Add avx2 assembly for cdef direction computation

---

src/deblock.rs

Threads running deblock_plane are spawned from deblock_filter_frame. It
would be nice to be able to track them.

Add hawktracer hook for deblock_plane

---

src/cdef.rs

These errors aren't blocked by our tools when they are in tests.

Remove unused imports in tests

---

src/context.rs
src/encoder.rs
src/entropymode.rs

- Added some of the functions to decide the cdf (i.e. context) for txfm_split signal
- The tx-partition for intra mode block is enabled in Inter frame,
which previoulsly only enabled for Intra frame because tx_mode_select
flag is signabled at frame header..
TODO: If txfm_split = true is signaled in coming commits,
the location of each of four tx blocks (assuming a partition is a square)
within a partition is used to decide context, so the functions added in
this commit will need accomodate it.
AWCY speed 5:
| -0.8710 | -1.5453 | -0.9854 |  -0.6434 | -1.0012 | -0.8416 |    -0.9641 |

Enabling tx partition for inter mode, no-split

---

src/ec.rs

Removes the bounds check branch from inside the loop,
removes the counter variable,
and reduces the generated assembly by 9 instructions (18%).
[ASM Diff](https://www.diffchecker.com/Ab8aKUGm)

Optimize loop in WriterBase<WriterRecorder>.replay

---

benches/transform.rs
src/asm/x86/transform/forward.rs
src/transform/forward.rs
src/transform/forward_shared.rs

Instead of taking both an input and output, overwrite over the input
slice. Avoids using an extra array to perform forward transforms. This
will help us remove uninitialized arrays from the forward transforms.

Perform 1-d forward transform inplace

---

benches/transform.rs
src/transform/forward_shared.rs

The 1d benchmarks profile the native code and aren't very representitive
of the performance of the transforms as a whole. Switching to 2d
transforms also lowers the exposure of the benchmark code to the more
unstable internals of our forward transforms.

Replace 1d fwd tx benchmarks with 2d benchmarks

---

src/bin/rav1e.rs
src/lib.rs

None of these currently trigger any warnings in our code base,
but are generally useful and non-annoying to have enabled.
- expl_impl_clone_on_copy: Avoids potentially unsound manual `Clone`
implementations.
- linkedlist: Avoids `LinkedList`s, which are almost always worse
than a `Vec` or `VecDeque`.
- map_flatten: Prefer `.flat_map()` over `.map().flatten()`.
- mem_forget: Avoid using `mem::forget` with `Drop` types,
which will not trigger the `Drop` implementation.
- mut_mut: Avoid useless duplicate mutable borrows.
- mutex_integer: Recommend atomic integers over wrapping an integer in a
`Mutex`.
- needless_continue: Recommend when a conditional `continue` can be
refactored to a simpler control flow.
- path_buf_push_overwrite: Avoid pushing to `PathBuf`s a segment
starting with `/`, …

Enable potentially useful Clippy lints that are off by default

---

src/api/internal.rs
src/api/lookahead.rs
src/bin/rav1e.rs
src/cdef.rs
src/encoder.rs
src/header.rs
src/lib.rs
src/lrf.rs
src/me.rs
src/predict.rs
src/rdo.rs
src/scenechange/mod.rs
src/tiling/plane_region.rs

This will warn if a reference is used
which is unneeded and immediately elided by the compiler.
Removing the unneeded borrows can marginally
reduce compile time, and is generally a good practice.

Enable clippy needless_borrow lint

---

src/api/config.rs
src/api/test.rs
src/bin/common.rs
src/encoder.rs

Results for speed 10
```
PSNR |  PSNR Cb |  PSNR Cr | PSNR HVS |     SSIM |  MS SSIM | CIEDE 2000
-30.9829 | -19.2587 | -15.9204 | -18.5035 | -24.9531 | -17.7345 |   -25.8095
```
11% increase in execution time

Switch speed 10 from 64x64 to 32x32 partitions

---

benches/rdo.rs
src/api/internal.rs
src/encoder.rs
src/rdo.rs

Removes a conversion to and from f64.
Also, when implementing simd, it will be easier to work with integer
types.
https://beta.arewecompressedyet.com/?job=master-70dc401df1b7547ad1b1157004189febedb71e04&job=fixed_point_distortion_scores%402020-01-20T20%3A31%3A34.865Z
| PSNR | PSNR Cb | PSNR Cr | PSNR HVS |    SSIM | MS SSIM | CIEDE 2000 |
|-|-|-|-|-|-|-|
|0.0023 |  0.0434 |  0.0165 |  -0.0043 | -0.0257 | -0.0101 |     0.0498 |
Microbench results
```
cdef_dist_wxh_8x8
time:   [117.93 ns 118.11 ns 118.36 ns]
change: [-10.326% -10.058% -9.6566%] (p = 0.00 < 0.05)
sse_wxh_8x8
time:   [126.92 ns 127.02 ns 127.16 ns]
change: [+0.8375% +1.0859% +1.3056%] (p = 0.00 < 0.05)
sse_wxh_4z4
time:   [64.275 ns 64.332 ns 64.399 ns]
change: [-12.212% -11.607% -11.069%] (p = 0.00 < 0.05)
sse_wxh_2x2
time: …
```

Reimplement distortion scale using fixed points

---

src/asm/x86/transform/forward.rs
src/util/uninit.rs

First commit is single line patch that needs to be resolved for the next patch to work.
Use uninitialized memory to avoid invoking memset. Avoid assuming
uninitialized are initialized in one case and in the other, brazenly
use assume_init on an uninitialized array.

Avoid invoking memset in avx2 forward transforms

---

benches/bench.rs
benches/predict.rs
src/api/lookahead.rs
src/asm/aarch64/predict.rs
src/asm/x86/predict.rs
src/context.rs
src/encoder.rs
src/partition.rs
src/predict.rs
src/rdo.rs
src/tiling/tile_state.rs

This adds support for and enables the intra edge filter for directional prediction and closes #1065.
[This AWCY run](https://beta.arewecompressedyet.com/?job=master-s2-e9db8ff6c255491f44e321505d1d272ff1bcc855%402020-01-13T18%3A34%3A47.902Z&job=ief-rdo-s2-e9db8ff6c255491f44e321505d1d272ff1bcc855%402020-01-14T17%3A30%3A16.615Z) has the following results (at speed level 2):
```
-0.4245 | -0.7415 | -0.5551 |  -0.4450 | -0.4508 | -0.5157 |    -0.4762
```
Run time when called natively is around 4% worse than master on this run. The native version could probably be better optimized.
I was considering adding a speed preset for it, but I don't think it would be too useful since it is only applied when directional prediction modes …

Support intra edge filtering

---

src/rdo.rs

AWCY result at [speed 5 vs before tx_mode_select was enabled](https://beta.arewecompressedyet.com/?job=master-691e5605_s5%402020-01-16T00%3A16%3A53.649Z&job=tx-mode-select-prune-intra_s5%402020-01-17T05%3A26%3A23.276Z):
| -0.4098 | -0.5555 | -0.2928 |  -0.2246 | -0.4430 | -0.2509 |    -0.3236 |
At high rates, the increase in encoding time is reduced from ~180% to ~40%.

Restore intra mode pruning for tx_mode_select

---

src/api/config.rs
src/context.rs
src/encoder.rs
src/rdo.rs

This commit is prepared for the urgent demo purposes,
which requires tx partitions for inter mode blocks and one level split only at speed 10.
- DCT_DCT only
Known bug or limitation.
- Only works for reduced_tx_set enabled, with unknown reason.
TODO: Fix the bug!

Enable tx partition for inter mode at speed 10, always split once

---

src/context.rs

a813477b2acf460a4a54f981f53ceb6d96d45549 made a variable inconsistent to
how it is used in the spec.

Make variable in write_coeff consistent with spec

---

benches/predict.rs
src/asm/aarch64/predict.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/predict.rs
src/asm/x86/quantize.rs
src/asm/x86/transform/forward.rs
src/context.rs
src/encoder.rs
src/me.rs
src/partition.rs
src/predict.rs
src/rdo.rs
src/transform/forward.rs
src/util/align.rs

Because this struct can be used with any data types,
not only arrays, this commit updates the naming
of the struct and its internals to reflect this.

Clarify naming of AlignedArray struct

---

src/api/config.rs

~40% reduction in encoding time for 5% loss.
Will be turned on again when LRF is threaded.
master-2020-01-23_140900-5b94130e -> lrf_speed_level_9-2020-01-23_141104-1b821aa2
5.8688 |  1.9804 |  2.9445 |   4.3249 | 9.4403 |  7.3227 |     7.5342

Disable LRF at speed 10.

---

src/ec.rs

This function is particularly hot in WriterCounter,
taking about 5% of total encode time at speed 10.
This commit reduces the generated assembly
by 3 instructions and 1 branch.
Overall encode time reduced by 1%.

Simplify logic in Counter/Recorder store method

---

src/partition.rs

The output is same and encode time is almost same as [AWCY](https://beta.arewecompressedyet.com/?job=remove_unrequired_mode_in_selecting_part%402020-01-25T06%3A24%3A27.450Z&job=master-8ebe9233f6fbea4b3c83dd8f76129d196082e3d7).

Exclude unrequired mode for needs_top decision in get_intra_edges

---

src/context.rs
src/tiling/tile_blocks.rs

It's possible to change this in safe code. Changing frame_cols would
change the stride, letting the TileBlock access areas it shouldn't.

Remove public variable in TileBlocksMut

---

src/api/config.rs

Since we disabled lrf at speed 10, it might be nice to have a speed
level where this is enabled.
https://beta.arewecompressedyet.com/?job=less-lrf-s9%402020-01-26T22%3A34%3A57.608Z&job=master-5a085dce-s9%402020-01-26T22%3A34%3A00.083Z
~14% faster
```
-0.0272 | -0.1581 | -0.2157 |  -0.0570 | -0.0828 | -0.0697 |    -0.1354
```

Reduce lrf complexity for speed 9

---

Cargo.toml

In preparation to the next pre release.
rust_hawktracer 0.7.0 fixes a random crash on macOS
dav1d-sys 0.3.0 uses the up to date bindgen

Dependencies version bump

---

src/context.rs
src/encoder.rs
src/entropymode.rs
src/partition.rs

It will always be enabled in still picture mode.
Tested on nyan.y4m only. Running on AWCY [here](https://beta.arewecompressedyet.com/?job=master-sp-d65f25da6deb9df2289799d7e022f19bfc093e1e%402020-01-27T19%3A56%3A04.257Z&job=rsph-sp-d65f25da6deb9df2289799d7e022f19bfc093e1e%402020-01-27T19%3A56%3A21.154Z), there is on average a small improvement in BD-rate, though there is some added overhead from coding palette mode info. AWCY is not yet updated to detect desyncs, but if tests pass I assume all is well.
Closes #1000.

Fix and enable the reduced still picture header

---

src/cdef.rs
src/rdo.rs

This continues #1910 - the allocating function `cdef_analyze_superblock`, was in another file.

Reduce number of allocations for CDEF

---

src/api/lookahead.rs
src/asm/x86/predict.rs
src/encoder.rs
src/partition.rs
src/predict.rs
src/rdo.rs

This works towards supporting the assembly versions of directional predictors with the intra edge filter. However it seems like there is extra work to be done, as I am still getting desyncs locally when enabling the Z2 prediction.
As pointed out by @takehirokj, assembly for Z1 and Z3 prediction does not cause desyncs, so is enabled as well.

Pre-process the top-left intra edge pixel for dav1d IEF assembly

---

src/partition.rs

Non-directional modes do not need top-right edge

---

CONTRIBUTING.md

Original step showed difference in header even if there's no difference in frame data.
This is confusing.
This additional step excludes the difference in Y4M header as desync detection in
rav1e/build.sh (L56-59).

Remove y4m header in desync finding step of contribution guide

---

src/lrf.rs

The next rustc will mark it as a warning.

Remove unneeded parens

---

src/context.rs

The largest size of tx block that can be encodeded by AV1 coefficient
encoder is 32x32, thus reduce it down to around~1/4 of previous size.

Reduce the buffer of coeff encoder from 64x64 downto 32x32

---

src/encoder.rs

Currently the only CDEF "search" we do is to select parameters based on quantizer. This makes this choice explicit and defines placeholders for the 2 other search types we will want to implement.

Explicit cdef search types

---

benches/plane.rs
src/frame/plane.rs

Hi,
Currently, the hres and qres are talking half(1/2) and one-fourth(1/4) of the
width and height which is rounded down, when we have an odd-sized frame this becomes
a problem so to solve that we are rounding one up for both width and height.
Earlier: src.cfg.width / 2
Now    : (src.cfg.width + 1) / 2,
Fixes #2055
I am not 100% if doing this causes any other harm, but it would be great, to hear the comments with this

frame: plane: Fix Downsampling of odd sized frames

---

src/ec.rs

WriterCounter::store is especially hot,
and these branches were not easily predictable.
Provides a 6% encoding time improvement at default settings.

Remove branches in store methods

---

Cargo.toml

- [Faster and better](https://beta.arewecompressedyet.com/?job=v0.2.0-s10&job=v0.3.0-s10) Speed 10
- Smaller binaries (Around 3MB stripped on x86_64/Linux)
- Faster build times (About 14% faster build time)
- Multi-threaded deblocking filter
- Additional x86_64 SIMD code
- More auto-vectorizable codepaths and bounds check elisions
- ⅙ less memory allocations
- Improvements on the intra-modes pruning logic in the RDO
- More float to fixed-point conversions
- Make an early-exit condition in RDO faster
- Simplify logic in Counter/Recorder store method
- Support `wasm32-wasi` as build target.
- Intra edge filter (native mode only, about 4% slower at speed level 2 for 0.5% enhanced compression)
- Switch frame support (use `-S`, `--switch-frame-interval <SWITCH_FRAME_INTERVAL>` to enable it …

Prepare for release 0.3.0

---

src/bin/common.rs

This interface has been ignored and unviable
for quite some time.
Rather than attempt to maintain it,
I prefer to delete it, and if needed,
come up with a new approach for testing settings individually.
Up until now, we've been getting by with modifying settings
manually by editing the code base, because our need for
editing individual settings has been relatively uncommon.
This option has always been hidden and intended for developers only,
so there is no public API breakage from this change.

Remove speed test option from CLI

---

src/encoder.rs

Because it slow down encoder too much, 30% ~ 300%, for the given 1% coding gain.

Disable tx-split of intra blocks in inter frames

---

src/api/config.rs
src/rdo.rs

Closes #2167.
~30% speed up in speed 5 in [AWCY](https://beta.arewecompressedyet.com/?job=master_s_5%402020-02-14T14%3A11%3A21.320Z&job=disable_fine_dir_s_5%402020-02-14T14%3A07%3A13.758Z).
| PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
| ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| 0.6833 | 1.4316 | 1.3890 | 0.6723 | 0.7174 | 0.6667 | 0.8463 |

Disable fine directional intra prediction between speed levels 2 and 5

---

src/asm/x86/dist/hbd.rs
src/asm/x86/dist/mod.rs

There are probably still possible improvements,
and ideally we'd have ASM we can share with dav1d,
but this implementation provides a 50% speedup
in HBD get_satd for all block sizes compared to
the native implementation.
Overall encode speed improves about 1%.

Naive x86_64 intrinsics for get_satd HBD

---

benches/plane.rs

This fixes the warnings below:
"warning: unused variable: `output`
--> benches/plane.rs:22:11
|
22 |       let output = input.downsampled(960, 540);
|           ^^^^^^ help: consider prefixing with an underscore: `_output`
|
= note: `#[warn(unused_variables)]` on by default
..."

Fix build warnings in bench for plane downsample

---

appveyor.yml

Don't let AppVeyor run on documentation changes, CI changes, etc.

AppVeyor: Don't run on non-essential code changes

---

src/api/internal.rs
src/api/util.rs

This commit adds Reference Frame from the FrameData(Input) to the packets, so we could take this for calculation, for instance, Metrics calculations can be independent of API changes and will be cleaner to implement with fewer API breakages in favour of 1.0 Future Release.

api: Introduce reference frame for Packets

---

src/tiling/plane_region.rs

Fix clippy warnings: [iter_nth_zero](https://rust-lang.github.io/rust-clippy/master/index.html#iter_nth_zero).
Defining next() without nth(0) will be little bit redundant. Therefore, it's better to allow it in this case.

Suppress the nth(0) clippy warning

---

CONTRIBUTING.md
src/asm/aarch64/mc.rs
src/asm/aarch64/predict.rs
src/asm/aarch64/transform/inverse.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/cdef.rs
src/asm/x86/dist/mod.rs
src/asm/x86/ec.rs
src/asm/x86/lrf.rs
src/asm/x86/mc.rs
src/asm/x86/predict.rs
src/asm/x86/quantize.rs
src/asm/x86/transform/forward.rs
src/asm/x86/transform/inverse.rs
src/cdef.rs
src/cpu_features/aarch64.rs
src/cpu_features/mod.rs
src/cpu_features/rust.rs
src/cpu_features/x86.rs
src/dist.rs
src/ec.rs
src/lrf.rs
src/mc.rs
src/predict.rs
src/quantize.rs
src/transform/forward.rs
src/transform/inverse.rs

The term "native" is confusing, as in GCC/Clang,
"native" means use the highest optimization set possible,
whereas we were using it to mean the opposite.
This also renames all "native" modules accordingly.
Also adds documentation on how to change the ASM level at runtime.

Rename "native" CPU feature level to "rust"

---

.github/workflows/rav1e.yml
.travis/install-dav1d.sh

The deb-multimedia pool marches forward, and GitHub Actions caches expire.
So we must, once again, bump the package version.

CI: Update libdav1d to 0.6.0-dmo1

---

benches/bench.rs
src/cdef.rs
src/encoder.rs
src/rdo.rs

Closes #2056.
~1.2% performance improvements with 2x2 tiles in [AWCY](https://beta.arewecompressedyet.com/?job=master_tile_2_2%402020-02-09T04%3A02%3A27.514Z&job=thread_cdef_04%402020-02-11T12%3A18%3A23.482Z).
There's difference in the encoding output between with/wo threading when tile size is more than 2.
The output is same when tile is 1x1.
I'm not sure this is OK and need review.

Thread CDEF with tiles

---

src/rdo.rs

Part 1:
There is a known upper bound to the number of superblocks
and LRUs that this function can analyze at once,
so we can allocate a fixed sized array for the results.
Reduces the total allocation count by 25%.
No measurable impact on encoding speed.
Part 2:
Because looping through the planes is the inner-most loop,
reversing the layout of the nested arrays helps with linear
cache access.
Improves encoding time by 1%.

Optimizations to rdo_loop_decision

---

tests/binary.rs

The default (unset) and the option set exercise two different codepaths in the
rate control.

Add a test for reservoir-frame-delay

---

src/cdef.rs

This fixes the debug_assert failure in tile_restoration_state.rs.
This change makes the number of tiles for CDEF to the same
number of tiles for tile encoding specified by --tile-cols
and --tile-rows option.
Closes #2221.
Using the new TilingInfo different from encoding tile is better because more tiles can be used for
CDEF. However, using different TilingInfo and same FrameState caused the problem.
Therefore, this fix uses the same TilingInfo and same FrameState between CDEF and tile encoding.

Fix debug_assert with high quantizers

---

src/rdo.rs
src/test_encode_decode/mod.rs

The included tests also hit a condition in
tile_restoration_state.rs:367,
which currently passes CI because it is only a debug_assert,
but is something we should hope to fix quickly as well.
(A separate issue #2222 has been created for this.)
Fixes #2219

Fix panic on specific inputs with high quantizers

---

src/test_encode_decode/dav1d.rs

This resolves memory leaks in the fuzzer.

Add safe wrappers to dav1d test_encode_decode

---

src/test_encode_decode/aom.rs
src/test_encode_decode/dav1d.rs
src/test_encode_decode/mod.rs

Wonder no longer to which plane and row that diff belongs.
`compare_plane` asserts on a row at a time and is called for each plane.
Annotate the assertion with the plane and row indices.

Add context to failures in test_encode_decode

---

.github/workflows/rav1e.yml
.travis/install-aom.sh

It has been 14 weeks since the last libaom package update. This is much more stable than the libdav1d packages. For the curious, the differences with the last version follow:
```diff
diff -Nru aom-1.0.0.errata1/debian/changelog aom-1.0.0.errata1/debian/changelog
--- aom-1.0.0.errata1/debian/changelog	2019-12-20 10:38:51.000000000 +0000
+++ aom-1.0.0.errata1/debian/changelog	2020-04-13 15:14:23.000000000 +0000
@@ -1,30 +1,21 @@
-aom (1.0.0.errata1-2ubuntu3~18.04.york0) bionic; urgency=medium
+aom (1.0.0.errata1-3~18.04.york0) bionic; urgency=medium
* Revert to debhelper 11
- -- Jonathon Fernyhough <jonathon.fernyhough@york.ac.uk>  Fri, 20 Dec 2019 10:38:51 +0000
+ -- Jonathon Fernyhough <jonathon.fernyhough@york.ac.uk>  Mon, 13 Apr 2020 16:14:23 +0100
-aom (1.0.0.errata1-2ubuntu3) focal; …
```

CI: Update libaom to 1.0.0.errata1-3~18.04.york0

---

src/deblock.rs

Fixes #2239. All but the last row of horizontal edges were skipped for horizontally decimated chroma planes with a frame width of 16.

Fix deblocking of horizontal edges for narrow frames

---

src/rate.rs

`twopass_in()` is a function that does too much at the same time:
-  It initializes the second pass rc.
-  It provides the user the amount of bytes the same function would like to consume next
-  It consumes and parses the initial global header, called in the code summary.
-  It consumes and parses the per-frame information, depending on the configuration either a single per-frame data or a variable number of them in a single pass.
This PR addresses this problem by splitting the function in smaller ones with, I hoped, self-describing names:

Split the rate control twopass_in() in smaller functions

---

src/asm/x86/predict.rs
src/cpu_features/x86.rs
src/ec.rs
src/header.rs
src/rdo.rs

Due some miscommunication upstream disabled all the icelake flags in the
current stable release.
The issue is tracked in https://github.com/rust-lang/rust/issues/71473

Disable icelake detection

---

.github/workflows/rav1e.yml

Since `Rust 1.43` is out, this hack shouldn't be necessary anymore.

Remove cargo-c hack

---

.github/workflows/rav1e.yml

In order to find regressions like
https://github.com/rust-lang/rust/issues/71473
before stable releases.

Add beta to CI matrix

---

src/bin/common.rs

This is a partial fix for #2188.

Abort pass encoding without a bitrate target in CLI

---

src/bin/common.rs

Due to a bug, `-V` was not showing the short version number,
but instead it was mapping to `-0`, because this is the first digit
in rav1e's version number.

Fix version flag

---

src/rate.rs

Separate the rate control logic from the serialization/deserialization logic.

Further cleanup the rate control code

---

.github/workflows/rav1e.yml

It is unclear how safely failures can be recovered from with cache steps.
So I would lean toward reviewing the action's code before applying this.

CI: Continue on cache failures

---

src/api/config.rs

Fixes crash / panic when rdo_lookahead_frames was set to 0.

api: Properly validate minimum rdo_lookahead_frames value

---

.github/workflows/rav1e.yml

We may prefer to have the latest release even if it is not yet in homebrew.
This change tests the alternative, installing a pre-built release.

CI: Install cargo-c package on macOS

---

src/api/util.rs
src/stats.rs
v_frame/src/frame.rs
v_frame/src/plane.rs

When serialize feature is enabled, otherwise uses the
dummy noop trait.

Implement Serialize and Deserialize for Frame and Plane types

---

src/deblock.rs

This could happen if you pass a plane from the first pass,
for example.
This is not allowed because of math to look up blocks from
pixel coordinates.

Assert on deblocking a plane with subsampling > 1.

---

src/encoder.rs

This field is never used until it is assigned,
so the initial allocation is not needed.
Closes #2277

Remove initial allocation for lookahead_intra_costs

---

src/api/config/speedsettings.rs

While rationalising the speed presets in preparation for MSU Annual Video Codecs Comparison 2020, we identified that speed 5 is a good candidate for 1080p at 1fps encoding speed with a few changes. To avoid subjective quality regression relative to speed 6, we should also enable fine directional intra prediction at speed 5.

Enable fine directional intra prediction at speed 5

---

src/rdo.rs

While rationalising the speed presets in preparation for MSU Annual Video Codecs Comparison 2020, we identified that speed 5 is a good candidate for 1080p at 1fps encoding speed with a few changes. To reduce the large jump in encoding time relative to speed 6 while preserving the majority of the benefit from transform type and size RDO, disable the type RDO for inter. After this change, transform type and size RDO is only performed for intra blocks. In future, we should add speed settings to enable a wider search at slower speed levels.

Disable RDO of transform type for inter blocks

---

src/rate.rs

While rationalising the speed presets in preparation for MSU Annual Video Codecs Comparison 2020, we identified that color performance has not yet been optimised for non-4:2:0 subsamplings. This is relevant because half of the test sequences are 4:2:2.
Numeric analysis indicated 401 +/- 2 in Q12.
Gradient for 4:2:2 is estimated by the midpoint with 4:2:0, rounded down.
Before this change, it is likely that too many bits are given to chroma for 4:2:2 and 4:4:4.

Optimize chroma quantizer offsets for subset3 4:4:4

---

src/cdef.rs
src/encoder.rs

As far as I can tell, there are no outstanding issues with this combination.
However, I will attempt to revive the fuzzer to answer this with confidence.
Closes #1149.

Enable CDEF and restoration filters for 4:2:2

---

.github/workflows/rav1e.yml

This resolves an error in the action due to an argument name change.

CI: Upgrade grcov to 0.5.14

---

src/api/config/speedsettings.rs

Results for speed 5
|   PSNR | PSNR Cb | PSNR Cr | PSNR HVS |   SSIM | MS SSIM | CIEDE 2000 |
|   ---: |    ---: |    ---: |     ---: |   ---: |    ---: |       ---: |
| 0.0437 |  0.2620 |  0.2548 |   0.0581 | 0.1219 |  0.0928 |     0.1911 |

Extend reduced sgr complexity to speed 5

---

src/api/config/speedsettings.rs

Use full transform set at speed 5. [AWCY results at speed](https://beta.arewecompressedyet.com/?job=master-e78ea024-s5%402020-05-12T13%3A20%3A32.240Z&job=reduced-sgr-full-tx-set-s5%402020-05-13T00%3A23%3A29.650Z) 5 show a 6.7% reduction in encoding speed:
| -0.4730 | -0.0666 | -0.0089 |  -0.3140 | -0.3945 | -0.2972 |    -0.3169 |
Enable fine directional intra prediction at speeds 3 and 4. [AWCY results at speed 3](https://beta.arewecompressedyet.com/?job=master-e78ea024-s3%402020-05-12T17%3A21%3A50.704Z&job=fine-dir-s3%402020-05-13T02%3A29%3A31.716Z) show a 21.7% decrease in encoding speed:
|    PSNR | PSNR Cb | PSNR Cr | PSNR HVS | …

Balance speed levels 3 to 5

---

src/rdo.rs

1. Search matching deltas for luma and chroma
2. Refine chroma delta for best luma delta
Iterations are the sum of luma/chroma deltas rather than the product.
This should make this loop more than 4 times as fast, with insignificant change to BD-rate. AWCY results to come when it is less overloaded.
On `thaloundeskmtg360p_60f.y4m` at speed 5 and quantizer 100, this yields 37% overall speed-up. This clip has 2 keyframes out of 60 frames and they are ~40 directionally predicted.

Split fine directional prediction search into 2 passes

---

src/ec.rs
src/encoder.rs
src/header.rs
src/tiling/tiler.rs

Two patches implement the missing infrastructure needed to fix issue 2212 and allow proper Tile/LRU sizing in arbitrary 4:2:2 video.

Issue 2212

---

src/rdo.rs

This `collect::<Vec<_>>()` yields nearly 90,000 allocations for 5 frames of 1080p at speed 3. Replacing Vec with ArrayVec eliminates these allocations.

Avoid many temporary allocations for inter pruning

---

src/encoder.rs
src/rdo.rs
src/tiling/tile_state.rs

Fixes #2299.
Also added doc comments for the block context accessors.

Fix 4:2:0 assumption in IEF block context selection

---

.github/workflows/rav1e.yml
.travis/install-dav1d.sh

Now that dav1d 0.7.0 is out, bump our CI dependency before the previous version is removed from the pool.

CI: Update libdav1d to 0.7.0-dmo1

---

.github/workflows/deploy.yml

The script deploys:
- linux-musl binary
- aarch64-musl binary
- wasm32 binaries
- macos binary
- windows binary
- windows-msvc binaries produced by `cargo-c`
- windows-gnu binaries produced by `cargo-c`
- Cargo.lock
You can find a pre-release [here](https://github.com/Luni-4/rav1e/releases/tag/p20200229) and a release [here](https://github.com/Luni-4/rav1e/releases/tag/v0.4.9)

Improve the deploy script

---

build.rs
src/bin/common.rs

This is to easily identify if we have a
debug or release binary in use.
Closes #2257

Add profile name to version string 

---

src/bin/common.rs
tests/binary.rs

Needed to use the compile time value of the PROFILE var.
Trying to use the runtime value would cause the binary
to fail to run when not run through cargo.
Updates the binary tests to remove environment variables
set via cargo, so this sort of issue will be caught in the future.

Fix printing of the profile in version string

---

tests/binary.rs

This PR applies various refactoring to [`tests/binary.rs`](tests/binary.rs):
* add 
```rust
fn get_common_cmd(outfile: &str) -> Command
```
* combine related arguments in `Command.args(&[arg1, arg2])`
* refactor `fn get_tempfile_path(extension: &str)` to return `OsString`
* don't store `Command` in intermediate variable
Fixes #2337

Refactor the binary tests

---

src/bin/common.rs
src/bin/muxer/ivf.rs
src/bin/muxer/mod.rs

PR to fix #2295 :
- Add function ``IvfMuxer::check_file(path)``
- Calling from ``bin/muxer/mod.rs``, ``create_muxer(path)``
- Default value "N" 
- Add arg ``-y`` to overwrite uninteractive

Prompt overwrite file message

---

build.rs
src/arm/64/sad.S
src/asm/aarch64/dist.rs
src/asm/aarch64/mod.rs
src/dist.rs

When backported to v0.3.0 (see [barrbrain:aarch64-sad-0.3.0](https://github.com/barrbrain/rav1e/commits/aarch64-sad-0.3.0)), this yields a 66% overall increase in speed for the Phoronix test. The SAD calculations are about 7 times faster than the Rust version and the reduction in CPU-time is more substantial than the reduction in wall-time.
Fixes #2335.

 Add NEON assembly for dist::get_sad on aarch64

---

src/api/context.rs
src/bin/rav1e.rs
src/rate.rs
tests/binary.rs

The integration tests were not reporting the errors due the incomplete error management in the CLI.
This set addresses the errors and make sure the tests work as intended.
Also fixes #2354.

Unbreak the rate control

---

src/arm/asm.S
src/arm/tables.S

Compiling with clang-6, clang-9 there seems symbol redefinition
error:
cargo:warning=src/arm/tables.S:44:1: error: invalid symbol
redefinition
cargo:warning=rav1e_mc_subpel_filters:
cargo:warning=^
The symbols are actually being redefined which GCC did not catch
while clang did, so by exporting the constant which is defined in
the src/arm/arm.S for all macros fixes the issue.
Tested with clang-6, 9, GCC 7.5
Also have compiled all 3 individually to make sure there are no build failure
Closes #2352

arm: tables: Fix the symbol redefinition error

---

Cargo.toml

Due to how cargo parallelises building dependencies,
this has no effect on compile wall time with 4+ threads,
but does reduce compile CPU time by 3-5%.

Avoid building serde with default feature set

---

src/asm/x86/dist/hbd.rs

5m 00 to 4m 47 on awcy. 30188832 to 29804944 bytes for release build.

Reduce compile time for hbd satd intrinsics

---

src/recon_intra.rs

- Remove left over libaom code when poring to rav1e
- Uncomment some array declarations, which are not used now but required
for PARTITION_VERT_A and _B in the future.

Clean up recon_intra.rs, which are ported from libaom

---

Cargo.lock

This Cargo.lock is know to work with rustc 1.38.0.
The previous was not because of the doctest cfg key being still unstable on this version. `regex-1.3.9` addresses this.

Bump the Cargo.lock

---

.github/workflows/rav1e.yml
Cargo.lock
Cargo.toml
src/lrf.rs

Release 0.3.2 started pinning the dependencies using Cargo.lock.
Release 0.3.3 pins a newer regex version to support older (1.38.0) compiler
versions.

Prepare for release

---

.travis.yml
build.rs
src/asm/aarch64/mc.rs
src/asm/x86/cdef.rs
src/asm/x86/mc.rs

Integrated:
* `rav1e_avg_16bpc_neon`
* `rav1e_prep_8tap_regular_16bpc_neon`
* `rav1e_prep_8tap_regular_sharp_16bpc_neon`
* `rav1e_prep_8tap_regular_smooth_16bpc_neon`
* `rav1e_prep_8tap_sharp_16bpc_neon`
* `rav1e_prep_8tap_sharp_regular_16bpc_neon`
* `rav1e_prep_8tap_sharp_smooth_16bpc_neon`
* `rav1e_prep_8tap_smooth_16bpc_neon`
* `rav1e_prep_8tap_smooth_regular_16bpc_neon`
* `rav1e_prep_8tap_smooth_sharp_16bpc_neon`
* `rav1e_prep_bilin_16bpc_neon`
* `rav1e_put_8tap_regular_16bpc_neon`
* `rav1e_put_8tap_regular_sharp_16bpc_neon`
* `rav1e_put_8tap_regular_smooth_16bpc_neon`
* `rav1e_put_8tap_sharp_16bpc_neon`
* `rav1e_put_8tap_sharp_regular_16bpc_neon`
* `rav1e_put_8tap_sharp_smooth_16bpc_neon`
* `rav1e_put_8tap_smooth_16bpc_neon`
* `rav1e_put_8tap_smooth_regular_16bpc_neon`
* …

Integrate aarch64 assembly: src/arm/64/mc16.S

---

README.md

Since appveyor is no longer used anymore, this does not apply

README: Remove Windows builds sections

---

src/rdo.rs

A previous patch tried to do this, but missed the 4x4 case on subsampled
frames. Roughly 2% speedup on the default speed level.
https://beta.arewecompressedyet.com/?job=ref_c1432f0%402020-06-13T00%3A43%3A41.614Z&job=sse4x4%402020-06-13T00%3A42%3A15.960Z

Correctly chunk sse calc in importance block sizes

---

Cargo.toml

The performance difference has shrunk substantially adding inline to a
bunch of functions. The performance difference with or without lto is
about 4 seconds on the slowest clip/qp on a standard awcy run
(MINECRAFT, objective-1-fast, qp 80). The compile time difference is 42
seconds.
If it's possible to have good performance with lto off, then optimizing
without it will provide a good development profile. Going forward, it
would be advisable to use lto to check for performancem problems. It
may be possible to create a seperate profile between dev and release.
AWCY would need to be modified to use this and also work with old
versions of rav1e.

Remove lto from the release profile

---

Cargo.toml

It was added to workaround a limitation of the old cargo-c.

Remove the crate-type specifier

---

Cargo.toml

Decreases compile time on AWCY from ~4 mins to ~2.25 mins. Increases run
time roughly 4% and 10 seconds on the most intense clip/qp (MINECRAFT @
80).
Testing also shows that codegen-units=1 actaully causes a substantial
performance decrease when iterative compilation is enabled.

Remove limit on codegen units for release profile

---

Cargo.toml

Dramatically improves the speed of rebuilding release (i.e. not from
scratch). Little to no difference in runtime on awcy.
https://beta.arewecompressedyet.com/?job=codegen-units-incremental%402020-06-17T17%3A26%3A41.471Z&job=codegen-units%402020-06-17T14%3A13%3A14.505Z
before:
release profile: full build time
real    0m51.344s
user    6m47.160s
release profile: touch src/lib.rs
real    0m18.483s
user    1m29.580s
after:
release profile: full build time
real    0m48.754s
user    6m53.001s
release profile: touch src/lib.rs
real    0m3.177s
user    0m2.793s
---
Would appreciate arm benchmarks.

Use incremental builds for the release profile

---

.github/workflows/rav1e.yml
.travis/install-aom.sh
Cargo.toml
src/test_encode_decode/aom.rs

Decoders version bump

---

Cargo.toml
rav1e_js/Cargo.toml
rav1e_js/LICENSE
rav1e_js/src/encoder.rs
rav1e_js/src/encoder_config.rs
rav1e_js/src/frame.rs
rav1e_js/src/lib.rs
rav1e_js/src/packet.rs
rav1e_js/src/utils.rs
rav1e_js/tests/utils.rs
rav1e_js/tests/web.rs
rav1e_js/www/index.ts
rav1e_js/www/package.json
src/api/color.rs
src/api/context.rs
src/encoder.rs
src/lib.rs
v_frame/Cargo.toml
v_frame/src/lib.rs
v_frame/src/pixel.rs

This PR implements v0.1 of the jsapi. At this stage it mainly replicates the functionality from `example/simple_encoding.rs`, but controlled from JavaScript.
Next step towards #2381 
<details>
<summary><b>functions, classes etc. exposed to js</b></summary>
```ts
/**
* Runs on module import
*/
export function main_js(): void;
/**
*/
export enum Tune {
Psnr,
Psychovisual,
}
/**
* Sample position for subsampled chroma
*/
export enum ChromaSamplePosition {
/**
* The source video transfer function must be signaled
* outside the AV1 bitstream.
*/
Unknown,
/**
* Horizontally co-located with (0, 0) luma sample, vertically positioned
* in the middle between two luma samples.
*/
Vertical,
/**
* Co-located with (0, 0) luma sample.
*/
Colocated,
}
/**
* Allowed pixel value range
*
* C.f. …
```

Jsapi v0.1

---

src/bin/stats.rs

Fix issue #2395
Description: The number of frames is already shown when is not quiet, I just added the elapsed time when limit is passed or not.
Example:
- cargo run --release --bin rav1e -- input.y4m -o output.ivf -l 120
```
encoded 120/120 frames, 9.326 fps, 105.05 Kb/s, est. size: 0.10 MB, est. time: 0s,  elap. time: 12s
```
- cargo run --release --bin rav1e -- input.y4m -o output.ivf
```
encoded 120 frames, 9.571 fps, 105.05 Kb/s, elap. time: 12s
```

Add elapsed time

---

src/bin/stats.rs

Fix issue #2394
Description: Clear transient status before printing the last summary.
Before:
```
>  Using 1 tile
encoded 120 frames, 9.297 fps, 105.05 Kb/s                    >  encoded 120 frames, 9.297 fps, 105.05 Kb/s
>  ----------
```
After:
```
>  Using 1 tile
>  encoded 120 frames, 8.963 fps, 105.05 Kb/s                 
>  ----------
```

Clear transient status

---

.github/workflows/deploy.yml

This PR fixes #2404 
A pre-release is deployed on every Tuesday at 21:00 (UTC) automatically. If an error occurs during the build process, the pre-release can also be deployed manually, that's why the old method has been kept.

Deploy pre-releases periodically

---

.github/workflows/rav1e.yml

In this way it shouldn't be no more necessary to pin a nightly version for `grcov`

Run grcov on stable

---

src/context/frame_header.rs
src/rdo.rs
src/tiling/tile_blocks.rs

The borrow rules that were being used were too permissive. To make the
existing code work, it was necessary to split make additional changes.
Instead of calling count_lrf_switchable from ContextWriter, we make it a
function of CDFContext and call it from there.
#2379
#2380

Fix broken borrow checker for tile_blocks

---

src/api/internal.rs
src/api/test.rs

Also rearrange the test to make debugging the output easier.

Add low latency versions of frame queue tests.

---

.travis/install-dav1d.sh

Hi,
Debian deb has updated dav1d to 0.7.1.
Tested the script on pi it works fine

travis: Update the dav1d sha256 checksums

---

src/tiling/tile_blocks.rs

Reduce manual indexing in for_each in TileBlocks

---

src/asm/aarch64/mc.rs
src/asm/x86/ec.rs
src/asm/x86/mc.rs
src/asm/x86/quantize.rs

From perf, I'd estimate that this gives 0.5% total performance
improvement. This is also preventative, since some of these were already
getting inlined.

Inline some asm/simd callers

---

src/context/superblock_unit.rs
src/encoder.rs
src/me.rs
src/predict.rs
src/rdo.rs
src/tiling/tile_state.rs
src/util/align.rs

A large stack allocation was causing probestack to be called. This patch
improves performance by about 1.5% in total.
It should be noted that calling probestack on linux for a stack
allocation this size might be a bug in rustc/llvm.

Remove large stack allocation from interprediction

---

src/api/context.rs
src/bin/rav1e.rs
src/rate.rs

Do not assume the value returned by rc_second_pass_data_required is reliable
Receiving non-show_frame pass data may not reduce the number of packets
required.
Also set the current metrics correctly.
Fixes #2433

Unbreak reservoir-frame-delay

---

doc/README.md
doc/regress_log-bitrate_wrt_log-quantizer.ipynb

Add a brief description to the documentation table-of-contents. Add text from related commits and pull requests to the notebook to provide context. Hide code by default to focus on the results.

doc: Add a description for Rate-control Empirical Analysis

---

src/predict.rs

Not going to benchmark since the speedup should be fairly small.

Simplify extracting fractional mv data

---

.gitignore
tools/draw-importances.py

This commit refactors the draw-importance tool with multiple features like
+ Use click module for CLI parsing
+ Add --help for getting help
+ Add --verbose mode to get detailed output
+ Add --raw mode to get raw values
+ Add --path mode for batch processing of multiple files in a nice way
+ Uses regex pattern to matx the strings
The default mode where $program $hres.png $imps.bin is now replaced with the --input mode.
Screenshots:
- Help Screen
`./draw-importance.py --help`:
- Single File Mode
`tools/draw-importances.py --input tools/19-hres.png tools/19-imps.bin`
- Batch Mode
`tools/draw-importances.py --path /Volumes/buildBox/rav1e/rav1e/tools/ --verbose`

draw-importance: Rewrite CLI with batch mode

---

src/encoder.rs
src/header.rs
src/rate.rs

Fixes panics on saturating_add(100) and corruption on saturating_sub(100) to the dc qi.
Should I remove these debug asserts too?
https://github.com/YaLTeR/rav1e/blob/9721626144b00c377530c1dd0c9199040ef36a58/src/encoder.rs#L940-L943

Fix quantizer index clamping

---

src/api/internal.rs
tools/draw-importances.py

Right now we are exporting/storing width, height, block_importance,
for exhaustive analysis we need frame_subtype.
The get_frame_subtype from encoder.rs, will give the type of frame:
- if key_frame, then I(0) frame
- else, it will P(1) frame + pyramid level depth.
We are currently not using B0, B1 Frames for rav1e, but with help
of pyramid level value we can get the index.
Edit:
CLI Output preview:
<Details>
```bash
vibhoothiiaanand@derpBox /V/b/r/r/t/o/dump (draw-importance) [1]>
/Volumes/buildBox/rav1e/rav1e/tools/draw-importances.py --path .  --verbose
Input given: (None, None)
Path given: .
MODE 2
Frame Type List: [2, 3, 2, 3, 3, 2, 3, 0, 3, 1, 3, 1, 3, 1, 1, 3, 2, 3, 2, 3]
png list: ['./6-hres.png', './7-hres.png', './14-hres.png', './15-hres.png', './19-hres.png', './18-hres.png', …
```

api: internal: Export frame_subtype and update script to store it.

---

src/mc.rs
src/me.rs

The old predictors were sampling without regards to block size. All of
the samples would be taken from 4x4 blocks adjacent or on the upper left
corner of the currently tested block. The top right subset B (EPZS,
current frame) predictor and right and bottom subset C (prev frame) were
sampling entirely incorrect locations. The other predictors were biased
to that upper left corner.
Add an additional top left predictor.
| -0.3292 | -0.3730 | -0.1695 |  -0.3330 | -0.3641 | -0.3603 |    -0.3046 |

Use new, non-broken me predictors

---

src/api/config/rate.rs
src/rate.rs

This is a potentially breaking change (from what I could see, the only public component affected is the Error struct), and as such we might want to spiffy it up a bit more before merging. But I needed something to help debug my two-pass woes, and this does provide significantly more context into why parsing first-pass data would fail.

Improve error reporting from rate control API

---

doc/README.md
doc/TILE_ON_FRAME_BOUNDARY.md
src/cdef.rs
src/partition.rs
src/tiling/tile_state.rs
src/tiling/tiler.rs

The goal of this work is to establish the ground so that rav1e can encode blocks that straddle on bottom or right frame boundaries (i.e. #2396).
I thought it would better approach to first land this groundwork then land the open-partition feature,  #2396.
Because, that way we can ensure the groundwork itself does not affect the integrity of current master without any open-partition code mixed.
With this PR only, it is expected to not change coding behavior of current master.
Until it is finished, it will fail many of rav1e's internal cargol tests, mostly when comparing encoder and decoder outputs, not because the enc and dec's outputs really unmatched but more likely the dimension of plane when it is declared is not correctly changed.
When compare the two reconstructed outputs from rav1e …

Ground work to allow rav1e to access PlaneRegion memory that are outside of coded frame size

---

.github/workflows/js_api.yml

Add `--dev` to `wasm-pack build`. This is needed, because of https://github.com/rustwasm/wasm-pack/issues/886.
This should be reverted as soon it is fixed in `wasm-pack`.

CI (js_api.yml): Fix wasm-pack build

---

.github/workflows/js_api.yml

This PR has two purposes:
* basic checking of the javascript in `rav1e_js/www/`
* prepare for a continuous deployment of the rav1e_js example website
* ~~Upload artifact 'rav1e_js-pkg'~~
* Install and build javascript 
* Fix `wasm-pack test --headless --firefox`

Jsapi update ci

---

doc/AOM_ANALYZER.md

aomanalyzer.org needs an update too, but I don't know if we want to replace it with a link to media.xiph.org or try to get it to redirect there.
Also, it currently redirects to https://people.xiph.org/~mbebenita/analyzer/, which is the root directory containing the wasm files, so I don't understand why the instructions say to download "the AOM Analyzer" followed by the files in the directory. Maybe the instructions need to be rewritten as well.

Update dead links for AOM Analyzer

---

tools/submit_awcy.py

With this commit, users can submit runs to AWCY with
custom commit ID instead of choosing head which is the
current behaviour.
Usage: submit_awcy.py <normal commands> -commit $ID

tools: submit_awcy: Submit runs by commit ID

---

src/context/block_unit.rs
src/context/transform_unit.rs
src/deblock.rs
src/scan_order.rs
src/tiling/tile_blocks.rs
src/transform/mod.rs

Reduces size from 96 bytes to 36 bytes. A single block is used for every
4x4 of the current frame.

Reduce space to store Block struct

---

build.rs
src/asm/x86/mc.rs
src/cpu_features/x86.rs
src/util/align.rs

Closes #2195. The NEON assembly will be handled in #2376.

Implement AVX-512 assembly from dav1d 0.6

---

benches/bench.rs
src/context/block_unit.rs
src/context/transform_unit.rs
src/encoder.rs
src/me.rs
src/partition.rs
src/rdo.rs
src/tiling/tile_blocks.rs

Issue #2166
- AV1 spec allows to use a partition that straddle on frame boundary if
certain condition met, i.e, 'Not Split' is allowed if more than half of
the partition size is available (based on coded frame size, i.e. multipe
of 8 pixels) in either horizontal or vertical.
- For top-down partition search (i.e current speed levels 2~10),
use bottomup on frame boundary
- Functon for computing visible area of a partition or a tx block based
on actual frame size (not a coded size) is added and in general it should
be only used for a compute distortion. Hence, do not use it for adjusting the block size.
One good critical example would be that a coefficient block size, when it is encoded, is not affected by visibility.
- CFL specially requires to read outside the coded frame, when it compute …

Enable open partition on frame boundary

---

src/context/block_unit.rs

This bug has not affected current master because the RDO mode decision
does not include testing a skip case for intra mode partition.

Fix tx size context update for skipped intra block

---

src/rdo.rs

Avoid choosing a suboptimal luma delta if the optimal chroma delta mismatches, by varying only the luma angle delta in the first pass.
[AWCY results at default speed](https://beta.arewecompressedyet.com/?job=master-2e8d4bb35cb7d40eb7b06fd5b83211428c29739c&job=fine-dir-pred%402020-08-07T08%3A13%3A35.120Z):
| -0.0972 | -0.0008 | -0.0481 |  -0.1170 | -0.0991 | -0.1460 |    -0.1162 |

Improve first pass of fine directional prediction search

---

src/encoder.rs
src/header.rs

The false case is never implemented, and implementing it is not currently a priority, so it is essentially dead code.

Remove Sequence::separate_uv_delta_q

---

rav1e_js/Cargo.toml
rav1e_js/src/encoder/frame_encoder.rs
rav1e_js/src/encoder/video_encoder.rs
rav1e_js/src/lib.rs
rav1e_js/tests/utils.rs

* `encoder`
* Pass `EncoderConfig` as ref to constructor
--> This enables still using the config afterwards
* Rename [FrameEncoder, VideoEncoder]::fromEncoderConfig(...) to ::new(...)
--> doesn't change anything from js user perspective
* Rm `::default()` from `FrameEncoder`, `VideoEncoder`
--> get default config via `new Encoder(new EncoderConfig())`
* `mod`: `pub use encoder::VideoEncoder`
* `tests`: Clean `utils::simple_encoding`
--> Make test output less verbose
* bump version to `0.3.0`

rav1e_js: Various small changes

---

.github/workflows/rav1e.yml
src/asm/x86/dist/sse.rs

This testing feature fails to compile after #2444 was merged. Fix that error and enable the feature in CI.

CI: Add check_asm to extra features

---

build.rs
src/asm/aarch64/transform/inverse.rs
src/asm/shared/transform/inverse.rs

This commit integrates the following functions
~~This is still in WIP, current state: it do compile, encode, some tests are failing viz. 3~~
~~1. test transform::test::roundtrips_u16~~
~~2.  test_encode_decode::high_bit_depth_10_dav1d~~
~~3.  test_encode_decode::high_bit_depth_12_dav1d~~
~~due to mismatch in output.~~
~~Once it is fixed, the PR will be ready for review~~
Advances #2376

asm: aarch64: Integrate aarch64 assembly: src/arm/64/itx16.S 

---

src/asm/aarch64/transform/inverse.rs

The 16bpc is not having alignment issues, tested to see if there are any regression, no change in objective-metrics, also almost no change in FPS and encoding time, tested with chimera and costa-rica both of them are 10-bit clips.
Objective Metrics 
<Details>
```mindfreeze@honey-g ~/rav1e (master)> env RUSTFLAGS="-C target-cpu=native" cargo build --release; env RUSTFLAGS="-C target-cpu=native" time cargo run --release ~/COSTA-RICA-1080p-10b-400.y4m -l 100 -o /dev/null --tiles 15 --metrics
Finished release [optimized + debuginfo] target(s) in 0.12s
Finished release [optimized + debuginfo] target(s) in 0.12s
Running `target/release/rav1e /home/mindfreeze/COSTA-RICA-1080p-10b-400.y4m -l 100 -o /dev/null --tiles 15 --metrics`
>  Using y4m decoder: 1920x1080p @ 60000/1001 fps, 4:2:0, 10-bit
> …
```

aarch64: transforms: Enable identity transforms for 16bpc

---

Cargo.toml
src/api/config/encoder.rs
src/api/config/mod.rs
src/api/test.rs
src/bin/decoder/mod.rs
src/bin/decoder/y4m.rs
src/bin/rav1e.rs
src/capi.rs
src/encoder.rs
src/header.rs

This adds an aspect ratio input parameter
to the Rust and C APIs, computes the render
size by upscaling one dimension, and codes
it in-bitstream, as well as in Y4M output.
The default aspect ratio is parsed from
Y4M input, or set to 1:1 if absent.
Note that neither aomdec nor dav1d will propagate the bitstream render size to the Y4M files they output.
It doesn't seem to be honored by ffmpeg with aomdec either, but it might be with dav1d (haven't tested it myself, but the code seems present). Reconstruction output is affected as well.
I think we can close #2504 with this, as it implements everything that should be needed for decoders/players to correctly output/display the encoded video.

Support arbitrary SAR anamorphic video

---

Cargo.toml
README.md
src/api/channel.rs
src/api/config/mod.rs
src/api/internal.rs
src/api/mod.rs
src/api/test.rs
src/bin/common.rs
src/bin/decoder/mod.rs
src/bin/decoder/y4m.rs
src/bin/muxer/ivf.rs
src/bin/muxer/mod.rs
src/bin/muxer/y4m.rs
src/bin/rav1e-ch.rs
src/bin/rav1e.rs
src/rate.rs

This set provides a channel-based API that should make much simpler the normal usage.
TODO:
Open questions:
- Fit a `last-error` inside the ReceiverPacket abstraction and a mean to retrieve it
- For multipass the api can be a single function and use the Config rc information to decide if it has to be multipass/firstpass/secondpass/normal
Solves: #689
(apparently github got some consistency issue with #2118 so I ended up opening this)

Channel API

---

src/api/config/mod.rs
src/encoder.rs

Missing change for #2505, which causes panics when trying to encode clips specifying an SAR of 0:0.

Interpret 0:0 SAR as 1:1

---

src/encoder.rs
src/transform/mod.rs

Note that https://github.com/xiph/rav1e/commit/22bf11b7fc5ec47c2f31716fc916f8c3a5c11817 disabled RDO of transform type for inter blocks. To verify this change I reverted that commit, forced `reduced_tx_set_preset()` to `false` and forced `enable_inter_tx_split_preset()` to `true`. i.e.: https://github.com/barrbrain/rav1e/commit/ab278ccc2ddcc0bf1d2959ec28e1d786952f07cc
The only test failure I was able to induce was an assertion in `test_encode_decode::chroma_sampling_444_dav1d`.
This implementation uses the same simplification as in dav1d to remove the indirection via `TxSet`. Fixes #2122.

Map chroma transform types for inter

---

src/api/internal.rs
src/api/lookahead.rs
src/encoder.rs
src/me.rs
src/rdo.rs
src/tiling/mod.rs
src/tiling/tile_motion_stats.rs
src/tiling/tile_state.rs
src/tiling/tiler.rs

* Removes consideration of various coarse motion vectors from the list
of candidate motion vectors. This seems to be the largest source of
regression.
* Limit use of fullsearch behind a threshold value determined by the sad
of candidate motion vectors.
* Consolidate logic to handle subsampling and partioning the superblock.

Substantially rework initial motion estimation

---

crates/vergen/src/lib.rs

FIxes the warning on master, this came up after we enabled CI for all workspaces, ie. #2525

crates: vergen: Remove unused import

---

src/api/internal.rs
src/encoder.rs
src/header.rs

The spec has a code path in the uncompressed header named frame_size_with_refs(), defined in section 5.9.7, which an inter frame may use to infer its dimensions from one of the seven frames it uses as reference instead of inferring them from the sequence header or ultimately hardcoding them. This path is triggered on non error resilient encodings by signaling frame_size_override_flag == 1, a bit that means that either frame dimensions are coded in the frame, or that an attempt to infer both frame and render dimensions from a reference frame should be done.
For encodings using a SAR other than 1:1, rav1e is currently hardcoding the render sizes on every frame, which is an overhead of about 4 bytes. With this change, for inter frames the encoder will look at each of the seven reference …

header: implement frame_size_with_refs()

---

src/api/config/mod.rs
src/bin/decoder/y4m.rs
src/encoder.rs

This fixes the minimum SAR to 1:1 so that
Y4M files signaling 0:0 SAR can be processed,
without allowing illegal SAR values at the
API level or handling them from the encoder.
In practice this slightly simplifies the SAR handling in the `encoder` module, as well as validation in the API `config` module, while making the Y4M `decoder` module responsible for filtering the input SAR. A validation error will be returned if the SAR is set to 0:0 at the API level.
As suggested in the comments of #2523.

Filter input Y4M SAR

---

src/api/internal.rs
src/bin/common.rs

As pointed out by @ycho, still picture mode streams must be single frames for compliance.
I am not sure if this is enough to block API users from pushing extra frames, so would like a check from someone who is more familiar with that part.
The CLI will panic if a user sends a limit > 1.

Enforce a frame limit of 1 in still picture mode

---

src/api/config/speedsettings.rs

Changes only speed 2. Encoding speed is reduced by 5.5%:
| -0.7704 | -1.6432 | -1.4803 |  -0.6959 | -0.7822 | -0.7149 |    -0.8890 |
The faster speed levels adopted fine directional prediction prior to #2301 and #2486.
The penalty for consistency with other speed levels is more reasonable now.

Enable fine directional intra for all presets

---

src/asm/x86/cdef.rs

In `rav1e::cdef::rust::pad_into_tmp16` while fuzzing:
```
AddressSanitizer: stack-buffer-underflow
```
The pointer into the buffer was negative-offset for alignment, but a one-stride offset is also required to ensure that writes occur within the bounds of the buffer.

Avoid buffer underflow in CDEF pad_into_tmp16()

---

src/tiling/tiler.rs

```
running 1 test
Overrun in OBU bit buffer into next OBU
test test_encode_decode::fuzz_422_77x17_tile_cols_2_dav1d ... FAILED
failures:
---- test_encode_decode::fuzz_422_77x17_tile_cols_2_dav1d stdout ----
thread 'test_encode_decode::fuzz_422_77x17_tile_cols_2_dav1d' panicked at 'assertion failed: `(left == right)`
Diff < left / right > :
<1
>0
', src/test_encode_decode/mod.rs:144:7
```

Fix and add test case for 4:2:2 fuzzing failure

---

Cargo.toml

Do not build av-metrics with the decoders dependency

---

Cargo.toml
fuzz/Cargo.toml
fuzz/fuzz_targets/construct_context.rs
fuzz/fuzz_targets/encode.rs
fuzz/fuzz_targets/encode_decode.rs
src/fuzzing.rs

This is necessary after #2489, which replaced usage of `RingBuffer` by `Unstructured`. We unwrap an `Error` when the fuzz input is small. We should rather implement `Arbitrary` and raise the `Error` there.

Implement Structure-Aware Fuzzing

---

.github/workflows/rav1e.yml
CONTRIBUTING.md

Removes our one remaining dependency on a pinned nightly toolchain.

CI: Build fuzzers with stable rustc

---

src/fuzzing.rs
src/test_encode_decode/mod.rs

Increase the value ranges for fields of DecodeTestParameters. Ensure the still_picture limit is respected.
Use a single thread for encode_decode - This helps to avoid over-allocating threads when running with many cores.

fuzzer: Increase coverage of encode and encode_decode

---

src/lrf.rs
src/me.rs
src/transform/mod.rs

The first fix here is simply to add a clippy annotation to the
`get_subset_predictors` function to allow stable sorts. I suspect
order matters in these sorts hence this annotation.
second is a simple use of the `matches!` macro
and the third is a removal of a Self type.
Clippy links:
https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro
https://rust-lang.github.io/rust-clippy/master/index.html#needless_arbitrary_self_type
https://rust-lang.github.io/rust-clippy/master/index.html#stable_sort_primitive

Cleanups based on clippy suggestions

---

src/api/config/mod.rs

I forgot to include this change with my last PR to the encoder config validation.

Fix width/height limits in configuration errors

---

src/api/lookahead.rs

Simplify compute_motion_vectors

---

.github/workflows/js_api.yml

This PR pins up the `Rust` version used by the `js_api` CI to 1.46

CI: Pin js_api Rust version to 1.46

---

.github/workflows/deploy.yml

This PR avoids deploying automatically the binaries on forks.

CI: Avoid deploying automatically binaries on forks

---

src/fuzzing.rs

Document the fields that are not yet fuzzed for `encode`. Increase the value ranges for `sample_aspect_ratio`, `enable_timing_info`, `switch_frame_interval` and others.
For `encode_decode`, increase the value range for `switch_frame_interval` where `low_latency` is enabled.

fuzz: Increase coverage of encode and encode_decode

---

src/transform/inverse.rs

The zeroing of this buffer was a hotspot within the native implementation of inverse_transform_add. Changed it to only zero a buffer equivalent to the size that will be used. This is significantly more efficient for smaller-than-64x64 transforms and equivalent for 64x64.
This results in an overall 2% encoding time improvement on HBD content at speed 5.
```
> hyperfine -w 1 "~/Downloads/rav1e-master -s 5 --quantizer 42 -o /dev/null ~/data/objective-1-fast-10bit/blue_sky_360p_60f.y4m --limit 10" "~/Downloads/rav1e-try1 -s 5 --quantizer 42 -o /dev/null ~/data/objective-1-fast-10bit/blue_sky_360p_60f.y4m --limit 10"
Benchmark #1: ~/Downloads/rav1e-master -s 5 --quantizer 42 -o /dev/null ~/data/objective-1-fast-10bit/blue_sky_360p_60f.y4m --limit 10
Time (mean ± σ):     15.188 s ±  0.079 s …
```

Optimize the buffer size in inverse_transform_add

---

src/api/context.rs
src/api/internal.rs

The limit was overridden at the wrong place. The `simple_encoding` example hangs trying to queue up more than one frame if `still_picture` is set in the encoder configuration.
This returns `Err(EncoderStatus::EnoughData)` when one frame has already been processed in still picture mode, which allows `simple_encoding` to run through completely, while any frame beyond the first one is simply ignored.

Fix still picture frame limiting in the API

---

src/api/internal.rs
src/api/test.rs
src/rate.rs

When specifying e.g. `--bitrate 10000 --min-quantizer 100`, the min-quantizer setting did not appear to take effect. For example, on a test clip of BBB 720p first 500 frames, the average QPs were 20 and 68 for I and P frames respectively. After this PR, the QPs are flat as would be expected of a `--quantizer 100` encode (since bitrate 10000 would, in this case, always want a lower quantizer).

Ensure that min and max quantizer are respected

---

src/api/config/mod.rs

Resolve #2518 
~~Note that this change violates the constraint of AV1 spec:
"FrameWidth is greater than or equal to 16"
"FrameHeight is greater than or equal to 16"
in https://aomediacodec.github.io/av1-spec/#levels~~

Change the minimum frame size from 16x16 to 1x1

---

.github/workflows/deploy.yml
.github/workflows/js_api.yml
.github/workflows/rav1e.yml

As of last week, GitHub's add-path command has been deprecated.

Use env var $GITHUB_PATH instead of add-path

---

Cargo.toml

Provides minor build time improvements on all platforms.
Provides minor runtime improvements on x86_64.
Provides significant runtime improvements (~13%) on ARM.

Enable Thin LTO

---

src/encoder.rs

This initialization was a hotspot detected in profiling.
This change avoids initializing the unused parts of the array,
and avoids re-initializing the used parts since they will be set
anyway via the call to `diff`.
Provides approximately 3% speedup on 8-bit and 1% speedup on 10-bit.

Optimize initialization of residual array

---

src/encoder.rs

This prevents the value from the previous frame cloned at the beginning of new_inter_frame() from being used if none of the existing checks succeeds.

always set frame_size_override_flag when creating new inter frames

---

Cargo.toml
src/api/internal.rs
src/lib.rs
src/scenechange/mod.rs

The intent is to stop av-scenechange from having
to duplicate all of the internals of rav1e's
scenechange detection.
This makes all necessary items public and interoperable
with av-scenechange, so that av-scenechange can pull in
rav1e as a dependency and always be up to date
with its scenechange detection.

Make the scenechange detector publicly usable

---

src/encoder.rs
src/header.rs

For non show_existing_frame frames, and seeing rav1e currently doens't offer
the option to write more than one Tile Group per frame, it's more
efficient to use Frame OBUs instead of a pair of Frame Header and Tile Group
OBUs.
This saves a few bytes per frame by removing the overhead from the superfluous
OBU header.

Write Frame OBUs instead of a pair of Frame Header and Tile Group OBUs

---

src/bin/common.rs

Hello! This is my first PR here and thought this would be a good issue.
Fixes #2555
Ran cargo fmt && cargo clippy && cargo test
Edits and feedback are welcome.
Thanks

Add warning if chromaticity coords are out of range

---

src/arm/64/sad.S

Reduces execution time for this function by between 18% and 40%.
The most commonly used block size, 16x16, is improved by 29%.
<details>
```
get_sad/(BLOCK_16X8, 8) time:   [10.095 ns 10.104 ns 10.111 ns]                                     
change: [-25.513% -25.484% -25.457%] (p = 0.00 < 0.05)
Found 25 outliers among 100 measurements (25.00%)
7 (7.00%) low severe
1 (1.00%) low mild
5 (5.00%) high mild
12 (12.00%) high severe
get_sad/(BLOCK_16X16, 8)                                                                             
time:   [15.758 ns 15.769 ns 15.780 ns]
change: [-30.763% -30.703% -30.644%] (p = 0.00 < 0.05)
get_sad/(BLOCK_16X32, 8)                                                                             
time:   [26.581 …
```

Optimise NEON assembly for get_sad for width 16

---

.github/workflows/rav1e.yml
.travis/install-dav1d.sh

A new dav1d release is out, let's pull it into CI before the current release is dropped.

CI: Update libdav1d to 0.8.0-dmo1

---

src/arm/64/sad.S

Reduces execution time for these functions by between 35% and 42%.
Binary size of the SAD module is reduced by 23%, to less than 1kB.
Reorder widths 4 and 8 for consistency with other widths.

Optimise NEON assembly for get_sad for widths 32, 64 and 128

---

src/api/lookahead.rs
src/bin/muxer/ivf.rs
src/bin/stats.rs
src/lib.rs
src/scenechange/mod.rs

Intra cost and inter cost estimation account for 99%
of the time spent in keyframe detection (except at speed 10).
These two computations can be run in parallel,
thus providing a 30-40% speedup on keyframe detection
and a 1-3% speedup overall (depends on speed level, etc).

Run keyframe cost estimations in parallel

---

.github/workflows/rav1e.yml

Adds cargo build and cargo-c build jobs to the macOS build matrix for the aarch64-apple-darwin target (for Apple Silicon / M1).
On the release of Rust 1.49 all toolchains can be switched back to stable (and it can be removed from the build matrix).

CI: Add aarch64-apple-darwin jobs to GitHub Actions

---

Cargo.toml
src/activity.rs
src/api/internal.rs
src/api/lookahead.rs
src/bin/muxer/ivf.rs
src/bin/stats.rs
src/cdef.rs
src/deblock.rs
src/encoder.rs
src/lib.rs
src/lrf.rs
src/me.rs
src/scenechange/mod.rs

Hawktracer already has a feature, "profiling_enabled",
which controls whether it performs profiling or performs a no-op.
With the feature disabled, it performs the equivalent of our
noop_proc_macro. Therefore, we can remove our extra layer of
boilerplate.

Simplify Hawktracer boilerplate

---

src/asm/x86/lrf.rs

The sgrproj_box_ab_r1_avx2() and sgrproj_box_ab_r2_avx2() functions call
sgrproj_box_ab_8_avx2() which only implements the 8bpc path.

Only use 8-bit AVX2 assembly when bdm8 equals 0.

---

src/x86/me.asm

Accumulate SAD in 32 bits as 16 * 16 * 1023 = 261888 exceeds a 16-bit value.

Fix 16-bit overflow in rav1e_sad_16x16_hbd_ssse3.

---

src/x86/mc16_avx2.asm
src/x86/me.asm

These errors would have been found if we had regression tests on MacOS
and a similar register clobber checker to the one in dav1d.

Fix assembly issues not found in our CI.

---

Cargo.toml
v_frame/Cargo.toml

It is needed by the stand-alone rav1e.js

Prepare to release v_frame

---

.github/workflows/rav1e.yml

Now that `Rust 1.49` has been released, the stable version can be used instead of beta for `arm` jobs on `macos`

CI: Use stable version for arm jobs on macos

---

.github/workflows/deploy.yml

The deploy action should run only on the `xiph` organization regardless
of the events.

CI: Remove a useless condition

---

.github/workflows/rav1e.yml
.travis/install-dav1d.sh

This includes `.travis/install-dav1d.sh`.

CI: Update libdav1d to 0.8.1-dmo1

---

src/api/config/speedsettings.rs

Correcting a comment in the speedsettings documentation about speed 10 using minimum block sizes of 64x64, which was changed to a minimum and maximum block size of 32x32 in this commit:
https://github.com/xiph/rav1e/commit/8d3affb

Fix documentation speed 10

---

src/header.rs
src/test_encode_decode/mod.rs

Zero bits were incorrectly chosen to encode a dimension of 1; enforce a minimum of 1 bit per dimension.
Dimensions smaller than 16 are only admitted for still_picture. Add encode-decode tests for these tiny images.

Fix crash on width or height of 1

---

.github/workflows/deploy.yml
.github/workflows/rav1e.yml

- Removes empty lines and reformat single-line `run:` commands
- Simplify Nasm installation by using [ilammy/setup-nasm](https://github.com/ilammy/setup-nasm) also on Ubuntu
- Update Cargo C to 0.7.1 (also for the regular CI workflow)
I tested the updated deploy config on [this release](https://github.com/EwoutH/rav1e/releases/tag/p20210124-test2).

Deploy CI: Reformat, simplify Nasm installation, Cargo C 0.7.1

---

.github/workflows/rav1e.yml

Resolves a failure after upgrading to Ubuntu 20.04.

CI: Upgrade grcov to 0.7.1

---

src/api/color.rs
src/api/config/mod.rs
src/header.rs

Fixes #2586. Full pixel range and 4:4:4 subsampling are implied by:
CP_BT_709, TC_SRGB, MC_IDENTITY
<https://aomediacodec.github.io/av1-spec/#color-config-syntax>

Reject mismatched color configurations

---

.github/workflows/deploy.yml
.github/workflows/rav1e.yml

This PR ports all the CI changes from #2650, #2651 and #2655 over to the 0.4 maintenance branch.
**Main CI**
- Run the CI also on pushes and pull request to the 0.x maintenance branches (0.3, 0.4 etc.)
- Update Cargo C to 0.7.1
- Update grcov to 0.7.1
**Deploy CI**
- Removes empty lines and reformat single-line run: commands
- Simplify Nasm installation by using ilammy/setup-nasm also on Ubuntu
- Update Cargo C to 0.7.1 (also for the regular CI workflow)

[0.4] Sync CI: Run on pushes and PRs, simplify deploy, update Cargo C and grcov

---

src/context/block_unit.rs
src/context/mod.rs

After this change, all calls to `Writer::symbol_with_update()` are mediated by `macro_rules! symbol_with_update`. This completes the `desync_finder`  feature's coverage of CDF updates.

Add missing macro calls for symbol_with_update

---

src/context/cdf_context.rs
src/ec.rs
src/encoder.rs

Detailed performance analysis to be added shortly. The essence is that large `memmove` is replaced by smaller copies:
```
5.69%     -3.32%  libc-2.32.so        [.] __memmove_avx_unaligned_erms
3.16%     +1.63%  rav1e               [.] <rav1e::ec::WriterBase<S> as rav1e::ec::Writer>::symbol_with_update
```

Add a log struct for CDFContext rollback

---

src/asm/x86/ec.rs
src/context/block_unit.rs
src/context/cdf_context.rs
src/context/frame_header.rs
src/context/partition_unit.rs
src/context/transform_unit.rs
src/ec.rs
src/entropymode.rs
src/token_cdfs.rs
src/util/cdf.rs

A similar approach is used in dav1d and this enables some improvements to the CDF log.

Shrink CDFs by merging counter to final symbol position

---

src/context/block_unit.rs
src/context/cdf_context.rs

The vast majority of writes are to small CDFs, so we may partition the log to reduce redundant storage. Ordering the CDFs by size ensures that however we split rollback write sizes, the writes will not overlap between regions.

Partition CDF log by size

---

build.rs
src/x86/looprestoration16_avx2.asm

```
Relative speed-ups over C code (compared with gcc-9.3.0):
C      AVX2
wiener_5tap_10bpc:                  194892.0   14831.9    13.14x
wiener_5tap_12bpc:                  194295.4   14828.9    13.10x
wiener_7tap_10bpc:                  194391.7   19461.4     9.99x
wiener_7tap_12bpc:                  194136.1   19418.7    10.00x
```

x86: lr: Add AVX2 implementation of wiener filter for 16 bpc

---

build.rs
src/asm/x86/cdef.rs
src/x86/cdef.asm
src/x86/cdef16_avx2.asm
src/x86/cdef16_sse.asm
src/x86/cdef_sse.asm

```
Relative speed-ups over C code (compared with gcc-9.3.0):
C       ASM
cdef_dir_16bpc_avx2:                   534.2      72.5     7.36x
cdef_dir_16bpc_ssse3:                  534.2     104.8     5.10x
cdef_dir_16bpc_ssse3 (x86-32):         854.1     116.2     7.35x
```

x86: cdef: Add SIMD implementation of cdef_dir for 16bpc

---

Cargo.toml
src/api/internal.rs
src/api/test.rs
src/api/util.rs
src/capi.rs
src/frame/mod.rs

It makes the code a little tidy and paves the way to add `Sync` to the traits once https://github.com/rust-lang/rust/pull/80945 lands.

Add Opaque as shorthand for Box<dyn Any + Send>

---

src/context/block_unit.rs
src/context/cdf_context.rs
src/encoder.rs
src/rdo.rs

Saving and restoring over 4KiB at a time is excessive considering the vast majority of rollbacks change less than 10 bytes.
We may store only the data for the current superblock in the checkpoint. This further advances issue #2646.

Reduce size of BlockContextCheckpoint

---

src/quantize.rs

* Resolve a surprising compiler decision to invoke memmove.
* Calculate indices in a way that rustc may elide bounds checks.

Use explicit table lookup for ac_q and dc_q

---

src/context/cdf_context.rs
src/ec.rs

* Mostly avoid calling Vec::reserve() in CDFContextLogOps::push().
* Manually elide bounds checks in WriterBase::symbol() as they are not easily inferred by the compiler although statically known.
* Rewrite ec::rust::update_cdf() to be panic-free and hint to the compiler not to unroll beyond the maximum CDF length.

Tune flow of inline methods in symbol_with_update

---

src/api/internal.rs
src/lib.rs

Initial naive implementation, it nearly halves the `compute_block_importances` execution time according to hawktracer.
It is ~9% faster for 1080p at speed 6.

Parallel temporal rdo update

---

src/api/config/speedsettings.rs
src/bin/common.rs

Make speed settings faster with reasonable trade-off on different rdo-lookahead-frames values and suggest new defaults for each speed
* `rdo-lookahead-frames` 10 for speeds 10,9.
* `rdo-lookahead-frames` 20 for speeds 8,7,6.
* `rdo-lookahead-frames` 30 for speeds 5,4,3.
* `rdo-lookahead-frames` 40 for speeds 2,1,0.

per speed rdo-lookahead-frames

---

src/asm/x86/quantize.rs

The test was generating values one less than -i16::MAX.
Fixes #2276

Fix intermittent dequantize test failure

---

.github/workflows/rav1e.yml
.travis/install-dav1d.sh

This is early for once, the build is expected to break in 5 days when the current package is dropped from DMO.

CI: Update libdav1d to 0.8.2-dmo1

---

Cargo.toml
src/bin/common.rs

It improves the usability quite a bit.

Add colored help to the CLI

---

src/activity.rs
src/api/config/speedsettings.rs
src/api/internal.rs
src/context/superblock_unit.rs
src/encoder.rs
src/rdo.rs
src/segmentation.rs

This exposes the implicit scaling of `cdef_dist` and combines it with the explicit temporal scaling to produce a unified model for segment selection. Fixes #2141.

Unify spatial and temporal adaptive quantization

---

src/api/channel.rs
src/api/config/mod.rs

Use the current threadpool if no thread nor threadpool are specified

---

.github/workflows/rav1e.yml

Adds a Windows job targeting the Arm64 platform.
Moves Nasm installation to ilammy/setup-nasm and upgrades to Cargo-C v0.7.3.
I'm still working on the deploy CI (on [this branch](https://github.com/EwoutH/rav1e/tree/win-arm64-ci)), that will follow in a separate PR.
Part of #2652.

CI: Add Windows Arm64 job

---

src/api/channel.rs

It is a leftover from a refactor.

Remove a stray import

---

src/api/config/mod.rs
src/api/internal.rs
src/bin/rav1e-ch.rs
src/bin/rav1e.rs

Move all the info! lines in the context creation out, it makes a little simpler to rework the internals (see the by_gop poc PRs)

Move away the info logging

---

.github/workflows/rav1e.yml
src/lib.rs
src/predict.rs

This lint incorrectly matches with screaming snake-case.
In the few cases it correctly matches, readbility is not improved.
The clippy transcript is quite long, with 305 matches reported.
Also, narrowly allow collapsible `else if` in `pred_directional`.
This function already admits collapsible `if` for readability reasons.

Allow upper-case acronyms

---

.github/workflows/rav1e.yml
Cargo.toml
README.md
build.rs
src/api/internal.rs
src/context/block_unit.rs
src/encoder.rs
src/me.rs
src/rdo.rs
src/segmentation.rs
src/stats.rs

This is the const generics release of arrayvec. It seems to give about a 1.5% global encode speed improvement. However, it requires a minimum of Rust 1.51.
Before merging:

Bump arrayvec to 0.6

---

Cargo.toml

tl;dr they released arrayvec 0.6.1 making `new` a const fn, but that led to performance regressions so they reverted it, which was a breaking change.

Bump arrayvec to 0.7

---

.github/workflows/rav1e.yml

Updates the GitHub Actions to macOS 11.0 environment and add aarch64-apple-darwin target for cargo and cargo-C builds.

CI: Update to macOS environment, add Arm64 target

---

src/context/block_unit.rs
src/context/frame_header.rs
src/context/mod.rs
src/context/partition_unit.rs
src/context/transform_unit.rs
src/encoder.rs
src/rdo.rs

Profiling revealed that some very small Writer functions, such as `bit`, were not being inlined. These functions were sometimes used within loops and therefore the inability to inline resulted in inefficient code. This inability to inline was due to the writers being passed as dynamic objects at runtime. Using generics to monomorphise the functions at compile-time allows the writer functions to be inlined and produces more optimized code.
Testing shows that this produces an overall speed increase of 1-2% at all speed levels.

Use compile-time generics instead of dyn dispatch for writers

---

src/bin/common.rs

The reasoning for this change is that in short scenes without any significant scenes changes, the need for scene detection is null. Therefore, disabling scene detection has no visual or metric deficit, and gives a nice free speedup.
This is particularly useful in per GOP software where scene detection is done externally(like av1an or rav1e-by-gop soon), so this would result in essentially a free speedup.
Average speed difference for each speed preset tested(tested on own machine as AWCY has a large backlog, so numbers may not be indicative of a large dataset)
Speed 4 --- 5,5% speed increase
Speed 6 --- 16% speed increase
Speed 10 --- 9% speed increase

Adding no-scene-detection as a CLI argument

---

src/context/cdf_context.rs
src/ec.rs

After using compile-time generics instead of `dyn` dispatch for writers, the `#[always(inline)]` on `symbol_with_update` causes it to be inline for the long tail of larger CDF sizes. This results in larger binary size, for no speed benefit. Converting to const generics and removing inline preserves the specialization for smaller CDF sizes and reduces binary size by 40KiB on `x86_64`. The code is also more clear and concise.

Replace symbol_with_update macros by const generics

---

src/rdo.rs

Admits full unrolling and autovec for the following loop.
At speed 2, this yields a 9.6% increase in encoding speed.

Check available rows upfront in cdef_dist_wxh_8x8

---

.github/workflows/deploy.yml
.github/workflows/rav1e.yml

Update the CI config to use cargo-c [v0.8.0](https://github.com/lu-zero/cargo-c/releases/tag/v0.8.0).
Currently cargo-c updates automatically for the macOS runs by using Brew, but not on Linux and Windows. Maybe it would be useful to keep those versions in sync.

CI: Update to cargo-c v0.8.0

---

src/api/config/speedsettings.rs

The average encoding time increase is [approximately 5% on objective-1-fast](https://beta.arewecompressedyet.com/?job=cdf-dist-opt-s2%402021-04-22T23%3A32%3A03.840Z&job=cdf-dist-opt-s3-bottom-up%402021-04-23T20%3A18%3A55.832Z):
| -1.4287 |  0.2338 | -0.0450 |   -0.8039 | -1.3400 | -1.2139 |    -1.5199 |      0.2588 |     -0.0137 |  -1.4722 | -1.2587 |  -1.1720 |

Reconfigure speed level 2 to be level 3 with bottom-up partitioning

---

src/api/config/speedsettings.rs

Drop speed level 4 which requires [14.69% greater encoding time than speed 5](https://beta.arewecompressedyet.com/?job=cdf-dist-opt-s5%402021-04-28T07%3A57%3A17.637Z&job=cdf-dist-opt-s4%402021-04-28T07%3A57%3A01.338Z) for very marginal gains:
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |   ---: |    ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 0.0187 | -0.1219 | -0.2468 |   -0.0744 | 0.0048 | -0.0100 |     0.0146 |     -0.0276 |     -0.1719 |   0.0107 | 0.0978 |   0.0966 |
Insert a new speed level with [twice the encoding time of the prior speed 1](https://beta.arewecompressedyet.com/?job=cdf-dist-opt-s1%402021-04-26T12%3A19% …

Create new speed level 1, drop level 4

---

src/capi.rs

The configuration is validated already on encoder instantiation.
Fixes #2730

Remove the dimension validation when setting it in the C API

---

.github/workflows/deploy.yml

For beta-testing purposes, build and deploy a rav1e-ch binary for Windows that targets AVX2.

CI: Add rav1e-ch.exe binary to pre-release deployment

---

src/api/internal.rs
src/header.rs

These will be enabled by default in a future stable Rust,
so fixing them now keeps us ahead of the ball.
Relevant lints:
- used `assert_eq!` with a literal bool
- all if blocks contain the same code at the end
- called `is_none()` after searching an `Iterator` with `find`

Fix clippy warnings from Rust nightly

---

src/api/internal.rs
src/capi.rs
src/encoder.rs

This change requires a bit of explanation, because the way Arc::make_mut works is slightly complicated.
First, I found that there are a couple of places in the code where we **want** to clone the rec data so we can keep a copy of it prior to changes being made. This was working coincidentally, because we were cloning the Arc containing it (meaning, the inner data was not cloned, we only made a new reference to it), but a later call to Arc::make_mut caused the original data to be cloned and preserved. I changed the locations where we want to clone the data into explicit clones of the inner data, and changed the `make_mut` calls to `get_mut` to verify that this is the case (get_mut ensures that there is only one reference to an Arc and fails if that is not the case).
I was then …

Resolve an unnecessary clone of rec data

---

src/asm/x86/cdef.rs

The current workaround to use 16-bit intermediates also means that
we do not need to fall back to the Rust implementation on edges.

Use the x86 8-bit CDEF assembly on edges

---

src/encoder.rs

The input stride for forward transforms did not match the output stride of residual computation in this case. Extend the residual stride to the transform width and zero the non-visible portion.
Fixes #2662. Fixes #2757.

Initialise residual when less than the transform width is visible

---

src/asm/x86/predict.rs

Found by a failure of `asm::shared::predict::test::pred_matches_u8` when running:
```
RAV1E_CPU_TARGET=rust cargo test --release --lib
```

Fix fall-through of x86 dispatch_predict_intra for CpuFeatureLevel::RUST

---

fuzz/Cargo.toml
fuzz/fuzz_targets/encode_decode_hbd.rs
src/asm/aarch64/cdef.rs
src/asm/aarch64/mc.rs
src/asm/aarch64/predict.rs
src/asm/x86/cdef.rs
src/asm/x86/mc.rs
src/asm/x86/predict.rs
src/fuzzing.rs

Pass `check_asm` feature through to rav1e from fuzz crate. Disable HBD asm without 8-bit support for 8-in-16 on x86_64 and aarch64. Add a new fuzz target, `encode_decode_hbd`.

Disable HBD asm without 8-bit support for 8-in-16 and enhance fuzzing

---

src/api/channel/by_gop.rs
src/api/internal.rs
src/scenechange/mod.rs

Current fast scene detection in rav1e relatively slow to compared methods of scene detection, and have proclivity to show false results or don't detect scene changes where they appear
This pr reworks fast scene detection algorithm, making it faster, better, and more accurate
Achieved goals are:
* Faster decision making ( Both less and more efficient computations )
* More accurate scene detection, by adjusting threshold based on previous frames
* Frame downscale for faster decisions.
```
?  [SC-Detect] Frame 519: T=25.0 P=9.5 No cut
?  [SC-Detect] Frame 520: T=25.0 P=10.2 No cut
?  [SC-Detect] Frame 521: T=25.0 P=17.2 No cut
?  [SC-Detect] P: 29.0 [0.0, 1.8, 9.5, 10.2, 17.2] Cut: false
?  [SC-Detect] Frame 522: T=25.0 P=29.0 No cut
?  [SC-Detect] P: 33.6 [1.8, 9.5, 10.2, 17.2, 29.0] Cut: …
```

Improved scene detection

---

Cargo.toml
README.md
build.rs

They tend to confuse the debugger and are overall unnecessary.

Strip the local symbols from the nasm objects

---

.github/workflows/rav1e.yml

Note that Travis scripts are not maintained as they are inactive.
If we decide to bring back Travis integration, we should upgrade the base image first.

CI: Update to libaom to 3.1.2-dmo1

---

src/api/channel/by_gop.rs
src/api/channel/mod.rs
src/api/test.rs
src/asm/x86/quantize.rs
src/scenechange/mod.rs
src/tiling/tiler.rs

Replace deprecated use of std::{number} and min/max_value

Replace some deprecated call

---

src/scenechange/mod.rs

This function never gets called if distance < min_keyint, so these two branches are unnecessary. (If distance == min_keyint, then the math works out so that the result equals THRESH_MIN.)

Remove dead branches in scenecut code

---

src/scenechange/mod.rs

It is redundant with THRESN_MAX and THRESH_MIN.

Remove scale factor parameter for medium scenecut detection.

---

src/bin/rav1e.rs

The second print came from the stdlib's Result return from main(),
so manually return via std::process::exit.

Don't print the Error twice in the CLI.

---

build.rs

It will be used to experiment with the aarch64 and wasm SIMD intrinsics mainly.

Add a configuration attribute to use nightly features

---

src/scenechange/mod.rs

This removes an unused clone and removal of an element since it appears to be completely unused afterwards.

Remove unused clone of `score_deque` in `adaptive_scenecut`

---

Cargo.toml
src/api/lookahead.rs

It was extremely slow, especially at higher max values.
We can just calculate the mean directly by summing and division.
This version makes the slow scenechange only 15% slower than medium. (Approximately a 4x speedup compared to before.)
As part of a speed 6 encode, the difference in full encode time is 1-2% between slow and medium scenecut.
There is a slight AWCY difference, likely due to differences in how the means are rounded.
I don't feel that this is significant enough to hold up this PR, although I am open to opinions.
https://beta.arewecompressedyet.com/?job=master-vimeo%402021-09-06T18%3A36%3A16.994Z&job=no-histogram-try3%402021-09-06T19%3A26%3A04.175Z

Remove the histogram crate

---

src/api/channel/data.rs
src/api/context.rs

The original code write the 'monochrome' bit with the value
seq.bit_depth == 1. I suspect this comes from misunderstanding what
monochrome means in AV1. In AV1, monochrome is what is usually known as
grayscale, rather than black and white. Therefore the correct check for
monochrome should be seq.chroma_sampling == ChromaSampling::Cs400.
Also change the comment "sample_position" to "chroma_sample_position"
because chroma_sample_position is the name of that field in the AV1
ISOBMFF specification.

Write the 'monochrome' bit correctly

---

src/scenechange/mod.rs

By getting a subslice of the plane before the actual calculation of the
delta, the compiler is able to utilize SIMD instructions, but can't for
some reason when doing `.take()`. When compiling with AVX2 enabled, this
results in about a 5x speedup for `delta_in_planes`.
Difference in generated assembly (simplified for example):
https://godbolt.org/z/oTKe7n5dr

Better autovectorization of `delta_in_planes` for faster fast scene detection

---

.github/workflows/rav1e.yml

Our Coveralls job appears to be broken,
as it is currently returning a 405 error upon upload.
This is causing all builds to fail.
This commit disables the Coveralls step temporarily
until the job can be fixed properly.

Disable Coveralls step in CI

---

src/scenechange/mod.rs

This removes unnecessary allocations and overhead.

Do not downscale if `self.scale_factor == 1`

---

src/ec.rs
src/rdo.rs

This fixes an underflow bug triggered when the counter is larger than the previous value. Fixes #2780.
[AWCY results at default preset](https://beta.arewecompressedyet.com/?job=master-0c066cbba2637ba0587a8685f7796be5e24a44a5&job=issue-2780%402021-09-28T05%3A17%3A20.528Z):
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |   ---: |    ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 0.0029 |  0.1181 |  0.0019 |    0.0017 | 0.0059 |  0.0158 |    -0.0040 |      0.1020 |      0.0126 |  -0.0006 | 0.0959 |   0.0822 |

Use reduced precision in PDF sort

---

src/api/config/speedsettings.rs
src/api/lookahead.rs
src/bin/common.rs
src/scenechange/mod.rs

This changeset introduces a significant number of changes to the way that scene detection works internally.
- All frames are now analyzed. Previously, frames that were within `min-keyint` frames from a keyframe were not analyzed at all. Analyzing these frames, even if we know they will not be set as keyframes, improves the accuracy of both the histogram-based cost adjustments as well as flash detection.
- There are several fixes to how flash detection works, as it contained a number of bugs in the previous iteration.
- The histogram-based cost adjustments were improved to give more accurate results, especially in high detail scenes with motion. The threshold bias was adjusted to account for this.
- The last few frames of the video are now ignored, similar to a scene flash. This removes …

Merge medium and slow scenechange methods into one method

---

build.rs

Currently, it will just say that NASM version too old if NASM doesn't exist in the system.
This PR checks if NASM exists before checking its version.

Explicitly check if NASM installed/reachable

---

src/asm/x86/mod.rs
src/asm/x86/sad_row.rs
src/lib.rs
src/sad_row.rs
src/scenechange/mod.rs

We can utilize the instruction psadbw on x86 to make `delta_in_planes`
faster for 8-bit input, which benefits fast scene detection. This change
makes `delta_in_planes` about 2x faster than the current implementation
for both SSE2 and AVX2.
Here are some measurements of the performance according to hawktracker, tested on a 240x240 resolution video on a Zen 1 Threadripper 1950x. 
Original Rust version (but compiled with `-C target-cpu=native` so it is autovectorized with AVX2):
New SSE2 version:
New AVX2 version:

x86: Add SSE2 and AVX2 SAD intrinsics for `delta_in_planes`

---

src/dist.rs
src/rdo.rs

Fix cropping at the bottom boundary for weighted SSE.
Fall back to weighted SSE only near the boundary for tune=Psychovisual, rather than for the whole block.
Also, apply spatial weights when falling back in this case.
Fixes #2817.
AWCY results [at default speed on subset1](https://beta.arewecompressedyet.com/?job=master-2021-10-01_055153-48149f18&job=issue-2817%402021-10-05T02%3A18%3A03.973Z):
| -0.1797 | -0.6004 | -0.5008 |   -0.2449 | -0.1481 | -0.1592 |    -0.1544 |     -0.4386 |     -0.4213 |  -0.1608 | -0.2098 | …

Fix distortion calculations overlapping boundaries

---

benches/plane.rs
v_frame/src/plane.rs

The compiler cannot assume that `.chunks` will always produce
slices with 2 elements, because the final chunk may only
contain one element. However, we can assume that if the source
bytewidth is 2 bytes, that there must be an even number of bytes
and every chunk will have 2 elements.
Therefore, we can safely remove the bounds checks in the HBD path.
This improves performance of the HBD version of this function by 30%.
Approximately 1% overall encode performance at speed 10.

Avoid bounds checks in copy_from_raw_u8 for HBD

---

.github/workflows/deploy.yml

If the apt index in the base image is outdated, fetching packages may fail with an HTTP 404 error.

CI: Run apt-get update before install

---

.github/workflows/rav1e.yml

Now that they are available, pulling these dependencies from the Debian archive should result in less CI configuration churn thanks to a longer retention policy.

CI: Move to Debian Unstable for aom and dav1d

---

.github/workflows/deploy.yml
.github/workflows/rav1e.yml

Prevents having to update it manually all the time

CI: Always use latest cargo-c and grcov versions

---

src/api/config/speedsettings.rs
src/mc.rs
src/me.rs

Implement uneven multi-hexagon (UMH) and insert it before full search.
On faster speed settings (>= 6), full search is disabled entirely and
UMH is the final search where full search was before.
Other changes:
* Rewrite motion searches using the tools added with UMH.
* Implement regular hexagon search which is currently called from UMH.
* Add comments in places that haven't been changed.
* Refactor to make the newly added code more understandable.
objective-1-fast results
```text
Measured Speedup (using awcy, so high variance)
Speed Preset         | -s 5 || -s 6 | -s 7 | -s 8 | -s 9 | -s 10
Runtime Decrease (%) | 0.27 || 2.31 | 3.53 | 3.57 | 2.98 | 6.77\
```
BD-rate. Values < 0 are good.
```text
Speed Preset | -s 5 || -s 6 | -s 7 | -s 8 | -s 9 | -s 10 …
```

Partially replace full search with UMH

---

src/activity.rs
src/rdo.rs

In cdef distortion, replace floating point sqrt and divide with a fixed
point approximation of reciprocal sqrt.
The rsqrt implementation was pulled from daala, then modified by
removing the householder iteration.
```
Benchmarks:
cdef_dist_wxh_8x8       time:   [93.549 ns 93.572 ns 93.597 ns]
change: [-6.9962% -6.7169% -6.5117%]
Encode time (AWCY): -0.37%
PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y |
0.0541 | -0.1335 | -0.0211 |    0.0290 | 0.0557 |  0.0050 |     0.0150 |
PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG
-0.1746 |     -0.0119 |   0.0122 | 0.0040 |  -0.0030
```
https://beta.arewecompressedyet.com/?job=master-runagain-136672c58e21803633df72dc8f62214dd2ad6b35%402021-10-31T02%3A07%3A13.188Z&job=polynomial_only_2%402021-10-31T01%3A50%3A49.561Z

Replace float sqrt+divide with fixed point rsqrt

---

.github/workflows/deploy.yml
.github/workflows/rav1e.yml

This works around SSL-related issues that `cargo-c` has from time to time. If `cargo fetch` fails, we have bigger problems.

CI: Run cargo-c in offline mode

---

src/cdef.rs
src/context/cdf_context.rs
src/deblock.rs

Currently these are causing CI to fail.

Fix stable clippy lints for Rust 1.57

---

src/bin/common.rs

rav1e-by-gop is deprecated, but this option is still useful for
speeding up other chunked encoding tools.

Update a help message to be more relevant

---

src/api/channel/by_gop.rs
src/api/channel/mod.rs
src/api/config/encoder.rs
src/api/config/mod.rs
src/api/config/speedsettings.rs
src/api/internal.rs
src/api/test.rs
src/bin/common.rs
src/capi.rs
src/fuzzing.rs
src/scenechange/mod.rs

The impetus for this change is that the documentation for speed
settings, being a manually-maintained comment, would easily become out
of date and was difficult to maintain. The primary change this
introduces is that, rather than having a separate function for each
speed setting to determine when to enable it, the `from_preset` function
now sets all settings per speed level, with the `default()` being speed
0, and overriding as the speed increases. The idea is that this will
make it much easier to see which features are enabled at which speed
levels.
This also consolidates a couple of fields which were redundant, namely:
- `no_scene_detection` and `fast_scene_detection` are now one setting
called `scene_detection_mode`
- `rdo_lookahead_frames` existed on EncoderConfig, but the function …

Refactor the SpeedSettings struct and impl

---

src/api/config/encoder.rs
src/api/config/mod.rs
src/api/config/speedsettings.rs
src/api/test.rs
src/bin/common.rs
src/encoder.rs
src/me.rs
src/rdo.rs

The number of speed settings has grown to be quite large, and upcoming
work will add more speed settings. To help maintain readability and
extensibility of this structure, this commit breaks the speed settings
into sub-structs of related settings.

Organize speed settings into sub-structs

---

src/transform/forward_shared.rs

On the latest Rust nightly, compilation produces a large number of
identical warnings within this macro, stating:
attribute `allow` with an empty list has no effect
This commit silences the warnings by adding an item (ironically, the lint
being triggered by the empty list) to the allow list.

Silence repetitive warning on Rust nightly

---

src/api/config/encoder.rs
src/api/config/speedsettings.rs
src/api/test.rs
src/encoder.rs
src/partition.rs

To allow for more fine-tuned balancing of our speed levels,
this commit changes the boolean non_square_partition speed feature
to a block size threshold, below which non-square partitions will be
disabled, and above which non-square partitions will be tested.
Many tests were done on a local, quiet AWCY instance, producing
the following results (negative is better):
| Setting        | Encoding Time | MSSSIM | VMAF  | CIEDE2000 |
|----------------|---------------|--------|-------|-----------|
| Speed 2 >8x8   | 62.54         | -3.64  | -3.30 | -4.66     |
| Speed 2 >16x16 | 30.11         | -1.95  | -1.89 | -2.65     |
| Speed 2 >32x32 | 6.70          | -0.67  | -0.40 | -0.90     |
| Speed 3 >8x8   | 92.20         | -3.63  | -3.55 | -4.80     |
| Speed 3 >16x16 | 48.64         | -1.88  | …

Change non_square_partition feature to a threshold

---

src/asm/x86/dist/sse.rs
src/context/partition_unit.rs
src/encoder.rs
src/partition.rs
src/rdo.rs

This should improve the codegen of `width_log2`, `height_log2`, `tx_size`, and `is_rect_tx_allowed` by removing checks of the invalid variant, and it also forces callers of `subsampled_size` and `subsize` to check that the return value was not an invalid block size. If there is any performance-critical code where it is not desirable to check for the invalid block size, then it is still possible to use `unsafe` to remove the check.

Refactor `BlockSize` to not have an invalid variant

---

src/rdo.rs

With 12 bit input, an overflow can occur when squaring the sum of pixel
values over an 8x8 region.
(8x8  x  (2^12-1))^2
= (2^6  x  (2^12-1))^2
= 2^12  x  (2^12-1)^2
= a 36-bit number

Fix overflow in cdef distortion

---

src/bin/rav1e-ch.rs
src/bin/rav1e.rs

A user on Discord reported that rav1e was reaching an unreachable
branch, which was in this section of the codebase. This commit
explicitly returns an error message for each potential type of y4m
error, instead of assuming that some are unreachable.

Display info for all y4m error types

---

benches/rdo.rs
build.rs
src/activity.rs
src/asm/x86/dist/cdef_dist.rs
src/asm/x86/dist/mod.rs
src/dist.rs
src/rdo.rs
src/x86/cdef_dist.asm

Around ~7% faster on speed 2. It should be roughly the same for most
speed levels.
It would have been more, but some recent patches seem to have allowed
autovecterization to happen again.

Add x86 assembly for cdef distortion

---

src/dist.rs

Using const generics allows the compiler to optimize the hadamard transforms significantly better: https://godbolt.org/z/YdWe7518h

Use const generics for hadamard transforms

---

Cargo.toml
src/asm/x86/transform/forward.rs
src/transform/mod.rs

- Switch to fixed-size arrays for avx2 transposes (more readable than copying tuples around), which brings in the arrayref crate, since it is safer than manually transmuting/casting
- Use `for_each` which for some reason allows autovectorization of `av1_round_shift_array` (https://godbolt.org/z/xMvv3bY6b)
- Slightly improve codegen of `round_shift_array_avx2` (https://godbolt.org/z/noYYbc7Gb) (also removed `size` parameter as it was never called with a different length then the length of the slice being passed)

Improve codegen of av1_round_shift_array

---

src/deblock.rs

`stride_sse` is only called on fixed size slices where the size is statically known. Using const generics guarantees that the compiler specializes the implementation for each array size, which allows much better optimization: https://godbolt.org/z/a7EKnEc7r

Use const generics for stride_sse

---

src/me.rs

The min sad was being scaled to the size of the block on the fullres
plane, when it should to be scaled to the size of the block on the
subres plane.
Speed 10:
https://beta.arewecompressedyet.com/?job=master-5da2a86bc98d9-s10%402022-01-07T23%3A58%3A02.424Z&job=fix_normalization_s10%402022-01-10T20%3A21%3A49.554Z
Speed 6:
https://beta.arewecompressedyet.com/?job=master-5da2a86bc98d9%402022-01-07T21%3A00%3A58.566Z&job=fix_normalization%402022-01-10T19%3A37%3A01.387Z
Speed 5:
https://beta.arewecompressedyet.com/?job=master-5da2a86bc98d9-s5%402022-01-08T14%3A19%3A23.189Z&job=fix_normalization_s5%402022-01-10T19%3A39%3A14.571Z
It's maybe a little bit slower. Hard to tell, since awcy is very
inconsistent right now.
| speed       | 10      | 6       | 5       | …

Fix scale of motion estimation threshold

---

.github/workflows/rav1e.yml
Cargo.toml
README.md
build.rs
ivf/Cargo.toml
v_frame/Cargo.toml

dav1d-sys has updated to edition 2021, forcing us to raise our minimum supported Rust version to 1.56. Since we are now raising the minimum version, it makes sense to update ourselves to edition 2021 at the same time.

Update to Edition 2021

---

src/asm/aarch64/mc.rs
src/asm/x86/mc.rs
src/mc.rs
v_frame/src/plane.rs

put, prep, and avg now check bounds and width/height before calling
assembly functions.

Add safety asserts for mc assembly callers

---

src/api/lookahead.rs
src/scenechange/mod.rs

As far as I could tell, 8x8 blocks are always used, so dynamically counting the number of pixels is not necessary.

Simplify importance block sum in `estimate_importance_block_difference`

---

src/me.rs
src/rdo.rs

The old code partitions to handle edges.
| -0.0015 |  0.0376 | -0.0965 |    0.0117 | -0.0389 | -0.0521 |    -0.0404 |     -0.1133 |     -0.0595 |  -0.0368 | -0.0292 |  -0.0377 |

Handle edges by cropping in initial motion estimation

---

src/api/lookahead.rs
src/encoder.rs
src/me.rs
src/scenechange/mod.rs

This reuses very expensive allocations of `FrameMEStats` instead of allocating for every time `estimate_inter_costs` is called.
Speed difference for `estimate_inter_costs` for 1080p yuv420p:
Before:
After:

Speed up estimate_inter_costs

---

src/api/lookahead.rs
src/encoder.rs

- Avoids downscaling and allocating hres and qres, since they are not used for inter cost estimation.
- Fixes optimization where allocation was supposed to be avoided, but was not completely eliminated because of padding.
Before this change (tested on yuv420p 1080p):
After this change:

Speed up estimate_inter_costs again

---

src/scenechange/mod.rs

It is not used for cost based scene detection, but it is still calculated for some reason.

Fix confusing scale factor

---

src/mc.rs
src/me.rs

After doubling the sample rate of motion estimation (e.g. quarter-res
to half-res), refine the search performed at the lower supsampling level
by searching a 3x3 region around the previous mv.
https://beta.arewecompressedyet.com/?job=crop_edge_init_me%402022-01-27T19%3A13%3A43.336Z&job=refine_me_ssdec2%402022-02-02T15%3A07%3A38.563Z
| -0.1379 | -0.3436 |  0.0475 |   -0.2930 | -0.1618 | -0.1902 |    -0.1447 |     -0.3812 |      0.0422 |  -0.1501 | -0.1780 |  -0.1903 |

Init Motion Est: Refine mvs when subsampleing reduced

---

src/api/internal.rs
src/scenechange/mod.rs

Since intra costs are computed completely independently of any
information outside the frame itself, these costs are guaranteed not to
change for a given input frame.

Cache and reuse intra costs from scenechange

---

.github/workflows/rav1e.yml
Cargo.toml
README.md
build.rs
src/asm/x86/sad_row.rs

There is no way to force the compiler to not auto-vectorize a loop without changing the global compilation flags. However, it is possible with inline assembly which was stabilized in Rust 1.59.0.
Before, the compiler aggressively vectorized a loop that was supposed to be scalar since it was only a residual loop of an already vectorized function. With this PR, the correct assembly code is generated: https://godbolt.org/z/e6KTfqnxG

Fix unnecessary auto-vectorization in residual loop of SAD intrinsics

---

src/api/test.rs

These tests were filtering out frames that may have been in between
other frames we wanted to check, leading to tests that don't fully check
what we expect them to check. To resolve this, the filtering has been
removed from the test verifications, and we now check all frames in the
set.
This also removes comments about the frame type for non-keyframes, as
these were not particularly useful and may have even been incorrect.

Fix pyramid and frame type tests

---

src/api/internal.rs
src/api/lookahead.rs
src/api/test.rs
src/capi.rs
src/encoder.rs
src/header.rs
src/rdo.rs

Thie commit changes invalid frame invariants to be represented by a
`None` value, and for SEFs to no longer contain any additional data that
is only needed by coded frames (at the moment, this is only lookahead
data).
This results in a ~3% overall reduction in memory usage, and a ~1%
improvement in encode runtime at speed 6 (with low-latency=false).

Improve storage of invalid and SEF frame invariants

---

src/asm/x86/sad_row.rs

Before, `sad_scalar` was called in multiple different places for `sad_8bpc_avx2` and `sad_8bpc_sse2`, thus causing the residual loop to be inlined more than once. This PR improves the SAD intrinsics so that the residual loop is only called once for each of these functions, which ultimately avoids slightly bloated generated assembly.
Comparison of generated assembly: https://godbolt.org/z/xKzqv8Yss

Avoid multiple inlining of residual loop in SAD intrinsics

---

clippy.toml
ivf/src/lib.rs
src/util/align.rs
v_frame/src/lib.rs
v_frame/src/pixel.rs
v_frame/src/plane.rs

Since these crates are within the rav1e workspace, and used heavily by
rav1e, it makes sense to apply the same additional lints.

Also apply custom clippy lints to ivf and v_frame

---

ivf/src/lib.rs
src/bin/rav1e-ch.rs
src/bin/rav1e.rs
src/encoder.rs
src/lib.rs
src/rdo.rs
v_frame/src/lib.rs

Uses single-operation mul_add for more accurate and performant
floating-point math.

Enable suboptimal_flops clippy lint

---

src/scenechange/mod.rs

The cached intra costs ended up using a non-trivial amount of memory, so
we need to ensure they are not kept around when they are not needed.
In the case of temporal RDO, these are already removed from the cache
when we move them into the FrameInvariants.

Fix memory leak when temporal RDO not in use

---

src/api/config/speedsettings.rs

Currently the speed gap for speeds 1-3 is very unbalanced.
Speed 2 is only 20% faster than speed 1, while speed 3 is 150% faster
than speed 2. After this change, speed 2 becomes 50% faster than speed
1, and speed 3 becomes 50% faster than speed 2. Impact on metrics at
speed 2 is very small: [AWCY](https://bit.ly/3q0sJrl)

Move complex pred modes for keyframes to s2

---

Cargo.toml
src/rate.rs

Caveat: it may be preferable to wait for const function assertions to be available natively.

rate: add assertion for q57 input range

---

Cargo.toml
src/bin/stats.rs

Due to the interface of av-metrics, we were cloning two uncompressed
frames of data for each encoded frame, even when not doing any metrics
calculation. The interface to av-metrics has been changed to support
passing a `&Frame`, allowing us to avoid the clones entirely.
This reduces the total allocation count by about 6%, and peak
memory usage and encoding time by 1% at all speeds.

Remove unnecessary clones from metrics calculation

---

src/lib.rs

This lint has too many false positives, and is becoming more annoying than useful.

Disable missing const fn clippy lint

---

Cargo.toml

Profiling becomes considerably more difficult to read when rayon is
involved, because rayon nests many layers of function calls which
obscure where CPU and memory usage is actually occurring. This uses the
maybe-rayon crate as a wrapper around rayon, which by default passes
through to rayon with zero overhead, but by disabling the "threading"
feature in rav1e, the maybe-rayon crate will become a mock which calls
functions serially.
Examples:
Memory flamegraph with rayon:
Memory flamegraph without rayon:

Add a mock around rayon for disabling threading

---

src/scenechange/standard.rs

Some change seems to have occurred which causes this specific hawktracer
annotation to fail to compile. For the time being, remove it so that
hawktracer support can compile again.

Remove a broken hawktracer annotation

---

src/bin/common.rs
src/bin/muxer/ivf.rs
src/bin/muxer/mod.rs

Treat input, output, first pass, second pass, and reconstruction IO paths as `OsString` to improve portability. This requires the corresponding arguments be allowed to be non-utf8. This is a first pass at the issue to support non-utf8 file systems (#2356).

Treat IO paths as native os strings.

---

Cargo.toml
src/asm/x86/sad_row.rs
src/asm/x86/transform/forward.rs
src/scenechange/fast.rs
src/scenechange/mod.rs
v_frame/Cargo.toml
v_frame/src/pixel.rs
v_frame/src/plane.rs

The main bottleneck of the fast scene detection mode is the internal downscaling which is performed. This PR changes the downscaling code to be specialized for each chosen scale factor (rather than one function which handles all scale factors), which in turn enables several optimizations in the compiler that are not possible for a general downscaling function. Overall, this PR's new downscaling is over 6x faster when compiling with AVX2 enabled, benchmarked on a 1280x720 yuv420p video.
Other changes:
- Remove rayon threading from `downscale_in_place`, as it seemed to prevent auto-vectorization by the compiler
- Allocate `frame_ref_buffer` and `downscaled_frame_buffer` on the stack instead of the heap
- Remove initialization checks with `unreachable_unchecked` (which originally existed …

Use const generics for downscaling

---

src/asm/aarch64/dist.rs

Silence unused variable warning. This only shows up on aarch64 builds.

Silence unused variable warning.

---

.github/actions-rs/grcov.yml
.github/workflows/rav1e.yml

This PR uses the new [source-based code coverage](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#source-based-code-coverage) to compute code coverage

Enable source base code coverage on CI

---

src/lrf.rs

This lifetime is unused in this impl. This is a fix for an upcoming clippy lint.

Remove unused lifetime.

---

build.rs
src/asm/x86/sad_row.rs
src/x86/sad_row.asm

This speeds up the sad_row functions mainly by avoiding a residual loop altogether, and avoiding mixing 128 bit and 256 bit vector instructions which causes slow downs on some CPUs. Instead of using a scalar residual loop to clean up the elements that don't fit into the SIMD register and unroll size, this code always uses vector instructions and just reads past the end of the array and masks out the irrelevant bytes (similar to glibc's AVX2 memchr implementation).
This also actually ends up de-duplicating some code between the SSE2 and AVX2 versions of the code, since a single macro is now used to generate both versions of the function.
Maybe in the future this function could just operate over 2 entire planes instead of just a row, this way there would be less looping overhead between …

Rewrite x86 SAD row intrinsics in ASM

---

src/x86/sad_row.asm

I didn't initially see this problem in #2940. I believe executing VEX-encoded instructions on processors that don't support them (e.g., if it only supports sse2) will cause SIGILL.

Remove explicit VEX coding from sad ASM

---

build.rs
src/asm/x86/mod.rs
src/asm/x86/sad_plane.rs
src/lib.rs
src/sad_plane.rs
src/scenechange/fast.rs
src/x86/sad_plane.asm

This should remove any overhead of Rust having to loop through each row and call the ASM implementation of sad_row, and instead allow a new sad_plane function to iterate over the rows by itself.

Reimplement sad_row as sad_plane

---

src/context/block_unit.rs
src/context/partition_unit.rs
src/dist.rs
src/predict.rs
src/quantize.rs
src/sad_plane.rs

This is an upcoming clippy lint. unsigned_abs() was added in Rust 1.51.0, meeting the current version requirement. This avoids a potential panic in debug mode. cargo test passed and sample bitstreams are identical.

Replace abs() as unsigned with dedicated alternative.

---

src/asm/x86/mc.rs
src/ext/x86/x86inc.asm
src/x86/cdef16_avx2.asm
src/x86/cdef16_sse.asm
src/x86/cdef_avx2.asm
src/x86/cdef_sse.asm
src/x86/ipred16_avx2.asm
src/x86/itx16_sse.asm
src/x86/itx_sse.asm
src/x86/looprestoration16_sse.asm
src/x86/looprestoration_sse.asm
src/x86/mc16_avx2.asm
src/x86/mc16_sse.asm
src/x86/mc_avx2.asm
src/x86/mc_avx512.asm
src/x86/mc_sse.asm

Comparing cherry-picked changes with the full log of `0.9.1..0.9.2`:
* Missing changes to `x86inc.asm` from previous integrations are included.
* The addition of film-grain and `splat_mv` assembly are excluded.
<details>
```diff
+Properly fix LOAD_MM_PERMUTATION for AVX-512
+x86inc: Add stack probing on Windows
+x86inc: Support memory operands in src1 in 3-operand instructions
x86/itx: 16x4 inverse transforms hbd/sse4
x86/itx: 16x8 inverse transforms hbd/sse4
x86/itx: 16x16 inverse transforms hbd/sse4
x86: Add minor improvements to sgr16 SSSE3 asm
x86: Rewrite sgr8 SSSE3 asm
x86/itx: document third argument in INV_TXFM_WxH_FN macros
x86/itx: replace .transpose8x8 with 2 calls to .transpose4x8packed
x86/itx: 32x{8,16,32} & {8,16}x32 idtx transforms hbd/sse4
x86/itx: merge pass=2 rounding …
```

Integrate new dav1d assembly (0.9.2) 

---

src/asm/x86/mc.rs

Function names for `avg` were accidentally swapped with `w_avg`.
There should only have been a suffix change. Fixes #2951.

fix-up: x86: Add bpc suffix to mc functions

---

src/me.rs
src/rdo.rs

They do very similar things but with slight tweaks, so it makes sense
for them to be one function instead of two to reduce code duplication
and remove naming confusion.
[AWCY](https://beta.arewecompressedyet.com/?job=master-295ad2e385366fe0f0a42957509275f43e941bf2&job=estimate-motion%402022-05-31T07%3A30%3A27.070Z) confirmed no change in output.

Merge estimate_motion and motion_estimation into one function

---

Cargo.toml
ivf/src/lib.rs
src/api/config/encoder.rs
src/api/config/speedsettings.rs
src/api/test.rs
src/bin/common.rs
src/bin/rav1e-ch.rs
src/bin/rav1e.rs
src/fuzzing.rs
src/lib.rs
src/test_encode_decode/mod.rs
v_frame/src/lib.rs

This is something that has been on the radar for a while, but the recent
deprecation of everything from Clap 3.1 in Clap 3.2 has pushed our hand
a bit to get it done now with the new best practices from Clap 3.2.

Rewrite argument parsing to use Clap's derives

---

src/api/channel/by_gop.rs
src/api/internal.rs
src/scenechange/mod.rs

The current use of taking ownership of the passed in `Arc<Frame<T>>` in the scenechange module becomes problematic when trying to pass in a struct wrapped in `ManuallyDrop`, as it attempts to run the destructor and you can't coerce a `ManuallyDrop<Arc<Frame<T>>>` into an `Arc<Frame<T>>` that doesn't run the destructor.

Avoid taking ownership of Arc<Frame<T>> in scenechange API

---

Cargo.toml

Workaround for #2960, because of rust-lang/rust#98302

Add a release-nolto profile

---

.github/workflows/deploy.yml

This PR fixes Windows `gnu` deployment enabling the new `release-no-lto` profile

Use release-no-lto profile for gnu deploy on Windows

---

src/partition.rs

This should slightly reduce the overhead of calling ASM functions, since many of them are dispatched via block size and thus `BlockSize::from_width_and_height_opt` is called.
Comparison of generated assembly: https://godbolt.org/z/ja5c4zr6K

Optimize `BlockSize::from_width_and_height_opt`

---

.github/workflows/rav1e.yml

This PR improves Windows toolchains:
- Remove bugged aarch64 target not to waste CI time
- Remove linker options because they are now default in GitHub Actions
Closes #2721

CI: Improve Windows toolchains

---

src/api/config/encoder.rs
src/api/internal.rs
src/api/test.rs
src/bin/common.rs
src/context/partition_unit.rs
src/encoder.rs
src/fuzzing.rs
src/segmentation.rs

This changeset, in lieu of reusing variance calculations to do spatial AQ, factors in the fact that the spatiotemporal scales we have _already consider_ both spatial and temporal importance. Therefore, this changeset uses the existing metric and uses an assessment of the distribution of that metric within a frame to determine how many segments to use and what the deltaq offset should be for each of them, rather than using a constant set of +21/-21/0.
The segment splitting code in this changeset is originally from @cyanreg in #2247.
As an immediate followup to this pull request, I still plan to add luma-based AQ bias to provide more bits to dark areas and adapt AQ for HDR clips. Ideas for future improvements are also very welcome. …

Compute segmentation offsets dynamically

---

src/api/config/encoder.rs
src/api/config/mod.rs
src/api/test.rs
src/bin/common.rs
src/encoder.rs
src/fuzzing.rs
src/header.rs
src/lib.rs
src/test_encode_decode/mod.rs

The grain table spec does not require denoising, and is consistent across all three major AV1 encoders. I believe it makes sense to stabilize this while the grain synth denoising is being worked out. This also keeps the old name `--photon-noise-table` for compatibility, but since grain tables are not specific to photon noise, the canonical name is changed to `--film-grain-table`.
Using a grain table already requires being a somewhat advanced user, given that it requires an external tool to generate one (or writing one by hand), so there is less risk of beginners accidentally stumbling upon it and having it not do what they expect.

Stabilize the --film-grain-table parameter

---

.github/workflows/rav1e.yml

This PR does not consider `crates` directory for code coverage computation

CI: Do not consider crates directory for code coverage

---

.github/workflows/rav1e.yml
README.md

This PR switches the CI to [codecov](https://about.codecov.io/) because it seems to offer more info about code coverage than `coveralls`

CI: Switch to codecov

---

src/api/context.rs
src/api/internal.rs
src/api/lookahead.rs
src/api/test.rs
src/api/util.rs
src/capi.rs
src/encoder.rs
src/frame/mod.rs
src/header.rs
tests/doctests.rs

This currently only adds a Rust API. Note that this is a breaking
change as it extends the publicly visible "params" struct.
The T.35 metadata support in AV1 is very flexible - this is
intended in particular for T.35 metadata attached to frames,
in the style of the AV1 HDR10+ metadata specification:
https://aomediacodec.github.io/av1-hdr10plus/

Add T.35 metadata support.

---

src/activity.rs

There are two target properties:
* When `svar == dvar`, `ssim_boost ~= k / cbrt(svar)`
* The constant `k` is chosen such that `mean(log(ssim_boost)) ~= 0`
The value of `k` derived from subset3 was very near `cbrt(2)`.
AWCY results for [objective-1-fast at default speed](https://beta.arewecompressedyet.com/?job=master-cd256770a3b718d595f3112a4f217ac3af0b50d1&job=ssim-boost-icbrt-2%402022-08-05T15%3A01%3A26.384Z):
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |    SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |    VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |    ---: |    ---: |       ---: |        ---: |        ---: |     ---: |    ---: |     ---: |
| 0.0814 |  1.3359 |  1.4880 |    0.3151 | -0.6091 | -0.6798 |    -0.1721 |      1.2087 |      1.4406 | …

Retune constants for ssim_boost

---

build.rs
src/arm/64/satd.S
src/asm/aarch64/dist.rs
src/dist.rs

This PR only adds assembly for block sizes that use a 4x4 transform for now.

Add aarch64 NEON 8-bit SATD assembly for 4x4-transformed block sizes

---

src/encoder.rs

`must_split` is always false in this branch, because if it was true, the previous branch would have been taken.

Remove always-true if statement in encode_partition_topdown()

---

src/arm/64/satd.S

gcc doesn't support arrangement specifiers after the instruction mnemonic like clang does, so they instead need to be specified after each register.

Fix aarch64 satd compilation on gcc

---

src/api/internal.rs
src/api/test.rs
src/encoder.rs
src/rate.rs
src/rdo.rs

This should enhance the effectiveness of dynamic segmentation by normalizing the scales.
AWCY results for [objective-fast-1 at default speed](https://beta.arewecompressedyet.com/?job=master-0bee40b875b694fe5cb85d65a309dbdd9edaa423&job=rate-control-frame-mean-rebased%402022-08-09T17%3A02%3A49.994Z)
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |    SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |    ---: |    ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 2.1192 |  0.0424 | -0.4626 |    0.2634 | -1.9722 | -1.9259 |     0.6551 |     -1.4601 |     -1.9457 |   0.6588 | 1.2593 |   1.3857 |

Use frame-relative spatiotemporal scores

---

src/encoder.rs
src/segmentation.rs

It is possible for inter frames to have lower base_q_idx than intra when temporal complexity is low, due to rate control.
Find and restrict to the maximum valid segment. Fixes #2985.

segmentation: Limit minimum segment to avoid lossless mode

---

src/encoder.rs
src/segmentation.rs

This feature was inadvertently removed when `select_segment()` was
rewritten in #2933.
AWCY results on [obective-1-fast at speed level 0](https://beta.arewecompressedyet.com/?job=issue-2985-s0%402022-08-12T22%3A43%3A41.354Z&job=segmentation-level-full-s0%402022-08-13T00%3A38%3A05.050Z):
| -4.9622 |  0.0513 | -0.5654 |   -2.1766 | -1.2898 | -1.0981 |    -4.0175 |      2.4461 |      1.4434 |  -3.8521 | -4.8615 |  -4.7457 |
Encoding time relative to `SegmentationLevel::Simple` was 262%.

Implement `SegmentationLevel::Full` again

---

Cargo.toml
src/stats.rs

According to #2236, this was converted to an ArrayVec since at that time Rust did not support deriving `Debug` for fixed-sized arrays above 32 elements, but this is no longer the case and thus ArrayVec is not needed.

Use fixed-sized array in luma/chroma pred mode counts

---

benches/dist.rs
src/asm/x86/dist/sse.rs
src/encoder.rs
src/rdo.rs
src/segmentation.rs

AWCY results for [objective-1-fast at default speed](https://beta.arewecompressedyet.com/?job=master-3c05349095b4cdf1887c03f615c904799abe7ea3&job=segment-map%402022-08-19T06%3A01%3A31.082Z):
|  PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |    VMAF | VMAF-NEG |
|    ---: |    ---: |    ---: |      ---: |   ---: |    ---: |       ---: |        ---: |        ---: |     ---: |    ---: |     ---: |
| -1.0439 | -1.2423 | -1.2902 |   -0.3670 | 0.9061 |  0.8534 |    -0.4362 |     -0.9269 |     -1.0861 |  -0.4454 | -0.6953 |  -0.7345 |
Includes reworking of `DistortionScale` construction so that constants may be defined from rational numbers.

Compute segmentation map thresholds from the offsets

---

src/rate.rs

This removes a long-standing implicit boost of chroma quality for `tune=Psychovisual`. Which looks a lot like stealing chroma bits to boost luma, so it is instructive to compare against a baseline of `tune=Psnr`.
[master-537b1b91-psnr -> master-537b1b91-psy](https://beta.arewecompressedyet.com/?job=master-537b1b91-psnr%402022-08-17T13%3A24%3A15.386Z&job=master-537b1b91b861210062b1cf105a5bd0243bab0b90):
| PSNR Y |  PSNR Cb |  PSNR Cr | CIEDE2000 |     SSIM |  MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |     ---: |     ---: |      ---: |     ---: |     ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 4.0327 | -13.3105 | -13.5377 |   -7.3436 | -11.4949 | -12.0294 |    -0.6906 |    -16.1168 |    -16.4373 | …

Adjust chroma offsets for frame-mean spatiotemporal scale

---

src/segmentation.rs
src/util/kmeans.rs
src/util/mod.rs

Runs k-means on logarithms of distortion scale, with k chosen by variance in spacing of the result.
Now with more comments and AWCY results.

Derive quantizer index offsets for segments from distortion scales

---

src/api/internal.rs
src/encoder.rs

Without this, encoding with `--tune Psnr` crashes:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/davidbarr/Archive/exp/rav1e/src/util/kmeans.rs:23:42
stack backtrace:
```
<details>
```
0: rust_begin_unwind
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
2: core::panicking::panic
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
3: rav1e::util::kmeans::kmeans::{{closure}}
at ./src/util/kmeans.rs:23:42
4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:30 …
```

Add missing code for segmentation with --tune Psnr

---

src/rdo.rs
src/segmentation.rs

This is aligned to IEEE 754 `binary32` precision and avoids possible saturation of `i32` from extreme values of `DistortionScale`.
Also, restore internal documentation from the draft of #2993.

segmentation: Change precision of `log(scale)` to Q23

---

src/rdo.rs
src/segmentation.rs
src/util/logexp.rs

Adapted from `oc_blog32_q10()` in libtheora with blessing from @tterribe.
AWCY results on [ojective-1-fast at default speed](https://beta.arewecompressedyet.com/?job=master-c113c00353e605612a41c8dbca124aca3ce2a5dc&job=segment-opt%402022-08-29T16%3A32%3A54.536Z):
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |    SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |    ---: |    ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 0.4305 |  0.3834 | -0.2535 |    0.1353 | -0.2666 | -0.2792 |     0.3404 |      0.4239 |     -0.1232 |   0.4060 | 0.1488 |   0.1788 |

Replace binary log in `segmentation_optimize` with a polynomial approximation in Q11

---

src/activity.rs
src/deblock.rs
src/ec.rs
src/encoder.rs
src/me.rs
src/rdo.rs
src/transform/inverse.rs
src/transform/mod.rs

Fixes instances of lints for:
- `unstable_name_collisions` (due to addition of unstable `ilog` method)
- `clippy::partialeq_to_none`
- `clippy::needless_borrow`

Fix new lints from Rust nightly

---

src/util/logexp.rs

Lost in translation, an off-by-one occurred.
AWCY results for [objective-1-fast at default speed](https://beta.arewecompressedyet.com/?job=master-fe7d0f0eb0ecaa9b863a7ce5c49c0ead611f7d96&job=segment-opt%402022-09-02T06%3A32%3A25.834Z):
|  PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |    VMAF | VMAF-NEG |
|    ---: |    ---: |    ---: |      ---: |   ---: |    ---: |       ---: |        ---: |        ---: |     ---: |    ---: |     ---: |
| -0.4350 | -0.2492 |  0.2750 |   -0.1279 | 0.2865 |  0.3318 |    -0.3281 |     -0.3041 |      0.1465 |  -0.3910 | -0.2546 |  -0.2703 |
Compared to the commit [before `blog32_q11` was first used](https://beta.arewecompressedyet.com/?job=master-c113c00353e605612a41c8dbca124aca3ce2a5dc&job=seg …

logexp: Correct integer part in `blog32_q11`

---

src/entropymode.rs

These are defined as `pub const` in another module,
which is already used in this module, so it makes sense
to remove the duplication.

Remove duplicated constants

---

Cargo.toml
src/bin/rav1e-ch.rs
src/bin/rav1e.rs

Including `image`, `pretty_assertions`, and `av1-grain`. Not touching `arbitrary` and `libfuzzer-sys` in this patch because of breaking changes I don't feel like dealing with right now.

Bump several dependencies

---

src/api/internal.rs
src/asm/x86/dist/sse.rs
src/dist.rs
src/encoder.rs
src/rate.rs
src/rdo.rs
src/segmentation.rs
src/x86/sse.asm

The move to `DistortionScale` reduces `compute_distortion()` CPU time by about 10%.
AWCY results on [objective-1-fast at default speed](https://beta.arewecompressedyet.com/?job=master-8c260d2cd928fe3945ae41fa738b8e994fa5c68e&job=segment-opt%402022-09-06T05%3A03%3A46.038Z):
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |   ---: |    ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 0.0902 | -0.7627 | -0.4605 |   -0.0608 | 0.0927 |  0.0987 |     0.1329 |     -0.8583 |     -0.4014 |   0.1068 | 0.1648 |   0.1460 |

Calculate per-plane scales in Q14 and center `log(base_q)`

---

build.rs
src/bin/common.rs

This fixes a panic in build.rs on some aarch64 environments:
* Alpine Linux 3.16 (aarch64)
* Ubuntu 20.04 (aarch64)

build: Handle absent `CARGO_CFG_TARGET_FEATURE`

---

.github/workflows/deploy.yml
README.md

This yields about a 6% speed-up in preliminary tests.

CI: Deploy rav1e-ch binary tuned for modern x86_64

---

src/bin/common.rs
src/bin/rav1e-ch.rs
src/bin/rav1e.rs

Align the field name with the flag and the `av1-grain` API. This feature is external to `librav1e` and used only in binaries.

bin: Bring `--photon-noise` out from under unstable feature

---

src/bin/common.rs

This shorthand flag appears to have been dropped in #2962, the removal of which broke some scripts.

Add back shorthand for `--verbose` and `--quiet`

---

src/bin/common.rs

It would trip scripts parsing the version line otherwise.

Keep the version line compatible with 0.5

---

src/api/config/speedsettings.rs

Level 7 was too close to 6 and 8 in speed and efficiency. There was a small but significant gap from 6 to 8. So move the old level 8 up to 7. By lowering lookahead frames for level 8 as in speed 9 and disabling loop restoration filters as in speed 10, create a new level closer to 9. Trade the additional speed this implies for speed 9 with efficiency by searching for smaller blocks.
AWCY results for [objective-1-fast at speed 9](https://beta.arewecompressedyet.com/?job=cargo-lock-p20220913_s9_38-188%402022-09-20T10%3A04%3A15.094Z&job=speed-level-9c%402022-09-21T14%3A09%3A36.363Z), +2.53% encoding time:
|  PSNR Y |  PSNR Cb |  PSNR Cr | CIEDE2000 |     SSIM |  MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |     VMAF | VMAF-NEG |
|    ---: |     ---: |     ---: |      ---: | …

Create new speed level 8, drop level 7

---

src/bin/common.rs

Triple-pass can be implemented with the somewhat awkward: 
```sh
rav1e --first-pass pass.1 -b NNN -o /dev/null seq.y4m
rav1e --second-pass pass.1 --first-pass pass.2 -b NNN -o /dev/null seq.y4m
rav1e --first-pass pass.2 -b NNN -o seq.ivf seq.y4m
```

bin: Admit more than 2 encoder passes

---

src/predict.rs

Fix UB in pred_max test

---

Cargo.toml
src/api/internal.rs
src/encoder.rs

Useful to plot scale data for presentations.
i.e. https://mlug-au.org/doku.php#talks
https://mlug-au.org/lib/exe/fetch.php?media=rav1e_2022.pdf

Add scales and segment thresholds to `dump_lookahead_data`

---

src/segmentation.rs

Without this it is possible to reach an inconsistent state where `min_segment > max_segment` if for example:
* Rate control drives toward `base_q_idx = 1` resulting in `min_segment == max_segment`
* At the next keyframe, `max_segment` decreases as fewer segments are selected while `min_segment` is unchanged.
This was missed in #2986.

segmentation: Reset `min_segment` on data update

---

.github/workflows/deploy.yml
.github/workflows/rav1e.yml

actions-rs seems to be not maintained, so I'm replacing it with maintained actions, I couldn't find a published replacement for the clippy action yet, but [this fork](https://github.com/actions-rs-plus/clippy-check) seems the most promising.

Cleanup actions

---

src/asm/x86/dist/hbd.rs
src/x86/satd16_avx2.asm

A little more than 2x faster for 8x8 block size than the current intrinsics code. Relative speedup should be higher for larger block sizes because of lower looping overhead and using a vertical sum for each 8x8 satd, and using 1 horizontal sum at the end instead of doing a horizontal sum for each block, which is much slower.
Might be possible to go faster by recursively splitting each transform into 2 smaller transforms (like a radix-2 FFT), but I figured this is good enough for now.

Add AVX2 HBD SATD asm for 8x8-transformed blocks

---

Cargo.toml
src/dist.rs

The Rust version of get_sad is still used during ME for regions that are not of an exact block size.
This was consuming about 2.3% of runtime at speed 2.
This change causes the function to iterate over chunks of 4 that can easily be vectorized,
and then only the remainder will go through the slower non-vectorized SAD process.
After the change, the time spend in Rust get_sad
appears to be reduced by about 2/3, and the overall runtime of a speed 2 is decreased by about 1% on an AVX2 CPU.

Add SIMD helpers to speed up Rust get_sad

---

tests/binary.rs

This was previously uncovered when this feature regressed during CLI rework for a library upgrade.

tests: Add three-pass encode with target bitrate

---

.github/workflows/deploy.yml

There is up to a 10% performance improvement from compiling with `target-cpu=native`. We can provide the majority of this benefit to users of the pre-compiled binaries by providing avx2-optimized binaries which will be better autovectorized than the generic binaries.

Produced optimized binary versions from CI

---

.github/workflows/deploy.yml

Confusingly, the LLVM target-cpu format is not the same as in the target triple.

CI: Correct format of target_cpu for x86_64 in deploy workflow

---

src/asm/x86/transform/inverse.rs

This avoids a segmentation fault specifically in `rav1e_idct_8x16_internal_16bpc_sse4`, a minimal fix for #3066.

x86: Disable 8x16 16bpc inverse transforms for SSE4.1

---

src/asm/shared/transform/inverse.rs
src/asm/x86/transform/inverse.rs
src/encoder.rs

The prior segmentation fault in `rav1e_idct_8x16_internal_16bpc_sse4` revealed that we were calling the assembly functions with EOB values off by one. So amend the shared calling functions to align with the convention in dav1d. The rav1e convention admits a zero EOB value when all coefficients are zero. In this case, transforms are a no-op and we may can stay in range when subtracting one otherwise. We may safely revert #3067 with this adjustment in place. Fixes #3066.

`inverse_transform_add`: Align to dav1d EOB convention

---

src/asm/shared/transform/inverse.rs
src/asm/x86/mc.rs
src/asm/x86/transform/inverse.rs

* Enable new SSE4.1 HBD Inverse Transform x86 assembly
Through the 27 patches merged since initial SS4.1 HBD ITX support, the remaining 95 functions have been added.
* Enable AVX2 12-bit Inverse Transform x86 assembly
Up to dav1d 1.0.0, 140 functions have been implemented.
* Enable SSE2/AVX512ICL put/prep/avg x86 assembly
Up to dav1d 1.0.0, another 21 functions have been implemented.

Enable new x86 assembly from dav1d 1.0.0 merge

---

src/asm/x86/ec.rs
src/ec.rs

This commit results in an overall performance improvement of about 2% at speed 2 10-bit:
```
Time (mean ± σ):     43.704 s ±  0.148 s    [User: 43.702 s, System: 0.183 s]
Range (min … max):   43.480 s … 43.933 s    10 runs
Time (mean ± σ):     42.789 s ±  0.067 s    [User: 42.806 s, System: 0.170 s]
Range (min … max):   42.679 s … 42.856 s    10 runs
```

Template entropy coding functions to help optimiser

---

src/partition.rs

This commit results in an overall performance improvement of about 2% at speed 2 10-bit:
```
Time (mean ± σ):     43.602 s ±  0.152 s    [User: 43.596 s, System: 0.176 s]
Range (min … max):   43.426 s … 43.933 s    10 runs
Time (mean ± σ):     42.951 s ±  0.085 s    [User: 42.948 s, System: 0.179 s]
Range (min … max):   42.850 s … 43.118 s    10 runs
```

Optimise BlockSize::from_width_and_height_opt

---

src/frame/plane.rs
src/tiling/plane_region.rs

This commit results in an overall performance improvement of about 2% at speed 2 10-bit:
```
Time (mean ± σ):     43.646 s ±  0.088 s    [User: 43.656 s, System: 0.170 s]
Range (min … max):   43.471 s … 43.787 s    10 runs
Time (mean ± σ):     42.919 s ±  0.082 s    [User: 42.934 s, System: 0.169 s]
Range (min … max):   42.813 s … 43.039 s    10 runs
```

Optimise plane::as_region

---

src/encoder.rs

This commit results in an overall performance improvement of about 2% at speed 2 10-bit:
```
Time (mean ± σ):     43.695 s ±  0.151 s    [User: 43.684 s, System: 0.180 s]
Range (min … max):   43.518 s … 44.033 s    10 runs
Time (mean ± σ):     42.808 s ±  0.081 s    [User: 42.828 s, System: 0.170 s]
Range (min … max):   42.702 s … 42.961 s    10 runs
```

Use chunks_exact for performance in diff method

---

src/ec.rs

This allows us to avoid accounting for bits in WriterCounter, which is used heavily when estimating bit costs of various decisions.

Use a bit counter instead of a byte counter in EC

---

src/ec.rs

Also due to them not being forced inline in the `v_frame` crate.

ec: Manually inline `msb()` and `ilog()` for clarity

---

.github/workflows/rav1e.yml

Specifically, the fetch step before cargo-c build seems to be adversely impacted by this feature.

CI: Disable unstable sparse cargo registry

---

src/asm/x86/dist/cdef_dist.rs

This resolves an issue where occasionally the ASM test for cdef_dist_hbd would fail due to the result being slightly off.

Fix rounding issue in HBD CDEF code

---

src/quantize.rs

The resulting ASM is identical, but this method makes the intent clearer.

Use is_power_of_two method in divu_gen

---

src/api/config/encoder.rs
src/api/config/mod.rs
src/api/test.rs
src/dist.rs

It is recommended to use the constants MIN and MAX instead.

Remove uses of deprecated min_value/max_value

---

src/asm/x86/lrf.rs
src/lrf.rs

sgrproj_sum_finish in particular was identified as a hotspot in HBD encoding. This changeset attempts to improve the performance of it and surrounding code by:
- Moving bounds checks out of a hot loop
- Use builtin saturating_sub method which is more efficient than performing multiple casts
- Use generics to allow compile-time computation of math dependent on bit-depth

Improvements to sgrproj HBD performance

---

src/quantize/tables.rs

Replace fallible run-time one-off conversion with checked compile-time conversion.
If the `ac_qlookup_12_Q3_raw` array contained a zero at index 190 for example, we would receive a compile-time error:
```
error[E0080]: could not evaluate static initializer
--> src/quantize/tables.rs:201:32
|
35  |   nonzero_checked(ac_qlookup_12_Q3_raw);
|   ------------------------------------- inside `tables::ac_qlookup_12_Q3` at src/quantize/tables.rs:35:3
...
201 |       let _ = if raw[i] == 0 { [(); 0][i] } else { () };
|                                ^^^^^^^^^^
|                                |
|                                index out of bounds: the length is 0 but the index is 190
|                                inside `nonzero_checked` at src/quantize/tables.rs:201:32
```

Check quantizer values are non-zero with const fn

---

.github/dependabot.yml

This will be particularly useful if we are committing the Cargo.lock file to aid in keeping us up-to-date.

Enable dependabot to update Cargo dependencies

---

renovate.json

The PRs were becoming too noisy having it run "any time" and defeated the purpose of using renovate to group updates together.

Only run renovate once a week

---

benches/bench.rs

Fixes #3175. Integrated `ipred_cfl_ac` assembly uses aligned loads.

benches: Fix alignment issue for `cfl_rdo`

---

src/lrf.rs

Fixes the main part of https://github.com/xiph/rav1e/issues/3161
I believe the potential for integer overflows still makes it unsound though.

Safety critical bounds checking is off-by-one in sgrproj_box_ab_internal

---

.github/workflows/deploy.yml
Cargo.toml
cross/Dockerfile.libs
cross/entrypoint-build-libs.sh

This adds artifacts to the deploy workflow for the cargo-c library and headers. I have created [a release on my fork](https://github.com/fdintino/rav1e/releases/tag/p20230414) that includes the new release artifacts.
I have held off on opening this pull request in the hope that cross would add support for custom subcommands (cross-rs/cross#716) but that doesn't seem to be happening anytime soon. I'm using a pretty ugly hack to get around this limitation: I run `cross` with a custom dockerfile whose entrypoint rewrites `cargo build` to `cargo cbuild` in the `CMD` arguments.
I have also added targets for i686 linux and aarch64 mac.
I was motivated to do this work so that I would not need to maintain cross-platform builds of rav1e when packing pillow-avif-plugin. The librav1e artifacts on my …

CI: deploy library artifacts, add i686 linux and aarch64 mac targets

---

src/asm/x86/cdef.rs
src/asm/x86/dist/mod.rs
src/asm/x86/mc.rs
src/asm/x86/transform/inverse.rs
src/cpu_features/x86.rs

CPU features `avx512gfni`, `avx512vaes` and `avx512vpclmulqdq` are renamed. The `avx512` prefix is removed but the original names remain as aliases.

CI: Allow new `clippy::deprecated` warning for rustc 1.69

---

src/asm/shared/predict.rs
src/cpu_features/aarch64.rs
src/cpu_features/rust.rs
src/cpu_features/x86.rs

Expand `asm::shared::predict::test::pred_matches_u8` to cover all available CPU feature levels and bit depths.

Increase test coverage for intra prediction

---

.github/workflows/rav1e.yml

- Add `aarch64-unknown-linux-gnu` target with `rustup`
- Install `gcc-aarch64-linux-gnu` for linking and `qemu-user` for running
- Install `libdav1d-dev:arm64` from Ubuntu Ports for `decode_test_dav1d` feature
- Set up cargo environment for all of the above

CI: Add aarch64 tests with decode_test_dav1d

---

src/context/block_unit.rs
src/cpu_features/rust.rs
src/predict.rs

Fix a few warnings and errors encountered with `rust-analyzer` in preparation for `aarch64` changes.
Most significantly, remove the `Vec` allocations from the Rust implementation of `ipred_directional`.

Miscellaneous fixes

---

Cargo.lock
Cargo.toml
src/util/logexp.rs

Our version of rust already support natively panic in const context.

Remove const_fn_assert

---

.devcontainer/Dockerfile
.devcontainer/build.json
.devcontainer/devcontainer.json
.github/workflows/devcontainer.yml
CONTRIBUTING.md
README.md

The primary audience is new contributors, providing a one-click fully functional development environment.
The installed packages include:
- gcc cross-compiler and qemu for aarch64 testing
- Intel SDE for AVX512-ICL testing
- dav1d binary for decoding ivf output
- cargo-fuzz and libfuzzer-14-dev configured for libfuzzer-sys
- cargo-criterion for running and reporting benchmarks

Add `devcontainer` with deps for `x86_64` and `aarch64`

---

renovate.json

This update will cause Renovate to update all versions in the lockfile to the latest Cargo.toml-compatible versions once per week. This is necessary in order to ensure all dependencies are included in the updates.
This may raise the question of why bother with a lockfile. The answer is that having the lockfile committed, but having it updated automatically, allows us to have the CI run before we merge the updates, preventing rav1e from randomly breaking.

Enable Renovate to update lockfile dependencies

---

src/context/cdf_context.rs

Fixes: "warning: use of `default` to create a unit struct"

cdf_context: fix clippy lint caught by 1.72.0 nightly

---

ivf/src/lib.rs

These validate:
- erroring out on bad magic
- reading a valid header
- reading a "valid" but dummy IVF packet.

ivf: add read tests

---

.github/workflows/rav1e.yml
ivf/src/lib.rs

- Get rid of unreachable error handling in tests added in #3220 
- Exclude `unreachable` expressions from coverage reporting
- Add ability to exclude lines from coverage by appending a `// grcov-excl-line` comment to the end of the line

Improve coverage

---

src/bin/common.rs

Currently when passing `--version` to rav1e, rav1e will output whether assembly is enabled, as well as CPU features that the binary was compiled with. This has shown to be a bit confusing for end users. This change clarifies the text by specifying that the assembly refers to runtime assembly, i.e. the dynamically activated assembly based on CPU detection, as well as specifying what runtime assembly level would be used on the current machine (this is also affected by environment vars).
Example output as follows:
```
rav1e 0.6.1 (p20230627-2-g73440a1) (debug)
rustc 1.70.0 (90c541806 2023-05-31) x86_64-unknown-linux-gnu
Compiled CPU Features: adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sha,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveo …
```

Show runtime assembly level in long version output

---

src/predict.rs

Removes an allow which is no longer necessary

Clippy updates for rustc 1.71

---

src/scenechange/fast.rs
src/scenechange/mod.rs

The optimizations to `.trailing_zeros()` will automatically be applied by rustc when using NonZero types. This allows us to remove the unsafe code.
You can check this will actually work by running:
`RUSTFLAGS="-C target-feature=-bmi1,-lzcnt -C llvm-args=-x86-asm-syntax=intel --emit asm" cargo b -r`
and then inspecting the output assembly. If you use `#[inline(never)]` on fast_idiv for testing, you can find the generated ASM easily:
```asm
; ...
_ZN5rav1e11scenechange9fast_idiv17h2ad3db97a8f4c4c5E:
.Lfunc_begin583:
.file	147 "/home/user/Development/rav1e" "src/scenechange/mod.rs"
.loc	147 32 0
.cfi_startproc
.loc	107 254 1 prologue_end
rep		bsf	rax, rsi
.Ltmp17962:
.loc	147 35 3
shrx	rax, rdi, rax
.loc	147 36 2
ret
.Ltmp17963:
.Lfunc_end583:
; ...
```
The assertion …

Remove unsafe code from fast_idiv by using NonZeroUsize

---

src/bin/rav1e-ch.rs
src/bin/rav1e.rs

More accurately report that resource usage reporting is not supported on these platforms since the lack of support is not necessarily a Windows-only issue.
Addresses https://github.com/xiph/rav1e/issues/2517

Improve error message for platforms without rusage support

---

.github/workflows/rav1e.yml
Cargo.lock
Cargo.toml
src/activity.rs
src/asm/aarch64/cdef.rs
src/asm/aarch64/dist.rs
src/asm/aarch64/mc.rs
src/asm/aarch64/predict.rs
src/asm/x86/cdef.rs
src/cpu_features/aarch64.rs
src/cpu_features/rust.rs
src/cpu_features/x86.rs
src/partition.rs

Now only quickcheck depends on syn1.
See https://github.com/BurntSushi/quickcheck/pull/317 for the last dep

Update two dependencies that relied on syn1

---

.github/workflows/deploy.yml

I noticed that rav1e is compiling against the OS X 12 SDK, whereas the binaries I distribute for pillow-avif-plugin target 10.10 and 11 for x86_64 and arm64, respectively—which is pretty common practice for python wheels. I've confirmed that cargo-c respects the `MACOSX_DEPLOYMENT_TARGET` environment variable and that the artifacts are in fact built against the desired SDKs.

ci: Set MACOSX_DEPLOYMENT_TARGET to 10.10 for x86_64, 11.0 for arm64

---

.github/workflows/deploy.yml

Adding the LICENSE to the library archives makes it easier for dependent projects to include it in their build artifacts.

ci: Bundle LICENSE file in librav1e deploy artifacts

---

src/encoder.rs

When skipping, we may ignore the quantizer value. Fixes #3209.

Fix assertion against entering lossless mode

---

src/asm/aarch64/transform/inverse.rs
src/asm/x86/transform/forward.rs
src/asm/x86/transform/inverse.rs
src/transform/forward.rs
src/transform/forward_shared.rs
src/transform/inverse.rs
src/transform/mod.rs

Reference implementations in Rust to provide primitives for losslessly encoded blocks.

Add forward and inverse Walsh-Hadamard transforms

---

benches/mc.rs
benches/transform.rs
src/asm/shared/predict.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/quantize.rs
src/asm/x86/transform/forward.rs
src/context/block_unit.rs
src/context/mod.rs
src/context/transform_unit.rs
src/encoder.rs
src/quantize/mod.rs
src/transform/forward.rs
src/transform/mod.rs
src/util/align.rs

I'm trying to remove UB of `Aligned::uninitialized()` — #1572

Reduce uses of uninitialized arrays

---

src/asm/aarch64/transform/inverse.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/transform/forward.rs
src/asm/x86/transform/inverse.rs
src/transform/forward.rs
src/transform/forward_shared.rs
src/transform/inverse.rs
src/transform/mod.rs

* Introduce `TxType::WHT_WHT` and so unify the `forward_transform` and `inverse_transform_add` functions.
* Plumb `fwht4` through the existing forward transform code and gain an `AVX2` implementation.
* Improvements to round trip and  transform tests
* Found and fixed a bug with aarch64 assembly integration

Integrate lossless forward transform intrinsics

---

src/asm/aarch64/transform/forward.rs
src/asm/aarch64/transform/mod.rs
src/asm/shared/transform/forward.rs
src/asm/shared/transform/mod.rs
src/asm/x86/transform/forward.rs
src/transform/forward.rs
src/transform/forward_shared.rs

This is a 1:1 translation, not specifically optimized for NEON differentiators.

Port AVX2 forward transforms to NEON

---

src/asm/aarch64/predict.rs
src/asm/aarch64/transform/inverse.rs
src/asm/shared/predict.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/predict.rs
src/asm/x86/quantize.rs
src/asm/x86/transform/inverse.rs
src/context/block_unit.rs
src/context/transform_unit.rs
src/encoder.rs
src/partition.rs
src/predict.rs
src/quantize/mod.rs
src/rdo.rs
src/transform/inverse.rs
src/transform/mod.rs

In various `pred_cfl_ac` I've added checks that `ac[..].len()` must be exactly as long as needed, i.e. `plane_bsize.width() * plane_bsize.height()`. The multiplication got repetitive, so I've added `plane_bsize.area()`.
Those prediction functions are in assembly. I haven't checked whether they initialize exactly `plane_bsize.area()` and nothing else, but I don't see a reason why they wouldn't, it would be a bug otherwise. Anyway, it's not a safety issue in pratice, since the allocated memory behind `ac` is the same size as before.
`get_nz_map_contexts` initializes context up to `eob` which is `u16`. Other code used `usize` for `eob`. To be type-safe sure it can't be longer than `u16` anywhere (therefore reading past what `get_nz_map_contexts` could init), I've changed `eob` to be …

Reduce risk of uninit ac in luma_ac and encode_coeffs

---

src/asm/aarch64/transform/inverse.rs
src/asm/shared/transform/inverse.rs
src/asm/shared/transform/mod.rs
src/asm/x86/transform/inverse.rs

* Explicitly elide bounds checks for `TxSize` and `TxType` as array indices.
* Expand transform function tables to make room for `WHT_WHT` implementations.
* Replace branch for `WHT_WHT` with table lookup for `aarch64` and `x86_64`.
Note: The `x86_64` table generation code is getting unwieldy.

Move WHT inverse transforms to common lookup table for `x86_64` and `aarch64`

---

benches/predict.rs
src/api/lookahead.rs
src/asm/aarch64/predict.rs
src/asm/shared/predict.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/predict.rs
src/context/block_unit.rs
src/encoder.rs
src/partition.rs
src/predict.rs
src/rdo.rs
src/transform/forward.rs
src/util/align.rs

Inspired by #3276. Introduce new types to capture the requirements of intra edge buffers and avoid undefined behavior.
Analysis from @kornelski quoted below:
```rust
// left pixels are ordered from bottom to top and right-aligned
let (left, not_left) = edge_buf.data.split_at_mut(2 * MAX_TX_SIZE);
let (top_left, above) = not_left.split_at_mut(1);
```
> Right-aligned pixels suggests that not all of the `left` pixels are always initialized, so `get_intra_edges` was returning `edge_buf` without initializing all of its elements. That's technically UB, and an example of [a safety comment being misleading about safety](https://github.com/xiph/rav1e/blob/3d43ecac0145688ac9d17712e685e80ee4eefbe2/src/partition.rs#L617).
> 
> I don't think I could simply change `edge_buf` to be a contiguous slice of …

Well-defined lazy initialization for `get_intra_edges`

---

src/arm/64/satd.S
src/asm/aarch64/dist.rs

This roughly matches the architecture of the intrinsics: a central function that the rest fall into. Unlike the generated code from the instrinsics, this uses 8 temporary vector registers for width 8, rather than the minimum of 3. A width-16x kernel is included,  admitting a simple loop for the width-8 kernel.

Complete 8-bit SATD aarch64 assembly implementation

---

Cargo.lock
Cargo.toml
doc/PROFILING.md
src/activity.rs
src/api/internal.rs
src/api/lookahead.rs
src/bin/muxer/ivf.rs
src/bin/muxer/y4m.rs
src/bin/rav1e-ch.rs
src/bin/rav1e.rs
src/bin/stats.rs
src/cdef.rs
src/context/block_unit.rs
src/deblock.rs
src/encoder.rs
src/lrf.rs
src/me.rs
src/rate.rs
src/rdo.rs
src/scenechange/fast.rs
src/scenechange/mod.rs
src/segmentation.rs

It is feature equivalent, we can easily extend the tracing abilities to use [tracy](https://crates.io/crates/tracing-tracy) and [coz](https://crates.io/crates/tracing-coz) later.

Replace hawktracer with tracing-chrome

---

src/arm/64/satd.S
src/asm/aarch64/dist.rs

Adds 4x4, 8x4 and 8x8 kernels as well as functions that can be composed from them. Not restricted to 10-bit input but valid for 12-bit input as well.

HBD SATD aarch64 assembly implementation

---

.github/workflows/rav1e.yml

This works around temporary failures in repositories that we don't need for dependencies.

CI: Update fewer apt lists

---

src/asm/aarch64/transform/forward.rs

Remove a redundant into()

---

.github/workflows/deploy.yml

In order for the rav1e shared library to work on glibc systems, it needs musl libc to be statically linked. Fixes #3242

fix: Build musl librav1e deploy artifacts with crt static

---

Cargo.lock

This reverts `Cargo.toml` and `Cargo.lock` to the state prior to #3241, except that the changes in #3283 are re-applied.
Updated all uniquely versioned packages. This did not cause the deploy workflow to regress.
Manually updated remaining packages and verified with deploy workflow.
The following packages are not udpated from `v0.48.0`:
- `windows-targets`
- `windows_aarch64_gnullvm`
- `windows_aarch64_msvc`
- `windows_i686_gnu`
- `windows_i686_msvc`
- `windows_x86_64_gnu`
- `windows_x86_64_gnullvm`
- `windows_x86_64_msvc`
Finally, we may re-apply the `Cargo.toml` changes, taking care to pin the above packages,

CI: Revert Cargo.toml and Cargo.lock to fix deploy

---

.github/workflows/deploy.yml

Deploy fails after this change:
```
warning: dropping unsupported crate type `cdylib` for target `x86_64-unknown-linux-musl`
```

Revert "fix: Build musl librav1e deploy artifacts with crt static"

---

src/arm/64/sad.S

Easier to read and reduces compressed compiled object size by 10%.

Unify register assignment in NEON assembly for get_sad

---

src/asm/aarch64/predict.rs

Parameters `max_w` and `max_h` were inadvertently swapped.
Before this patch:
```
$ rav1e -o test.ivf -r rec.y4m --limit 1 tractor_1080p10_25.y4m -y
>  CPU Feature Level: NEON
>  Using y4m decoder: 1920x1080p @ 25/1 fps, 4:2:0, 10-bit
>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=20 multiref=true fast_deblock=false scene_detection_mode=Standard cdef=true lrf=true enable_timing_info=false min_block_size=8x8 max_block_size=64x64 encode_bottomup=false non_square_partition_max_threshold=8x8 reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false rdo_tx_decision=false prediction_modes=Complex-KFs fine_directional_intra=true include_near_mvs=false use_satd_subpel=true
>  Using 1 …
```

Fix desync with `aarch64` assembly for `ipred_z2`

---

.github/workflows/deploy.yml

Fixes deployment failures for `x86_64-pc-windows-gnu` targets, due to linker errors.

CI: Use MSYS2 toolchain for `x86_64-pc-windows-gnu`

---

.github/workflows/deploy.yml

This was missed when the artifact was added in #3052.

CI: Build `windows-gnu-avx2` artifact with `x86_64-pc-windows-gnu`

---

.github/workflows/deploy.yml

Follow-up to #3309 and #3308, which necessitated renaming some artifacts.

CI: Fix artifact names for manual pre-release tag

---

src/api/config/speedsettings.rs
src/segmentation.rs

[AWCY result at speed 0](https://beta.arewecompressedyet.com/?job=master-f3c8d7b2-s0%402023-12-29T09%3A40%3A27.341Z&job=wip-segmentation-level-up%402023-12-29T09%3A39%3A56.551Z)
| PSNR Y | PSNR Cb | PSNR Cr | CIEDE2000 |   SSIM | MS-SSIM | PSNR-HVS Y | PSNR-HVS Cb | PSNR-HVS Cr | PSNR-HVS |   VMAF | VMAF-NEG |
|   ---: |    ---: |    ---: |      ---: |   ---: |    ---: |       ---: |        ---: |        ---: |     ---: |   ---: |     ---: |
| 1.0826 | -0.2250 | -0.0412 |    0.2315 | 0.0593 |  0.1193 |     0.8248 |     -0.8888 |     -0.6546 |   0.7733 | 1.0963 |   1.1068 |
Average encoding speed-up of 1.41x, with some clips averaging 2.16x. In the most extreme case, 2.63x for ducks_take_off at Q=80.
Note that that [AWCY results relative to speed …

Add SegmentationLevel::Complex and set for speed 0

---

src/scenechange/fast.rs
src/scenechange/mod.rs

`downscaled_frame_buffer` is an `Option<([Plane<T>; 2], bool)>`. The bool is called `is_initialized` and is supposed to show whether the memory in the `[Plane<T>; 2]` is initialized or not.
As far as I can tell, there is no code path that results in the Planes being uninitialized: `downscaled_frame_buffer` starts out as a `None`, the first buffer access allocates & initializes the memory, and the memory should always be initialized after that. The bool never seems to be `false` from what I can tell, which would support my assumption, I think.
There's also a field called `frame_ref_buffer` which caches the `Arc<Frame<T>>` when no downscaling is being done. Unless I am missing something, there's no real benefit to caching these pointers (because refs to both frames will always be passed …

Simplify fast scenechange code a bit

---

src/asm/aarch64/transform/forward.rs
src/asm/shared/transform/forward.rs
src/asm/x86/quantize.rs
src/asm/x86/transform/forward.rs
src/partition.rs
src/predict.rs
src/util/align.rs
src/util/uninit.rs

The two functions are equivalent except for an additional `T: Copy` bound on one function. That bound is always fulfilled at the moment, so I left it as-is.
I preferred the name `slice_assume_init_mut` over the other one because [std uses the same name](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.slice_assume_init_mut).

Remove duplicate assume_slice_init_mut

---

Cargo.lock
Cargo.toml
build.rs

This was added in #1552 but is no longer necessary. The cfg value `nightly_rustc` does not seem to be used anywhere, and [rust-version](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) in Cargo.toml allows a built-in way of checking the MSRV.
`rust-version` is only supported in toolchains >=1.56, but all older toolchains will fail compilation for other reasons (mostly edition = "2021").
Examples:
```
$ cargo +1.55 c
error: failed to parse manifest at `/.../Development/rav1e/Cargo.toml`
Caused by:
feature `edition2021` is required
```
```
$ cargo +1.60 c
error: package `clap_complete v4.4.5` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.60.0
```

Remove rustc_version_check from build.rs

---

.gitignore

These include developer-specific IDE customizations and generally aren't intended to be committed.

Ignore IDE config folders

---

Cargo.toml

This improves compile time when the serialize feature is disabled, at least on my machine.

Only enable av1-grain/serialize with rav1e/serialize

---

ivf/src/lib.rs
src/asm/x86/sad_plane.rs
src/tiling/plane_region.rs
src/tiling/tile_blocks.rs
src/tiling/tile_motion_stats.rs
src/tiling/tile_restoration_state.rs

There were two bugs ([1](https://github.com/rust-lang/rust-clippy/issues/9142), [2](https://github.com/rust-lang/rust-clippy/issues/8264)) that made these necessary. Both bugs are fixed in 1.70, so the `allow`s can be removed now.

Remove `allow(clippy::undocumented_unsafe_blocks)` where not necessary

---

build.rs

On macOS, `cargo build --target=x86_64-unknown-linux-musl` makes rustc panic in compiler/rustc_codegen_llvm/src/back/archive.rs:397:67, because the `librav1easm.a` file is invalid and unusable. This is because running aarch64-darwin's `strip` command run on an x86-64-musl archive ruins it.
I've made rav1e not run `strip` during cross-compilation, unless `CARGO_TARGET_{target}_STRIP` or `STRIP` env var is set.

Don't use host's strip command when cross-compiling

---

src/api/config/speedsettings.rs
src/api/test.rs
src/context/partition_unit.rs
src/partition.rs
src/tiling/tiler.rs

These aren't checked for in CI, but it's not a bad idea to fix them anyway.

Fix test-specific clippy lints

---

src/x86/sse.asm

My local version of NASM (2.16.01) produces some warnings when compiling:
```
warning: trailing garbage after macro name ignored [-w+pp-trailing]
/.../sse.asm:444: ... from macro `WEIGHTED_SSE' defined here
```
Looks like the `%undef sum, kernel_width, res` only undefines `sum` and ignores everything after that. `res` doesn't seem to exist (anymore), so I removed it from the `%undef`s.

Fix NASM warning about %undef statement

---

src/bin/common.rs

From the [reference regarding environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) set by Cargo:
> **CARGO_ENCODED_RUSTFLAGS** — extra flags that Cargo invokes rustc with, separated by a 0x1f character (ASCII Unit Separator).
Before:
```
Compiler Flags: -Ctarget-cpu=native-Clink-arg=-fuse-ld=mold
```
After:
```
Compiler Flags: -C target-cpu=native -C link-arg=-fuse-ld=mold
```

Add whitespace to compiler flags in long version string

---

Cargo.lock
Cargo.toml
src/bin/common.rs
src/capi.rs

`std::sync::OnceLock` is effectively the same as `once_cell::sync::OnceCell`, and because the MSRV is now 1.70 it can be used instead. `Lazy<T>` can also simply be replaced by a `OnceLock`, making the `once_cell` dependency unnecessary.

Replace types from once_cell with std::sync::OnceLock

---

src/activity.rs

The `ILog` trait was introduced in v_frame before `{integer}::ilog` became stable. `const fn` doesn't do much here, but it's simple to do, so one might as well.
Note that the functions are similar but not equal in behavior:
`ILog::ilog` is effectively
```rs
if x == 0 {
0
} else {
x.ilog2() + 1
}
```
`x.ilog2()` will panic if `x == 0`, but that is already assumed to not be the case here (and it looks like the check for zero is optimized away in all callsites).

Make apply_ssim_boost a const fn

---

src/asm/shared/dist/sse.rs
src/asm/shared/transform/inverse.rs
src/asm/x86/cdef.rs
src/asm/x86/quantize.rs
src/bin/common.rs
src/bin/decoder/y4m.rs
src/bin/stats.rs
src/context/block_unit.rs
src/context/partition_unit.rs
src/encoder.rs
src/predict.rs
src/quantize/mod.rs
src/rdo.rs
src/sad_plane.rs
src/transform/inverse.rs

These result in warnings on [1.78](https://github.com/rust-lang/rust/pull/117772) (current nightly). For example:
```rs
warning: the item `Pixel` is imported redundantly
--> src/bin/stats.rs:14:21
|
10 | use av_metrics::video::*;
|     -------------------- the item `Pixel` is already imported here
...
14 | use rav1e::{Packet, Pixel};
|                     ^^^^^
```

Remove redundant imports

---

renovate.json

Clap 4.5 requires rustc 1.74, so to avoid having to bump the minimum version for now, lock renovate to only bump to clap 4.4 patch versions.

Lock clap auto-updates to 4.4 until we bump rustc version

---

renovate.json

- It appears the additional clap_* packages in Cargo.lock also needed to be version locked, so this adds these
- renovate validator showed there were some deprecated keys that needed migrated, so this migrates to the new keys

Further renovate changes

---

renovate.json

This package also bumped their minimum rustc version in a patch version to one that we don't support.

Also lock assert_cmd version

---

build.rs

Fixes #3330.
This raises the minimum NASM version to 2.15.0 which was released in [June 2020](https://repo.or.cz/nasm.git/tag/refs/tags/nasm-2.15). The minimum Rust version 1.70 was released in [June 2023](https://releases.rs/docs/1.70.0/), so I don't think this is a problem.
I also spent a bit of time refactoring the build script slightly.

Add new NASM pragma regarding macro parameter expansion

---

.github/workflows/rav1e.yml

The job only checks a default x86 build and a minimal wasm32 build. That should be enough to find most problems before starting the big build matrices.
This addresses the MSRV part of #3363. Tests are still needed.

Add CI job to check the MSRV

---

Cargo.lock
Cargo.toml
src/predict.rs
src/util/align.rs

Closes #3370.
`ABox<[T]>` generally works the same way as `AlignedBoxedSlice<T>`, but uses a different alignment by default:
AlignedBoxedSlice: 8 on wasm, 64 everywhere else
ABox: Generally two cachelines, 64 bytes for unknown archs ([exact rules](https://github.com/sarah-ek/aligned-vec/blob/b52b2e78d940cda6622f99ffb8deb4c505e2635b/src/lib.rs#L30))
I am pretty sure the wasm allocation bug mentioned in the code comment has been [fixed](https://github.com/rust-lang/rust/pull/70585), so using a higher alignment should be fine on the wasm32 arch.
It's possible to configure aligned_vec to reproduce the old behaviour exactly, but I think it's probably better to stick to the crate defaults.

Replace AlignedBoxedSlice with aligned_vec::ABox

---

Cargo.lock
Cargo.toml

nasm-rs versions before 0.3 ignored the number of jobs set by cargo's job server. This means that even with `cargo b -j1` or `NUM_JOBS=1 cargo b`, the rav1e build script uses 100% CPU.

Update nasm-rs to 0.3.0

---

Cargo.toml

[Context](https://blog.rust-lang.org/2024/05/06/check-cfg.html).
TL;DR: Custom `cfg`s are considered unexpected by `rustc`, so they will produce a warning (on 1.80+) unless they're added to a list of known custom cfgs.

Disable compiler warnings for known custom `cfg` values

---

src/transform/inverse.rs
src/transform/mod.rs

`get_rect_tx_log_ratio` is only used with width & height of `TxSize` (tx is in the name), so it makes sense to make it a `TxSize` method instead.
Using `tx_size.width_log2() - 2` seemed more straightforward than the call to `ILog`, so I replaced that too.

Turn get_rect_tx_log_ratio into associated function for TxSize

---

.github/workflows/rav1e.yml
src/rate.rs

Drop `binary` integration test from coverage

---

Cargo.lock
Cargo.toml

This was locked to 4.4.17 because of MSRV incompatibilities. #3359 ultimately decided to bump the MSRV to 1.74 which is enough for clap 4.5, so I unlock and update it here.
The only remaining locked dependency is `bitstream-io`, which now has an MSRV of 1.79.

Update clap to v4.5

---

.github/workflows/deploy.yml

Closes #3397.
[proof that it works](https://github.com/FreezyLemon/rav1e/actions/runs/11001342466) (the [commit](https://github.com/FreezyLemon/rav1e/commit/f704289e3212a89a3026f2b85077f5492f2b068b) on that branch includes another change for testing).
GHA uses `pwsh` by default on Windows runners. Powershell uses backticks instead of backslashes.

Fix `deploy` CI job

---

src/bin/common.rs

The color theme from clap v3 is more pleasing.

Use the clap v3 style

---

Cargo.toml

rust-lang/rust#98302 is fixed in Rust 1.83.0

Cargo.toml: remove irrelevant comment

---

src/api/channel/data.rs
src/api/context.rs
src/ec.rs
src/encoder.rs
src/header.rs

`bw.write(5, 31)` is writing an 31i32 but that doesn't fit into 5 bits because of the sign bit.
As part of this, also move everything to the non-compat `BitWrite` trait.

Fix bit overflows when writing headers
